### ISSUE TITLE
n_core is hardcoded in fc_run.py  for fc_ovlp_filter.py

### ISSUE THREAD

**Issue by aclum** [PacificBiosciences/FALCON#10]
line 718 of fc_run.py  uses a hardcoded number of cores.  It would be better to have this as part of the the overlap_filtering_setting

717         script.append( """fc_ovlp_filter.py --fofn las.fofn %s \
718                                  --n_core 24 --min_len %d > preads.ovl""" % (overlap_filtering_setting, length_cutoff_pr) )
719

**Comment by pb-jchin** [comment]
This is fixed in commit https://github.com/PacificBiosciences/FALCON/commit/b9257cb6579c0654fe7398d37984f503e5f47fac
