### ISSUE TITLE
length_cutoff vs length_cutoff_pr

### ISSUE THREAD

**Issue by janvanoeveren** [PacificBiosciences/FALCON#101]
Hi Jason,
A question on the length_cutoff and length_cutoff_pr parameters, as you discussed with David Gordon in issue #75.
If length_cutoff is the seed read cutoff (so only seeds used longer than this) and length_cutoff_pr is the cutoff of preads used for the final assembly, how can the length_cutoff_pr effectively be set lower than the length_cutoff: no seeds will be present shorter than this right?
What am I missing? I do see the point of using a longer length_cutoff_pr when using preassembled data for input.
Is there actually a parameter for the minimum read length for the short reads used for error correction (so as an initial filter step as in HGAP)?

Jan

**Comment by pb-jchin** [comment]
The p-reads can be generated from the fragment of the seed reads hence the legnth can be shorter the seed reads.
