### ISSUE TITLE
how secondary reads are determined by DALIGNER?

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/FALCON#105]
Dear Dr. Chin,

How are secondary reads defined by DALIGNER? Based on the following comment, it looks like that the longest read is considered the best, all else are secondary for a particular ZMW well, is this true?

```
./DAZZ_DB/DB.h:#define DB_BEST 0x0800   //  This is the longest read of a given insert (may be the only 1)
```

Thanks!

**Comment by pb-jchin** [comment]
Please check the section about the `-a` option for `DBsplit` in [Gene's blog](https://dazzlerblog.wordpress.com/2014/06/01/the-dazzler-db/).  

Here is the related paragraph:

> DBsplit [-a] [-x<int>] [-s<int(200)>] <path:db|dam>

>Divide the database <path>.db or <path>.dam conceptually into a series of blocks referable to on the command line as <path>.1, <path>.2, … If the -x option is set then all reads less than the given length are ignored, and if the __-a option is not set then secondary reads from a given well are also ignored__. The remaining reads, constituting what we call the trimmed DB, are split amongst the blocks so that each block is of size -s * 1Mbp except for the last which necessarily contains a smaller residual. The default value for -s is 200Mbp because blocks of this size can be compared by our “overlapper” dalign in roughly 16Gb of memory. The blocks are very space efficient in that their sub-index of the master .idx is computed on the fly when loaded, and the .bps and .qvs files (if a .db) of base pairs and quality values, respectively, is shared with the master DB. Any relevant portions of tracks associated with the DB are also computed on the fly when loading a database block.


You should also look at the `DBsplit.c` souce code,

https://github.com/thegenemyers/DAZZ_DB/blob/master/DBsplit.c, line 192-221

```
  if (ALL)
      for (i = 0; i < nreads; i++)
        { rlen = reads[i].rlen;
          if (rlen >= CUTOFF)
            { ireads += 1;
              treads += 1;
              totlen += rlen;
              if (totlen >= size)
                { fprintf(dbfile,DB_BDATA,i+1,treads);
                  totlen = 0;
                  ireads = 0;
                  nblock += 1;
                }
            }
        }
    else
      for (i = 0; i < nreads; i++)
        { rlen = reads[i].rlen;
          if (rlen >= CUTOFF && (reads[i].flags & DB_BEST) != 0)
            { ireads += 1;
              treads += 1;
              totlen += rlen;
              if (totlen >= size)
                { fprintf(dbfile,DB_BDATA,i+1,treads);
                  totlen = 0;
                  ireads = 0;
                  nblock += 1;
                }
            }
        }
```
The `DB_BEST` is defined in [`DB.h`](https://github.com/thegenemyers/DAZZ_DB/blob/master/DB.h), line 212 with informative comment:
```
#define DB_BEST 0x0800   //  This is the longest read of a given insert (may be the only 1)
```

**Comment by yunfeiguo** [comment]
Thanks for your detailed response!

Just to confirm, so secondary read is any read other than the longest read for a given ZMW (an insert).
