### ISSUE TITLE
Intermediate files

### ISSUE THREAD

**Issue by jasperlinthorst** [PacificBiosciences/FALCON#111]
Hi Jason and others,
I'm trying to use Falcon from my own pipeline on the ecoli dataset that is also used in the documentation.
I can't use the exact same approach that is outlined in the manual, because I'm running stuff on a combination of multiple Grids (no SGE), which needs some tweaking.

So what i did was that I reverse engineered the code that I saw in fc_run.py and came up with the following steps in a snakemake pipeline:

PREASSEMBLY
- Create dazzler DB from the supplied fasta files and DBsplit the database, parameters: "-x500 -s50"
- Have HPCdaligner create a shell script of commands, parameter: "-dal4 -t16 -e.70 -l1000 -s1000 -H12000"
- Use fc_consensus.py to generate preads for every final las file generated my LAMerge, as follows:
"LA4Falcon -H12000 -so -f:{db} {lasfile} | fc_consensus.py --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 4 > preads{n}.fasta"
- Merge all preads{n}.fasta files into a single preads.fasta file, while filtering out sequences that are shorter than 12000bp and rewriting the header (conform code in fc_run.py..)

At this point I end up with a single preads.fasta file of ~318MB

ASSEMBLY
- Create a new dazzler DB from the preads.fasta file and DBsplit the database, parameters: "-x500 -s50"
- Have HPCdaligner create a new shell script of commands for the preads database, parameter: "-dal4 -t32 -h60 -e.96 -l500 -s1000 -H12000"
- Create a file called preads_lasfiles.fofn containing a list of the produced las files
- Filter overlaps using: fc_ovlp_filter.py --fofn preads_lasfiles.fofn --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --min_len 12000 > preads.ovl
- Construct assembly graph: fc_ovlp_to_graph.py preads.ovl --min_len 12000 > fc_ovlp_to_graph.log
- Output data in dazzler database to preads4falcon.fasta using, "DB2Falcon {preadsdb}"
- Write contigs by calling fc_graph_to_contig.py in the same directory

Now, the problem is that the p_contigs.fa file contains ~2022 contigs and has a size of ~85MB... I should expect 1 contig of ~4.5MB, right?

I guess something is going wrong in one of the above steps. To narrow down the problem, could you supply me with a list of intermediate files and the respective filesizes so I can check where I'm going wrong?

Thanks in advance for helping out!
Jasper

Ps, I use the commits for all dazzler stuff that's mentioned in the manual...

**Comment by pb-jchin** [comment]
Here is some of a run I just did... (not totally up-to-date code.. but it is close.)
```
-rw-r--r-- 1 jchin Domain Users     868 May 19 23:01 run_falcon_asm.sh
drwxr-xr-x 9 jchin Domain Users    4096 Jun 25 10:11 ..
-rw-r--r-- 1 jchin Domain Users     971 Jun 25 10:13 las.fofn
-rw-r--r-- 1 jchin Domain Users 1571828 Jun 25 10:13 preads.ovl
lrwxrwxrwx 1 jchin Domain Users      93 Jun 25 10:13 preads4falcon.fasta -> /lustre/hpcprod/jchin/fc_run_test_Dec2014/Ecoli_increamental/1-preads_ovl/preads4falcon.fasta
-rw-r--r-- 1 jchin Domain Users       0 Jun 25 10:13 fc_ovlp_to_graph.log
-rw-r--r-- 1 jchin Domain Users   40351 Jun 25 10:13 utg_data
-rw-r--r-- 1 jchin Domain Users 1200189 Jun 25 10:13 sg_edges_list
-rw-r--r-- 1 jchin Domain Users    1167 Jun 25 10:13 ctg_paths
-rw-r--r-- 1 jchin Domain Users    2000 Jun 25 10:13 c_path
-rw-r--r-- 1 jchin Domain Users   90068 Jun 25 10:13 p_ctg_tiling_path
-rw-r--r-- 1 jchin Domain Users 4635573 Jun 25 10:13 p_ctg.fa
-rw-r--r-- 1 jchin Domain Users       0 Jun 25 10:13 falcon_asm_done
-rw-r--r-- 1 jchin Domain Users     413 Jun 25 10:13 a_ctg_tiling_path
-rw-r--r-- 1 jchin Domain Users   30098 Jun 25 10:13 a_ctg.fa
-rw-r--r-- 1 jchin Domain Users     419 Jun 25 10:13 a_ctg_base_titling_path
-rw-r--r-- 1 jchin Domain Users   30041 Jun 25 10:13 a_ctg_base.fa
drwxr-xr-x 2 jchin Domain Users    4096 Jun 25 10:13 .
```

```
$ ls -l /lustre/hpcprod/jchin/fc_run_test_Dec2014/Ecoli_increamental/1-preads_ovl/preads4falcon.fasta
-rw-r--r-- 1 jchin Domain Users 470107386 Jun 25 10:13 /lustre/hpcprod/jchin/fc_run_test_Dec2014/Ecoli_increamental/1-preads_ovl/preads4falcon.fasta
```

you should try to use `DBstat` to examine the read database.

**Comment by pb-jchin** [comment]
Do you sort the `*.las` files from the 2nd stage?

**Comment by jasperlinthorst** [comment]
Ok, so I changed to tag 0.2.2-p1 from FALCON-integrate repository and removed the -s (skip contained reads...) option from LA4Falcon and fixed a bug in my code wrt merging the preads into a single fasta file. Now my assembly indeed results in a single contig of +/-4.5MB. Thanks!

**Comment by mictadlo** [comment]
Hi @jasperlinthorst ,
Where could I find your snakefile?
Thank you in advance,
Michal
