### ISSUE TITLE
consensus failed

### ISSUE THREAD

**Issue by mahulchak** [PacificBiosciences/FALCON#116]
I am using FALCON-integrate on SGE. The pipeline seems to work fine up to creation of the las files within 0-rawreads folder. However, it stalls at the consensus step which outputs into the 0-rawreads/preads folder. When I checked the content the log files in this folder, I see this --
```
compute-7-2.local
Fri Jun 26 15:37:06 PDT 2015
Traceback (most recent call last):
  File "/dfs1/bio/mchakrab/pacbio/FALCON-integrate/fc_env/bin/fc_consensus.py", line 4, in <module>
    import pkg_resources
  File "/dfs1/bio/mchakrab/pacbio/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources.py", line 2716, in <module>
    working_set.require(__requires__)
  File "/dfs1/bio/mchakrab/pacbio/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources.py", line 685, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/dfs1/bio/mchakrab/pacbio/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources.py", line 588, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: networkx>=1.7
0.12user 0.10system 0:00.66elapsed 33%CPU (0avgtext+0avgdata 648768maxresident)k
23993inputs+8outputs (22major+24549minor)pagefaults 0swaps
```
Do you know what is causing this error? Is it missing certain packages? 
Thanks.
Mahul

**Comment by pb-jchin** [comment]
The error message says...
```
pkg_resources.DistributionNotFound: networkx>=1.7
```

**Comment by pb-cdunn** [comment]
A typical problem is when your build environment is different from your SGE runtime environment. You could `qsub make install`, but that's annoyingly slow.

I recommend using SGE for you development environment too. (That's what I do.)
```
qrsh
cd FALCON-integrate
make init
make virtualenv
make -j install
make test
```
If that works, then the next thing to be aware of is that **qrsh** might kill your interactive shell in 24 hours. You can use `qrsh -l h_rt=99:0:0`. Or you can use `qsub make run-ecoli` within FALCON-examples, which would let you run `qstat` from anywhere to see how it's doing.

**Comment by pb-cdunn** [comment]
Another possibility is that you didn't run `. fc_env/bin/activate` within your job. Our scripts should do that for you (and they have to re-activate at the top of bash scripts because virtualenv does not fully export its environment). But if you're running **fc_consensus.py** directly from your shell, then this is *possible*.

The immediate cause of error is that **fc_consensus.py** looks like this:
```py
#!/FALCON-integrate/fc_env/bin/python
# EASY-INSTALL-SCRIPT: 'falcon-kit==0.3.0','fc_consensus.py'
__requires__ = 'falcon-kit==0.3.0'
__import__('pkg_resources').run_script('falcon-kit==0.3.0', 'fc_consensus.py')
```
And the default *setuptools* on your grid machine [is too old](http://stackoverflow.com/questions/7446187/no-module-named-pkg-resources) or non-existent. But the root-cause is deeper.

**Comment by mahulchak** [comment]
Thank you so much. Turns out the problem was due to networkx. After I installed it, the issue went away.

**Comment by pb-cdunn** [comment]
Please explain. **FALCON-make** runs `python setup.py install` in FALCON, which should automatically install **networkx**.
