### ISSUE TITLE
bug in fc_ovlp_filter.py

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/FALCON#118]
See "BUGGY" at [this line](../blob/master/test/test_ovlp_filter.py#L16) of `filter_stage1()`. (Can't grep for "BUG" b/c "DEBUG" is everywhere.) I don't think `None` should appear there. Fix that, and add more (hopefully small) functional tests.

Impact: Tiny. This only fails to filter the first read, I think. Not sure though. I don't have time to look into it today.

**Comment by dgordon562** [comment]
This is probably unrelated, but I did have fc_ovlp_filter.py stall the other day.  Looking with top I noticed that LA4Falcon was not running (did it crash?) and fc_ovlp_filter.py was using 0.0% cpu time.  I let it go like this for 4 or 5 hours and then restarted falcon.  Falcon them completed without problems.  I've never had fc_ovlp_filter.py stall before.

**Comment by pb-cdunn** [comment]
Interesting. What branch? Could you point us to your fork?

**Comment by dgordon562** [comment]
I downloaded the main fork on June 5, 2015

Contact me offline (Jason has my contact info)

**Comment by pb-cdunn** [comment]
Ok. I'll ask him. `master`branch? Or the older `0.2.0` stuff?

**Comment by pb-cdunn** [comment]
I think I found another bug:
```python
            if q_s == 0:
                overlap_data["5p"] += 1
            elif q_e == q_l:
                overlap_data["3p"] += 1
```
That should be:
```python
            if q_s == 0:
                overlap_data["5p"] += 1
            if q_e == q_l:
                overlap_data["3p"] += 1
```
since it is perfectly ok to increment *both* 5p *and* 3p if there is alignment at both ends.

**Comment by pb-jchin** [comment]
I think if the query is NOT contained in the target, both code snippets will get the same result.  I will need to check where this code is again to ensure this is working for the non contained query reads.

**Comment by pb-cdunn** [comment]
The code is in #235.

**Comment by pb-jchin** [comment]
The `if`-`elif` block is within a `if not contained`.  However, the variable "contained" is never updated and the default value is `False` in `filter_stage1()`.  I think the variable is a left-over from some earlier version. We should remove the variable `contained` here and change the `if`-`else if` to two `if.

**Comment by pb-jchin** [comment]
The changes have been put in #235. Closing this issue.
