### ISSUE TITLE
how to confirm the rate of progress

### ISSUE THREAD

**Issue by AnWD** [PacificBiosciences/FALCON#121]
Hi Chin:
When the program come to 0-rawreads/ LAsort stage,I mean ,based on the number of ./sge_log/d_* finished files,I know  the first stage daligner was just completed.But when falcon is running the next step,LAsort , right? I do not know how to comfirm its progress.
# Daligner jobs (23653)
# Initial sort jobs (187489)
and during this stage,I can't see any file modification,only see that ：
top：
 PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
3910 smrtanal  20   0 3596m 1.3g 3728 R 100.0  0.2  30:59.30 fc_run.py

Is there anything I can do to comfirm its progress,or make sure that it's still running normally?
thank you!

**Comment by pb-jchin** [comment]
For old v0.2 branch, here are a list of related discsussin Issue #46 #70 #53 #43.  If you want to get latest developers' support, you will need to use the master branch, and you need to learn some process to keep pace with the developers. (This the a nature of a fast moving open source project.)

**Comment by AnWD** [comment]
Jason,thanks for your reply. I can't agree more about your advice.And I have seen the issue you provided,it seems that there is no answer about my question. Would you please give me a evaluation about my program progress? How to check the falcon version I upgraded in April.

**Comment by AnWD** [comment]
It seems that I can't rerun falcon wherever I want like makefile,is thar right?

**Comment by pb-jchin** [comment]
check https://github.com/PacificBiosciences/FALCON/wiki/FAQs

**Comment by AnWD** [comment]
thanks.
