### ISSUE TITLE
can falcon read bax.h5 files directly?

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#124]
(doesn't hurt to ask...)

**Comment by pb-jchin** [comment]
not really.  you will need to some tools from pbcore package to dump the reads in fasta files.  I have not done it recently, so I don't know what the most up-to-date code for that. (check out https://github.com/PacificBiosciences/pbcore and http://pacificbiosciences.github.io/pbcore/pbcore.io.html_
