### ISSUE TITLE
some basic questions about what Falcon is doing

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#126]
Hi, Chris and Jason,

I've read Gene Myer's blog (https://dazzlerblog.wordpress.com), but he doesn't answer these basic questions:

LAsort and LAmerge are supposed to sort and merge alignments.  But on what basis do they sort and merge?  alignment length?  alignment score?  (they can't do it by position in the genome because that isn't known at this stage...)

What does LA4Falcon do?  It is said to create a "pread", but what is that?  An error-corrected read?  How does the length of a pread differ from the length of a raw read?

(I'm putting these questions here because I'm sure others could benefit from the answers.  If they are already answered somewhere, please point me to it.)

Thanks!
David

**Comment by pb-jchin** [comment]
You should read this. 
https://github.com/PacificBiosciences/FALCON/wiki/Manual or
https://github.com/PacificBiosciences/FALCON/blob/v0.2.2/doc/falcon_manual.md 

There is defintion of "p-read" = "error-corrected reads" there. "error-corrected reads" is sometime too long...

some of more detailed are documented in this paper http://www.ncbi.nlm.nih.gov/pubmed/23644548

Also, @mchaisso can help to understand the background more too.

LAsort is sorting the alignment by "aread" (the internal read indentifer of the first read.)

**Comment by dgordon562** [comment]
Thanks!
