### ISSUE TITLE
Assembling a midsize, repetitive genome w/ FALCON

### ISSUE THREAD

**Issue by peterdfields** [PacificBiosciences/FALCON#127]
Hi. I'm trying to use FALCON to assemble a small to midsize genome (~200 to 230Mb), where it's known that the genome is highly repetitive. I'm trying to optimize the cfg settings to increase the assembly length , which is quite short falling between 120 and 140Mb. Using Celera Assembler 8.3rc1, with -sensitive setting, I was able to get an assembly length closer to the expected size at ~ 200Mb. Using the following settings (essentially the dmel example, with a shorter length cutoff, as around 1/4 of the reads are from an earlier chemistry), all on filtered subreads:

```
[General]
# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn
job_type= local
input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 6000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 6000


sge_option_da =
sge_option_la =
sge_option_pda =
sge_option_pla =
sge_option_fc =
sge_option_cns =
pa_concurrent_jobs = 7
ovlp_concurrent_jobs = 7

pa_HPCdaligner_option =  -v -dal128 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal128 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 7

overlap_filtering_setting = --max_diff 30 --max_cov 60 --min_cov 5 --n_core 7 
```

The DBstats output is as follows for the above settings

```
Statistics for all wells in the data set

      1,955,783 reads       out of       3,382,306    42.2% loss
  9,015,643,499 base pairs  out of  13,833,928,954    34.8% loss

Base composition: 0.304(A) 0.214(C) 0.203(G) 0.280(T)

          4,609 average read length
          3,401 standard deviation

Distribution of Read Lengths (Bin size = 1,000)

    Bin:      Count  % Reads  % Bases   Average
 47,000:          1      0.0      0.0    47224
 46,000:          1      0.0      0.0    47047
 45,000:          1      0.0      0.0    46390
 44,000:          0      0.0      0.0    46390
 43,000:          1      0.0      0.0    45554
 42,000:          3      0.0      0.0    44260
 41,000:          1      0.0      0.0    43897
 40,000:          3      0.0      0.0    42927
 39,000:          4      0.0      0.0    41985
 38,000:          4      0.0      0.0    41296
 37,000:          2      0.0      0.0    40934
 36,000:         10      0.0      0.0    39459
 35,000:         18      0.0      0.0    37976
 34,000:         30      0.0      0.0    36672
 33,000:         27      0.0      0.0    35854
 32,000:         41      0.0      0.1    34914
 31,000:         57      0.0      0.1    33952
 30,000:         72      0.0      0.1    33043
 29,000:         90      0.0      0.1    32169
 28,000:        140      0.0      0.2    31157
 27,000:        152      0.0      0.2    30314
 26,000:        181      0.0      0.3    29487
 25,000:        248      0.1      0.3    28573
 24,000:        365      0.1      0.4    27545
 23,000:        409      0.1      0.6    26654
 22,000:        548      0.1      0.7    25706
 21,000:        742      0.2      0.9    24709
 20,000:      1,014      0.2      1.1    23680
 19,000:      1,392      0.3      1.4    22622
 18,000:      1,919      0.4      1.8    21555
 17,000:      2,808      0.5      2.3    20439
 16,000:      3,971      0.7      3.1    19331
 15,000:      5,930      1.0      4.1    18196
 14,000:      8,655      1.5      5.5    17077
 13,000:     12,874      2.1      7.4    15964
 12,000:     19,450      3.1     10.1    14851
 11,000:     28,575      4.6     13.7    13774
 10,000:     41,993      6.7     18.6    12719
  9,000:     61,555      9.9     25.0    11683
  8,000:     90,827     14.5     33.6    10655
  7,000:    132,257     21.3     44.5     9643
  6,000:    187,448     30.9     58.0     8659
  5,000:    194,230     40.8     69.9     7897
  4,000:    170,826     49.5     78.4     7296
  3,000:    212,583     60.4     86.6     6608
  2,000:    272,034     74.3     94.1     5836
  1,000:    275,671     88.4     98.7     5147
      0:    226,620    100.0    100.0     4609
```

The FAQ about overlap mapping seems broken https://github.com/PacificBiosciences/FALCON/blob/master/doc/falcon_manual.md#overlap-filtering
Though it seems like that sort of analysis would be useful to figure out how best to increase assembly length. 

I've looked at a couple of issues, including #62 about read loss which seems substantial here, #28 about shorter than expected assembly, and #76 for coverage issues. The following are 5' and 3' overlap plots, (trimmed to fall between 0 and 100):

![5primeplot](https://cloud.githubusercontent.com/assets/202746/8521593/8a349444-23e5-11e5-86f6-a30433d4cbbd.jpeg)

and 

![3primeplot](https://cloud.githubusercontent.com/assets/202746/8521598/92ee8b26-23e5-11e5-89f9-a42383f41334.jpeg)

All recommendations or further questions welcome.

**Comment by pb-cdunn** [comment]
Dr. Chin might have something more concrete to say, but I have some questions.

Which commit (SHA1) are you using? Try the master branch. (v0.2.2 is the default.) And try FALCON-integrate, if you're not already.

Can you share your test-case with us? Might be useful.

**Comment by peterdfields** [comment]
I used the FALCON-integrate version (f1569366ccb7b810fe1e3bf56feaf531933d148b) I believe. Could you explain to me a bit more about how I can run the assembly process different for FALCON-integrate? And will it introduce any problems since I'm using job_type= local?

**Comment by pb-jchin** [comment]
try to add `-a` in `pa_DBsplit_option`. Your SMRTbell template might short. You might loose some coverage (from what I can see out of the DBstats output) due to not including the 2nd subreads from the same SMRTbell.

**Comment by peterdfields** [comment]
Okay, I will do that now. The reads deriving from the earlier chemistry constitute ~12-15X  (out of a total coverage ~ 60X) of the total coverage. Would it be better or worse to throw these out?

**Comment by pb-jchin** [comment]
try to use them unless one figures out some good reason to throw them away...

**Comment by peterdfields** [comment]
The DBstats output with the current run is the same as above with the -a option added (though the analysis is still running). The only modification made to the cfg script was to:

```
pa_DBsplit_option = -a -x500 -s400

```
Is this an indication that these reads are still not being used?

**Comment by pb-jchin** [comment]
Did you re-geneater the DB? (If you just re-run `fc_run.py`, it may re-use the old DB.) 

Here is the meaning of `-a`. It is unlikely that the DBstat will not change unless there is something unusual:
```
DBsplit [-a] [-x<int>] [-s<int(200)>] <path:db|dam>

Divide the database <path>.db or <path>.dam conceptually into a series of blocks referable to on the command line as <path>.1, <path>.2, … If the -x option is set then all reads less than the given length are ignored, and if the -a option is not set then secondary reads from a given well are also ignored. The remaining reads, constituting what we call the trimmed DB, are split amongst the blocks so that each block is of size -s * 1Mbp except for the last which necessarily contains a smaller residual. The default value for -s is 200Mbp because blocks of this size can be compared by our “overlapper” dalign in roughly 16Gb of memory. The blocks are very space efficient in that their sub-index of the master .idx is computed on the fly when loaded, and the .bps and .qvs files (if a .db) of base pairs and quality values, respectively, is shared with the master DB. Any relevant portions of tracks associated with the DB are also computed on the fly when loading a database block.
```

**Comment by peterdfields** [comment]
It should be entirely new (I renamed all the previous run's directories with a suffix to keep track of intermediate files from different settings), and so the 0-rawreads directory, as well as the others, were generated anew.

**Comment by pb-jchin** [comment]
It is unlikely the database (and the assembly) looks the same with `-a` and without `-a`. Can you rebuild the DB with and without  `-a` and using `DBstat` to check whether they the same? If the database is indeed different but the assembly results are the same, then one might need to look for other causes.

**Comment by peterdfields** [comment]
There's no change in the DBstat output whether the -a is included or not, at least with the present setup I'm trying. I tried both deleting/moving/renaming the whole set of directories generated as part of the fc_run.py script. It's clear that I must be doing something wrong but I'm not sure what. I've tried to make the tests by only modifying the .cfg script, not executing individual steps outside the scripts that are generated. Is there a set of commands outside of modifying the .cfg file and running the fc_run.py that would allow for me to determine what might be going wrong?

**Comment by pb-cdunn** [comment]
Would it be possible for you to make your raw reads available to us? Maybe via *ftp:* or *http:*? I can give you a private email address if that would help.

**Comment by peterdfields** [comment]
sure. please send the necessary info to peter.fields@unibas.ch

**Comment by DamienFr** [comment]
Hello everybody,

I read your topic, and i really wonder if you did or did not obtain your 200Mb assembly from Falcon at the end.
Please keep us updated, right now reading the topic is frustrating: it is like watching a scratched dvd that would cut in the middle ;)

Thanks in advance,
Damien

**Comment by pb-cdunn** [comment]
I'm not sure whether that would be confidential information from @peterdfields. But in general, yes, we are able to produce 200Mb assemblies from Falcon.
