### ISSUE TITLE
missing some .las files from d_aligner

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#129]
Hi, Chris or Jason,

I am missing several las files in the 0-rawreads stage.  LAsort correctly reports them as missing since the symbolic link is missing.    Is there any way to figure out which job_ directory they should have been in (or perhaps still are there)?

For example,
there should have been a 

/(longpath)/0-rawreads/m_00080/raw_reads.80.raw_reads.152.C0.las -> /(longpath)/0-rawreads/job_4f1725ec/raw_reads.80.raw_reads.152.C0.las

where I don't know the  "4f1725ec" but I'm trying to determine it.

I am guessing that it is missing from the job_ directory and d_aligner had some problem, but want to check for sure.

So which job_ directory?

Thanks!
David

**Comment by pb-cdunn** [comment]
First, look in `sge_log/`. Those are logs from SGE jobs, and you should be able to find the job id there somewhere.

To figure out which job *should* have created `*.80.*.152.*`, try this:

    find . -name 'rj_*.sh'|xargs grep daligner |grep 'raw_reads.80 '|grep 'raw_reads.152'

For example, for `*.11.*.20.*` in E.coli:

    ./job_18e96948/rj_18e96948.sh:time daligner -v -t16 -H12000 -e0.7 -s1000 raw_reads.20 raw_reads.9 raw_reads.10 raw_reads.11 raw_reads.12

We have some redundancy in naming conventions, but the info is all there.

**Comment by dgordon562** [comment]
Great!  Thanks!

Here is some more info for the documentation:

Each job_ directory is associated with a number N.  That job_ directory has all of the las files for N and all x < N.  For example, if N is 62 for this job_ directory, then it will have:

raw_reads.5.raw_reads.62.N1.las
raw_reads.62.raw_reads.5.N1.las

However, it will not have 

raw_reads.67.raw_reads.62.N1.las
That las file will be in the job_ directory associated with N=67.

You can tell what N is  for a particular job directory by looking at the rj_*.sh command in the job directory.  The first raw_reads file on that line will tell you the value of N.  For example,

/usr/bin/time daligner -v -t16 -H6000 -e0.7 -s1000 raw_reads.62 raw_reads.1 raw_reads.2 ...

shows you that N = 62 for this job_ directory.

The las files in a job_ directory have symbolic links to them from the m_ directories.  Las files have 2 numbers in them such as:
raw_reads.7.raw_reads.62.N3.las
The first number in the las file (in this case "7") tells you which m_ directory is linked to this las file, in this case it is m_00007

(I know it is detailed, but very useful in debugging and will save you and Jason lots of questions.)

**Comment by dgordon562** [comment]
One more sentence:

The *larger* number (which could be the first or the second number) tells you which job_ directory this las file will be in.  In this example, raw_reads.7.raw_reads.62.N3.las will be in the job_ directory with N = 62.

**Comment by pb-cdunn** [comment]
> That job_ directory has all of the las files for N and all x < N.

Not quite, and I'm surprised if you're seeing that. It won't have anything `> N`, but the stuff `< N` can be spread through several job directories. A given N can be the left-side for multiple jobs. It depends on the settings for daligner, which should be based on available memory.

But thanks. That would be good in the wiki somewhere. I'll copy it.

**Comment by dgordon562** [comment]
And one more sentence still:

There can be multiple job_ directories for the same N.  In my experience a single job_ won't have files for more than about 104 x's where x < N.  So if N = 300, it will put x = 1 to 104 in one job directory, x = 105 to 209 in the next and 210 to 313 in a 3rd.

**Comment by dgordon562** [comment]
crossing posts.  thanks for the catch.
I think all of this is way beneath Gene Myers to document, but still useful info so someone else doesn't have to re-research it.
