### ISSUE TITLE
Warning about using Falcon in a disk with quotas

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#133]
If the disk fills up to the level of the quota, the entire Falcon assembly may become corrupted and you will need to delete everything and start the assembly over from the beginning.

The reason is that in many case daligner will not crash when no more files can be written--it simply writes 0-length or truncated files, but will blithely continue on, and the done flag will be set, so fc_run.py will not know anything is wrong.  The Falcon assembly will then start crashing at the LAsort stage.  Restarting Falcon will not work.  It becomes difficult to determine which job_ directories are corrupted and which are not.

Chris:  Might be good to put in the wiki?

**Comment by pb-cdunn** [comment]
Oh, that is interesting. We'll have to address that someday. Copied to wiki. Thx.
