### ISSUE TITLE
Falcon Master Branch vs Default Branch

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#134]
Hi, Chris/Jason,

1)  Have you made any daligner changes since v0.2.2?
2)  Can I use v0.2.2 to run daligner, then kill fc_run.py and restart Falcon with the Master branch?
(sounds crazy, I know, but it will take me more than this afternoon to get the master branch running and I don't want to lose the weekend's worth of daligner jobs).

Thanks!
David

**Comment by pb-cdunn** [comment]
Hmm. Let's see. In FALCON-integrate:
```
$ git diff 0.2.2 0.3.0 -- DALIGNER
diff --git a/DALIGNER b/DALIGNER
index aea1a1d..c6cda80 160000
--- a/DALIGNER
+++ b/DALIGNER
@@ -1 +1 @@
-Subproject commit aea1a1dfbdac10a50a4bfbd81292842c7a7b4828
+Subproject commit c6cda805f9425658362b21cbd00ddf3ca8b7cb8b
```
Those diffs can be compared here:
* https://github.com/PacificBiosciences/DALIGNER/compare/aea1a1dfbdac10a50a4bfbd81292842c7a7b4828...c6cda805f9425658362b21cbd00ddf3ca8b7cb8b

That's a lot. Might work; might not.

**Comment by pb-jchin** [comment]
No. v0.2.2 is designed to use with older version of daligner.  Gene made some fundemental changes after that. We need to adapt to the newer version. The DB formats are not compatible. Gene did provide some tools to convert them but I have not tried them out myself.
