### ISSUE TITLE
question on header in p_ctg.fa

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#138]
If a sequence has a header like this:

>000000F 000084222:B~000072603:B~000049555:E~000049555:E ctg_linear 221334 933548

what is the "933548"?

**Comment by pb-jchin** [comment]
you can ignore that for most of time. 221334 is the estimated contig length.   933548 is the number of overlapped bases in the contig path.

**Comment by pb-cdunn** [comment]
Noted in FAQ.

**Comment by ebioman** [comment]
Hi
The link in the FAQ is broken.
If you say it is the estimated length, what is that supposed to mean. Is it the actual length of this contig or not ?
