### ISSUE TITLE
want pypeflow's logger messages directed to a file

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#139]
Is there a way to have pypeflow's logger messages sent to a file instead of stderr other than just doing it on the command line?  Even better, can just logger info messages be sent to a file, and warning/fatal ones be sent to stderr?

**Comment by pb-cdunn** [comment]
Yes, that's all completely configurable. Look first at `logging.ini` in **FALCON-examples**. (Even if you aren't using that package, you can use the configuration there.) It sends some logging to stderr, above some level, and the more detailed logging (along with the less detailed) is split into 2 files, depending on the source.

For details on Python logging:
* https://docs.python.org/2/library/logging.config.html
* https://docs.python.org/2/howto/logging.html#logging-advanced-tutorial
* https://docs.python.org/2/howto/logging-cookbook.html#logging-cookbook

Currently, you pass `logging.ini` as the 2nd argument:

    fc_run.py fc_run.cfg logging.ini

**Comment by pb-cdunn** [comment]
[Added to FAQ](https://github.com/PacificBiosciences/FALCON/wiki/FAQs#how-do-i-configure-logging).
