### ISSUE TITLE
running Falcon on corrected reads 

### ISSUE THREAD

**Issue by chklopp** [PacificBiosciences/FALCON#140]
Is it possible to run falcon without the correction part of the process?

Cheers,

Christophe

**Comment by pb-cdunn** [comment]
Yes.
* https://github.com/PacificBiosciences/FALCON/wiki/Manual#raw-sub-reads-overlapping-for-error-correction

>  If you set the option `input_type = preads` rather than `input_type = raw`, **fc_run.py** will assume the fasta files in input_fofn are all error-corrected reads and it will ignore any error correction step and go directly into the final assembly overlapping step.

Especially note the discussion of *length cutoff*.

**Comment by chklopp** [comment]
Thank you.
