### ISSUE TITLE
ridiculous # of daligner jobs

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#141]
I'm assemblying just 700 .bax.h5 files.  But Falcon has create 3.4 million daligner jobs.  This is the main branch of Falcon.  The previous version of Falcon created 1300 daligner jobs for 546 of these 700 .bax.h5.   

Furthermore, fc_run.py never submits these jobs.  Rather it stops with this error:
```
2015-07-21 21:37:33,447 - pypeflow.controller - INFO - _refreshTargets() finished with no thread running and no new job to submit
2015-07-21 21:37:33,447 - pypeflow.controller - INFO - _refreshTargets() finished with no thread running and no new job to submit
```
and stops giving any output.

I've got to get this assembled right away and will not be allowed time to do debugging.  Any quick suggestions before I'm forced to revert old version of Falcon?

**Comment by dgordon562** [comment]
Perhaps it is something in my cfg file:


input_fofn = input.fofn
input_type = raw
length_cutoff = 10000
length_cutoff_pr = 6000
sge_option_da = -pe serial 4 -l mfree=7.5G -q all.q -m a -M dgordona@uw.edu
sge_option_la = -pe serial 6 -l mfree=6G -q all.q -l disk_free=60G -soft -l ssd=TRUE -soft -l falcon_local_disk_1=TRUE -m a -M dgordona@uw.edu
sge_option_pda = -pe serial 4 -l mfree=10G -l ssd=FALSE -q all.q  -m a -M dgordona@uw.edu
sge_option_pla = -pe serial 2 -l mfree=6G -soft -l ssd=TRUE -soft -l falcon_local_disk_2=TRUE -q all.q  -m a -M dgordona@uw.edu
sge_option_fc = -pe serial 6 -l mfree=6G -q all.q  -m a -M dgordona@uw.edu
sge_option_cns = -pe serial 2 -l mfree=7G -q all.q  -m a -M dgordona@uw.edu
pa_concurrent_jobs = 200
ovlp_concurrent_jobs = 200
cns_concurrent_jobs = 200
pa_HPCdaligner_option =  -v -dal4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal128 -t32 -h60 -e.96 -l500 -s1000
pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6 --output_dformat
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24

**Comment by dgordon562** [comment]
I should also mention that I had no problem assemblying ecoli with this same version/virtual environment.

**Comment by mseetin** [comment]
You should increase the -dal flag in pa_HPCdaligner_option from 4 to about 128 or so.  I would also increase the -s flags in pa_DBsplit_option and ovlp_DBsplit_option from 50 to about 400 or so.  Using 4 and 50, respectively, is only appropriate for E. coli.

**Comment by dgordon562** [comment]
Thank you!  I owe you one!  (saved my butt)

**Comment by mseetin** [comment]
While I'm at it, your choice of min_cov at 20 is almost certainly only appropriate for E. coli and will likely result in assembly only a fraction of your expected genome size.  Few people have enough coverage to meet that standard for any non-E.-coli organism.  I would pick something like 2-5 as a first guess.

**Comment by dgordon562** [comment]
thank you!  Do have a sample cfg for human on the web or that you could post here?  (Having trouble with git-sym so haven't generated FALCON-examples)

What is your name, so I can thank you?

**Comment by mseetin** [comment]
I'm Matt Seetin.  This is a sample cfg for human-scale assembly from Falcon 0.2.2: 

https://github.com/PacificBiosciences/FALCON/blob/master/examples/fc_run_LG.cfg

**Comment by dgordon562** [comment]
Thanks, Matt!

**Comment by dgordon562** [comment]
I notice a few other differences:

I have 
falcon_sense_option = --n_core 6
you have 16

I have:

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 2 --bestn 10

and he has --max_diff 60 --max_cov 60 and no --bestn

Should I change to yours?  What do these mean?

**Comment by mseetin** [comment]
These flags are described in the most detail here, but, long story short, if the repetitiveness of your genome is cramping your style to the point of causing your cluster to crash, go with the 60 numbers, but if your system is great, then maybe you can get away with 100.

**Comment by dgordon562** [comment]
Thanks!

Primate genome.  Too repetitive?  At what stage would the cluster crash?

How about the --n_core of falcon_sense_option?

**Comment by pb-cdunn** [comment]
I know it's hard to find, but some of that is described [in the wiki](https://github.com/PacificBiosciences/FALCON/wiki/Manual).

**Comment by dgordon562** [comment]
Thanks, Chris.
