### ISSUE TITLE
Stop running virtualenv-activate within scripts

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/FALCON#143]
The environment should be set up before the script starts.

dgordon has had problems using virtualenv (e.g. [#137](https://github.com/PacificBiosciences/FALCON/issues/137#issuecomment-121681632) and [#142](https://github.com/PacificBiosciences/FALCON/issues/142#issuecomment-123847311)), so I want to decouple, though we'll still use it within FALCON-integrate.

Not high priority, but I'll get to it eventually, without objection.

**Comment by pb-jchin** [comment]
@pb-cdunn  can you link the corresponded changes in FALCON-integrate for tracking purpose? Thanks.
