### ISSUE TITLE
urgent:  daligner repeatedly crashing at same spot

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#147]
See below for the sge_log file (partial).  In both crashes, it crashed when comparing raw_reads.545 to raw_reads.193

How about if I just remove raw_reads.193 from the list from daligner?

Any other changes I must make for this assembly to run to completion?

(I need to report to the boss on this assembly in 1 hour.)
```
Comparing c(raw_reads.545) to raw_reads.193

   Capping mutual k-mer matches over 10000 (effectively -t100)
   Hit count = 997,361,227
   Highwater of 39.67Gb space
*** glibc detected *** daligner: free(): invalid pointer: 0x00002bb67c0008c0 ***
======= Backtrace: =========
/lib64/libc.so.6[0x37b6c75e66]
daligner[0x4097a2]
daligner[0x406f1d]
daligner[0x402817]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x37b6c1ed5d]
daligner[0x401339]
======= Memory map: ========
00400000-00421000 r-xp 00000000 00:36 3895273357                         /net/gs/vol1/home/dg
ordon/falcon150714/FALCON-integrate/DALIGNER/daligner
00620000-00621000 rw-p 00020000 00:36 3895273357                         /net/gs/vol1/home/dg
ordon/falcon150714/FALCON-integrate/DALIGNER/daligner
00621000-00624000 rw-p 00000000 00:00 0 
01d80000-01dd9000 rw-p 00000000 00:00 0                                  [heap]
37b6800000-37b6820000 r-xp 00000000 fd:00 41418757                       /lib64/ld-2.12.so
37b6a1f000-37b6a20000 r--p 0001f000 fd:00 41418757                       /lib64/ld-2.12.so
37b6a20000-37b6a21000 rw-p 00020000 fd:00 41418757                       /lib64/ld-2.12.so
37b6a21000-37b6a22000 rw-p 00000000 00:00 0 
37b6c00000-37b6d8a000 r-xp 00000000 fd:00 41418763                       /lib64/libc-2.12.so
37b6d8a000-37b6f8a000 ---p 0018a000 fd:00 41418763                       /lib64/libc-2.12.so
.
.
.
7fffbc271000-7fffbc2e3000 rw-p 00000000 00:00 0                          [stack]
7fffbc3ff000-7fffbc400000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
/var/spool/uge/e205/job_scripts/6820149: line 7: 22146 Aborted                 (core dumped) daligner -v -t16 -H10000 -e0.7 -s1000 raw_reads.545 raw_reads.110 raw_reads.111 raw_reads.112 raw_reads.113 raw_reads.114 raw_reads.115 raw_reads.116 raw_reads.117 raw_reads.118 raw_reads.119 raw_reads.120 raw_reads.121 raw_reads.122 raw_reads.123 raw_reads.124 raw_reads.125 raw_reads.126 raw_reads.127 raw_reads.128 raw_reads.129 raw_reads.130 raw_reads.131 raw_reads.132 raw_reads.133 raw_reads.134 raw_reads.135 raw_reads.136 raw_reads.137 raw_reads.138 raw_reads.139 raw_reads.140 raw_reads.141 raw_reads.142 raw_reads.143 raw_reads.144 raw_reads.145 raw_reads.146 raw_reads.147 raw_reads.148 raw_reads.149 raw_reads.150 raw_reads.151 raw_reads.152 raw_reads.153 raw_reads.154 raw_reads.155 raw_reads.156 raw_reads.157 raw_reads.158 raw_reads.159 raw_reads.160 raw_reads.161 raw_reads.162 raw_reads.163 raw_reads.164 raw_reads.165 raw_reads.166 raw_reads.167 raw_reads.168 raw_reads.169 raw_reads.170 raw_reads.171 raw_reads.172 raw_reads.173 raw_reads.174 raw_reads.175 raw_reads.176 raw_reads.177 raw_reads.178 raw_reads.179 raw_reads.180 raw_reads.181 raw_reads.182 raw_reads.183 raw_reads.184 raw_reads.185 raw_reads.186 raw_reads.187 raw_reads.188 raw_reads.189 raw_reads.190 raw_reads.191 raw_reads.192 raw_reads.193 raw_reads.194 raw_reads.195 raw_reads.196 raw_reads.197 raw_reads.198 raw_reads.199 raw_reads.200 raw_reads.201 raw_reads.202 raw_reads.203 raw_reads.204 raw_reads.205 raw_reads.206 raw_reads.207 raw_reads.208 raw_reads.209 raw_reads.210 raw_reads.211 raw_reads.212 raw_reads.213 raw_reads.214 raw_reads.215 raw_reads.216 raw_reads.217 raw_reads.218
touch /net/eichler/vol24/projects/whole_genome_assembly/nobackups/gorilla/gor150721/0-rawreads/job_51c19d14/job_51c19d14_done.exit
+ touch /net/eichler/vol24/projects/whole_genome_assembly/nobackups/gorilla/gor150721/0-rawreads/job_51c19d14/job_51c19d14_done.exit
```

**Comment by pb-cdunn** [comment]
Well, it can be tricky. You need to modify `0-rawreads/run_jobs.sh`. Then you can re-run that directly.

**Comment by dgordon562** [comment]
Thanks VERY much for your quick response.

I have daligner running again removing just the offending raw_reads.193 

when I modify run_jobs.sh, besides changing this daligner line, I assume I must also change some of the LAsort and LAmerge lines?  

Also, I should give you some context:  there are 2040 daligner jobs in run_jobs.sh.   Of these, 2023 have now completed successfully and the remaining 17 (including this one problem one) are close to being finished.  This is a time-critical assembly so I definitely don't want to start over.

So my idea was to modify not run_jobs.sh, but rather job_(blah blah blah)/blah.sh

Presumably I will also have to modify some of the m_blah/blah.sh   It is this modification that I am least sure about.  Do I need to modify just one of them or all (God forbid) of them?

**Comment by pb-cdunn** [comment]
> when I modify run_jobs.sh, besides changing this daligner line, I assume I must also change some of the LAsort and LAmerge lines? 

Yes, that's what makes it tricky.

> So my idea was to modify not run_jobs.sh, but rather job_(blah blah blah)/blah.sh

Hmmm. I'd set the good files to read-only, to be safe. Those jobs are generated from run_jobs.sh, so in theory they would be regenerated. But your way might be a bit safer. Touching run_jobs.sh might force things to re-run because its timestamp changes.

> Do I need to modify just one of them or all (God forbid) of them?

Possibly all of them? You can look at `mains/run.py` to see what depends on what. If you delete the m_ stuff, they should get regenerated, and merging is much faster than daligner.

But sorry in advance if I'm wrong. We've never used this workflow. No guarantees.

**Comment by pb-jchin** [comment]
We can only guess what is going on.  what I suggest is to use "-M" to cap the memory usage and re-run 
this `daligner -v -t16 -H10000 -e0.7 -s1000 raw_reads.545 raw_reads.110 raw_reads.111 raw_reads.112 raw_reads.113 raw_reads.114 raw_reads.115 raw_reads.116 raw_reads.117 raw_reads.118 raw_reads.119 raw_reads.120 raw_reads.121 raw_reads.122 raw_reads.123 raw_reads.124 raw_reads.125 raw_reads.126 raw_reads.127 raw_reads.128 raw_reads.129 raw_reads.130 raw_reads.131 raw_reads.132 raw_reads.133 raw_reads.134 raw_reads.135 raw_reads.136 raw_reads.137 raw_reads.138 raw_reads.139 raw_reads.140 raw_reads.141 raw_reads.142 raw_reads.143 raw_reads.144 raw_reads.145 raw_reads.146 raw_reads.147 raw_reads.148 raw_reads.149 raw_reads.150 raw_reads.151 raw_reads.152 raw_reads.153 raw_reads.154 raw_reads.155 raw_reads.156 raw_reads.157 raw_reads.158 raw_reads.159 raw_reads.160 raw_reads.161 raw_reads.162 raw_reads.163 raw_reads.164 raw_reads.165 raw_reads.166 raw_reads.167 raw_reads.168 raw_reads.169 raw_reads.170 raw_reads.171 raw_reads.172 raw_reads.173 raw_reads.174 raw_reads.175 raw_reads.176 raw_reads.177 raw_reads.178 raw_reads.179 raw_reads.180 raw_reads.181 raw_reads.182 raw_reads.183 raw_reads.184 raw_reads.185 raw_reads.186 raw_reads.187 raw_reads.188 raw_reads.189 raw_reads.190 raw_reads.191 raw_reads.192 raw_reads.193 raw_reads.194 raw_reads.195 raw_reads.196 raw_reads.197 raw_reads.198 raw_reads.199 raw_reads.200 raw_reads.201 raw_reads.202 raw_reads.203 raw_reads.204 raw_reads.205 raw_reads.206 raw_reads.207 raw_reads.208 raw_reads.209 raw_reads.210 raw_reads.211 raw_reads.212 raw_reads.213 raw_reads.214 raw_reads.215 raw_reads.216 raw_reads.217 raw_reads.218`

there are many block affected. to hack it consistently for downstream might be tricky. (You can try the news less sensitive setting which could be more robust.)

**Comment by dgordon562** [comment]
Thanks, jason!  What value of M would you suggest?  (-M takes an integer, correct?)

**Comment by dgordon562** [comment]
i ran daligner like this (see below).  looks funny to me as though it is running twice,but it does give the expected output of .las files, I think.  So will this assembly be ok now?

> ll | grep \\.193\\.
-rw-rw-r--    1 dgordon dgordon_g 7328704 Jul 27 12:39 raw_reads.193.raw_reads.545.N3.las
-rw-rw-r--    1 dgordon dgordon_g 7387040 Jul 27 12:39 raw_reads.545.raw_reads.193.N3.las
-rw-rw-r--    1 dgordon dgordon_g 7782044 Jul 27 12:39 raw_reads.193.raw_reads.545.N2.las
-rw-rw-r--    1 dgordon dgordon_g 7931268 Jul 27 12:39 raw_reads.545.raw_reads.193.N2.las
-rw-rw-r--    1 dgordon dgordon_g 8169204 Jul 27 12:39 raw_reads.193.raw_reads.545.N0.las
-rw-rw-r--    1 dgordon dgordon_g 8286740 Jul 27 12:39 raw_reads.545.raw_reads.193.N0.las
-rw-rw-r--    1 dgordon dgordon_g 8265912 Jul 27 12:39 raw_reads.193.raw_reads.545.N1.las
-rw-rw-r--    1 dgordon dgordon_g 8221608 Jul 27 12:39 raw_reads.545.raw_reads.193.N1.las
-rw-rw-r--    1 dgordon dgordon_g 6127660 Jul 27 12:42 raw_reads.193.raw_reads.545.C3.las
-rw-rw-r--    1 dgordon dgordon_g 6194060 Jul 27 12:42 raw_reads.545.raw_reads.193.C3.las
-rw-rw-r--    1 dgordon dgordon_g 6348532 Jul 27 12:42 raw_reads.193.raw_reads.545.C2.las
-rw-rw-r--    1 dgordon dgordon_g 6466580 Jul 27 12:42 raw_reads.545.raw_reads.193.C2.las
-rw-rw-r--    1 dgordon dgordon_g 6882860 Jul 27 12:42 raw_reads.193.raw_reads.545.C0.las
-rw-rw-r--    1 dgordon dgordon_g 6974268 Jul 27 12:42 raw_reads.545.raw_reads.193.C0.las
-rw-rw-r--    1 dgordon dgordon_g 6994068 Jul 27 12:42 raw_reads.193.raw_reads.545.C1.las
-rw-rw-r--    1 dgordon dgordon_g 6918524 Jul 27 12:42 raw_reads.545.raw_reads.193.C1.las
(fc_env){dgordon}e186:/net/eichler/vol24/projects/whole_genome_assembly/nobackups/gorilla/gor150721/0-rawreads/job_51c19d14


> daligner -v -t16 -H10000 -e0.7 -s1000 raw_reads.545 raw_reads.193

Building index for raw_reads.545

   Kmer count = 399,670,644
   Using 11.91Gb of space
   Revised kmer count = 333,702,119
   Index occupies 4.97Gb

Building index for c(raw_reads.545)

   Kmer count = 399,670,644
   Using 11.91Gb of space
   Revised kmer count = 333,702,119
   Index occupies 4.97Gb

Building index for raw_reads.193

   Kmer count = 399,655,782
   Using 11.91Gb of space
   Revised kmer count = 334,780,204
   Index occupies 4.99Gb

Comparing raw_reads.545 to raw_reads.193

   Capping mutual k-mer matches over 10000 (effectively -t100)
   Hit count = 1,012,793,261
   Highwater of 40.13Gb space

     1,012,793,261 14-mers (6.329532e-09 of matrix)
         1,183,804 seed hits (7.398277e-12 of matrix)
         1,091,121 confirmed hits (6.819048e-12 of matrix)

Building index for raw_reads.193

   Kmer count = 399,655,782
   Using 11.91Gb of space
   Revised kmer count = 334,780,204
   Index occupies 4.99Gb

Comparing c(raw_reads.545) to raw_reads.193

   Capping mutual k-mer matches over 10000 (effectively -t100)
   Hit count = 997,361,227
   Highwater of 39.67Gb space

     997,361,227 14-mers (6.233088e-09 of matrix)
       1,005,751 seed hits (6.285521e-12 of matrix)
         913,381 confirmed hits (5.708247e-12 of matrix)
(fc_env){dgordon}e186:/net/eichler/vol24/projects/whole_genome_assembly/nobackups/gorilla/gor150721/0-rawreads

**Comment by pb-jchin** [comment]
if you get the necessary `*.las` and have the right sentinal file `*done`, the downstream should work.

**Comment by dgordon562** [comment]
Thanks, Jason!

**Comment by dgordon562** [comment]
Success!

Apparently
daligner a b c d e
gives the same results as:
daligner a b
daligner a c
daligner a d
daligner a e

and in this case, the latter did not run into the bug.

Gene is so far unresponsive.  Are any of you guys interested in reproducing/troubleshooting this daligner bug?  If so, I could provide the data

**Comment by pb-cdunn** [comment]
Sweet!

Yes, interested.  If the data-set is fairly small and we can repro with *only* daligner. Otherwise, there are other bugs to be addressed sooner.

**Comment by dgordon562** [comment]
Yes, you can reproduce it from the command line running daligner.

71 G for the .bps file

I don't know a method of getting it to you.  Do you have somewhere I can upload it?

**Comment by pb-cdunn** [comment]
That's too big for hosting. We'd need an ftp URL, I guess. If you can get a stack-trace, just post that.

**Comment by dgordon562** [comment]
is what I have at top inadequate?

**Comment by pb-cdunn** [comment]
We need filenames and line numbers in the backtrace. I"m not sure how you got a backtrace, but that's a good sign. Try building daligner with debug flags and running again. You can still optimize, e.g. (`-g -O2`).

**Comment by rhallPB** [comment]
Chris, Jason,
I have an internal example of this bug if you ever want to take a closer look.

**Comment by pb-jchin** [comment]
@rhallPB, I am not sure what you see is indeed the same. We will bring the discussion internally.

**Comment by pb-cdunn** [comment]
We can open a new issue if this recurs with a reproducible test-case.
