### ISSUE TITLE
No handlers for pypeflow.controller and missing bin/activate

### ISSUE THREAD

**Issue by DamienFr** [PacificBiosciences/FALCON#148]
Hello everyone,

I'm new on the forum, and quite new in long-reads bioinformatics processing as well.
After installing Falcon, i tested it with a small input file but i get some error messages.

I though maybe you know how to solve it. I've researched the web and the repository and found nothing about these errors.

>**user@server:~/FALCON> fc_run.py fc_run.cftg**
No target specified, assuming "assembly" as target
No handlers could be found for logger "pypeflow.controller"
/work/user/FALCON/0-rawreads/prepare_db.sh: line 1: /usr/local/bin/activate: No such file or directory
/work/user/FALCON/0-rawreads/job_29043a82/rj_29043a82.sh: line 1: /usr/local/bin/activate: No such file or directory
/work/user/FALCON/0-rawreads/m_00001/rp_00001.sh: line 1: /usr/local/bin/activate: No such file or directory
/work/user/FALCON/0-rawreads/preads/c_00001.sh: line 1: /usr/local/bin/activate: No such file or directory
/work/user/FALCON/1-preads_ovl/job_b38caf3c/rj_b38caf3c.sh: line 1: /usr/local/bin/activate: No such file or directory
/work/user/FALCON/1-preads_ovl/m_00001/rp_00001.sh: line 1: /usr/local/bin/activate: No such file or directory
/work/user/FALCON/2-asm-falcon/run_falcon_asm.sh: line 1: /usr/local/bin/activate: No such file or directory
**user@server:~/FALCON>**

Thanks in advance,
Damien

**Comment by pb-cdunn** [comment]
> No handlers could be found for logger "pypeflow.controller"

I think this means that you're using an old version. What commit are you using? Please tell us the result of this:

    cd FALCON
    git rev-parse HEAD

> prepare_db.sh: line 1: /usr/local/bin/activate: No such file or directory

This means you have not set up a Python **virtualenv**.

You are free to integrate however you choose, but I recommend that you *start* with **FALCON-integrate**.
* https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation

**Comment by DamienFr** [comment]
Hello,

Thanks for your answer.
I just installed Falcon-integrate, as you advised me. Thanks for the tip.

I still have the exact same error message.

The command you gave me got me this info :
>88f269bdcba3febc9b70a08aa43793d65432d8a2

**Comment by DamienFr** [comment]
Well, after installing the new version, i re-ran my project, and i still have the same issues ...

>user@server:~/FALCONINSTALL/FALCON-integrate/FALCON/build/scripts-2.7> fc_run.py /work/user/FALCON/fc_run.cftg
 No target specified, assuming "assembly" as target
/work/user/FALCONINSTALL/FALCON-integrate/FALCON/build/scripts-2.7/0-rawreads/prepare_db.sh: line 1: /usr/local/bin/activate: No such file or directory
.fasta for 'r'ot open /work/user/FALCON/input.subreads.fasta
DBsplit: Cannot open ./raw_reads.db for 'r'
cat: raw_reads.db: No such file or directory
HPCdaligner: Cannot open ./raw_reads.db for 'r'
No handlers could be found for logger "pypeflow.controller"
Skipping 'preads_norm', file is empty!
/work/user/FALCONINSTALL/FALCON-integrate/FALCON/build/scripts-2.7/2-asm-falcon/run_falcon_asm.sh: line 1: /usr/local/bin/activate: No such file or directory
find: ‘/work/user/FALCONINSTALL/FALCON-integrate/FALCON/build/scripts-2.7/1-preads_ovl/las_files’: No such file or directory

**Comment by pb-cdunn** [comment]
I think that you have not set up Python **virtualenv**.  Or you have not installed all executables into the virtualenv bin. Try running *all* these rules from the **FALCON-integrate** directory (in both README.md and travis.sh):
```
make init
make virtualenv
make check
make -j install
make test
```

**Comment by DamienFr** [comment]
Hello,

Bad settings for virtualenv was not the only problem, as we can see in the several lines of errors posted before.

My colleague (much more competent than me for installing tools on a server) contacted you privately  (someone else from your team ?) to tell you about the invisible caracter of the prepare_db.sh.

I couldn't explain clearly the problem myself, but it might be a good idea to clarify it a little bit here, for the googlers than will find this thread and want to solve the problem for themselves as well.

Anyway, thanks for the developement of the falcon tool and active posting here guys !

**Comment by pb-cdunn** [comment]
(Related to PacificBiosciences/FALCON-integrate#5.)

**Comment by pb-cdunn** [comment]
I like your avatar!
