### ISSUE TITLE
fc_graph_to_contig.py has dropped core 2x at the same location

### ISSUE THREAD

**Issue by cariaso** [PacificBiosciences/FALCON#149]
after 3h of runtime on 2-asm-falcon/run_falcon_asm.sh I'm reproducibly dropping core during fc_graph_to_contig.py

error message:
```
fc_graph_to_contig.py
+ fc_graph_to_contig.py
/opt/sge6/default/spool/exec_spool_local/node001/job_scripts/1474: line 11:  2652 Segmentation fault      (core dumped) fc_graph_to_contig.py
touch /mnt/work/falcon/run2/2-asm-falcon/falcon_asm_done.exit
```

first run failure:
```
root@master:/mnt/work/falcon/run2# ls -tral 2-asm-falcon.hide/
total 7687468
-rw-r--r-- 1 root root        675 Jul 28 04:17 run_falcon_asm.sh
-rw-r--r-- 1 root root       8892 Jul 28 04:23 las.fofn
-rw-r--r-- 1 root root  184818536 Jul 28 06:35 preads.ovl
lrwxrwxrwx 1 root root         54 Jul 28 06:35 preads4falcon.fasta -> /mnt/work/falcon/run2/1-preads_ovl/preads4falcon.fasta
-rw-r--r-- 1 root root  105925400 Jul 28 06:38 sg_edges_list
-rw-r--r-- 1 root root    1497012 Jul 28 06:40 c_path
-rw-r--r-- 1 root root   22184767 Jul 28 06:40 utg_data
-rw-r--r-- 1 root root   10302587 Jul 28 06:40 ctg_paths
-rw-r--r-- 1 root root    1597104 Jul 28 06:40 fc_ovlp_to_graph.log
-rw-r--r-- 1 root root          0 Jul 28 06:51 a_ctg_tiling_path
-rw-r--r-- 1 root root          0 Jul 28 06:51 a_ctg_base_tiling_path
-rw-r--r-- 1 root root  715128832 Jul 28 06:52 p_ctg.fa
-rw-r--r-- 1 root root    8388608 Jul 28 06:52 a_ctg.fa
-rw-r--r-- 1 root root    7340032 Jul 28 06:52 a_ctg_base.fa
-rw-r--r-- 1 root root   10485760 Jul 28 06:52 p_ctg_tiling_path
drwxr-xr-x 2 root root       4096 Jul 28 06:52 .
-rw-r----- 1 root root 6804254720 Jul 28 06:52 core
drwxr-xr-x 9 root root       4096 Jul 28 08:43 ..
```

second run failure, nearly identical:
```
total 7687432
drwxr-xr-x 9 root root       4096 Jul 28 08:43 ..
-rw-r--r-- 1 root root        675 Jul 28 08:46 run_falcon_asm.sh
-rw-r--r-- 1 root root       8892 Jul 28 08:53 las.fofn
-rw-r--r-- 1 root root  184818536 Jul 28 11:04 preads.ovl
lrwxrwxrwx 1 root root         54 Jul 28 11:04 preads4falcon.fasta -> /mnt/work/falcon/run2/1-preads_ovl/preads4falcon.fasta
-rw-r--r-- 1 root root  105925400 Jul 28 11:07 sg_edges_list
-rw-r--r-- 1 root root    1497012 Jul 28 11:09 c_path
-rw-r--r-- 1 root root   22184767 Jul 28 11:09 utg_data
-rw-r--r-- 1 root root   10302587 Jul 28 11:09 ctg_paths
-rw-r--r-- 1 root root    1597104 Jul 28 11:09 fc_ovlp_to_graph.log
-rw-r--r-- 1 root root          0 Jul 28 11:21 a_ctg_tiling_path
-rw-r--r-- 1 root root          0 Jul 28 11:21 a_ctg_base_tiling_path
-rw-r--r-- 1 root root    8388608 Jul 28 11:21 a_ctg.fa
-rw-r--r-- 1 root root    7340032 Jul 28 11:21 a_ctg_base.fa
-rw-r--r-- 1 root root   10485760 Jul 28 11:21 p_ctg_tiling_path
-rw-r--r-- 1 root root  715128832 Jul 28 11:21 p_ctg.fa
drwxr-xr-x 2 root root       4096 Jul 28 11:21 .
-rw-r----- 1 root root 6804217856 Jul 28 11:21 core
```

contents of sge_log ends with
```
-rw-r--r-- 1 root root  84694 Jul 28 04:16 rp_00122.sh-m_00122_preads-m_00122_preads.o1472
-rw-r--r-- 1 root root      0 Jul 28 04:17 run_falcon_asm.sh-falcon-falcon.po1473
-rw-r--r-- 1 root root 201479 Jul 28 06:52 run_falcon_asm.sh-falcon-falcon.o1473
drwxr-xr-x 9 root root   4096 Jul 28 08:43 ..
-rw-r--r-- 1 root root      0 Jul 28 08:46 run_falcon_asm.sh-falcon-falcon.po1474
drwxr-xr-x 2 root root 561152 Jul 28 08:46 .
-rw-r--r-- 1 root root 199669 Jul 28 11:21 run_falcon_asm.sh-falcon-falcon.o1474
```
contents of 2-asm-falcon/run_falcon_asm.sh
```
cat 2-asm-falcon/run_falcon_asm.sh

set -vex
trap 'touch /mnt/work/falcon/run2/2-asm-falcon/falcon_asm_done.exit' EXIT
source /mnt/work/falcon/fc_env/bin/activate
cd /mnt/work/falcon/run2/1-preads_ovl
DB2Falcon -U preads
cd /mnt/work/falcon/run2/2-asm-falcon
find /mnt/work/falcon/run2/1-preads_ovl/las_files -name "*.las" > las.fofn
fc_ovlp_filter.py --db /mnt/work/falcon/run2/1-preads_ovl/preads.db --fofn las.fofn --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --min_len 2000 > preads.ovl
ln -sf /mnt/work/falcon/run2/1-preads_ovl/preads4falcon.fasta .
fc_ovlp_to_graph.py preads.ovl --min_len 2000 > fc_ovlp_to_graph.log
fc_graph_to_contig.py
touch /mnt/work/falcon/run2/2-asm-falcon/falcon_asm_done
```
running on an r3.8xlarge, via starcluster. dedicated machine, freshly booted, no other processes running

help!

**Comment by pb-cdunn** [comment]
7GB core file. That can be hard to debug, but I'll give it a shot.
Could you make the following available to us?
```
sg_edges_list
utg_data
ctg_paths
preads4falcon.fasta
```
Maybe via dropbox. Compressed if possible. A tarball is fine. Whatever works for you. But first check the filesize of preads4falcon.fasta. Hopefully it's less than 100MB.

Also, please tell us the result of this:
```
cd FALCON
git rev-parse HEAD
```
Are you using FALCON-integrate for dependencies? If so, please tell me the SHA1 for that too. Otherwise, are you running `git submodule` within FALCON? Better give me as much info as possible to increase the chances of a proper repro.

**Comment by cariaso** [comment]
Ha, ha, not even close.
./1-preads_ovl/preads4falcon.fasta is 57G

cd ../FALCON-integrate/
root@master:/mnt/work/falcon/FALCON-integrate# git rev-parse HEAD
cb1116eb5e3531b8702c59b7a6c15518dd3fe789

root@master:/mnt/work/falcon/FALCON-integrate# cd FALCON
root@master:/mnt/work/falcon/FALCON-integrate/FALCON# git diff
root@master:/mnt/work/falcon/FALCON-integrate/FALCON# git rev-parse HEAD
cee6a580e97b209ff4d025b402a9f2c180c30bff

FALCON-integrate is at
*   cb1116e - (HEAD, origin/master, origin/HEAD, master) Merge pull request #2 from pb-jchin/pb-jchin_v0.3_test (4 weeks ago)
with the only difference being that I've replaced some of the 'qdel' commands with 'echo qdel', because qdelling 100 machines which have been running for hours, because one of them went over memory is criminal.


technically I can share everything via an s3 bucket, but need you to confirm that you want to pursue this given the size. 

regardless, I still need clearance from my management to consider if I have permission to share it.

if you've got an instrumented version of fc_graph_to_contig.py I can certainly run that.

I'll be at the NIST meeting.

**Comment by pb-cdunn** [comment]
./1-preads_ovl/preads4falcon.fasta is 57G

That might be too big to send. Try to run *only* **fc_graph_to_config.py**. Let's see how quickly it crashes. Also, watch peak memory if you can.

> I'll be at the NIST meeting.

You mean in last August? Ok. Me too.

**Comment by pb-cdunn** [comment]
Would you be willing to work with me on producing a [*minidump*](https://code.google.com/p/google-breakpad/wiki/GettingStartedWithBreakpad)? I'll set up [Linux integration for Google Breakpad](https://code.google.com/p/google-breakpad/wiki/LinuxStarterGuide) in our FALCON-integrate. See PacificBiosciences/FALCON-integrate#4.

I have to double-check this plan with our management, but I think that debugging your crash is pretty high priority. And being *able* to debug is pretty high too. However, we have some functionality tasks which might be higher.

**Comment by cariaso** [comment]
It takes ~9 minutes to dump core. 

I'm willing to work on the minidump approach.

**Comment by cariaso** [comment]
The first two failures were on a r3.8xlarge worker, but the problem reproduces when run on the c4.8xlarge master (which has much less memory), which is where I'm now testing. plenty of memory (~55G) remains free/cached. 

Mem:  61583276k total, 54675632k used,  6907644k free,    25572k buffers
Swap:        0k total,        0k used,        0k free, 53032136k cached

lsof and strace shows it has finished reading filehandle 3
/mnt/work/falcon/run2/1-preads_ovl/preads4falcon.fasta
has also read filehandle 4
/mnt/work/falcon/run2/2-asm-falcon/sg_edges_list
before the crash and seems to briefly have all of these files open shortly before the crash

fc_graph_ 47407 root    3r   REG  252,0 716148736 272146374 /mnt/work/falcon/run2/2-asm-falcon/p_ctg.fa
fc_graph_ 47407 root    4r   REG  252,0   8581120 272146375 /mnt/work/falcon/run2/2-asm-falcon/a_ctg.fa
fc_graph_ 47407 root    5w   REG  252,0   7852032 272146376 /mnt/work/falcon/run2/2-asm-falcon/a_ctg_base.fa
fc_graph_ 47407 root    6w   REG  252,0  11198464 272146377 /mnt/work/falcon/run2/2-asm-falcon/p_ctg_tiling_path
fc_graph_ 47407 root    7w   REG  252,0    126976 272146378 /mnt/work/falcon/run2/2-asm-falcon/a_ctg_tiling_path
fc_graph_ 47407 root    8w   REG  252,0    167936 272146379 /mnt/work/falcon/run2/2-asm-falcon/a_ctg_base_tiling_path
fc_graph_ 47407 root    9r   REG  252,0  10302587 272146373 /mnt/work/falcon/run2/2-asm-falcon/ctg_paths

virtual memory briefly spikes to ~8G while resident memory seems to be ~6.5G

**Comment by pb-jchin** [comment]
Just assign this issue to me. I think I know where the seg-fault is from.  When there is parallel paths in the assembly grap, we align the sequence of one path to the other. We will only output the alternative one if the difference is big. There are some boundary cases that break the alignment code. When I have time, I will look into it to make it mroe robust. There is a way to turn off the alignment checking to work around this problem for now.

**Comment by pb-jchin** [comment]
Here is the diff showing the temporary workaround is to disable the code for alignment checking. You will have more spurious associate contigs. Namely, some associated contigs are almost the same as the primary contigs. You will need to do your own alignments to remove the redundant associated contigs.

```
--- graph_to_contig.py  2015-06-28 20:37:24.786622000 -0700
+++ graph_to_contig2.py 2015-07-29 04:53:53.107688000 -0700
@@ -250,30 +250,8 @@
                 atig_output.append( (v, w, atig_path, total_length, total_score, base_seq, atig_path_edges, 1, 1) )


-                duplicated = True
-                for score, atig_path in a_ctg_group[ (v, w) ][1:]:
-                    atig_path_edges = zip(atig_path[:-1], atig_path[1:])
-                    sub_seqs = []
-                    total_length = 0
-                    total_score = 0
-                    for vv, ww in atig_path_edges:
-                        rid, s, t, aln_score, idt, e_seq = edge_data[ (vv, ww) ]
-                        sub_seqs.append( e_seq )
-                        total_length += abs(s-t)
-                        total_score += aln_score
-
-                    seq = "".join(sub_seqs)
-
-                    aln_data, x, y = get_aln_data(base_seq, seq)
-                    if len( aln_data ) != 0:
-                        idt =  1.0-1.0*aln_data[-1][-1] / aln_data[-1][-2]
-                        cov = 1.0*(aln_data[-1][3]-aln_data[-1][2])/aln_data[-1][4]
-                        if idt < 0.96 or cov < 0.98:
-                            duplicated = False
-                            atig_output.append( (v, w, atig_path, total_length, total_score, seq, atig_path_edges, idt, cov) )
-                    else:
-                        duplicated = False
-                        atig_output.append( (v, w, atig_path, total_length, total_score, seq, atig_path_edges, 0, 0) )
+                duplicated = False
+                atig_output.append( (v, w, atig_path, total_length, total_score, seq, atig_path_edges, 0, 0) )

                 if len(atig_output) == 1:
                     continue
```

**Comment by cariaso** [comment]
with an additional
seq = ''
to avoid the undefined variable, this works.

**Comment by conte1** [comment]
I was running into this issue running version 0.3.0 and the fix was implemented in 0.4.0 which gets around this error. Just an FYI for anyone else who might run into it. Thanks.

**Comment by liuqianhn** [comment]
Hi Dr. Chin,

I was confronted with the similar error below when I used FALCON-integrate for my project. May I know whether this issue is fixed in the version of FALSCON I used. How to solve this error? Thank you very much. 

```
[ql@biocluster FALCON-integrate]$ git rev-parse HEAD
c6da52c1a7154b585357be208b4b77ab9a4c8a31
```

The error is below:
```
fc_ovlp_to_graph.py preads.ovl --min_len 1000 > fc_ovlp_to_graph.log
+ fc_ovlp_to_graph.py preads.ovl --min_len 1000
fc_graph_to_contig.py
+ fc_graph_to_contig.py
/opt/gridengine/default/spool/dragon/job_scripts/110538: line 13:  4121 Segmentation fault      (core dumped) fc_graph_to_contig.py
```

The files under 2-asm-falcon is below
```
[ql@biocluster mmerge]$ ls -tral 2-asm-falcon/
total 4502164
-rw-r--r-- 1 ql wanglab       2065 Jul 19 23:53 run_falcon_asm.sh
-rw-r--r-- 1 ql wanglab       8881 Jul 19 23:53 las.fofn
-rw-r--r-- 1 ql wanglab     557707 Jul 19 23:53 preads.ovl
lrwxrwxrwx 1 ql wanglab         83 Jul 19 23:53 preads4falcon.fasta -> /home/ql /tutorial/falcon_test/Celegan2/mmerge/1-preads_ovl/preads4falcon.fasta
-rw-r--r-- 1 ql wanglab     295310 Jul 19 23:53 sg_edges_list
-rw-r--r-- 1 ql wanglab       2460 Jul 19 23:53 c_path
-rw-r--r-- 1 ql wanglab      44283 Jul 19 23:53 utg_data
-rw-r--r-- 1 ql wanglab      31846 Jul 19 23:53 ctg_paths
-rw-r--r-- 1 ql wanglab       1704 Jul 19 23:53 fc_ovlp_to_graph.log
-rw-r--r-- 1 ql wanglab          0 Jul 19 23:55 p_ctg_tiling_path
-rw-r--r-- 1 ql wanglab          0 Jul 19 23:55 a_ctg_base.fa
-rw-r--r-- 1 ql wanglab          0 Jul 19 23:55 a_ctg_all.fa
-rw-r--r-- 1 ql wanglab          0 Jul 19 23:55 a_ctg_tiling_path
-rw-r--r-- 1 ql wanglab          0 Jul 19 23:55 a_ctg_base_tiling_path
-rw-r--r-- 1 ql wanglab    6291456 Jul 19 23:55 p_ctg.fa
-rw------- 1 ql wanglab 4602953728 Jul 19 23:56 core.4121
drwxr-xr-x 2 ql wanglab       4096 Jul 20 02:15 .
drwxr-xr-x 8 ql  wanglab       4096 Jul 26 03:04 ..
```

**Comment by pb-jchin** [comment]
there could some strange situation of the tentative contigs are too short or some strange characters in the file that may cause the set-fault of the internal aligner used.  Can you turn off the alignment for de-duplication step to see if everything go through?

**Comment by liuqianhn** [comment]
Hi Dr. Chin,

Thank you very much for your quick reply. I will try. May I know how to turn off the de-duplication step? Thanks.

By the way, some reads have very high similarity. Will this cause some errors?  Thanks.

**Comment by pb-jchin** [comment]
@liuqianhn please see my comment from Jul 29, 2015

**Comment by liuqianhn** [comment]
Hi Dr. Chin,

Thanks.
