### ISSUE TITLE
is there a way to quickly figure out which d jobs should be run for certein ct jobs?

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/FALCON#152]
Dear Falcon developers,

I have some ct jobs that failed to due missing las files. I know I can go through the m jobs with same id to figure out which of the smaller, prerequisite las files are missing and then search through all d jobs to identify those to be re-run. Is there a quicker way to do this? Thanks!

**Comment by pb-cdunn** [comment]
We definitely want to ensure that a restart will use any existing .las files and just create new ones. Soon.

But there is a deeper problem when daligner fails in some scenario, so some .las files will never exist without a change in parameters. Do you know whether that was the case for you? Any clue as to why they were missing?

Also, please specify your FALCON-integrate commit, or at least your FALCON commit:

    git rev-parse HEAD

**Comment by yunfeiguo** [comment]
We replaced some compute nodes when some jobs are still running on it. So it is possible some las files failed to be copied from /tmp to falcon folder. This problem happened before and it was fixed after I re-run some daligner jobs.

We are using a forked version falcon. Briefly speaking, I added some commands to do file staging so local /tmp is utilized to speed up IO.

https://github.com/WangGenomicsLab/FALCON

**Comment by pb-cdunn** [comment]
A fork is fine, but you need to rebase onto our **master** branch.

We would be happy to include the local-staging code into the master branch. I might even be able to help you with the git rebasing. But I cannot spend time debugging old code. We have made many improvements.

**Comment by pb-cdunn** [comment]
Your forked is currently based here:
```
commit 58ebe7e7f4632e85a44aaac58ee7bd1778ef3fe4
Author: pb-jchin <jchin@pacificbiosciences.com>
Date:   Thu Apr 16 09:22:53 2015

    fix another missing local variable
```
That's 0.2.0.

**Comment by yunfeiguo** [comment]
I see, that makes sense. Thank you all the same!

I will write a script to go through all `.sh` files of daligner jobs to identify failed ones.

**Comment by pb-cdunn** [comment]
We have a much better system to handle that already, way better than the script you would use. There is really not that much code in this project, and I am willing to help you rebase. Strongly recommended.

**Comment by yunfeiguo** [comment]
Thank you so much for offering help. I actually haven't tried rebase before. Let's try it.

I have created a branch 'forRebase'. Which branch in https://github.com/PacificBiosciences/FALCON do you suggest to rebase to?

**Comment by pb-cdunn** [comment]
1. Fork **FALCON-integrate**: https://github.com/PacificBiosciences/FALCON-integrate
    * By using a fork, you'll have mostly the same dependencies as we have, but you can over-ride the **FALCON** version.
1. Clone your fork in a fresh repo.
    * Then edit `.gitmodules` from

            url = git://github.com/PacificBiosciences/FALCON.git
      to

            url = https://github.com/WangGenomicsLab/FALCON.git
    * Then

            git submodule update --init
            cd FALCON
            git remote add upstream git://github.com/PacificBiosciences/FALCON.git
            git fetch upstream
            git checkout -b pb upstream/master
            git push origin pb
            # That should push into your GitHub fork of FALCON.
            cd ..
            git add .gitmodules FALCON
            git commit -m 'use WangGenomics fork'
            git push origin master
            # That should push into your GitHub fork of FALCON-integrate.
1. To test, follow these directions: https://github.com/PacificBiosciences/FALCON-integrate/wiki
    * That proves that your environment is set up properly, so we have a basepoint.

Let me know when you've gotten that far. The next step will be rebasing.

**Comment by yunfeiguo** [comment]
Thanks. Let me try.

**Comment by yunfeiguo** [comment]
Hi Christopher, I just finished the two tests and they both worked.
```       
make run-synth0
make run-ecoli
```

**Comment by pb-cdunn** [comment]
* https://github.com/WangGenomicsLab/FALCON/pull/1/files

> -#  * Redistributions of source code must retain the above copyright
> -#  notice, this list of conditions and the following disclaimer.

Hey! Removing our copyright notice is illegal. I'm sure it was an accident, but please be careful. At least include the `LICENSE` file, which has the same notice.

**Comment by pb-cdunn** [comment]
I am taking your changes which copy the db files and symlink to them from the job directory. Nice idea. A very simple change.  But I won't keep your exact code. I'll point you to a new branch when I'm done.

What do you plan to do about this file? `src/py_scripts/fc_ovlp_to_graph.py`

That has been renamed to `src/py/mains/ovlp_to_graph.py`. I think Jason has made many improvements, but if you really want your changes, then you'll have to update that file yourself, on the new branch.

Then, I will recommend deleting your old branch. The rest of the diffs do not seem important.

**Comment by pb-cdunn** [comment]
If you can pull from my pb-cdunn fork of FALCON, you can try this now. Otherwise, wait for the pull-request #155 to be merged.

**Comment by yunfeiguo** [comment]
Thanks, Christopher! I copied `fc_ovlp_to_graph.py` from 010167a7f1f1e64e0b52e963edc7af170d49e102, so it's okay to discard changes and just use your `ovlp_to_graph.py`. I will try the merged code.

**Comment by pb-cdunn** [comment]
Wait! There is a bug on **master**. I must fix #156 first...

**Comment by pb-cdunn** [comment]
You can work around the problem short-term by adding `-V` (capital V, not `-v`) to all the qsub options, to pass along *all* environment-variables. But that's not such a good idea long-term.

**Comment by yunfeiguo** [comment]
Thanks.
