### ISSUE TITLE
falcon code changes

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#154]
this is just a plea that you only make falcon code changes that have strong benefits

there have been some changes that don't appear to have compelling value.  e.g, renaming jobs from d_ m_ ct_ to rj_ rp_ c_
or changing pread file extensions from .fa to .fasta

Since we have tools/code built around falcon, such minor changes are disruptive.

thanks!
david

**Comment by pb-jchin** [comment]
change `.fa` to `.fasta` is necessary as we can save intermidate files for loading into DAZZ_DB. The code `fasta2db` needs `.fasta` suffix rather than `.fa`  

The good thing about open source and using git is that all changes are open and trackable

**Comment by dgordon562** [comment]
Understand on the fasta.  Please just don't miss my general point.
