### ISSUE TITLE
--output_dformat should be the default; add new flag for old format

### ISSUE THREAD

**Issue by HenrivdGeest** [PacificBiosciences/FALCON#162]
First of all, credits for using pypeflow,  it does a good job in tracking any failed jobs!

pypeflow log: (removed some long paths)

2015-08-06 08:23:54,959 - fc_run - INFO - '..../falcon/1-preads_ovl/pdb_build_done.exit' generated. job: 'prepare_pdb.sh-build_pdb-build_pdb' exited.
2015-08-06 08:23:54,960 - fc_run - WARNING - '....../falcon/1-preads_ovl/pdb_build_done' is missing. job: 'prepare_pdb.sh-build_pdb-build_pdb' failed!
2015-08-06 08:23:54,960 - fc_run - WARNING - '..../falcon/1-preads_ovl/pdb_build_done' is missing. job: 'prepare_pdb.sh-build_pdb-build_pdb' failed!
2015-08-06 08:23:55,148 - pypeflow.controller - INFO - message for task://localhost/build_pdb: 'fail'

I have the fasta files in 0-rawreads/preads/out.****.fasta:

85M Aug  6 03:34 out.00001.fasta
......
55M Aug  6 03:29 out.00129.fasta

when running the fasta2DB manually:
geest008@compute-0-2:~...../falcon/1-preads_ovl$ bash prepare_pdb.sh
.....
fasta2DB -v preads -f...../falcon/1-preads_ovl/input_preads.fofn
.........
Adding 'out.00001' ...
File out.00001.fasta, Line 1: Pacbio header line format error

When looking into this fasta file:
 head -n 1...../falcon/0-rawreads/preads/out.00001.fasta
>00000000_0

fasta2DB works for the /0-rawreads folder, so originally my fasta header is okay, for example:
head -n 1 m150607_*_s1_p0.1.subreads.fasta:
>m150607_022705_42179_c100789592550000001823170008251570_s1_p0/12/0_24678 RQ=0.848

When installing FALCON, I ran the make test command, and the synth example ran normally.
I checked the fasta headers for that example and they are fine:
head -n 1 ...bin/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/preads/out.00001.fasta
>prolog/000000000/0_1988

When comparing the /0-rawreads/preads/cp_0001.sh command with the example, I see one difference:

My run:
LA4Falcon -H10000 -fo raw_reads las_files/raw_reads.1.las |  fc_consensus.py --output_multi --min_idt 0.70 --min_cov 2 --local_match_count_threshold 2 --max_n_read 40 --n_core 4 > ....

example run:

LA4Falcon -H1 -fo raw_reads las_files/raw_reads.1.las |  fc_consensus.py --output_multi --min_idt 0.70 --min_cov 1 --local_match_count_threshold 100 --max_n_read 20000 --n_core 0 --output_dformat >

My command is missing the "--output_dformat" parameter.

Okay, I solved my own problem. I copied an old falcon.cfg file, but apparently some new options are present. Like the last one.
Please archive this topic, it might be of use for anyone else getting into the same problem :)

Solution: Use a new provided .cfg file from the example dir (for example: FALCON-integrate/FALCON-examples/run/synth0/fc_run.cfg) to make sure you use all options!

**Comment by pb-cdunn** [comment]
> My command is missing the "--output_dformat" parameter.

Jason, this keeps coming up. Maybe we should make that the default? We could provide "--old-output-format" if anybody needs it, but probably nobody would.

**Comment by pb-jchin** [comment]
@pb-cdunn Agreed. If you don't mind, can you change that.  Instead of "--old-output-format", maybe "--simple-fasta-header"...
