### ISSUE TITLE
Refactor tasks into executables.

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/FALCON#165]
pbsmrtpipe seems to want tasks to be executables. (And it does not currently support cmd-less tasks, though that would be allowed by PacificBiosciences/pbsmrtpipe#3.) So refactor our tasks into separate executables, available as [python `'console_scripts'` *entry_points* in **setup.py**](https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/). The pypeflow runner can then use those directly. I *think*.

- [x] make_fofn_abs
- [x] build_rdb
- [x] build_pdb
- [x] run_falcon_asm
- [x] run_daligner_task
- [x] run_merge_task
- [x] run_consensus_task
- [x] "check" tasks (which depend on ["*flag files*"](http://www.ruffus.org.uk/tutorials/new_tutorial/checkpointing.html#flag-files-checkpointing-for-the-paranoid) from chunkable tasks)
- chunkable tasks
  - [x] create_merge_tasks
  - [x] create_daligner_tasks
  - [x] run_jobs as output/input

**Comment by pb-jchin** [comment]
This is fine in priciple. The Pypeflow was designed with the idea that python function as task unit.  Most "tasks" in the Falcon run.py are calling scripts except a few exceptions.

**Comment by pb-cdunn** [comment]
More or less done.
