### ISSUE TITLE
NameError: global name 'fn' is not defined

### ISSUE THREAD

**Issue by outpaddling** [PacificBiosciences/FALCON#167]
Hi,
We're eager to get a stable installation of FALCON running at UWM.  I think we're pretty close, but I'm getting this error from fc_run.py.
I have the latest snapshot of pypeFLOW from today, py-rdflib 3.4.0, py-rdfextras 0.4, and the June 15 releases of daligner and dazz_db.
I also tried the FALCON-integrate installation method, but it failed with a missing DB.c, which I presume was caused by grabbiing the wrong versions of daligner and dazz_db.  I'd rather not run in a virtualenv anyway, but install via a package manager (we use mainly pkgsrc on CentOS).
This might be something as simple as a missing module, but Google has let me down on this one.
Below is the error in some context.
Thanks,
    Jason
~~~~~~~~~~
  File "/usr/local/lib/python2.7/site-packages/pypeflow/task.py", line 178, in _
runTask
    return self._taskFun(self)
  File "/usr/local/lib/python2.7/site-packages/falcon_kit/run_support.py", line
279, in make_fofn_abs_raw
    return make_fofn_abs(self)
  File "/usr/local/lib/python2.7/site-packages/falcon_kit/run_support.py", line
266, in make_fofn_abs
    i_fofn_fn = fn(self.i_fofn)
NameError: global name 'fn' is not defined
2015-08-12 20:28:32,397 - pypeflow.controller - INFO - #jobsReadyToBeSubmitted:
0
2015-08-12 20:28:32,398 - pypeflow.task - ERROR - PypeTaskBase failed:
{'__class__.__name__': 'PypeThreadTaskBase',
 '_status': 'TaskInitialized',
 'inputDataObjs': {'i_fofn': PypeLocalFile('file://localhost/usr/home/bacon/PacB
io-CLI/Falcon/input.fofn', '/usr/home/bacon/PacBio-CLI/Falcon/input.fofn')},
 'mutableDataObjs': {},
 'outputDataObjs': {'o_fofn': PypeLocalFile('file://localhost/usr/home/bacon/Pac
Bio-CLI/Falcon/0-rawreads/input.fofn', '/usr/home/bacon/PacBio-CLI/Falcon/0-rawr
eads/input.fofn')},

**Comment by pb-cdunn** [comment]
I'm sure I can solve this quickly if you tell me your commit SHA1 of FALCON.

However, we prefer that you use module commits from FALCON-integrate, even if you don't want to use FALCON-integrate for building and installation. We know that the versions in FALCON-integrate are at least consistent b/c we build them all and run an integration test in Travis CI. For example, [here](https://travis-ci.org/pb-cdunn/FALCON-integrate/builds/74439917) is the build for PacificBiosciences/FALCON-integrate@c6dd28d88fe28abe4b0719f3e50a0ea784d188ef, the current tip.

If you don't use the version contour specified by FALCON-integrate, support will be limited.

**Comment by pb-cdunn** [comment]
Actually, the new tip of FALCON probably solves this for you. But again, we *strongly* urge you to base your efforts of a contour of submodules from FALCON-integrate.

**Comment by outpaddling** [comment]
Chris,

Thanks for your quick action.  I just updated to the latest master and 
it appears to be working properly now.

I will heed your advice about the submodules.

Best,

     Jason

On 8/12/15 4:17 PM, Christopher Dunn wrote:
>
> Actually, the new tip of FALCON probably solves this for you. But 
> again, we /strongly/ urge you to base your efforts of a contour of 
> submodules from FALCON-integrate.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PacificBiosciences/FALCON/issues/167#issuecomment-130451579>.
>


-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Jason W. Bacon
   jwbacon@tds.net

   If a problem can be solved,
   there's no need to worry.
   
   If it cannot be solved, then
   worrying will do no good.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by outpaddling** [comment]
Are you planning any tagged releases in the near future, or should I 
plan on using FALCON-integrate snapshots for a while?

Thanks again,

     Jason

**Comment by pb-cdunn** [comment]
Good question! Our release strategy is evolving.

A tag typically means that a relatively large genome has been run and results analyzed. But the integration test is run on *every* update of FALCON-integrate. So I recommend trusting the tip of the master branch. There are improvements and bug-fixes all the time.

**Comment by outpaddling** [comment]
It's encouraging to know that you do such regular testing, thanks.  So, 
until the next release, I'll just use the git checkout instructions for 
FALCON-integrate and cache dist tarballs of the results for our package 
managers.

BTW, I was able to get FALCON-integrate working on FreeBSD 10.1 with a 
few simple changes to the scripts posted at

https://github.com/PacificBiosciences/FALCON/wiki/Setup:-Installation-and-Environment.

It was basically a matter of replacing any hard-coded "gcc" commands in 
the Makefiles with "cc" and using "gmake" instead of "make" for dazz_db 
and daligner.

I was going to suggest replacing those gcc commands before, since cc and 
gcc are (usually) the same command on Linux anyway.

For both FreeBSD and CentOS, I had to replace

     FC=fc_env

with

     FC=$(pwd)/fc_env

or the make install targets would fail.

I can submit this as a new issue if you like.

Regards,

     Jason

**Comment by pb-cdunn** [comment]
Which commit of DALIGNER are you using? (You can `cd DALIGNER; git rev-parse HEAD`, or you can run `git submodule summary` from the FALCON-integrate directory.) We have already dropped the hard-coded **gcc** from [our fork](https://github.com/PacificBiosciences/DALIGNER/blob/master/GNUmakefile). You can specify CC=whatever when you run **make**. Yes, it requires GNU make, which is sometimes called **gmake**. I'll try to note that somewhere.

Which makefile had `FC`? I see that only in the wiki link.

You don't have to use virtualenv. [FALCON-make/makefile](https://github.com/pb-cdunn/FALCON-make/blob/master/makefile) shows how to install into any `FALCON_PREFIX` directory. It's pretty short, and you could copy and adapt that to your own integration system.

The most important bit of information for us is to know the commit of FALCON-integrate that you are using. Or if you're cherry-picking submodule versions, then we would need to know the specific commits of submodules. Otherwise, it's hard to help you, or to apply your fixes. But I have update the wiki.

**Comment by outpaddling** [comment]
Sorry, scratch the gcc issue.  I was unaware that GNU make automatically 
chooses GNUmakefile over Makefile when run without arguments.  Hence, it 
was the fact that "make" == BSD make causing it to use the old Makefile 
instead of GNUmakefile.  Simply using gmake instead of make in the 
FALCON-integrate script is therefore sufficient to make the script work 
on FreeBSD.

So, the only real issue is that Makefile is out-of-date.  Makefile does 
contain gcc commands in the latest dazz_db and daligner.

I'm fetching everything via the following commands now:

git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git submodule update --init

FreeBSD unixdev.local bacon ~/Falcon/FALCON-integrate 445: git submodule
  dc506e67938c1c923ebb7e43ff8ce32ec923d8ba DALIGNER 
(remotes/origin/gm-master-10-gdc506e6)
  337a0ee0e77624094221577bdaa38c79b5444d91 DAZZ_DB 
(remotes/origin/gm-master-7-g337a0ee)
  d3939f2a4a5daaaa6090e1b386668c9c91d94f8e FALCON (0.2JASM-205-gd3939f2)
  97aecd0a69f62e3029bd5fd233ff9cceccd42bce FALCON-examples (heads/master)
  215e8cfcdda412258daff3b689cc7d0daeca4e47 FALCON-make (heads/master)
  483836854e1bafb6e40cf17f3a9382efe351daad git-sym (heads/master)
  a6751fac8aa575b130c558488af0532f47cf8999 pypeFLOW (v0.1.0-42-ga6751fa)
  8e9cb4a7c34a12762a0ef8b2c5003ded4346cd49 virtualenv (13.0.3-9-g8e9cb4a)

The FC was only in the scripts posted on 
https://github.com/PacificBiosciences/FALCON/wiki/Setup:-Installation-and-Environment, 
not in any Makefile that I'm aware of.  It was actually the "cp" 
commands after "make" that were failing.  Sorry, I didn't look closely 
at the script and assumed it was doing a "make install", not a "make" 
followed by "cp".

I'm assuming that the above it what you mean by the tip of the master 
branch.

If I use the v0.3.0 installation instructions at 
https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation-for-v0.3.0, 
I get the following:

FreeBSD unixdev.local bacon ~/Falcon/FALCON-integrate 439: git submodule
  c6cda805f9425658362b21cbd00ddf3ca8b7cb8b DALIGNER 
(remotes/origin/gm-master-5-gc6cda80)
  8b58e2e1f1b34631333ab3ea2cec5c3ede930a32 DAZZ_DB 
(remotes/origin/gm-master-3-g8b58e2e)
  cee6a580e97b209ff4d025b402a9f2c180c30bff FALCON (0.2JASM-189-gcee6a58)
  ea5e0d2814b54d0f0b9b0ce56d30510f96218eb7 FALCON-examples 
(remotes/origin/lambda-29-gea5e0d2)
  078683a3981e46d88605984c9c0e85cc011048b2 FALCON-make (078683a)
  483836854e1bafb6e40cf17f3a9382efe351daad git-sym (heads/master)
  74d2d9ce0984785f668528299ac03053d382b05f pypeFLOW (v0.1.0-40-g74d2d9c)
  8e9cb4a7c34a12762a0ef8b2c5003ded4346cd49 virtualenv (heads/develop)

Should I be using v0.3.0 instead?

Thanks,

     Jason


On 08/13/15 11:24, Christopher Dunn wrote:
>
> Which commit of DALIGNER are you using? (You can |cd DALIGNER; git 
> rev-parse HEAD|, or you can run |git submodule summary| from the 
> FALCON-integrate directory.) We have already dropped the hard-coded 
> *gcc* from our fork 
> <https://github.com/PacificBiosciences/DALIGNER/blob/master/GNUmakefile>. 
> You can specify CC=whatever when you run *make*. Yes, it requires GNU 
> make, which is sometimes called *gmake*. I'll try to note that somewhere.
>
> Which makefile had |FC|? I see that only in the wiki link.
>
> You don't have to use virtualenv. FALCON-make/makefile 
> <https://github.com/pb-cdunn/FALCON-make/blob/master/makefile> shows 
> how to install into any |FALCON_PREFIX| directory. It's pretty short, 
> and you could copy and adapt that to your own integration system.
>
> The most important bit of information for us is to know the commit of 
> FALCON-integrate that you are using. Or if you're cherry-picking 
> submodule versions, then we would need to know the specific commits of 
> submodules. Otherwise, it's hard to help you, or to apply your fixes. 
> But I have update the wiki.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PacificBiosciences/FALCON/issues/167#issuecomment-130750225>.
>


-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Jason W. Bacon
   jwbacon@tds.net

   If a problem can be solved,
   there's no need to worry.
   
   If it cannot be solved, then
   worrying will do no good.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by pb-cdunn** [comment]
> So, the only real issue is that Makefile is out-of-date. Makefile does contain gcc commands in the latest dazz_db and daligner.

Yeah, I'm trying to keep our fork easily merge-able with Gene Myers'. We're using only GNUmakefile.

> Should I be using v0.3.0 instead?

Nope! What you have is fine, as the tip of master is preferable. You'll get bug-fixes immediately, so I'll see fewer bug-reports. Don't use a specific release unless you have a reason.

**Comment by outpaddling** [comment]
OK, thanks.  We're running some test data on both CentOS and FreeBSD now.

If that succeeds, we'll try the SLURM integration feature next.

Thanks again,

     Jason

On 8/13/15 2:29 PM, Christopher Dunn wrote:
>
>     So, the only real issue is that Makefile is out-of-date. Makefile
>     does contain gcc commands in the latest dazz_db and daligner.
>
> Yeah, I'm trying to keep our fork easily merge-able with Gene Myers'. 
> We're using only GNUmakefile.
>
>     Should I be using v0.3.0 instead?
>
> Nope! What you have is fine, as the tip of master is preferable. 
> You'll get bug-fixes immediately, so I'll see fewer bug-reports. Don't 
> use a specific release unless you have a reason.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PacificBiosciences/FALCON/issues/167#issuecomment-130812355>.
>


-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Jason W. Bacon
   jwbacon@tds.net

   If a problem can be solved,
   there's no need to worry.
   
   If it cannot be solved, then
   worrying will do no good.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by outpaddling** [comment]
Is the external daligner mentioned here:

https://github.com/PacificBiosciences/cDNA_primer/wiki/Setting-up-virtualenv-and-installing-pbtranscript-tofu

any different from the latest tip?

Thanks,

     Jason

**Comment by outpaddling** [comment]
Actually, I wasn't clear about my question.  The real question is does 
it change anything important besides adding LA4Ice?  Or, can we just 
install LA4Ice from here and use all the other programs from the regular 
daligner dist?

Thanks,

     Jason

**Comment by pb-cdunn** [comment]
Looking into this...

**Comment by pb-cdunn** [comment]
Unfortunately, LA4Ice uses a very different version of daligner at the moment. We don't have a short-term solution for that. LA4Ice needs to use its own version.
