### ISSUE TITLE
LAmerge giving error "PT-point spacing conflict (0 vs 1000)"

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#168]
This is in the preads stage, which causes a missing .las file which causes another LAmerge to fail...  

This is the end of a painful 3 week assembly.  I just want to get past it.  Any way to either solve this error or else just get Falcon to ignore this file?

**Comment by pb-jchin** [comment]
you can create a fake "_done" files for the corresponded LAmerge jobs to by-passing it.

**Comment by dgordon562** [comment]
Thanks!  Done that.  We'll see...

**Comment by dgordon562** [comment]
I don't know if this is related, but Falcon is now stuck in fc_overlap_filter.py
There are 25 fc_overlap_filter.py processes "running" but each is using 0.0% cpu (and has been for an hour).
There are no LA4Falcon processes running.

Looking in the sge_log file:

> grep run_filter_stage1 run_falcon_asm.sh-falcon-falcon.o6894304 | grep starting | wc
    339    2373   93352
> grep run_filter_stage1 run_falcon_asm.sh-falcon-falcon.o6894304 | grep finished | wc
    185    1295   50947
I modified LA4Falcon so it prints out when it completes all iterations of the loop:

> grep "completed all records" run_falcon_asm.sh-falcon-falcon.o6894304 | wc
    317     951    6974

Any ideas of what the problem is or what I can do?

Any suggestions as to where/what diagnostic output to put into fc_overlap_filter.py ?

**Comment by pb-jchin** [comment]
Does the related process generating the reads in the `preads/*fasta`?

**Comment by dgordon562** [comment]
No, but it shouldn't, unless I'm confused.  It is running:

fc_ovlp_filter.py --db /net/eichler/vol24/projects/whole_genome_assembly/nobackups/gorilla/gor150721/1-preads_ovl/preads.db --fofn las.fofn --max_diff 100 --max_cov 100 --min_cov 2 --bestn 10 --n_core 24 --min_len 6000 > preads.ovl

so it should be creating preads.ovl   right?

This file exists but is 0 length.

Any suggestions?

**Comment by pb-jchin** [comment]
My bad. I misread the initial post.  

yes, it should creat the `preads.ovl`. There will be `LA4Falcon -mo` processes running if there are there, you need to wait. However, if, for any reason, those jobs get killed, then you need to restart them.

**Comment by dgordon562** [comment]
Yes, but unfortunately they aren't jobs--they are tasks (pypeflow?) within fc_ovlp_filter.py
so I can't just restart the failed ones, but all of them.  

So I'm doing that.  I didn't find any message in the sge_log file about why any failed.  Any way I can determine that?

**Comment by pb-cdunn** [comment]
> I modified LA4Falcon so it prints out when it completes all iterations of the loop.

(And we'll take that change if you post it into a separate Issue or PullRequest.)

> unfortunately they aren't jobs--they are tasks (pypeflow?) within fc_ovlp_filter.py
so I can't just restart the failed ones

(That's helpful feedback. We'll turn those into tasks, but not soon enough for your current problem.)

**Comment by dgordon562** [comment]
Thanks, Chris.  Restarted the fc_ovlp_filter.py and it has frozen again.  25 processes of fc_ovlp_filter.py, no longer any LA4Falcon processes, and the fc_ovlp_filter.py all getting 0.0% cpu except for one which is 0.3% cpu (probably checking for tasks?)  It got further this time:

> grep "starting run_filter_stage1" run_falcon_asm.sh-falcon-falcon.o6899598 | wc
    339    2373   93796
> grep "completed all records" run_falcon_asm.sh-falcon-falcon.o6899598 | wc
    336    1008    7392
> grep "finished" run_falcon_asm.sh-falcon-falcon.o6899598 | wc
    114     798   31549


What should I try now?

**Comment by dgordon562** [comment]
Is there any way to tell *which* LA4Falcon process is terminating?  (We are assuming here that it is LA4Falcon, but I have some evidence that 3 of them are not.)

**Comment by pb-cdunn** [comment]
Find the script which runs **fc_ovlpl_filter.py**. Run it manually, from within that directory.

But first, modify it to use `--n_core=0`. That will turn off the multiprocessing module, which will make the whole thing easier to debug. Then, if hangs, hit Ctrl-C to get a true stack-trace. Maybe there is something we can do to exit early in the case, and to report more about the underlying processes. That doesn't solve the problem, but it could be less annoying.

**Comment by dgordon562** [comment]
Hi, Chris,

Progress.  Of  sorts.   Your method would have worked but this is what I did:  I modified LA4Falcon so it reports the command line when it starts and when it ends (to stderr).  Then after fc_ovlp_filter.py froze, I checked which LA4Falcon had started and not completed.  There were 2 of them.  I now know which 2.  

I ran them on the command line.  

Here's the rub:  both completed fine.

So why are they crashing (without an error message) from fc_ovlp_filter.py ?  How do I prevent that?

Here is one idea:  I run all of the LA4Falcon processes and put the output into files.  Then I make a copy of fc_ovlp_filter.py that, rather than running LA4Falcon, it runs "cat" on the particular file.

A real pain in the ...   but any thoughts of an easier way?  I just want to get this @!@@@ assembly done...it has been 3 weeks running and this is the last few hours...

Thanks!
david

**Comment by dgordon562** [comment]
Here's a question you or Jason can answer:  how can I modify fc_ovlp_filter.py to report the error status of any LA4Falcon process that it starts?  Even just reporting the error code would be helpful...  Any idea?

**Comment by pb-cdunn** [comment]
Which commit of FALCON are you based on?

I expect to see `starting ...` and `finished ...` for each process. v0.3.0 should have that in `run_falcon_asm.sh.log` (or maybe in the sge_log). Also, an exception should be raised whenever the process fails. Something is odd. If you run with n_core=0, I could see a stack-trace which would help me to diagnose the problem.

**Comment by dgordon562** [comment]
Hi, Chris,

I'm using Falcon v0.3.0  Let me know how to get more details if you would like.

All stderr of fc_ovlp_filter.py is reported in:
sge_log/run_falcon_asm.sh-falcon-falcon.o6901487

different runs of fc_ovlp_filter.py have different LA4Falcon
that fail.  Just 2 to 4 fail but that causes fc_ovlp_filter.py to not
complete.

I now changed the fc_ovlp_filter.py to use --n_core 0
This causes only one LA4Falcon to be run at a time.  All have
completed successfully.

However, this causes a different problem:  when all las files in
1-preads_ovl/las_files have been processed, fc_ovlp_filter.py does not
complete but rather processes them all over again.  It is now on the
3rd time through the list.  I don't think it will ever stop.

How to solve this problem?

How does fc_ovlp_filter.py determine that a las file has already been
processed and need not be done again?  How does it determine which
still need to be processed?

I'm assuming this is a bug in pypeflow--who maintains pypeflow?  Is it
a PacBio product?  Where is the pypeflow documentation?  What diagnostic code could I put into fc_ovlp_filter.py to debug this?

Thanks,
David

**Comment by dgordon562** [comment]
One other questions:  could you please post the structure of 2-asm-falcon/preads.ovl...what are the fields?

**Comment by pb-cdunn** [comment]
> How does fc_ovlp_filter.py determine that a las file has already been
processed and need not be done again? How does it determine which
still need to be processed?

At the moment, unfortunately, it doesn't. It re-runs them all.

> I'm assuming this is a bug in pypeflow--who maintains pypeflow? Is it
a PacBio product? Where is the pypeflow documentation?

pypeFLOW is open-source, maintained by me and Jason. I'm not sure the docs are hosted anywhere, but here they are:
* https://github.com/PacificBiosciences/pypeFLOW/tree/master/doc

But this is not a pypeFLOW bug. **fc_ovlp_filter.py** does not use pypeFLOW. It's the other way round.

> What diagnostic code could I put into fc_ovlp_filter.py to debug this?

That's a good question. **fc_ovlp_filter.py** has driven me crazy in the past, so I've added several improvements. I don't understand why you're not seeing any of that. I only need to repro once.

But I think you mentioned something which should work-around this mysterious problem. We can have **LA4Falcon** write to a file, and **fc_ovlp_filter.py** can simply issue a blocking system-call, check the return-code, and then read from the output file. That should be more debuggable, and as long as LA4Falcon does not actually hang, it should avoid the problem you are seeing.

I have until noon before I have to leave to catch a flight. I think I can get something to you before then, if you like this idea. But if not, I'll be unavailable until Tuesday at the earliest. Would you like me to move forward with this approach?

**Comment by dgordon562** [comment]
Yes, please.  Thank you.

**Comment by pb-cdunn** [comment]
I can give you a branch in FALCON. But it's a little safer to give you a branch in FALCON-integrate, if you know how to run `git submodule update`.

**Comment by dgordon562** [comment]
I'm afraid I don't.  I'm still a novice with git.  How many files are you changing?    Can I just download the zip file for those?

**Comment by pb-cdunn** [comment]
You can do it. I'll help you. Assuming that `origin` is the name of your Pacbio remote:
```
cd FALCON-integrate
git fetch origin
git checkout -t origin/issue-168
git submodule update
```
Then build and run.

This will look for `*.stdout` files for each **LA4Falcon** run. Since you don't have those yet, all **LA4Falcon** jobs will be run again. But hopefully nothing earlier than that.

If you have trouble, you can delete the entire `2-asm-falcon` sub-dir and re-run.

**Comment by dgordon562** [comment]
OK.

**Comment by dgordon562** [comment]
Hi, Chris,

About the original error:   LAmerge giving error "PT-point spacing conflict (0 vs 1000)" #168 

I could bring the dataset on a flash drive to you next week.  Do you have time/interest in tracking down this problem?

It did mean that 2/339 of our data is lost and we are missing some large contigs.  (May not be related.)  But this is a chance for you to get a dataset that reproduces the problem with Falcon 0.3.0

What do you say?

David

**Comment by pb-cdunn** [comment]
> I could bring the dataset on a flash drive to you next week. Do you have time/interest in tracking down this problem?

Yes, bring it. If we can reproduce the problem, we can debug it.

**Comment by pb-cdunn** [comment]
Thanks for the feedback at the conference. This all points to significant improvements that we will have to make at some point.
