### ISSUE TITLE
PypeTaskBase failed

### ISSUE THREAD

**Issue by lurebgi** [PacificBiosciences/FALCON#173]
```
2015-08-20 07:33:40,108 - fc_run - INFO - Cmd 'bash /global/scratch/zhouqi/D.miranda/falcon/0-rawreads/prepare_rdb.sh 1> /global/scratch/zhouqi/D.miranda/falcon/0-rawreads/prepare_rdb.sh.log 2>&1' (job 'prepare_rdb.sh-build_rdb-build_rdb') returned 256.
2015-08-20 07:33:40,116 - pypeflow.task - ERROR - PypeTaskBase failed:
{'__class__.__name__': 'PypeThreadTaskBase',
 '_status': 'TaskInitialized',
```

I did install with FALCON-integrate. Do you have an idea what's going on.

**Comment by pb-cdunn** [comment]
What's in `/global/scratch/zhouqi/D.miranda/falcon/0-rawreads/prepare_rdb.sh.log`?.

**Comment by lurebgi** [comment]
I checked all log files. It seemed there were no las outputs, as the file
sizes are only 12 bites. The raw_reads.db is also small, only 374 bites. I
didn’t see any issues reported in logs.

**Comment by pb-jchin** [comment]
can you just do 
```
cat raw_reads.db 
```

**Comment by lurebgi** [comment]
This's what in raw_reads.db

files =         2
      72609 pacbio.100752052550000001823154907081537
m141213_095313_42160_c100752052550000001823154907081537_s1_p0
      80656 pacbio.100761172550000001823160007221504
m150116_143041_42160_c100761172550000001823160007221504_s1_p0
blocks =         2
size =       200 cutoff =       500 all = 0
         0         0
     61642     41978
     80656     56333

Is that all right?

Luohao

**Comment by lurebgi** [comment]
on the step 'daligner -v -t16 -H12000 -e0.7 -s1000 raw_reads.1 raw_reads.1', I got no seed hits, what does it suggest?

**Comment by pb-jchin** [comment]
how big is your genome? -t16 might be too small. Have you tried the e. coli example yet?

**Comment by lurebgi** [comment]
it's a fly genome, like 130M.
Not tried the e. coli yet.

**Comment by pb-jchin** [comment]
mmm. you should get some hits at least.

**Comment by lurebgi** [comment]
The 'length_cutoff' was set too high. The issue is now resolved.

**Comment by pb-jchin** [comment]
Well. try to use DBstat to check the length distribution. There was a thread discussing the related issue.
