### ISSUE TITLE
names of the Falcon contigs:  00001F, 00001R, or 00001

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#174]
What does it mean for a Falcon contig name to end with F, R, or neither?

Thanks!
David

**Comment by pb-jchin** [comment]
Each contig has a dual contig which is reverse complement to the one layout. We only output one with "F" suffix.  For the full assembly graph as directed graph, you need both "F" and "R" contigs.

**Comment by dgordon562** [comment]
In one assembly I see 15,657 contigs with "F", 18 with "R", and 324 with neither.  What do the ones with neither mean?

**Comment by pb-jchin** [comment]
In your case, it is more like to be tandem repeat which creats a circle in the assembly graph.

**Comment by dgordon562** [comment]
thanks!

**Comment by pb-cdunn** [comment]
Added to FAQ. Thx.
