### ISSUE TITLE
falcon running failed,help!

### ISSUE THREAD

**Issue by AnWD** [PacificBiosciences/FALCON#18]
To assemble human genome with pacbio-only sequencing data, we tried to apply FALCON software. We installed the software following the instructions, and no error turned up in the process of installation, the installation information is attached.Here is our sever environment which is satisfied with the installation requirement too. 

[smrtanalysis@node4 FALCON-master]$ uname -a 
Linux node4.bnu.edu.cn 2.6.32-279.el6.x86_64 #1 SMP Wed Jun 13 18:24:36 EDT 2012 x86_64 x86_64 x86_64 GNU/Linux 

[smrtanalysis@node4 FALCON-master]$ gcc --version 
gcc (GCC) 4.8.2 

[smrtanalysis@node4 FALCON-master]$ python --version 
Python 2.7.3 

However, when I ran the FALCON following the instructions, it failed and the running error information is also attched.
```
fc_run.cfg:
{begin}
[General]
# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn
input_type = raw
#input_type = preads
# The length cutoff used for seed reads used for initial mapping
length_cutoff = 12000
# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 12000
sge_option_da = -l h=nodesuper -pe openmp 4 -q all.q
sge_option_la = -l h=nodesuper -pe openmp 4 -q all.q
sge_option_pda = -l h=nodesuper -pe openmp 2 -q all.q
sge_option_pla = -l h=nodesuper -pe openmp 2 -q all.q
sge_option_fc = -l h=nodesuper -pe openmp 4 -q all.q
sge_option_cns = -l h=nodesuper -pe openmp 4 -q all.q
pa_concurrent_jobs = 16
cns_concurrent_jobs = 16
ovlp_concurrent_jobs = 16
pa_HPCdaligner_option =  -v -dal4 -t16 -e.70 -l1000 -s400
ovlp_HPCdaligner_option = -v -dal4 -t32 -h60 -e.96 -l500 -s400
pa_DBsplit_option = -x50 -s50
ovlp_DBsplit_option = -x50 -s50
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 2 --local_match_count_threshold 1 --max_n_read 10 --n_core 2
overlap_filtering_setting = --max_diff 50 --max_cov 30 --min_cov 20 --bestn 10
{end}
```

```
{begin}
ERROR 1(input_type = raw)：
  command:  vi  ./0-rawreads/job_10684559/rj_10684559.log

"15079 vs 15111 :   3
15104 vs 15111 :   4

     18,604,978 14-mers (7.440891e-09 of matrix)
          5,100 seed hits (2.039698e-12 of matrix)
            560 confirmed hits (2.239669e-13 of matrix)
*** glibc detected *** daligner: double free or corruption (out): 0x0000003ea0c04b30 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3ea0c75366]
/lib64/libc.so.6[0x3ea0c77e93]
daligner[0x401ea6]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x3ea0c1ecdd]
daligner[0x401339]
======= Memory map: ========
00400000-0041f000 r-xp 00000000 00:1c 113118876                          /home/nfs_UserData_220/falcon/installation_dir/FALCON-master/fc_env/bin/daligner
0061e000-0061f000 rw-p 0001e000 00:1c 113118876                          /home/nfs_UserData_220/falcon/installation_dir/FALCON-master/fc_env/bin/daligner"
{end}

{begin}
command:    gdb ./0-rawreads/job_58132038/core.9839
"[New Thread 9839]
Core was generated by `daligner -v -t16 -H3000 -e0.7 -s1000 raw_reads.1 raw_reads.1'.
Program terminated with signal 6, Aborted."
{end}

{begin}
ERROR 2(input_type = preads)：
when run the command "fc_run.py fc_run.cfg",it shows

"No target specified, assuming "assembly" as target 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/nfs_UserData_220/falcon/installation_dir/FALCON-master/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 317, in __call__
    runFlag = self._getRunFlag()
  File "/home/nfs_UserData_220/falcon/installation_dir/FALCON-master/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 147, in _getRunFlag
    runFlag = any( [ f(self.inputDataObjs, self.outputDataObjs, self.parameters) for f in self._compareFunctions] )
  File "/home/nfs_UserData_220/falcon/installation_dir/FALCON-master/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 812, in timeStampCompare
    if min(outputDataObjsTS) < max(inputDataObjsTS):
ValueError: max() arg is an empty sequence

Exception in thread Thread-4:
Traceback (most recent call last):
  File
"/home/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/nfs_UserData_220/falcon/installation_dir/FALCON-master/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 317, in __call__
    runFlag = self._getRunFlag()
  File "/home/nfs_UserData_220/falcon/installation_dir/FALCON-master/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 147, in _getRunFlag
    runFlag = any( [ f(self.inputDataObjs, self.outputDataObjs, self.parameters) for f in self._compareFunctions] )
  File "/home/nfs_UserData_220/falcon/installation_dir/FALCON-master/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 812, in timeStampCompare
    if min(outputDataObjsTS) < max(inputDataObjsTS):
ValueError: max() arg is an empty sequence"
{end}

{begin}
and also the file sge_log/falcon-ea66cd36.o9615    shows :"/home/sgeadmin/node10/node10/job_scripts/9615: line 3: 42517               core dumped)DB2Falcon preads"  
"in <module>  for res in exe_pool.imap(filter_stage1, inputs): File  '/home/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/multiprocessing/pool.py', line 626, in next raise value
OSError: [Errno 2] No such file or directory"
{end}
```

ps:
we have also run the ecoli example descriped in the manual,the same error like above.

hardware environment:
supernode: 48 cores  2.7GHz ,600G memory * 1
node : 24 cores 2.1GHz, 64G memory * 8

Would you like to help us about these problems?

**Comment by pb-jchin** [comment]
This will be several step troubling shoot...
Can you test if you can reproduce the double free error by running `./0-rawreads/job_10684559/ri_10684559.sh` manually?

**Comment by AnWD** [comment]
thanks for your reply!I have tried it manually.there is no erroe any more.would you like to help us to fix this multi-step problem?Really appriciate it

**Comment by pb-jchin** [comment]
AnWD, so your jobs went through, right?

**Comment by AnWD** [comment]
The multi-step trouble has not been solved.And the same error still...

**Comment by pb-jchin** [comment]
If you have run the rawreads/job_10684559/rj_10684559.sh and run fc_run.py again, it should not re-run rawreads/job_10684559/rj_10684559.sh.  It is not clear from your description where it went wrong.  Maybe you need to elaborate it more.

**Comment by AnWD** [comment]
how to re-run fc_run.py without job_10684559?><

**Comment by pb-jchin** [comment]
if your the job_10684559 is finished probably, re-run fc_run.py will just start to process other jobs. If you know "make", it is the same idea. fc_run.py detected finished jobs and will only re-run those unfinished jobs.

**Comment by AnWD** [comment]
I know what you mean: I have re-run "fc_run.py fc_run_ecoli.cfg",and only one job "9618" was submitted and job_10684559 coredump again. And when I run the command "ps -ef |grep fc_run.py ", it shows the program is still running :  
"501      32236 32141  0 14:50 pts/1    00:00:03 /home/nfs_UserData_220/falcon/installation_dir/FALCON-master/fc_env/bin/python /usr/bin/fc_run.py fc_run_ecoli.cfg"

**Comment by AnWD** [comment]
hi jchin,could u please help us debug it through teamviewer?

**Comment by pb-jchin** [comment]
I am still confused. You said the job was ok when you run it manually. There is something usual in your system.  
Here is what you should do:
0. start flash,
1. run fc_run.py
2. if a job crashes, kill fc_run.py process
3. test running the crashed job manually
4. if the job still crashes, it means your data file might be corrupted or you might have some system mismatches
5. if the job goes through when you run it manually, you can restart fc_run.py, the same job should not be executed again (so there should be no crash on the same job.)

**Comment by AnWD** [comment]
I followed the manual,and run FALCON-master/fc_env/bin/activate for the first step...
how to "start flash"?><

**Comment by pb-jchin** [comment]
sorry, a type "start fresh", start from a "clean" environment and rebuild everything to ensure your environment is "correct"

**Comment by AnWD** [comment]
how to ensure it is a "clean" environment?Actually,it's new servers just bought.

**Comment by pb-jchin** [comment]
you will need to check with your system admin, check your ~/.bashrc ~/.profile, etc. Unfortunately, some basic UNIX skills is needed.

**Comment by AnWD** [comment]
You mean more settings need to be dond ,and the falcon manual hasn't been completed?
because here is just 100% clean machine whose OS is just installed.

**Comment by pb-jchin** [comment]
no, some of your default setting might not be compatible. before any trouble shooting, you will need to know that. this is not a topic which can be easily covered here.  Anyway, just try a couple things to see if it works for you

**Comment by AnWD** [comment]
5. if the job goes through when you run it manually, you can restart fc_run.py, the same job should not be executed again (so there should be no crash on the same job.)

there is the same crash on the same job.

All is about:
{begin}
command:    gdb ./0-rawreads/job_58132038/core.9839
"[New Thread 9839]
Core was generated by `daligner -v -t16 -H3000 -e0.7 -s1000 raw_reads.1 raw_reads.1'.
Program terminated with signal 6, Aborted."
{end}

 raw_reads.1 vs raw_reads.1,anything is wrong here?

**Comment by pb-jchin** [comment]
Please repeat some trouble shooting steps in https://github.com/PacificBiosciences/FALCON/issues/21 to check if you seq DB is ok.

**Comment by pb-jchin** [comment]
any progress?

**Comment by AnWD** [comment]
I have tried command DBstat and DBshow ,there is no error.  Is it showing  that the seq DB is ok?

**Comment by pb-jchin** [comment]
please paste the result of DBstat in as a Gist.. https://gist.github.com/

**Comment by AnWD** [comment]
I have create a secret gist. Can you see it?

**Comment by pb-jchin** [comment]
don't have a URL

**Comment by AnWD** [comment]
https://gist.github.com/AnWD/7a708f9769e3615bd3d1

**Comment by pb-jchin** [comment]
cut and paste the result of "daligner -v -t16 -H3000 -e0.7 -s1000 raw_reads.1 raw_reads.1"

**Comment by AnWD** [comment]
https://gist.github.com/AnWD/a7d3e35dacef5d652bde

**Comment by AnWD** [comment]
interrupted by "core dumped"

**Comment by AnWD** [comment]
the daligner.log has been uploaded into baidu

**Comment by AnWD** [comment]
the db has been uploaded into dropbox.~.~

**Comment by AnWD** [comment]
*.las has been uploaded.

**Comment by AnWD** [comment]
any progress,sir?

**Comment by AnWD** [comment]
any progress,sir?

**Comment by pb-jchin** [comment]
you need to upload ".raw_reads.bps" and ".raw_reads.idx" files. no need for "*.las" file

**Comment by AnWD** [comment]
because of the low upload speed through agency,I can't upload the 240M .raw_reads.bps file to the Dropbox. It cann't continue the thransferring from breakpoint. 
any other net disk? or if you do not have baidu account,I can offer you one.

**Comment by pb-jchin** [comment]
no rush. I can wait.

**Comment by AnWD** [comment]
https://www.dropbox.com/sh/puvw2pqfcg3923l/AACpXaS9UXEEWRPlG7ZjFgaga?dl=0
file list:  .raw_reads.bps , .raw_reads.idx,  .raw_reads.db
thanks for your patience.

**Comment by pb-jchin** [comment]
Hi, AnWD:

I take your db file and run `daligner -v -t16 -H3000 -e0.7 -s1000 raw_reads.1 raw_reads.1` and everything working fine. 

Here is a transcript of the result:
```
$ daligner -v -t16 -H3000 -e0.7 -s1000 raw_reads.1 raw_reads.1

Building index for raw_reads.1

   Kmer count = 12,356,488
   Using 0.18Gb of space
   Revised kmer count = 12,347,943
   Index occupies 0.09Gb

Building index for c(raw_reads.1)

   Kmer count = 12,356,488
   Using 0.18Gb of space
   Revised kmer count = 12,347,943
   Index occupies 0.09Gb

Comparing c(raw_reads.1) to raw_reads.1

   Capping mutual k-mer matches over 10000 (effectively -t100)
   Hit count = 2,681,893
   Highwater of 0.22Gb space

     2,681,893 14-mers (1.752418e-08 of matrix)
         4,499 seed hits (2.939762e-11 of matrix)
         4,135 confirmed hits (2.701915e-11 of matrix)

Comparing raw_reads.1 to raw_reads.1

   Capping mutual k-mer matches over 10000 (effectively -t100)
   Hit count = 718,287
   Highwater of 0.19Gb space

     718,287 14-mers (4.693471e-09 of matrix)
       4,418 seed hits (2.886834e-11 of matrix)
       3,901 confirmed hits (2.549013e-11 of matrix)

$ md5sum *.las
16b4ca0f289a20709b9752901c83ea20  raw_reads.1.raw_reads.1.C0.las
52fae20052bab858f4f5f4288ca1b96c  raw_reads.1.raw_reads.1.C1.las
8dece9a314ef81c0a075c465e9fc559b  raw_reads.1.raw_reads.1.C2.las
c4dcb7c20be2b889ef5086310460a4b7  raw_reads.1.raw_reads.1.C3.las
2164d49c7f7e346a6d762d7b533eb589  raw_reads.1.raw_reads.1.N0.las
264f30a3e3d6ecb528858fba1721b19e  raw_reads.1.raw_reads.1.N1.las
69b35f967177db4b5390f719a7f90749  raw_reads.1.raw_reads.1.N2.las
389ee828d95e7ad408e540f3c9ab3f19  raw_reads.1.raw_reads.1.N3.las
```

Since I am not able to re-reproduce what you see, it might be some of your system configuration problem. If you get someone who is familiar with Unix/Ubuntu locally, that will help most. I think if you can install a version of Ubuntu 14.04.1 LTS Linux Kernel 3.13.0-24, and test it, that will be great. If not, maybe you can contact your hardware/OS provider to see if you get some support from them. Also, my `gcc` compiler is `gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2`.

**Comment by pb-jchin** [comment]
I also notice you might use a different version of daligner. If you follow the instruction in the `doc/`, it should not dump debug information (namely, the log should be small.)  You can't mix and match different daligner version now. I only test everything that I package.

**Comment by AnWD** [comment]
hi jchin,thanks for your reply.
This is my log:

Building index for raw_reads.1

   Kmer count = 49,943,490
   Using 1.49Gb of space
   Revised kmer count = 49,876,154
   Index occupies 0.74Gb

Building index for c(raw_reads.1)

   Kmer count = 49,943,490
   Using 1.49Gb of space
   Revised kmer count = 49,876,154
   Index occupies 0.74Gb
Little

Comparing c(raw_reads.1) to raw_reads.1

   Capping mutual k-mer matches over 10000 (effectively -t100)
   Hit count = 13,538,725
   Highwater of 1.89Gb space
Here is a question:
why the building data is different with the same db files,such as "Kmer count"," Index occupies" ?
And each time I run the command,the result is the same to each other.
Are these all caused by system configuration difference ?

**Comment by pb-jchin** [comment]
please make sure you are using the same daligner version as described in the doc/

**Comment by AnWD** [comment]
how did you notice the different versions of daligner?I have deleted all the daligner installed but one.
But the error is still the same,no matter which way I chose, single command or multiple-step.
There is one thing I am very curious about. 
why the building data is different with the same db files,such as "Kmer count"," Index occupies" ?Is there anything that has influence on the "building data" results? I really doubts that the OS configuration like you said could influence the result like this.

**Comment by pb-jchin** [comment]
your output contains debugging information and is way larger than the one I use and test. I can't support untested code yet.

**Comment by AnWD** [comment]
Would you please give me a url of tested source code?
this is the link I used:
https://github.com/PacificBiosciences/FALCON
or, is there a switch "button" of debug&release log somewhere?

**Comment by pb-jchin** [comment]
check https://github.com/PacificBiosciences/FALCON/blob/master/doc/falcon_manual.md

make sure you use these two repository to build daligner.
https://github.com/pb-jchin/DAZZ_DB.git
https://github.com/pb-jchin/DALIGNER.git

**Comment by AnWD** [comment]
I reinstall it with source code above,it ran smoothly now!
Thank you,jchin.

**Comment by pb-jchin** [comment]
Great. Closing this issue now.
