### ISSUE TITLE
Trouble running FALCON example (no SGE)

### ISSUE THREAD

**Issue by kkrizanovic** [PacificBiosciences/FALCON#180]
Hi, I've been trying to set up FALCON to test it.

However, when I try to run the example as describe here: https://github.com/PacificBiosciences/FALCON/wiki/Setup%3A-Complete-example

I get en error (or several of them). Complete program output is rather lengthy, but the text around the part when I get the first error is this:

    /home/kkrizanovic/src/FALCON-integrate/ecoli_test/sge_log -j y                 -S /bin/bash     /home/kkrizanovic/src/FALCON-integrate/ecoli_test/0-rawreads/prepare_rdb.sh' (job 'prepare_rdb.sh-build_rdb-build_rdb') returned 32512.
    2015-08-31 10:51:41,352 - pypeflow.task - ERROR - PypeTaskBase failed:
    {'__class__.__name__': 'PypeThreadTaskBase',
     '_status': 'TaskInitialized',
     'inputDataObjs': {'input_fofn': PypeLocalFile('file://localhost/home/kkrizanovic/src/FALCON-integrate/ecoli_test/0-rawreads/input.fofn', '/home/kkrizanovic/src/FALCON-integrate/ecoli_test/0-rawreads/input.fofn')},
     'mutableDataObjs': {},
     'outputDataObjs': {'rdb_build_done':  PypeLocalFile('file://localhost/home/kkrizanovic/src/FALCON-integrate/ecoli_test/0-rawreads/rdb_build_done', '/home/kkrizanovic/src/FALCON-integrate/ecoli_test/0-rawreads/rdb_build_done')},
     'parameters': {'config': {'cns_concurrent_jobs': 8,
                               'falcon_sense_option': '--output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6 --output_dformat',
                               'falcon_sense_skip_contained': 'False',
                               'input_fofn_fn': 'input.fofn',
                               'input_type': 'raw',
                               'install_prefix': '/home/kkrizanovic/src/FALCON-integrate/fc_env',
                               'job_type': 'SGE',
                               'length_cutoff': 12000,
                               'length_cutoff_pr': 12000,
                               'openending': False,
                               'overlap_filtering_setting': '--max_diff 100 --max_cov 100 --min_cov 20 --bestn  10 --n_core 24',
                               'ovlp_DBsplit_option': '-x500 -s50',
                               'ovlp_HPCdaligner_option': '-v -dal4 -t32 -h60 -e.96 -l500 -s1000',
                               'ovlp_concurrent_jobs': 32,
                               'pa_DBsplit_option': '-x500 -s50',
                               'pa_HPCdaligner_option': '-v -dal4 -t16 -e.70 -l1000 -s1000',
                               'pa_concurrent_jobs': 32,
                               'sge_option_cns': '-pe smp 8 -q your_queue',
                               'sge_option_da': '-pe smp 8 -q your_queue',
                               'sge_option_fc': '-pe smp 24 -q your_queue',
                               'sge_option_la': '-pe smp 2 -q your_queue',
                               'sge_option_pda': '-pe smp 8 -q your_queue',
                               'sge_option_pla': '-pe smp 2 -q your_queue',
                               'target': 'assembly',
                               'use_tmpdir': False},
                    'work_dir': '/home/kkrizanovic/src/FALCON-integrate/ecoli_test/0-rawreads'}}

I'd be happy to provide more info if you need it.

I cloned FALCON-Integrate a few days ago. Not sure how to check the current version. I would appreciate it if you could help me make it run.

**Comment by pb-jchin** [comment]
I guess your SGE queue's name is not "your_queue".

**Comment by kkrizanovic** [comment]
I'll risk appearing even more ignorant. I don't have SGE (had to look up what it actually is) installed on my server, that is probably what I'm doing wrong. Is there a way to run FALCON without it?

**Comment by pb-cdunn** [comment]
job_type=local

I always recommend that people do this first:

* https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation
* https://github.com/pb-cdunn/FALCON-examples/wiki

From there, it's easier to customization your integration and examples.
