### ISSUE TITLE
CCS reads

### ISSUE THREAD

**Issue by fbemm** [PacificBiosciences/FALCON#183]
When using CCS reads as raw or preads (coming from the SMRT portal), Falcon dies It is dazzdb that does not like the headers and fails to create the database. Does falcon sense use the CCS information during the correction? If yes, then I would just use dextract to generate new raw fastq files right?

**Comment by mseetin** [comment]
Falcon takes fasta files, not fastq files.  In principle it should take fasta files of CCS reads, but I'm not sure that will really give you the best results.  CCS reads are usually far shorter than CLR reads, and Falcon does the correction of raw long reads itself.  You're going to sacrifice a lot of your assembly contiguity using short CCS reads.

**Comment by fbemm** [comment]
Sure it does use fasta files. That was just a typo. Falcon does not work with CCS reads (also not in principal). Main reason is daligner and the slightly different header format of CCS reads as I worte above. Sure CCS reads are shorter than CLR reads but there are occasions where you have CCS reads specifically after capturing experiments were the input fragment size is not longer than 2-5kb. Since they are undergoing 9-12 cycles one can directly use them as preads. Anyway, I converted headers which should bypass this issues.
