### ISSUE TITLE
when setting falcon job_type = local then the error occur

### ISSUE THREAD

**Issue by wattoBiotec** [PacificBiosciences/FALCON#185]
I have an error in the FALCON setting file( fc_run_ecoli.cfg)
when I set        job_type= local  it will give me the error but When I didn't set this parameter.
Falcon can finish the run so How to fix this problem.

I need to run by local.

The error message was show below

2015-09-04 09:24:05,493 - pypeflow.task - ERROR - PypeTaskBase failed:
{'__class__.__name__': 'PypeThreadTaskBase',
 '_status': 'TaskInitialized',
 'inputDataObjs': {'pread_fofn': PypeLocalFile('file://localhost/colossus/home/chutima/Falcon/1-preads_ovl/preads.fofn', '/colossus/home/chutima/Falcon/1-preads_ovl/preads.fofn')}

**Comment by pb-cdunn** [comment]
If it fails only with job_type=local, it's probably running out of memory. You should be able to find more logging in a sub-dir, in files like 'foo.sh.log'. And if you use `fc_run.py foo.cfg logging.ini`, where logging.ini is from FALCON-examples, you might get more Python logging.

I always recommend following these directions first:
* https://github.com/PacificBiosciences/FALCON-integrate/wiki

That gives you a fast, working example to experiment with.

**Comment by wattoBiotec** [comment]
Thank you for you quickly response. Now I have another question, How to set memory usage in Falcon version 0.2.0. Because the program automatic adjust memory usage.

**Comment by pb-cdunn** [comment]
This might be helpfu:
* https://github.com/PacificBiosciences/FALCON/wiki/Manual

**Comment by pb-cdunn** [comment]
We will soon have better memory adjustments, at least in another workflow. But we do not plan to update 0.2.0. You will have to work with specific settings, especially for daligner and falcon_sense.
