### ISSUE TITLE
how to use more than 4 threads for daligner_p?

### ISSUE THREAD

**Issue by moold** [PacificBiosciences/FALCON#186]
HI,
Because the computational nodes of my cluster  has 12 cpus and 48G memory, but during the daligner_p  step, I found the daligner_p used only 4 threads with total 46G memory, so each node i only can put one daligner_p jop on it  because of  the exhausted memory, while the cpu has some free, so how can i set the config file to use all cpus(12)？

Here is the top command for daligner_p:
```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
22908 sa    20   0 50.9g  46g  812 S 379.3 98.2 130:31.57 daligner_p -v -h60 -t32 -H10000 -e0.96 -l500 -s1000 preads.49 prea...
```

**Comment by pb-jchin** [comment]
at this moment, the number "4" is hard coded in daligner so it may not be easy to change.  What you can do is to make each block size smaller and use the "-M" parameters to control the daligner's memory usage.  If the blocks are small, you can put more process concurrent with smaller memory footprint.  However, right parameter choice would need some quick experiments though.

**Comment by moold** [comment]
Thanks！
