### ISSUE TITLE
Silent failure of daligner_p, fc_run.py hangs

### ISSUE THREAD

**Issue by lexnederbragt** [PacificBiosciences/FALCON#19]
I ran falcon on pre-corrected PacBio reads (from MHAP/PBcR), so skipping the error-correction steps. We don't have SGE (but SLURM) so I ran it with `job_type = local`. After all daligner_p processes were finished, nothing was happening. No new files, fc_run.py still showing up in 'top' and the run command not finished. 

@pb-jchin suggested that one or more of the daliger jobs might have failed with out a signal, and that I take a look at the folders and logs inside `1-preads_ovl` for anomalies.

Indeed, I found a folder with much fewer files (3 instead of the 50-70, no `.las` files):

```
find 1-preads_ovl | cut -d '/' -f 2 | uniq -c
```

Maybe a tip for others to always check these folders (and a feature request to catch this behavior :-) )

**Comment by pb-jchin** [comment]
can you check which `job_*` or `m_*` that does not have a `*done`? In the mean time, you can try to restart fc_run.py.  The fc_run.py will detect finished jobs and not re-run them in normal circumstance.  We have a much less than reliable cluster setup in-house. I constantly restart jobs to fix a couple of problem while I know some other people did human scale assembly without a single glitch.

**Comment by lexnederbragt** [comment]
Yes, there was indeed one `job_*` folder without `done` file. I have restarted fc_run.py and it started with one daligner_p.

Thanks!

**Comment by pb-jchin** [comment]
did it go through?  if so, I can close this issue.

**Comment by lexnederbragt** [comment]
It went fine after this, ticket closable. Thanks!

**Comment by rchikhi** [comment]
happened to me as well; the proposed solution fixed it.
