### ISSUE TITLE
Which settings apply where?

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#195]
Hi, Jason/Chris,

In your examples you sometimes have:

    --max_diff 30 --max_cov 60 --min_cov 5
and sometimes:

    --max_diff 100 --max_cov 100 --min_cov 2 --bestn 10 --n_core 24

Which is more appropriate for yeast?  Which is more appropriate for human?  
Which stage of Falcon are these used for--the 0-rawreads, the 1-preads_ovl, or the 2-asm-falcon stage?

Thanks!
David

**Comment by pb-cdunn** [comment]
Yeast should be fine with the first.

Settings are applied as follows:

* `0-rawreads/`:
  * `pa_*` (pre-assembly) settings
  * `length_cutoff`
* `1-preads_ovl/`:
  * `ovlp_*` settings apply
  * `length_cutoff_pr`
  * `falcon_sense_option`
* `2-asm-falcon/`:
  * `length_cutoff_pr` (yes, here too)
  * `overlap_filtering_setting`
