### ISSUE TITLE
types of overlaps used from daligner in 0-rawreads stage

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#196]
Hi, Jason,

1)  Our understanding is that all of the daligner jobs in 0-rawreads are only used for constructing preads.  Correct?

**Comment by dgordon562** [comment]
This didn't come out.  Let me try drawing it again:
2) In this daligner stage, are these kind of overlaps used and, if so, for which purpose?

                  ---------------------------------------------------
                                        -------------------------------------------------------------------

Note:  I am *not* talking about this kind of alignment that are obviously used for constructing preads:

              -----------------------------------------------------------------------------

                                         -------------------------------

**Comment by pb-jchin** [comment]
For error corrections, both are "proper alignment", you should take both. However, you might want to prioritize the overlaps.  The latest `LA4Falcon -f` takes all overlaps and I only output limited overlaps prioritized by the overlapped length. see.
https://github.com/PacificBiosciences/DALIGNER/pull/5
https://github.com/PacificBiosciences/DALIGNER/pull/6

**Comment by dgordon562** [comment]
thanks!

and i like your new ideas with la4falcon!
