### ISSUE TITLE
sge_logs disk space issue

### ISSUE THREAD

**Issue by achon** [PacificBiosciences/FALCON#197]
Hello,
  I'm currently having issues with the size of log files in sge_log.  I installed FALCON v0.3.0 using FALCON-integrate.  The test and ecoli example worked without any issues.  I thought it was strange, but the sge_log folder for the ecoli test is rather large (2.0T): 
```
3.9G    0-rawreads
1.2G    1-preads_ovl
7.3M    2-asm-falcon
989M    data
4.0K    fc_run_ecoli.cfg
12M     fc_run_ecoli.cfg.log
4.0K    input.fofn
0       pypeflow.log
0       scripts
2.0T    sge_log
```

I then setup a configuration for a larger genome (~500MB) at ~60x coverage.  However, running the daligner jobs has produced such large log files per job that it broke 100T usage in about 2000 of ~8000 daligner jobs.  Here's a snippet of the directory:
```
-rw-r--r-- 1 USER USER  65G  9ì›” 11 14:06 rj_ff5bc3b2.sh-d_ff5bc3b2_raw_reads-d_ff5bc3b2_raw_reads.o196194
-rw-r--r-- 1 USER USER    0  9ì›” 11 12:17 rj_ff5bc3b2.sh-d_ff5bc3b2_raw_reads-d_ff5bc3b2_raw_reads.po196194
-rw-r--r-- 1 USER USER  65G  9ì›” 10 06:17 rj_ff7d06f2.sh-d_ff7d06f2_raw_reads-d_ff7d06f2_raw_reads.o195810
-rw-r--r-- 1 USER USER    0  9ì›” 10 04:38 rj_ff7d06f2.sh-d_ff7d06f2_raw_reads-d_ff7d06f2_raw_reads.po195810
-rw-r--r-- 1 USER USER  65G  9ì›”  9 23:40 rj_ff876093.sh-d_ff876093_raw_reads-d_ff876093_raw_reads.o195663
-rw-r--r-- 1 USER USER    0  9ì›”  9 22:08 rj_ff876093.sh-d_ff876093_raw_reads-d_ff876093_raw_reads.po195663
-rw-r--r-- 1 USER USER  52G  9ì›” 12 16:07 rj_ffdcc9fc.sh-d_ffdcc9fc_raw_reads-d_ffdcc9fc_raw_reads.o196782
-rw-r--r-- 1 USER USER    0  9ì›” 12 14:41 rj_ffdcc9fc.sh-d_ffdcc9fc_raw_reads-d_ffdcc9fc_raw_reads.po196782
```
The contents of one file (anonymized and only a snippet): 
```
trap 'touch /PROJECT/2.Assembly-Falcon/0-rawreads/job_ff7d06f2/job_ff7d06f2_done.exit' EXIT
+ trap 'touch /PROJECT/2.Assembly-Falcon/0-rawreads/job_ff7d06f2/job_ff7d06f2_done.exit' EXIT
cd /PROJECT/2.Assembly-Falcon/0-rawreads/job_ff7d06f2
+ cd /PROJECT/2.Assembly-Falcon/0-rawreads/job_ff7d06f2
hostname
+ hostname
SERVER
date
+ date
Thu Sep 10 04:38:03 KST 2015
time daligner -v -t4 -H10000 -e0.7 -s1000 -M32 raw_reads.199 raw_reads.64 raw_reads.65 raw_reads.66 raw_reads.67
+ daligner -v -t4 -H10000 -e0.7 -s1000 -M32 raw_reads.199 raw_reads.64 raw_reads.65 raw_reads.66 raw_reads.67

Building index for raw_reads.199

 Kshift=28
 BSHIFT=8
 TooFrequent=4
 (Kshift-1)/BSHIFT + (TooFrequent < INT32_MAX)=4
 sizeof(KmerPos)=16
 nreads=8986
 Kmer=14
 block->reads[nreads].boff=100014072
 kmers=99888268
 sizeof(KmerPos)*(kmers+1)=1598212304
 Allocated 99888269 of 16 (1598212304 bytes) at 0x2abce5bc3010
   Kmer count = 99,888,268
   Using 2.98Gb of space

 ----
 ----
 shift=0, LEX_last=0, n=75066106
 @=0x2abce5bc3010+890436736 i=49997789,c&=136,x=55652296,c=71600264
 shift=0, LEX_last=0, n=24959104
 ----
 shift=0, LEX_last=0, n=99888268
 @=0x2abce5bc3010+94040160 i=75066106,c&=  5,x=5877510,c=168332805
 ----
 shift=0, LEX_last=0, n=49997789
 @=0x2abce5bc3010+451135744 i=24959104,c&= 56,x=28195984,c=177279544
 @=0x2abce5bc3010+922322224 i=     0,c&=143,x=57645139,c=178817167
 @=0x2abce5bc3010+295275056 i=49997790,c&= 32,x=18454691,c=17965600
 @=0x2abce5bc3010+505603216 i=     1,c&= 63,x=31600201,c=178397759
 @=0x2abce5bc3010+236261824 i=75066107,c&= 20,x=14766364,c=136460308
 @=0x2abce5bc3010+1577993296 i=     2,c&=255,x=98624581,c=176720127
 @=0x2abce5bc3010+1566884960 i=     3,c&=254,x=97930310,c=170009598
 @=0x2abce5bc3010+644309664 i=75066108,c&= 82,x=40269354,c=8970322
 @=0x2abce5bc3010+865592496 i=49997791,c&=131,x=54099531,c=71862403
 @=0x2abce5bc3010+594414768 i=75066109,c&= 74,x=37150923,c=35881290
 @=0x2abce5bc3010+1521426048 i=     4,c&=249,x=95089128,c=143167481
 @=0x2abce5bc3010+356172688 i=75066110,c&= 43,x=22260793,c=143525163
 @=0x2abce5bc3010+1058092544 i=75066111,c&=175,x=66130784,c=37229743
 @=0x2abce5bc3010+1142634736 i=75066112,c&=191,x=71414671,c=148918975
```

My configuration is also a slight alteration of the ecoli configuration from the [examples](https://github.com/PacificBiosciences/FALCON/tree/master/examples), allowing more jobs and threads.  Here are the related daligner lines:
```
pa_HPCdaligner_option =  -v -dal4 -t4 -M32 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal4 -t8 -M32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s100
ovlp_DBsplit_option = -x500 -s100
```

Do I need these files? Would turning off the -v option from daligner solve this or is this from sge and falcon?  How can I run this moderate genome without more disk space?

**Comment by pb-jchin** [comment]
see https://github.com/PacificBiosciences/DALIGNER/issues/10, you will need to use a recent verson of the daligner which do not do extra logging.

**Comment by achon** [comment]
Found it.  Updated and running.  However, the newest version with the same options still does the extra logging.  I've looked at https://github.com/PacificBiosciences/DALIGNER/issues/10 but so far the only option is to turn off -v.  Is there another solution?

**Comment by pb-cdunn** [comment]
That logging accidentally slipped into FALCON-integrate@0.3.0. I'll back-port the DALIGNER fix. FALCON-integrate@0.4.0 is fine.

>  However, the newest version with the same options still does the extra logging.

The tip of master for DALIGNER does *not* have the extra logging. What commit of DALIGNER are you using? (I recommend updating FALCON-integrate, pulling 0.4.0 or master, and running `git submodule update`.)

**Comment by pb-cdunn** [comment]
Oh! I'm totally wrong. That change never made it into any actual *release*:
* https://github.com/PacificBiosciences/FALCON-integrate/releases

Please use FALCON-integrate releases, not random combinations of code. You may build/install the submodules however you see fit, but you will reduce our support burden by using consistent sets of released submodules.
* https://github.com/PacificBiosciences/FALCON-integrate/wiki

**Comment by achon** [comment]
Yes, I used the FALCON-integrate releases.  Granted, I I followed https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation but it was last week (version 0.3.0).  I did update the DALIGNER submodule yesterday given the logging issue, however it still required the -v option to be removed.  I'll leave it out for now and will test the next release after this run.  

Thanks for all your help.

**Comment by pb-cdunn** [comment]
I'd like to understand how this can happen for you. Lines like the following are simply not printed in the latest source code:

    @=0x2abce5bc3010+451135744 i=24959104,c&= 56,x=28195984,c=177279544

Would you tell me the commit SHA1 of DALIGNER?

    cd DALIGNER
    git rev-parse HEAD

**Comment by achon** [comment]
I do not have the original version at the beginning of this issue, but I performed a ```git pull origin master``` for DALIGNER before responding to this issue after pb-jchin's initial response.  This is the current commit:
```
dc506e67938c1c923ebb7e43ff8ce32ec923d8ba
```
I also verified this again by running one job from the ecoli test.

**Comment by pb-cdunn** [comment]
Look at the list of commits here:
* https://github.com/PacificBiosciences/DALIGNER/commits/master

Your commit is way down the list. I don't understand how you obtained it. The fix is at 1ee01a199d4b04ba7b4c5d1dd8c5f869c5a86dce on Sept. 6. The accident was introduced at c9e7e2cbc4c8609a0626f94f8b212255299bff18 on July 31. Your commit unfortunately falls between those.

What bothers me is that you say you've been using FALCON-integrate releases, but here are releases and their DALIGNER versions:

* https://github.com/PacificBiosciences/FALCON-integrate/tree/0.3.0
  * c6cda805f9425658362b21cbd00ddf3ca8b7cb8b
  * This SHA1 is *before* verbose logging was accidentally added.
* https://github.com/PacificBiosciences/FALCON-integrate/tree/0.4.0
  * 1ee01a199d4b04ba7b4c5d1dd8c5f869c5a86dce
  * This SHA1 is *after* verbose logging was removed.

So I don't know what your mistake is, but you are clearly making a mistake. You are *not* using the versions from the FALCON-integrate releases.

**Comment by achon** [comment]
Hrm, unfortunately I don't know what to say.  Clearly I am using the wrong version, however I followed this https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation-for-v0.3.0 about 2 weeks ago (falls after the July commit but before the Sept one).  Given the issue, I then ```git pull origin master``` on DALIGNER which I had hoped would update to the post Sept 6th commit.  I'll just reinstall and rerun especially after verifying the commit versions.

**Comment by pb-cdunn** [comment]
Hmmm. It's possible that the 0.3.0 tag was moved, which would be our mistake. Anyway, the latest DALIGNER is fine.
