### ISSUE TITLE
tetraploid:0-rawreads,all the size of out.*.fa created in preads is zero,what is the problem?

### ISSUE THREAD

**Issue by AnWD** [PacificBiosciences/FALCON#201]
For example,in 0-rawreads/m_01490/,the rp_01490.log shows :
Merging 13 files totalling 1,738,764 records
LAmerge: Cannot open ./raw_reads.L1.1490.1967.las for 'r'
Merging 13 files totalling 1,897,853 records
Merging 13 files totalling 1,691,784 records
Merging 13 files totalling 1,757,122 records
Merging 13 files totalling 1,686,245 records
Merging 13 files totalling 1,687,551 records
Merging 13 files totalling 1,718,036 records
Merging 13 files totalling 1,188,580 records
Merging 13 files totalling 1,018,945 records
Merging 13 files totalling 1,171,450 records
Merging 13 files totalling 1,089,399 records
Merging 13 files totalling 1,171,344 records
Merging 13 files totalling 1,377,914 records
Merging 13 files totalling 1,623,509 records
Merging 12 files totalling 15,927,788 records
Merging 13 files totalling 18,709,600 records
Merging 13 files totalling 21,095,387 records
Merging 12 files totalling 23,201,606 records
LAmerge: Cannot open ./raw_reads.L2.1490.52.las for 'r'
Merging 13 files totalling 25,270,763 records
Merging 12 files totalling 19,255,048 records
Merging 13 files totalling 24,247,698 records
Merging 13 files totalling 30,411,529 records
Merging 12 files totalling 22,596,213 records
Merging 13 files totalling 22,693,074 records
LAmerge: Cannot open ./raw_reads.L2.1490.152.las for 'r'
Merging 13 files totalling 19,079,732 records
LAmerge: Cannot open ./raw_reads.L3.1490.5.las for 'r'
187.80user 185.35system 4:08:57elapsed 2%CPU (0avgtext+0avgdata 10114240maxresident)k
24714736inputs+81194384outputs (20030major+14610054minor)pagefaults 0swaps

and the  raw_reads.1490.las can not be created finally.And in preads/  ,the  c_01490.log shows : LA4falcon  can not open raw_reads.1490.las .there is no softlink las either.

would you please give me a hand ,thank you!

**Comment by AnWD** [comment]
every m_ directory lack of some raw_reads.L*.las file,like "LAmerge: Cannot open ./raw_reads.L3.1490.5.las for 'r'".I have check that this file was not created,should not be permission issue.

**Comment by pb-cdunn** [comment]
We don't test return-codes for mv or ln, so it's possible you ran out of disk space. Or possibly the runs which should have produced the missing files failed somehow.

**Comment by AnWD** [comment]
Yeah,when it finished daligner,there is no disk space ,so I killed the program,buy new network storage ,copy all the m_* directory to the new  storage and ln -s them back to 0-rawreads,rerun the program.   Is  there any shortcut way to get out of this situation?thank you!

**Comment by pb-cdunn** [comment]
If you keep the "*done" files, those jobs will not be repeated. But this system is not currently as robust as one would wish. Maybe you can get it working.

If you can get as far as finishing 0-rawreads stage, then you can use the output .fasta as 'preads' for the 1-preads stage. Just edit fc_run.cfg, copy the .fasta, and create a new .fofn file containing paths to fasta files. (Relative paths are fine, even preferred.) At that point, 0-rawreads/* can be discarded. In other words, the whole flow can start with preads. See the FALCON manual in the wiki.

**Comment by AnWD** [comment]
could u explain why it is not as robust as one would wish. I have read the manual,and know that      falcon can be rerun from where it was suspended.

**Comment by AnWD** [comment]
thank you,cdunn.
