### ISSUE TITLE
Missing check in get_aln_data

### ISSUE THREAD

**Issue by flowers9** [PacificBiosciences/FALCON#204]
In my copy of falcon (pulled 2015/7/22), FALCON/src/py/mains/graph_to_contigs.py is missing a check at the top of get_aln_data, in that small sequences (less than 8 bps) can cause a segfault in the call to find_kmer_pos_for_seq.  The fix is to add
```python
if len(t_seq) < K or len(q_seq) < K:
    return aln_data, x, y
```
right after the K = 8 line.

I ran across this with a q_seq that was 5 bps, but I don't see any reason not to test t_seq as well.

**Comment by pb-jchin** [comment]
Thanks for the information. The de-duplication logic has been change in the mater branch head already.  It will not try to align contigs < 2000bp, this will avoid crashing due to very short contigs.
