### ISSUE TITLE
Conflicting hash values in create_daligner_tasks

### ISSUE THREAD

**Issue by flowers9** [PacificBiosciences/FALCON#205]
In my copy of falcon (pulled 2015/7/22), in FALCON/src/py/mains/run.py, job_uids are created with hashlib.md5(l).hexdigest, then taking the first 8 characters.  This is prone to hash collisions (which I have experienced).  In practice, once a given configuration has demonstrated a hash collision, the only way to get the run to complete is to rerun with sufficiently different parameters that run_jobs.sh is different and produces different hash values (although there's always the possibility of hash collisions in the changed hashes).

The hash is being used to uniquely distinguish lines in the run_jobs.sh file.  However, there is an easy fix, which is simply to use the line number in the file (which will be unique).  I added

line_count = 0

after the file is opened,

line_count += 1

at the top of the for loop that processes all the lines, and

job_uid = str(line_count)

in place of the original job_uid = line.

**Comment by pb-jchin** [comment]
I agree with the hash collision concern.  (did you get collision runnning falcon or in other cases?) we can fix it.
