### ISSUE TITLE
Memory limits

### ISSUE THREAD

**Issue by ascendo** [PacificBiosciences/FALCON#208]
Dear Falcon

I saw the description and where can I put -M option?

Thank you.

"it uses up-to-date Gene’s daligner code. It helps to support read > 64kb and helps for tracking read identifiers through the pipeline (which is important for diploid assembly in the future). The cost is that the new code use twice more memory if the daligner parameters is the same before. One needs to use the “-M” option to set limit on the memory usage. For human assembly, we tested with -M 32 for using 32G RAM for each daligner. Other possibilities are under investigation."

**Comment by mseetin** [comment]
It can be specified in the pa_HPCdaligner_option and ovlp_HPCdaligner_option. Check https://dazzlerblog.wordpress.com/ for more information about the daligner flags.

**Comment by pb-cdunn** [comment]
Updated the [Release Notes](https://github.com/PacificBiosciences/FALCON-integrate/releases) and [Wiki Manual](https://github.com/PacificBiosciences/FALCON/wiki/Manual). Thanks.
