### ISSUE TITLE
Correct Pacbio header line format without restarting run?

### ISSUE THREAD

**Issue by afinit** [PacificBiosciences/FALCON#211]
I'm 2.5 days into processing my data and I've encountered the 'File out.00001.fasta, Line 1: Pacbio header line format error':

```
fasta2DB -v preads -f<dir>/1-preads_ovl/preads.fofn
+ fasta2DB -v preads -f<dir>/1-preads_ovl/preads.fofn
Adding 'out.00001' ...
File out.00001.fasta, Line 1: Pacbio header line format error
```

The 0-rawreads section has completed so I'm trying to avoid restarting the run entirely, but the fixes that have been suggested here aren't solving my issue: 
https://github.com/PacificBiosciences/FALCON/issues/145
https://github.com/PacificBiosciences/FALCON/issues/162

Specifically I've tried one run adding `--output_dformat` and one run adding `--output-simple-fasta-header` to the `falcon_sense_option` line starting with the preads created from the previous run. Both of these runs resulted in the above error indicating that my PacBio header line was formatted improperly

Do these require me to restart my run entirely? Or is there a way to correct the header line format myself?

**Comment by pb-cdunn** [comment]
Yes, you can correct this yourself. Give me a few minutes to find some simple code ...

**Comment by afinit** [comment]
If you could tell me what format it expects and what needs to be different between each header, I could probably write something up myself

**Comment by pb-cdunn** [comment]
This section of `src/py/mains/consensus.py` shows what needs to be done:
```python
227                     if not args.output_simple_fasta_header:
228                         if seq_i >= 10:
229                             break
230                         print ">prolog/%s%01d/%d_%d" % (seed_id, seq_i, 0, len(cns_seq))
231                         print format_seq(cns_seq, 80)
232                     else:
233                         print ">"+seed_id+"_%d" % seq_i
234                         print cns_seq
```
We need the top case, but you have the bottom (probably). Here is one way to modify the .fasta files:
```python
import sys, os
from pbcore.io import FastaIO

def run(reader, writer):
    for record in reader:
        seq_length = len(record.sequence)
        zmw = record.header.split('/')[1]
        bounds = record.header.split('/')[-1]
        start, end = [int(k) for k in bounds.split('_')]
        new_end = start + seq_length

        new_header = "m000_000/{zmw}/{start}_{end}".format(zmw=zmw, start=start, end=new_end)

        writer.writeRecord(new_header, record.sequence)

def main(iname, ofile):
    reader = FastaIO.FastaReader(iname)
    writer = FastaIO.FastaWriter(ofile)
    run(reader, writer)

if __name__ == '__main__':
    iname, oname = sys.argv[1:3]
    ofile = open(oname, 'w')
    try:
        main(iname, ofile)
    except:
        # clean up (for make)
        ofile.close()
        os.unlink(oname)
        raise
```
Actually, I don't think we use those header data for anything, so you could just do a search-and-replace to add the same header everywhere. (Although that might be a problem for a post-falcon step.)

But now I have a question for you: What commit of FALCON are you using? `git rev-parse HEAD`. And which release of FALCON-integrate. (We want everyone to pull FALCON-integrate for consistent submodules.)

**Comment by pb-cdunn** [comment]
The reason I ask about the version is because the latest should not output the old format at all!

**Comment by afinit** [comment]
We have been using FALCON-Integrate. We just updated to v0.4.0 today, but the errors were coming from an install of 0.3.0, commit:
de448e3cd0327d2a2dfc86ab18f36114ab5de66e

**Comment by pb-cdunn** [comment]
Thx.

**Comment by afinit** [comment]
to convert the header names, I changed the above script to:

```
import sys, os
from pbcore.io import FastaIO

def run(reader, writer):
    for record in reader:
        seq_length = len(record.sequence)
        zmw = record.header.replace('_','')
        #bounds = record.header
        start, end = 0,0
        new_end = start + seq_length

        new_header = "protocol/{zmw}/{start}_{end}".format(zmw=zmw, start=start, end=new_end)

        writer.writeRecord(new_header, record.sequence)

def main(iname, ofile):
    reader = FastaIO.FastaReader(iname)
    writer = FastaIO.FastaWriter(ofile)
    run(reader, writer)

if __name__ == '__main__':
    iname, oname = sys.argv[1:3]
    ofile = open(oname, 'w')
    try:
        main(iname, ofile)
    except:
        # clean up (for make)
        ofile.close()
        os.unlink(oname)
        raise
```
