### ISSUE TITLE
Optimising Parameter and jobs for De novo assembly of  Plant Genome (expected genome size 500mb and 52x coverage) on server having  1TB RAM and  80 Cores using falcon   

### ISSUE THREAD

**Issue by sudhirjadhao** [PacificBiosciences/FALCON#212]
I ran HGAP but its not working for me because of large data  and large genome size. I tried falcon with below parameter but its throwing error. Can you please help me out deciding parameter for above explain server.
```ini
[General]
# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads
job_type= local

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 500

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 2500


jobqueue = your_queue
sge_option_da = -pe smp 8 -q %(jobqueue)s
sge_option_la = -pe smp 2 -q %(jobqueue)s
sge_option_pda = -pe smp 8 -q %(jobqueue)s
sge_option_pla = -pe smp 2 -q %(jobqueue)s
sge_option_fc = -pe smp 24 -q %(jobqueue)s
sge_option_cns = -pe smp 8 -q %(jobqueue)s

pa_concurrent_jobs = 32
ovlp_concurrent_jobs = 32

pa_HPCdaligner_option =  -v -dal24 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal24 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 40
```

**Comment by pb-jchin** [comment]
hi, @sudhirjadhao, I think parameter optimization for a particular genome is not a direct software bug issue, I would prefer we bring the discussion here: https://groups.google.com/forum/#!forum/smrt_denovo
It depends on many factors and the repeat content of the genome. I think there is something you can do nicely with 1Tb / 80 cores. Let's discuss that in the forum.

**Comment by mseetin** [comment]
Hi @sudhirjadhao,  I'd be happy to work with you about parameter optimization in the Google group, but could you post the error you are getting here in case there is an issue separate from parameter choice?

**Comment by sudhirjadhao** [comment]
Thank you for your kind reply
Below are the two error I am getting

1) raise TaskFailureError("Counted %d failures." %failedJobCount)
TaskFailureError: 'Counted 1 failures.'
 No target specified, assuming "assembly" as target 


2) File "/home/bionivid-server/.local/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 447, in main1
    wf.refreshTargets(updateFreq = wait_time) # larger number better for more jobs, need to call to run jobs here or the # of concurrency is changed
  File "/usr/local/lib/python2.7/dist-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/usr/local/lib/python2.7/dist-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 706, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
pypeflow.controller.TaskFailureError: 'Counted 1 failures.'
