### ISSUE TITLE
Error with Ecoli Test Set

### ISSUE THREAD

**Issue by dshvets** [PacificBiosciences/FALCON#213]
It seems that there were no issues with installing Falcon as no errors appeared during installation. But I cannot get the fc_run.py script to run using the ecoli test data set. I am in the FALCON-integrate/FALCON-examples/run/ecoli directory, which includes the data directory with fasta files, and an input.fofn file, and the fc_run.cfg file. This is the script that I am trying to run:

/Users/dahlia/Desktop/PACBIO_Research/Falcon_Software/FALCON-integrate/fc_env/bin/fc_run.py fc_run.cfg

And I am getting errors, it looks like it is running because it does create output folders but they are empty. The only thing that I altered was going into the fc_run.cfg file and adding the line job_type = local as I saw others do if they are not running Falcon on a cluster. What could be going wrong? Here are some of the errors that I am getting: 

2015-10-01 14:39:30,701 - pypeflow.task - ERROR - PypeTaskBase failed:
{'__class__.__name__': 'PypeThreadTaskBase',
 '_status': 'TaskInitialized',

 File "/Users/dahlia-shvets/Desktop/PACBIO_Research/Falcon_Software/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 706, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
TaskFailureError: 'Counted 1 failures.'
2015-10-01 14:39:30,793 - pypeflow.controller - ERROR - Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
Traceback (most recent call last):
  File "/Users/dahlia-shvets/Desktop/PACBIO_Research/Falcon_Software/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/Users/dahlia-shvets/Desktop/PACBIO_Research/Falcon_Software/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 706, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
TaskFailureError: 'Counted 1 failures.'

I have absolutely no idea where to go from here, any help at all would be much appreciated, thank you so much!

**Comment by pb-jchin** [comment]
do you see anything in the `sge_log/` or `0-rawread/`?  Have you download the test dataset?

**Comment by dshvets** [comment]
No both of those are empty. There appears to be test data available when I install Falcon. It is located in the test_data directory, there is a fasta file as well as a .fofn file. What else is required to run the command? Why is this not explicitly listed anywhere, it is extremely confusing to find which sample data, where it is, how to run, exactly what location everything should be in. Because the .fofn file doesn't even provide the direct path, it's relative.

**Comment by pb-jchin** [comment]
you need to make sure you input.fofn files pointing to the data file.

**Comment by dshvets** [comment]
The ecoli data set had the .fofn file pointing to the correct data files but it still would give me errors. The make run-ecoli command does not work either. However, I got the lamba_filtered_subreads.fasta data set to run successfully. Thank you.

**Comment by pb-cdunn** [comment]
I'll look into the run-ecoli command. Might be out-of-date. Thanks for the details.

**Comment by dshvets** [comment]
Thank you for your time and help. 
Although I have gotten the sample eColi set to run, I cannot get my own data set to run successfully. I get many errors and in the prepare_rdb.sh.log file it says that one of the lines in the Fasta file is too long. Should I change some sort of parameters so that this will not be a problem? This is PacBio data. Thank you again.

**Comment by pb-jchin** [comment]
when I see the fasta file line too long, and I trace to the root cause, it always leads to corrupted fasta files.  Can you check if your fasta files are corrupted?

**Comment by dshvets** [comment]
I tried with a different fasta file and I seem to get the same error. 
It says:
 "Fasta line is too long (>9998 chars)". 
So this error is always caused by a corrupted file? If so, I will download a different data set and try again.
