### ISSUE TITLE
command to git latest FALCON for testing

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#215]
Hi, Jason,

To test FALCON with CHM1 as planned, shall I:

git clone git://github.com/PacificBiosciences/FALCON-integrate.git

or:
git clone git://github.com/PacificBiosciences/FALCON

?

Thanks!
David

**Comment by pb-jchin** [comment]
you should do `git clone git://github.com/PacificBiosciences/FALCON-integrate.git`  and do a `git checkout 0.4.0` inside the `FALCON-integrate` directory to use the tagged release.

**Comment by dgordon562** [comment]
Thanks, Jason!

**Comment by pb-cdunn** [comment]
You don't have to use FALCON-make or FALCON-examples. You can build/install however you want. But FALCON-integrate will at least ensure a consistent set of versions of packages.
