### ISSUE TITLE
determining which jobs have completed

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#216]
Is there a quick way to determine which daligner jobs have completed and which are still to be done?  (Looking through all of the job_ subdirectories to see which have _done files is not quick--it takes hours).

If not, a useful enhancement would be to log to a file whenever a job completes.  Not just for daligner, but for any job

Thanks!
David

**Comment by pb-cdunn** [comment]
Yes, good idea, but we're not putting time into pypeflow interactions right now because of the new internal workflow engine. A lot of (hard to understand) info already goes into the pypeflow.log file, depending on how you've configured the standard python logger.

**Comment by dgordon562** [comment]
OK.  Thanks for your quick response.

Best wishes,
David
