### ISSUE TITLE
error during 1-preads_ovl / p_merge_done step

### ISSUE THREAD

**Issue by conte1** [PacificBiosciences/FALCON#217]
Hi,

A couple of the p_merge jobs are failing with the following error:

```
...
Merging 32 files totalling 42,378 records
Merging 8 files totalling 517,039 records
Merging 8 files totalling 423,228 records
Merging 8 files totalling 388,383 records
Merging 8 files totalling 392,336 records
Merging 8 files totalling 376,861 records
LAmerge: Cannot open ./L1.37.45.las for 'r'
Merging 8 files totalling 388,468 records
Merging 9 files totalling 452,664 records
LAmerge: Cannot open ./L2.37.6.las for 'r'
...
```
And so I am missing a couple of the 1-preads_olv .las files. I have tried to re-run each of these rp_000.sh jobs manually, but they just fail with the same error.

Do I need to re-run the entire 1-preads_ovl step or is there a way to restart at the end of the "da_done" step?

Thanks,
Matt

**Comment by pb-jchin** [comment]
you have some block-block comparison job faile. If you can find what they are, you can just re-run the daligner job for those jobs to recover. However, there is no simple tool to do that. I typical find the suspicious block and take a look at the orginal *.las file. In your case, the block 37 might be problematic.

**Comment by pb-cdunn** [comment]
Jason, How does this occur? I mean, which step might run even though the pre-requisites are incomplete?

Matt, Which version/commit are you using?

**Comment by conte1** [comment]
Jason,

If I search for 1-preads_ovl/job_*/preads.37*, I get about 29 job_* directories that contain about 32 preads.37.preads*.las files and one directory that contains 1,184 preads.37.preads*.las files. 
Are you suggesting that I re-run all of the 1-preads_ovl daligner jobs that contain preads.37.preads*.las or just the directory that contains the 1,184? There doesn't seem to be anything wrong in any of these directories.

I'd also like to know how this occurs as Chris asked. And to answer your question Chris I am running version 0.3.0-0 / 88f269bdcba3febc9b70a08aa43793d65432d8a2.

Thanks,
Matt

**Comment by conte1** [comment]
Hey guys,

I was able to track down the problematic files in the 1-preads_ovl/job_* directories as there were a few .las files that were 0kb in size. I never did get any errors for those jobs, so I'm not sure why the failed. Re-running those couple rp_*.sh jobs fixed the problem and I was able to complete the assembly.

-Matt

**Comment by pb-cdunn** [comment]
We will definitely watch for that happening again.
