### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by compbiochem** [PacificBiosciences/FALCON#22]
Making a new thread, as per your request.  I am hoping you can help me out with an installation issue I have been having at a national computing resource. When I try to rebuild with:

virtualenv --no-site-packages --always-copy $PWD/fc_env
. $PWD/fc_env/bin/activate
git clone https://github.com/cschin/pypeFLOW
cd pypeFLOW
python setup.py install

cd ..
git clone https://github.com/PacificBiosciences/FALCON.git
cd FALCON
python setup.py install

cd ..
git clonehttps://github.com/pb-jchin/DAZZ_DB.git
cd DAZZ_DB/
make
cp DBrm DBshow DBsplit DBstats fasta2DB ../fc_env/bin/

cd ..
git clone https://github.com/pb-jchin/DALIGNER.git
cd DALIGNER
make
cp daligner daligner_p DB2Falcon HPCdaligner LA4Falcon LAmerge LAsort ../fc_env/bin
cd ..

I see the error, "line 6: /usr/bin/time: No such file or directory" when I try to run the test job for all of the d_* error correction jobs in 0-rawreads. Apologies, but I didn't do the original install, but some of the folks at this resource want me to prove the update fixes my issue, by doing an install in one my directories.

I am not sure how to remove "/usr/bin/time" from fc_run.py, as I don't see any instances in the script itself.

**Comment by pb-jchin** [comment]
You can safely remove all "/usr/bin/time" in fc_run.py it is used only for benchmarking computational performance and tracking resource usage. A good thing such you might want to request your admin to install it. If you don't have the permission to modify the system installation of the fc_run.py, you can make a copy and modify it and call it directly with `python fc_run.py`.

**Comment by mseetin** [comment]
compbiochem, on e.g. line 243, the python code is making a script that will eventually be submitted to the cluster.  Part of this script is using /usr/bin/time to measure the amount of computing resources used by this step of Falcon.  It does this by executing /usr/bin/time followed by the command it wishes to time. If you delete the text "/usr/bin/time" from this line of code, Falcon will no longer report how long it takes to execute this step, but it will still execute that step.

**Comment by pb-jchin** [comment]
mseetin, thanks for making it much more clear.   compbiochem, please try out this out to see if it works for you.

**Comment by pb-jchin** [comment]
compbiochem, any progress, if so, we can close this issue. Thanks.

**Comment by compbiochem** [comment]
Yes, the issue seems to have been resolved.  I have a test job, successfully completed the whole way through and one of my large assemblies is currently running (made it through the initial stages).

**Comment by pb-jchin** [comment]
ok. I am closing this issue for now.
