### ISSUE TITLE
fc_dedup_a_tigs drastically break my assembly

### ISSUE THREAD

**Issue by mbourgey** [PacificBiosciences/FALCON#225]
Hello

I'm currently testing falcon with my pacbio data and I noticed that I arrive to generate a decent genome size initially (in the p_ctg.fa file) but my assembly become completely out of scope after the  last fc_dedup_a_tigs step (in the a_ctg.fa file).
To give you an example here is the number I get if I run falcon on the test data set (E. Coli) with the test settings you provided (QUAST output):
Assembly	a_ctg	p_ctg
contigs Num (>= 0 bp)	1	1
contigs Num (>= 1000 bp)	1	1
Total length (>= 0 bp)	26353	4635483
Total length (>= 1000 bp)	26353	4635483
contigs Num	1	1
Largest contig	26353	4635483
Total length	26353	4635483
GC (%)	43.67	50.75
N50	26353	4635483
N75	26353	4635483
L50	1	1
L75	1	1

So clearly my p_ctg fits the expected genome size of E. Coli but not my a_ctg which is ridiculously small. 
Any idea to what is going on at the step ? 
and if I understood well the de-duplication process it would mean that my first set of contigs is just errors ! 

Could it be an issue with this script ?

Thank you in advance

Mathieu

**Comment by pb-jchin** [comment]
This is expected for the E. coli genome.
Please read the manual (https://github.com/PacificBiosciences/FALCON/wiki/Manual). There is some explanation what "a-tig" means.  Please also check out this presentation, https://speakerdeck.com/jchin/de-novo-diploid-genome-assembly-and-haplotype-sequence-reconstruction.
