### ISSUE TITLE
/FALCON-integrate/FALCON-module directory not created when installing "Setup: Complete example"

### ISSUE THREAD

**Issue by tpshea2** [PacificBiosciences/FALCON#226]
Hello-

I have installed FALCON using the script provided here:  https://github.com/PacificBiosciences/FALCON/wiki/Setup%3A-Complete-example

The main reason I am using the complete example script is to see how the test E. coli data will assemble.  Previous attempts to install FALCON using the https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation-for-v0.3.0 steps (the "easy way" resulted in missing E. coli test data.

I am not sure if the install worked.  I suspect it has not because early in the process of starting the E. coli test I see this reported:
cp: cannot stat `/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/FALCON-module/FALCON/examples/fc_run_ecoli.cfg': No such file or directory

And I see that there is no FALCON-module subdirectory in the FALCON-integrate.

There were some messages that I do not understand as the complete script ran.  I have copied these in below.  Based on this is there a recommendation for trying to install FALCON some other way?

/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources.py:2443: PEP440Warning: 'formic (0.9beta3j)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources.py:2443: PEP440Warning: 'rdfextras (0.1a.linux-i686)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources.py:2443: PEP440Warning: 'rdfextras-0.1a.linux (i686)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources.py:2443: PEP440Warning: 'rdfextras (dev)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources.py:2443: PEP440Warning: 'rdfextras (hgsnapshot-20100728)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
warning: no files found matching '*.py' under directory 'examples'
warning: no files found matching '*.pyc' under directory 'examples'
zip_safe flag not set; analyzing archive contents...
rdfextras.__init__: module references __path__
/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources.py:2443: PEP440Warning: 'rdflib (dev)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*$py.class' found anywhere in distribution
zip_safe flag not set; analyzing archive contents...
zip_safe flag not set; analyzing archive contents...
pyparsing: module MAY be using inspect.stack
zip_safe flag not set; analyzing archive contents...
zip_safe flag not set; analyzing archive contents...
no previously-included directories found matching 'documentation/_build'
zip_safe flag not set; analyzing archive contents...
six: module references __path__
DB.c: In function â€˜Load_QVsâ€™:
DB.c:728: warning: â€˜ncodesâ€™ may be used uninitialized in this function
At top level:
cc1: warning: unrecognized command line option "-Wno-unused-result"
DBshow.c: In function â€˜mainâ€™:
DBshow.c:127: warning: â€˜repsâ€™ may be used uninitialized in this function
DBshow.c:127: warning: â€˜ptsâ€™ may be used uninitialized in this function
DBshow.c:130: warning: â€˜inputâ€™ may be used uninitialized in this function
At top level:
cc1: warning: unrecognized command line option "-Wno-unused-result"
filter.c: In function â€˜lex_threadâ€™:
filter.c:218: warning: format â€˜%dâ€™ expects type â€˜intâ€™, but argument 4 has type â€˜int64â€™
filter.c:282: warning: format â€˜%dâ€™ expects type â€˜intâ€™, but argument 3 has type â€˜long long unsigned intâ€™
filter.c:282: warning: format â€˜%6dâ€™ expects type â€˜intâ€™, but argument 4 has type â€˜int64â€™
filter.c:282: warning: format â€˜%3dâ€™ expects type â€˜intâ€™, but argument 5 has type â€˜long long unsigned intâ€™
filter.c:282: warning: format â€˜%3dâ€™ expects type â€˜intâ€™, but argument 6 has type â€˜int64â€™
filter.c:282: warning: format â€˜%dâ€™ expects type â€˜intâ€™, but argument 7 has type â€˜uint64â€™
filter.c:298: warning: format â€˜%dâ€™ expects type â€˜intâ€™, but argument 3 has type â€˜int64â€™
filter.c: In function â€˜sort_kmersâ€™:
filter.c:755: warning: format â€˜%dâ€™ expects type â€˜intâ€™, but argument 3 has type â€˜long unsigned intâ€™
filter.c:755: warning: format â€˜%dâ€™ expects type â€˜intâ€™, but argument 4 has type â€˜long unsigned intâ€™
filter.c: In function â€˜report_threadâ€™:
filter.c:1258: warning: â€˜npairâ€™ may be used uninitialized in this function
At top level:
cc1: warning: unrecognized command line option "-Wno-unused-result"
In file included from filter_p.c:2:
filter.c: In function â€˜lex_threadâ€™:
filter.c:218: warning: format â€˜%dâ€™ expects type â€˜intâ€™, but argument 4 has type â€˜int64â€™
filter.c:282: warning: format â€˜%dâ€™ expects type â€˜intâ€™, but argument 3 has type â€˜long long unsigned intâ€™
filter.c:282: warning: format â€˜%6dâ€™ expects type â€˜intâ€™, but argument 4 has type â€˜int64â€™
filter.c:282: warning: format â€˜%3dâ€™ expects type â€˜intâ€™, but argument 5 has type â€˜long long unsigned intâ€™
filter.c:282: warning: format â€˜%3dâ€™ expects type â€˜intâ€™, but argument 6 has type â€˜int64â€™
filter.c:282: warning: format â€˜%dâ€™ expects type â€˜intâ€™, but argument 7 has type â€˜uint64â€™
filter.c:298: warning: format â€˜%dâ€™ expects type â€˜intâ€™, but argument 3 has type â€˜int64â€™
filter.c: In function â€˜sort_kmersâ€™:
filter.c:755: warning: format â€˜%dâ€™ expects type â€˜intâ€™, but argument 3 has type â€˜long unsigned intâ€™
filter.c:755: warning: format â€˜%dâ€™ expects type â€˜intâ€™, but argument 4 has type â€˜long unsigned intâ€™
In file included from filter_p.c:2:
filter.c: In function â€˜report_threadâ€™:
filter.c:1258: warning: â€˜npairâ€™ may be used uninitialized in this function
At top level:
cc1: warning: unrecognized command line option "-Wno-unused-result"
--2015-10-15 12:10:41--  https://www.dropbox.com/s/tb78i5i3nrvm6rg/m140913_050931_42139_c100713652400000001823152404301535_s1_p0.1.subreads.fasta
Resolving www.dropbox.com... 108.160.172.238, 108.160.172.206
Connecting to www.dropbox.com|108.160.172.238|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://dl.dropboxusercontent.com/content_link/DXzhghEmxnZuhYFLBI0EyWmPbV4NFVA4YrLquI2wQCH2E3jaWEz9Ur8AOG8o9ser/file [following]
--2015-10-15 12:10:42--  https://dl.dropboxusercontent.com/content_link/DXzhghEmxnZuhYFLBI0EyWmPbV4NFVA4YrLquI2wQCH2E3jaWEz9Ur8AOG8o9ser/file
Resolving dl.dropboxusercontent.com... 54.243.159.171, 54.243.71.4, 54.225.174.197, ...
Connecting to dl.dropboxusercontent.com|54.243.159.171|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 343006444 (327M) [text/plain]
Saving to: â€œm140913_050931_42139_c100713652400000001823152404301535_s1_p0.1.subreads.fastaâ€

100%[==========================================================================================>] 343,006,444 37.1M/s   in 11s     

2015-10-15 12:10:57 (29.2 MB/s) - â€œm140913_050931_42139_c100713652400000001823152404301535_s1_p0.1.subreads.fastaâ€ saved [343006444/343006444]

--2015-10-15 12:10:57--  https://www.dropbox.com/s/v6wwpn40gedj470/m140913_050931_42139_c100713652400000001823152404301535_s1_p0.2.subreads.fasta
Resolving www.dropbox.com... 108.160.172.238, 108.160.172.206
Connecting to www.dropbox.com|108.160.172.238|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://dl.dropboxusercontent.com/content_link/8RNwSthq38PoakKrwqvTVfrD2g2RakFZfZ4Q6dQsiJOUmUCpTRIwQexlYVnPinS2/file [following]
--2015-10-15 12:10:58--  https://dl.dropboxusercontent.com/content_link/8RNwSthq38PoakKrwqvTVfrD2g2RakFZfZ4Q6dQsiJOUmUCpTRIwQexlYVnPinS2/file
Resolving dl.dropboxusercontent.com... 54.225.174.197, 54.221.224.130, 54.243.71.4, ...
Connecting to dl.dropboxusercontent.com|54.225.174.197|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 324266993 (309M) [text/plain]
Saving to: â€œm140913_050931_42139_c100713652400000001823152404301535_s1_p0.2.subreads.fastaâ€

100%[==========================================================================================>] 324,266,993 14.4M/s   in 15s     

2015-10-15 12:11:16 (20.5 MB/s) - â€œm140913_050931_42139_c100713652400000001823152404301535_s1_p0.2.subreads.fastaâ€ saved [324266993/324266993]

--2015-10-15 12:11:16--  https://www.dropbox.com/s/j61j2cvdxn4dx4g/m140913_050931_42139_c100713652400000001823152404301535_s1_p0.3.subreads.fasta
Resolving www.dropbox.com... 108.160.172.238, 108.160.172.206
Connecting to www.dropbox.com|108.160.172.238|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://dl.dropboxusercontent.com/content_link/m43raYF15GNIppXJmTbiI7YODVjQm4jwpU3YHmLkZ4R39uJDdgEPdmJ5fFApwEJd/file [following]
--2015-10-15 12:11:17--  https://dl.dropboxusercontent.com/content_link/m43raYF15GNIppXJmTbiI7YODVjQm4jwpU3YHmLkZ4R39uJDdgEPdmJ5fFApwEJd/file
Resolving dl.dropboxusercontent.com... 54.225.167.76, 54.243.70.174, 54.221.224.130, ...
Connecting to dl.dropboxusercontent.com|54.225.167.76|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 369661959 (353M) [text/plain]
Saving to: â€œm140913_050931_42139_c100713652400000001823152404301535_s1_p0.3.subreads.fastaâ€

100%[==========================================================================================>] 369,661,959 23.2M/s   in 12s     

2015-10-15 12:11:33 (28.6 MB/s) - â€œm140913_050931_42139_c100713652400000001823152404301535_s1_p0.3.subreads.fastaâ€ saved [369661959/369661959]

cp: cannot stat `/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/FALCON-module/FALCON/examples/fc_run_ecoli.cfg': No such file or directory
2015-10-15 16:11:39,025 - fc_run - INFO - fc_run started with configuration fc_run_ecoli.cfg
2015-10-15 16:11:39,025 - fc_run - INFO - fc_run started with configuration fc_run_ecoli.cfg
Traceback (most recent call last):
  File "/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/fc_env/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.4.0', 'fc_run.py')
  File "/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources.py", line 646, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources.py", line 1567, in run_script
    exec(code, namespace, namespace)
  File "/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 572, in main
    main1(*argv)
  File "/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 392, in main1
    config = support.get_config(support.parse_config(input_config_fn))
  File "/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/run_support.py", line 147, in get_config
    length_cutoff = config.getint('General', 'length_cutoff')
  File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/python_2.7.1-sqlite3-rtrees/lib/python2.7/ConfigParser.py", line 351, in getint
    return self._get(section, int, option)
  File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/python_2.7.1-sqlite3-rtrees/lib/python2.7/ConfigParser.py", line 348, in _get
    return conv(self.get(section, option))
  File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/python_2.7.1-sqlite3-rtrees/lib/python2.7/ConfigParser.py", line 567, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'General'

**Comment by pb-cdunn** [comment]
> the "easy way" resulted in missing E. coli test data

Right. The "easy way" proves that FALCON is properly installed. It does not run E.coli. Please verify that the easy works first.

> `cp: cannot stat `/cil/shed/sandboxes/tshea/software/FALCON/attempt5_using_setup_complete_script_exaple/FALCON-integrate/FALCON-module/FALCON/examples/fc_run_ecoli.cfg': No such file or directory`

I don't know what `FALCON-integrate/FALCON-module/FALCON` is. You should have `FALCON-integrate/FALCON`, since **FALCON-integrate** is simply a parent for git-submodules. I suggest trying a brand-new checkout, using 0.4.0 this time.

After the "easy way" is working, you can run `. fc_env/bin/activate` to put the executables into your `$PATH`. Then,
```
cd FALCON-examples/run/ecoli
git-sym update
fc_run fc_run.cfg fc_run.log
```
