### ISSUE TITLE
local running #question

### ISSUE THREAD

**Issue by ascendo** [PacificBiosciences/FALCON#23]
Dear Jason,

I saw there is type=local for avoid to use SGE grid.

How can I use it ?

Our grid never allow job submission in computing node.

Thank you.

Won

**Comment by pb-jchin** [comment]
Well, the local mode is only for small assembly (or you have a high CPU cores + hi memory single node server).   Only the fc_run.py submits jobs. It typically uses not much CPUs but it needs to be running constantly until the assembly job finished. You may run it in the submitting host if it allows long running job. I do still have to change some code to avoid running I/O intensive stuff on the submitting node. (See https://github.com/PacificBiosciences/FALCON/issues/14)

**Comment by ascendo** [comment]
Thank you Jason!

Is there any doc for output?

**Comment by pb-jchin** [comment]
just some incomplete doc in `/doc`, need to find some time to finish it

**Comment by ascendo** [comment]
Hope it complete soon.

Thank you.
