### ISSUE TITLE
Can I re-direct the output of  FALCON?

### ISSUE THREAD

**Issue by adennis5** [PacificBiosciences/FALCON#234]
Hi there,

Is there a way to point the output of FALCON to a different directory?  Especially all of the folders it makes when I execute: fy_run.py? I have limited space in the home directory of my computing cluster, so as soon as it starts making copies of the data, my job gets shut down!

In case it matters, I'm trying to run FALCON on a computing cluster that uses and lsf job submission system (I think that's the right name?). Because of this, I'm using job_type=local, and that seems to be working ok.

thanks,
Alice

**Comment by pb-cdunn** [comment]
You can use `job_type=local` in `/tmp/my-run-dir`.

However, distributed jobs communicate their results back to the master via the network filesystem. Re-directing would not help.
