### ISSUE TITLE
Falcon rejects format of headers of FASTA reads (previously error-corrected by PBcR-MHAP)

### ISSUE THREAD

**Issue by SchwarzEM** [PacificBiosciences/FALCON#249]
I am trying to run FALCON-integrate 0.4.0 on a set of PacBio reads that I have already previously error-corrected using the PBcR-MHAP corrector/assembler.  In other words, having corrected them with MHAP and assembled them with PBcR, I would like to now try an alternative assembly with FALCON.  I would like do this using FALCON in its "skip the error-correction step" mode (i.e., with `input_type = preads` in its fc_run.cfg configuration file).

But when I start the run, it very quickly dies, giving me the error message:

```
fasta2DB -v preads -f/sternlab/redivivus/data02/schwarz/PacBio/FALCON-integrate/nigoni_2015.11.13.01/1-preads_ovl/input.fofn
+ fasta2DB -v preads -f/sternlab/redivivus/data02/schwarz/PacBio/FALCON-integrate/nigoni_2015.11.13.01/1-preads_ovl/input.fofn
Adding 'nigoni_mhap_haploid_2015.10.23.01' ...
File nigoni_mhap_haploid_2015.10.23.01.fasta, Line 1: Pacbio header line format error
```

Since these reads were generated by PBcR-MHAP, not FALCON, they do not have the format that FALCON (apparently) absolutely and non-negotiably demands.  Specifically, my header lines look like this:

```
>nigoni_mhap_haploid_2015.10.23.01_7306_1_0
>nigoni_mhap_haploid_2015.10.23.01_7316_1_1
>nigoni_mhap_haploid_2015.10.23.01_7317_1_0
[etc. etc. etc.]
```

rather than having the format they had back when they were filtered subreads right off of the PacBio machine, i.e., when they looked like this:

```
@m150726_091659_42137_c100833552550000001823181811251534_s1_p0/11/0_100
@m150726_091659_42137_c100833552550000001823181811251534_s1_p0/14/0_15293
@m150726_091659_42137_c100833552550000001823181811251534_s1_p0/19/0_8837
```

This is a pretty trivial reason not to be able to run FALCON -- but it's got me absolutely defeated.  Can somebody please tell me how to get FALCON to accept my reads?

Thank you for any advice you can provide!

In case anybody needs further details, I will list them below; if they're not needed, please skip them.

The basic commands I ran to get things going:

```
source /sternlab/redivivus/data02/schwarz/PacBio/FALCON-integrate/fc_env/bin/activate ;
fc_run.py fc_run.cfg logging.ini ;
```

The contents of my fc_run.cfg file:

```ini
[General]
job_type = local

input_fofn = input.fofn

input_type = preads

length_cutoff = 15000

length_cutoff_pr = 11990

sge_option_da =
sge_option_la =
sge_option_pda =
sge_option_pla =
sge_option_fc =
sge_option_cns =

pa_concurrent_jobs = 4

ovlp_concurrent_jobs = 4

pa_HPCdaligner_option =  -v -dal128 -t16 -e.70 -l1000 -s1000 -M 8

ovlp_HPCdaligner_option = -v -dal128 -t32 -h60 -e.96 -l500 -s1000 -M 8

pa_DBsplit_option = -a -x500 -s400

ovlp_DBsplit_option = -x500 -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6 --simple-fasta-header

overlap_filtering_setting = --max_diff 50 --max_cov 75 --min_cov 5 --bestn 10 --n_core 24
```

The contents of my input.fofn file:

```
nigoni_mhap_haploid_2015.10.23.01.fasta
```

**Comment by pb-jchin** [comment]
"@" is for fastq. try convert the files to fasta to see if it works.

**Comment by SchwarzEM** [comment]
I must not have been clear enough: the reads I am submitting are, indeed, fasta!  The 'header' problem has to be due to the content of the header; they start with '>' just fine.

Here are the headers of the reads that I am submitting (I am trying to not have github screw up the formatting this time):

    >nigoni_mhap_haploid_2015.10.23.01_1458893_1_2
    >nigoni_mhap_haploid_2015.10.23.01_1458897_1_0
    >nigoni_mhap_haploid_2015.10.23.01_1458898_1_0

The other headers I showed with '@' are from the *pre*-error-corrected subreads, right off the machine in FastQ format.  They have the read-name format that I believe FALCON wants (e.g., "m150726_091659_42137_c100833552550000001823181811251534_s1_p0/19/0_8837").   Of course, I can't provide that format because my error-corrected reads have passed through PBcR-MHAP, and have gotten renamed.

**Comment by pb-jchin** [comment]
the header needs to have three fields separated by "/"., the 2nd files has to be a unique number. The difference two numbers on the third field separated by "_" need to be the same as the sequence length. 

Also, the "-M 8" might be too small for 400Mb block. You can make the block smaller.

**Comment by SchwarzEM** [comment]
OK.  I'll whack out a script to take the exact sequence reads I have now and give them headers with this format.

Unique positive numbers in the second field will be easy to make.   Can the second field number be something like '0000134', or does it have to be '134' with no leading zeros?

I take it that, for a read 8,000 nt long, having the third field be "0_8000" would work fine.

Is there any specific content required for the 1st field (before the first '/'), other than standard word characters (A-Z, a-z, 0-9, and '_')?

**Comment by SchwarzEM** [comment]
Not quite on topic, but this is a genome about 130 Mb in size.  As I understand it, "-s400" controls the block size (currently setting it to 400 Mb).  My error-corrected reads are a total of 3,250,205,389 nt in 200,863 reads.  So, does it really make sense to lower '-s400', or should I instead increase "-M 8"?  I'm working on a machine with 16 CPUs and 256 GB of RAM.

**Comment by pb-jchin** [comment]
I typically use 24Gb for 400Mb block.  24G for 4 (virtual) cores. You have 256G, it should be fine to use "-M 24".

**Comment by SchwarzEM** [comment]
Thank you, Jason!

I'll write a read-renaming script, and confirm that it works once I have it running.

**Comment by pb-cdunn** [comment]
The reason for confusion was bad markdown formatting.
* `>` is translated to a block of quoted text, and the `>` is dropped.
* `"""` has no meaning.

What you want is "triple-backticks":

    ```
    code...
    code...
    ```

Search the web for "GitHub flavored markdown". I've reformatted your question to show you. Click on the pencil at the top of your comment to edit.

**Comment by pb-cdunn** [comment]
The program with the specific fasta requirements is **fasta2DB** from Gene Myers' dazzler suite. Our fork is a bit more relaxed, but basically the same.

* https://github.com/thegenemyers/DAZZ_DB/blob/master/fasta2DB.c#L375
* https://github.com/PacificBiosciences/DAZZ_DB/blob/master/fasta2DB.c

**Comment by QiushiLi** [comment]
Hi @SchwarzEM 
I encountered the same problem when using the preads option. It's really frustrating, odd rule... Thanks a lot for fixing it with the script!
