### ISSUE TITLE
Alternative to SGE

### ISSUE THREAD

**Issue by ebioman** [PacificBiosciences/FALCON#25]
Hello Jason
I would like to run Falcon on either a LSF cluster or on a single server.
Since your code is so far SGE only, could you give a hint whether it might be rather trivial to adapt this
for either of them or you would anticipate quite some work?
E.g. which executables will have to be modified and so on.
Cheers

**Comment by pb-jchin** [comment]
Current, a "local mode" is supported. See https://github.com/PacificBiosciences/FALCON/issues/23.  See 
https://github.com/PacificBiosciences/FALCON/blob/master/src/py_scripts/fc_run.py

**Comment by ebioman** [comment]
Thanks
I will try both and see how it works.

**Comment by Lance0404** [comment]
I have modified the fc_run.py into the following line: 

def run_script(job_data, job_type = "local" ):

But I still get error msg as below: 

/export/arrayPRO2/PacBio/FALCON/fc_env/lib/python2.6/site-packages/falcon_kit-0.2.1-py2.6-linux-x86_64.egg/falcon_kit/FastaReader.py:40: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
sh: qsub: command not found

Did I do it wrong?

**Comment by pb-jchin** [comment]
@Lance0404 `qsub` is not in your execution path.
