### ISSUE TITLE
job_type = local option not present in latest version

### ISSUE THREAD

**Issue by aslett1** [PacificBiosciences/FALCON#250]
Hi,

I've been asked to upgrade our installation of falcon to v0.4.0 by a couple of our users. I've done this but it seems that the option to run jobs locally using the "job_type = local" option in the config file isn't present. I'm getting errors about qsub in spite of including it. (Can't see any mentions of it in the code via grep either)

Do we need to revert back to the older version? (we had 0.2.1 installed previously) We're tied to using LSF as our job control software so can't go with SGE.

Thanks,

Martin

**Comment by pb-jchin** [comment]
The `job_type = local` is still working just not in the example configuration files.  However, this is not a feature under regular test though.

**Comment by aslett1** [comment]
Thanks! Can you see anything amiss with the attached config? It's what 
I've used previously but, as mentioned, I now get qsub related errors as 
the job isn't running locally.

On Tue, 24 Nov 2015, Jason Chin wrote:

> 
> The job_type = local is still working just not in the example configuration files. However, this is not a feature under regular test though.
> 
> —
> Reply to this email directly or view it on GitHub.[AAwjN8IcF28UPw9xg1hAG0b3iJXaHAngks5pJIT1gaJpZM4Gof76.gif]
> 
> 
>


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE. 

[General]
# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 12000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 12000

jobtype = local
sge_option_da = -pe smp 8 -q jobqueue
sge_option_la = -pe smp 2 -q jobqueue
sge_option_pda = -pe smp 8 -q jobqueue
sge_option_pla = -pe smp 2 -q jobqueue
sge_option_fc = -pe smp 24 -q jobqueue
sge_option_cns = -pe smp 8 -q jobqueue

pa_concurrent_jobs = 28
ovlp_concurrent_jobs = 28

pa_HPCdaligner_option =  -v -dal4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6 --output_dformat

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24

**Comment by pb-jchin** [comment]
please add a line
```
job_type = local
```
in the cfg file

**Comment by aslett1** [comment]
Ah! Missed the underscore...

On Tue, 24 Nov 2015, Jason Chin wrote:

> 
> please add a line
> 
> job_type = local
> 
> in the cfg file
> 
> —
> Reply to this email directly or view it on GitHub.[AAwjN_UHsY65bRawig5GQoOA8y3P2jPTks5pJIcpgaJpZM4Gof76.gif]
> 
> 
>


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by pb-cdunn** [comment]
We plan to add checking for misspelled parameters eventually. It could save hours in some cases.

**Comment by pb-cdunn** [comment]
Btw, you should use the latest **FALCON-integrate**, the tip of master. There is an important performance improvement for large genomes -- a bug-fix really.
