### ISSUE TITLE
ovlp_stats.py bug?

### ISSUE THREAD

**Issue by bredeson** [PacificBiosciences/FALCON#253]
If I'm reading the `ovlp_stats.py` code correctly, it is counting "contained" alignment overlaps (when it shouldn't) where the query alignment is contained within its target. 

There is a variable `contained` initialized to `False`, but no condition exists in which it could ever be set to `True` in the `filter_stats` function. _All_ alignments of sufficient length will then enter the `if not contained:` condition. The subsequent condition `if q_s == 0:` will then evaluate to `True` for alignments where the query is contained within the target sequence, leading to an over-estimate of 5'-end overlap counts.

See attached plot of an example of what I believe to be over-counting.

Am I understanding this correctly? Is this intended? Which curve most closely resembles the overlap depth examined by Falcon to determine whether a contigging break should be made or not? 

<img width="650" alt="screen shot 2015-11-27 at 01 48 38" src="https://cloud.githubusercontent.com/assets/601458/11438326/05f77b30-94a9-11e5-82a1-567bf28d19b3.png">

**Comment by pb-jchin** [comment]
Yes, it is a bug. You can fix it. We will fix it with next commit.

**Comment by bredeson** [comment]
After looking more deeply into the source code, I found that `ovlp_filter.py` contains the following code snippet: 
```
if l[-1] in ("contains", "overlap"):
    ave_idt += idt * overlap_len
    all_over_len += overlap_len
if q_s == 0:
    overlap_data["5p"] += 1
if q_e == q_l:
    overlap_data["3p"] += 1
```
This suggests "contained" reads are counted as overlaps for `--min_cov` and `--max_cov` on both the 5'-and 3'-ends of the query; do these reads also contribute toward the overlap count when Falcon is laying out the contig? The documentation on the wiki states these "contained" reads are transitive, which suggests that they are not counted; however, the above code seems to state that they are? Is my understanding correct? Should `ovlp_stats.py` also be counting overlaps on both the 5'- and 3'-ends for "contained" queries (should it also follow the `if q_s == 0:`...`if q_e == q_l:` logic), rather than not at all (`if q_s == 0 and q_e == q_l: pass`)?

**Comment by bredeson** [comment]
Thanks Jason, 

I looked at the code in `ovlp_filter.py` and found the following filtering logic (lines 53-59):
```
            if l[-1] in ("contains", "overlap"):
                ave_idt += idt * overlap_len
                all_over_len += overlap_len
            if q_s == 0:
                overlap_data["5p"] += 1
            if q_e == q_l:
                overlap_data["3p"] += 1
```
It would seem that the suggested fix to `ovlp_stats.py` (lines 51-54) should follow similar logic:
`if q_s == 0:` ... `if q_e == q_l:`
and not:
`if q_s == 0:` ... `elif q_e == q_l:`

And, that the blue curve represents the overlaps depth Falcon uses to filter on, even though the actual, usable depth is represented by the red curve.

-J
