### ISSUE TITLE
Can I use Falcon for TSLR?

### ISSUE THREAD

**Issue by YoungjunBhak** [PacificBiosciences/FALCON#257]
Hi. 

I want to use falcon assembler to assemble TSLR data. 
when i submit TSLR data(I modified header line), falcon works. 

But i can not sure falcon will work with a TSLR data properly.

could you give me any comments or tip?
(Possibility, parameter, example ... and so on)

thanks.

**Comment by pb-jchin** [comment]
What is TSLR data?

**Comment by YoungjunBhak** [comment]
Oh, sorry for that. 

It is Illumina TruSeq Synthetic Long-Reads(TSLR).

thanks.

**Comment by pb-jchin** [comment]
In the general assembly theory,  overlap-layout-consenuss paradigm used in Falcon works for general longer reads regardless the source. However, each platform has some characteristics which needs some special optimization.  I am not sure if the optimizations used for some nice feature in SMRT sequencing can be also the optimized way to assemble TSLR data.  You can try but you might need to figure out the best optimization by understanding the nature of TSLR data which we have no access in general.

**Comment by YoungjunBhak** [comment]
thanks a lot!
