### ISSUE TITLE
job_026f_done' is missing... preads' failed 

### ISSUE THREAD

**Issue by dibyendukumar** [PacificBiosciences/FALCON#263]
Hi,
I am trying to run falcon assembly for a large genome (3 gb). while running nicely, out of bloom it complains about missing *_done file and quits. Any suggestions? This happens several times. Here is most relevant part of the error message.
```python
[WARNING]'/efs/assembly/falcon/w22/1-preads_ovl/job_026f/job_026f_done' is missing. job: 'rj_026f.sh-d_026f_preads-d_026f_preads' failed!
[INFO]Failure ('fail'). Joining 'task://localhost/d_026f_preads'...
[ERROR]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
Traceback (most recent call last):
  File "/opt/falcon/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 519, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/opt/falcon/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 733, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
TaskFailureError: 'Counted 1 failures.'
'/opt/falcon/bin/fc_run.py', '16r34xlarge.cfg'
```
We are using fairly recent version of falcon (late Dec first week) on the amazon cluster.
Thanks,
Dibyendu

**Comment by pb-jchin** [comment]
you can run the shell scripts inside /efs/assembly/falcon/w22/1-preads_ovl/job_026f/ manually to see how it goes. If it finished, you can just run `fc_run.py` to finish it up.

**Comment by pb-cdunn** [comment]
If you have a job which fails repeated, I'd be curious why. If something is crashing, a test-case would interest us.

Ultimately, if you cannot get a particular job to pass, I want to allow you to skip that one manually. But with the latest code, all merged `*.las` are expected and required. This is something I plan to address early in 2016.

But first, follow pb-chin's tip to discover why it failed. You might be able to examine logs too (`*.sh.log` or `sge_log/*`).

**Comment by dibyendukumar** [comment]
Thanks jchin and cdunn,
1. sge_log is not very helpful in our case, none of the log file indicate any problem. 
2. The *_done failure message is not specific to any particular job. It is random and can occur at any time. We are are running dozens of instances, after every error message, it kills all other onging jobs as well. So, it is more than just reruning one job.
3. re-running fc_run.py skips all 'job_*' folder that contains more than one file (preads.db). It doesn't check if *_done is present or not. So we have to rerun couple of jobs manully. It would be nice if upon rerun, the program check for *_done file and rerun all job_* folder that doesnot have _done file.
4. So far, I am using a script (supplied by our IT support) that looks inside every '1-preads_ovl/job_*' and runs "rj_*.sh' script if there is no '*_done' file. On re-run, it seems okay as it contains a bunch of *.las files. However, re-run folder contans both *_done and *_done.exit file. Hope it is okay.
5. Occasionally, we also get a message "[INFO]'/efs/a.../1-preads_ovl/job_0344/job_0344_done.exit' not found, but job is done." Is it okay, or we need to rerun these jobs as well?
Thanks,

**Comment by pb-cdunn** [comment]
> after every error message, it kills all other onging jobs as well

I've been meaning to add a config to stop that. I can do that tonight or tomorrow at the latest, if you want.

But I guess that's not helpful without also giving you the ability to ignore some bad stuff on re-run. If you exclude a failing daligner run, you will have less coverage, but it should be a random exclusion. So I think the results will be unbiased. (Maybe Jason will correct me on that.) Definitely better than no results at all.

But the cause of any failure should be understood.

> However, re-run folder contans both *_done and *_done.exit file. Hope it is okay.

That's fine. The `.exit` file is only used by the dispatcher. The scheduler -- which does the topological sort and checks dependencies -- only looks at `done` files.

But I'm surprised that you're having run anything manually.

What commit of **FALCON-integrate** are you using? And the rest? Run this:
```
cd FALCON-integrate
git rev-parse HEAD
git submodule status
```

> Occasionally, we also get a message "[INFO]'/efs/a.../1-preads_ovl/job_0344/job_0344_done.exit' not found, but job is done." Is it okay?

Now that's weird. Check manually. Do you see the `.exit` file? If so, then it's an NFS issue, which we'll have to solve. If not, then maybe an old qsub job was still running while a new one started.

`.exit` without `done` means a job failed. `done` without `.exit` means we have a workflow problem.

**Comment by pb-jchin** [comment]
About whether to terminate whole workflow when a single job fail, I thought about it last night.  The jobs executing concurrently are independent to each other by design.  If a job fails, we terminate all jobs, for people who need to pay for computation, it will waste some computation time. For example, if 100 jobs running and most of them are 90% done, then terminating all job because one job fails would be a waste. 

Note that if a stage has a fail job, the workflow will terminate at whether the other jobs depending on the failed jobs. That is OK.

I understand that it is useful to terminate jobs early for debugging as we see the problem as early as possible.  If we let jobs running when some job fails, we might miss the chance to catch what is going one.

The question is probably how easy we can make such behavior toggle-able.

**Comment by pb-cdunn** [comment]
Jason, I've already coded this as an option. Testing now.

But maybe what we really want is to terminate all jobs on any failure but only if no jobs have yet succeeded (in the current refresh), by default. That's pretty easy.

**Comment by dibyendukumar** [comment]
I agree,
Most of these analyses were performed on paid server, so finishing ongoing task is economical, plus it saves time. Termination the job (at least in my case) creates more problem. Considering how easy it is to restart the program, I think, giving a chance to finish concurrent jobs and allow to restart the assembly after that might be a better option. Or at least upon restarting 'rj_.sh* should check the presence of *_done file to skip folders.

For commit version, the command you suggested (cd FALCON-integrate, git rev-parse HEAD and git submodule status) yield nothing, so I have to wait for our IT support. I don't see the falcon-integrate folder.

In the meantime, the assembly finished in the morning. The result came faster than my expectation, thanks for building a nice program.

I guess, it is not the right place to ask another question, still... (a) is there any option in the program to put coverage limit, (b) any idea how I can get read depth of the contigs. I am asking this because I got 900 Mb instead of 3 Gb expected size. Genome I am working on has 85% repeat. I started with 25x corrected data, have '59Gb preads4falcon.fasta' but only 900Mb p_ctg and 20Mb a_ctg. Below is my config. Any suggestions?

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 3000
# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 3000

# overlapping options for Daligner
pa_HPCdaligner_option =  -v -dal48 -t16 -e.70 -l1000 -s800 -M120
ovlp_HPCdaligner_option = -v -dal48 -t16 -h60 -e.96 -l500 -s800 -M120

pa_DBsplit_option = -x500 -s200
ovlp_DBsplit_option = -x500 -s200
#small for repeat genome

# error correction consensus optione
falcon_sense_option =  --output_multi --min_idt 0.72 --min_cov 4 --local_match_count_threshold 2 --max_n_read 50 --n_core 16

# overlap filtering options
overlap_filtering_setting = --max_diff 50 --max_cov 75 --min_cov 4 --bestn 4 --n_core 16

**Comment by pb-cdunn** [comment]
That latest commit, PacificBiosciences/FALCON-integrate@cd9e9373a9f897bc429ecf820809c6d773ee5c44, should work a bit better. Re-open if you have problems (and then please answer my question about which commits you are using).

If you have specific daligner problems, you can post at:
* https://github.com/PacificBiosciences/DALIGNER/issues/new

Please open separate issue for the other questions (just to keep this important thread short).

You need to be using **FALCON-integrate**. Otherwise, we have no idea what versions of different software you are using. Please try to follow directions here:
* https://github.com/PacificBiosciences/FALCON-integrate/wiki

**Comment by dibyendukumar** [comment]
Hi,
See the response from our IT 'guru'. He poked around a bit before I contact you. only indication he found was "unable to open file for write".
--------------------
Unfortunately we compiled it in the genomics home directory and copied the files over to /opt/. The files from the original git checkout might have been lost when we recreated the cluster, so there is no way to determine the exact checkout version. It would have been from about a week ago, say 12/7 or 12/8 probably.
Also, did you show him the messages that went "unable to open file for write"?
---------------------

**Comment by pb-cdunn** [comment]
>  the original git checkout

What was the procedure? Did he use FALCON-integrate?

If so, just tell him to repeat whatever he did so you can upgrade to the latest code.

> Also, did you show him the messages that went "unable to open file for write"?

Did you? I don't see it.

**Comment by dibyendukumar** [comment]
thanks...
