### ISSUE TITLE
question:  how to convert las filename to job id

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#267]
Hi, Chris,

Given a las file, such as L1.621.625.las 
 I want to find the job_NNN directory where this las file was created.  How can I find NNN?  

Thanks!
David

**Comment by pb-cdunn** [comment]
Hi, David. Just got off a plan in SF.

Good question! There is no mapping, and the job-dirnames are hashes. So you have to search for it.

    find . -name 'L1.621.625'

That can be slow for a large run, but it will work. Another way is to search the log file. Another is to look for it in the .sh files, using wildcards:

    for f in 0-rawreads/job_* ; do grep L1.632.625 $f/*.sh; done

That's pretty fast for me.

**Comment by dgordon562** [comment]
Thanks, Chris!

**Comment by dgordon562** [comment]
Thanks again!  (the gift that keeps on giving...)
