### ISSUE TITLE
Warning: Block size too big, index occupies more than 1/4 of desired memory allocation

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#268]
Hi, Chris,

I get this error from daligner  (the 0-rawreads stage) for every job (as far as I can tell).

1.  Should I be concerned about this?
2.  If so, what parameter change would you suggest?  Currently my .cfg file looks like this (below).

Thanks!
David
```ini
use_tmpdir = True
input_fofn = input.fofn
input_type = raw
length_cutoff = 15000
length_cutoff_pr = 15000
pa_HPCdaligner_option =  -v -dal128 -t16 -H15000 -e0.75 -M24 -l4800 -k18 -h480 -w8 -s100
ovlp_HPCdaligner_option =  -v -dal128  -M24 -k24 -h1024 -e.96 -l2500 -s100 -H15000
pa_DBsplit_option = -a -x500 -s400
ovlp_DBsplit_option = -s400
falcon_sense_option = --output_multi --output_dformat --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 8 
falcon_sense_skip_contained = False
overlap_filtering_setting = --max_diff 40 --max_cov 80 --min_cov 2 --n_core 12
```
(in addition to sge and concurrent parameters)

**Comment by pb-cdunn** [comment]
Gene fixed `-M` recently, since it was completely ignored in some cases (particularly for small genomes). Now that `-M` is actually followed, you'll see this when the kmer index takes more memory than seems sensible. It's not quite an error, but I'd reduce the block-size in **DBsplit**. Also, I'm not sure you need `-t` if you provide `-M` (now that `-M` is actually used).

**Comment by dgordon562** [comment]
Thanks, Chris.

Just so it is completely clear to me, could you cut/paste the parameters above with your suggested changes, please?

**Comment by pb-cdunn** [comment]
Drop `-t16` and reduce `-s400` until this message disappears. And let me know what `-s` worked for you if you find one.
```ini
pa_HPCdaligner_option =  -v -dal128 -H15000 -e0.75 -M24 -l4800 -k18 -h480 -w8 -s100
pa_DBsplit_option = -a -x500 -s300
```

**Comment by dgordon562** [comment]
Thanks!

**Comment by dgordon562** [comment]
Will changing these parameters affect the results at all?  We are doing a series of assemblies at different depths of coverage and want to compare the results.  If changing these parameters affects the results, we will need to start over or the results won't be comparable...

**Comment by pb-cdunn** [comment]
Not significantly. I mean, it's possible, but usually the output you lose will be uninteresting alignments.
