### ISSUE TITLE
assembled genome size is much smaller than expected

### ISSUE THREAD

**Issue by dibyendukumar** [PacificBiosciences/FALCON#271]
Two questions related to the Falcon assembly.
(a) is there any option in the Falcon that put a limit on the read coverage limit,
(b) any idea how I can check read depth of the contigs. 
I am asking this because I got ~900 Mb instead of 3 Gb expected size. Genome has 85% repeat. I started with 20+ corrected data (59 Gb PBcR corrected reads). but got only 900Mb p_ctg and 20Mb a_ctg. 
Below is my config file. Any suggestions, parameters?
```ini
# The length cutoff used for seed reads used for initial mapping
length_cutoff = 3000
# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 3000

# overlapping options for Daligner
pa_HPCdaligner_option =  -v -dal48 -t16 -e.70 -l1000 -s800 -M120
ovlp_HPCdaligner_option = -v -dal48 -t16 -h60 -e.96 -l500 -s800 -M120

pa_DBsplit_option = -x500 -s200
ovlp_DBsplit_option = -x500 -s200
#small for repeat genome

# error correction consensus option
falcon_sense_option =  --output_multi --min_idt 0.72 --min_cov 4 --local_match_count_threshold 2 --max_n_read 50 --n_core 16

# overlap filtering options
overlap_filtering_setting = --max_diff 50 --max_cov 75 --min_cov 4 --bestn 4 --n_core 16
```
Thanks,
Dibyendu

**Comment by pb-jchin** [comment]
Do you have the read length distribution of the PBcR reads? you can set `--max_cov` and `--max_diff` to high number in `overlap_filtering_setting` to avoid overlap filtering.  If that is the case that you miss some part of the genome, the the assembly could be fragmented caused by the repeats. In such case, you might need longer read length to resolve the repeats.

**Comment by dibyendukumar** [comment]
Thanks, 
I do have read-length distribution data (see below) and I set --max_cov to 2x genome overage (--max_cov --max_diff 50). Any advice for ovlp_HPCdaligner_option and ovlp_DBsplit_option.

Read Distribution is as follows
16,638,864 reads.
89,098,118,408 bases (32.99 times coverage).

Read length histogram
0--999      0 
1000--1999 3042603
2000--2999 3617713
3000--3999 1968018
4000--4999 1297905
5000--5999 1061360
6000--6999 1040168
7000--7999 1031698
8000--8999 823427
9000--9999 632186
10000--10999 477950
11000--11999 364198
12000--12999 280478
13000--13999 219609
14000--14999 171500
15000--15999 134295
16000--16999 105108
17000--17999  82862
18000--18999  65418
19000--19999  51398 
20000--20999  40340 
21000--21999  31674 
22000--22999  24363 
23000--23999  18776 
24000--24999  14468 
25000--25999  10970 
26000--26999   8249 
27000--27999   6160 
28000--28999   4473 
29000--29999   3344 
30000--30999   2496 
31000--31999   1742 
32000--32999   1230 
33000--33999    893 
34000--34999    596 
35000--35999    407 
36000--36999    294 
37000--37999    171 
38000--38999    140 
39000--39999     74 
40000--40999     45 
41000--41999     26 
42000--42999     14 
43000--43999     10 
44000--44999      5 
45000--45999      3 
46000--46999      5 
47000--47999      2

**Comment by pb-jchin** [comment]
Can you run `DBstats` on `pread.db`?

**Comment by dibyendukumar** [comment]
Hi,
Please see the attached file for DBstats summary (untrimmed and trimmed). Thanks
[Waksman_DBstats_trimmed_untrimmed.txt](https://github.com/PacificBiosciences/FALCON/files/86402/Waksman_DBstats_trimmed_untrimmed.txt)

14,872,170 reads        out of      14,895,209  ( 99.8%)
61,509,619,647 base pairs   out of  61,515,375,902  (100.0%)
4,135 average read length
3,554 standard deviation

**Comment by pb-jchin** [comment]
I could not really any obvious hits why it does not come together (yet). You get about 16x (48G or 3G genome) reads > 3 kb. While not the best read lengths, you should get the full assembly in theory. 

some previous related trouble shooting are in https://github.com/PacificBiosciences/FALCON/issues/127 & https://github.com/PacificBiosciences/FALCON/issues/76
 
It may be useful to check the overlap statistics. It is a way to probe the genome structure (and potential overlapper errors) just by the overlapping statistics.

**Comment by pb-jchin** [comment]
I have never used `-M120`. It looks un-necessary big. I am wondering whether there is some side effect too.

**Comment by dibyendukumar** [comment]
Hello pb,
Thanks, earlier post do offer some help. I can re-run the assembly, if you can suggest a better config parameter for a genome is this size and 85% repeat.
Dibyendu
