### ISSUE TITLE
Support for LSF bsub?

### ISSUE THREAD

**Issue by yfu** [PacificBiosciences/FALCON#272]
I know that FALCON supports SGE qsub. However, we use LSF job scheduler. Do you know if FALCON will support LSF? If not, is it easy for me to add this feature? I see that the code related to `qsub` is in `src/py/mains/run.py`.

Thanks in advance!
Yu Fu

**Comment by pb-cdunn** [comment]
If you add LSF support to your fork, submit a pull-request and we might be able to use it.

**Comment by stephenrdoyle** [comment]
Hi Yu Fu, 
Have you made any progress enabling LFS capability? 
Cheers, 
Steve

**Comment by yfu** [comment]
Hi @stephenrdoyle 

I do not have time to do it yet but I will try to make it work as soon as possible.

Best!
Yu

**Comment by Imoteph** [comment]
@yfu  maybe this helps #315
