### ISSUE TITLE
question:  where does preads4falcon.fasta come from?

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#274]
When is this file (in 1-preads_ovl) created and what creates it?

I'm a little puzzled because even though all of my 1-preads_ovl las links in m_* directories were missing, preads4falcon.fasta was non-empty.  When I added the las file links to m_* directories and restarted falcon, a new preads4falcon.fasta was created which was of identical size to the old one.  So the creation of it must not require the results of 1-preads_ovl stage of daligner.

???

**Comment by pb-cdunn** [comment]
It is produced by a program called **DB2Falcon**, in our fork of **DALIGNER**. It uses nothing but `preads.db` (a DAZZLER db), which was produced at the beginning of the `1-preads_ovl` stage.

It's easier to see that in the latest code because I've added some comments.

**Comment by pb-cdunn** [comment]
https://github.com/PacificBiosciences/DALIGNER/blob/master/DB2Falcon.c

**Comment by dgordon562** [comment]
Thank you!  That clears up all of the mystery.
