### ISSUE TITLE
unclear errors while running falcon

### ISSUE THREAD

**Issue by liweisdau** [PacificBiosciences/FALCON#275]
Hi, 
I have installed the falcon on my machine,but when I ran the command:
$ fc_run.py fc_run.cfg
The falcon stopped immediately with the error message:
```python
...
  File "/home/space2/liwei/Falcon0.3/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 61, in run_script
    raise Exception(msg)
Exception: Cmd 'bash /home/space2/liwei/F16/0-rawreads/prepare_rdb.sh 1> /home/space2/liwei/F16/0-rawreads/prepare_rdb.sh.log 2>&1' (job 'prepare_rdb.sh-task_build_rdb-task_build_rdb') returned 256
```

Any comments would be greatly appreciated.
Wei Li

**Comment by pb-cdunn** [comment]
> Exception: Cmd 'bash /home/space2/liwei/F16/0-rawreads/prepare_rdb.sh 1> /home/space2/liwei/F16/0-rawreads/prepare_rdb.sh.log 2>&1' (job 'prepare_rdb.sh-task_build_rdb-task_build_rdb') returned 256.

Examine `/home/space2/liwei/F16/0-rawreads/prepare_rdb.sh.log` for more details.

**Comment by liweisdau** [comment]
Thanks for your reply,and here is the prepare_rdb.sh.log,
cd /home/space2/liwei/F16/0-rawreads
+ cd /home/space2/liwei/F16/0-rawreads
trap 'touch /home/space2/liwei/F16/0-rawreads/rdb_build_done.exit' EXIT
+ trap 'touch /home/space2/liwei/F16/0-rawreads/rdb_build_done.exit' EXIT
ls -il prepare_rdb.sub.sh
+ ls -il prepare_rdb.sub.sh
599792823 -rw-rw-r--. 1 liwei liwei 295 Jan 25 10:37 prepare_rdb.sub.sh
hostname
+ hostname
localhost.localdomain
chmod +x prepare_rdb.sub.sh
+ chmod +x prepare_rdb.sub.sh
touch prepare_rdb.sub.sh
+ touch prepare_rdb.sub.sh
ls -il prepare_rdb.sub.sh
+ ls -il prepare_rdb.sub.sh
599792823 -rwxrwxr-x. 1 liwei liwei 295 Jan 25 10:37 prepare_rdb.sub.sh
time ./prepare_rdb.sub.sh
+ ./prepare_rdb.sub.sh
fasta2DB -v raw_reads -f/home/space2/liwei/F16/0-rawreads/input.fofn
+ fasta2DB -v raw_reads -f/home/space2/liwei/F16/0-rawreads/input.fofn
Adding 'test1' ...
DBsplit -x500 -s50 raw_reads
+ DBsplit -x500 -s50 raw_reads
LB=$(cat raw_reads.db | awk '$1 == "blocks" {print $3}')
cat raw_reads.db | awk '$1 == "blocks" {print $3}')
cat raw_reads.db | awk '$1 == "blocks" {print $3}'
++ cat raw_reads.db
++ awk '$1 == "blocks" {print $3}'
+ LB=7
HPCdaligner -v -dal4 -t16 -e.70 -l1000 -s1000 -H12000 raw_reads 1-$LB >| /home/space2/liwei/F16/0-rawreads/run_jobs.sh
+ HPCdaligner -v -dal4 -t16 -e.70 -l1000 -s1000 -H12000 raw_reads 1-7

real    0m3.042s
user    0m2.582s
sys     0m0.458s
touch /home/space2/liwei/F16/0-rawreads/rdb_build_done
+ touch /home/space2/liwei/F16/0-rawreads/rdb_build_done
touch /home/space2/liwei/F16/0-rawreads/rdb_build_done.exit
+ touch /home/space2/liwei/F16/0-rawreads/rdb_build_done.exit

It seems to be all right,I don't know what is the problem.
Thank you

**Comment by pb-cdunn** [comment]
Check the output of **HPCdaligner** in `/home/space2/liwei/F16/0-rawreads/run_jobs.sh`.

You can run `prepare_rdb.sh` script directly (if you have what you need in your `$PATH`). And if that doesn't help, you can run its individual commands in sequence. Something is failing on your system, and it is something unique to your system.

Try clean the `0-*`, `1-*`, and `2-*` directories before running again. It's possible that you're run it twice and over-written the log-file, since it certainly looks like nothing had a non-zero exit-value.

It's very hard for us to debug your particular system remotely.

**Comment by liweisdau** [comment]
Thanks for your advice,it seems to be that the data I used was not suitable for falcon,and I have solved the problem.Thank you!
