### ISSUE TITLE
genome size is underestimated

### ISSUE THREAD

**Issue by lfaino** [PacificBiosciences/FALCON#28]
Hi all,
i was trying to assemble the genome of a fungal pathogen. i know that the genome is of about 36Mb but the assembly output produce only few contigs for a total genome size of 2Mb. can you help me in optimizing the assembly parameters? 
here the conf file
```
[General]
job_type = local
# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads


# The length cutoff used for seed reads used for initial mapping
length_cutoff = 5000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 5000

# Cluster queue setting
sge_option_da = -pe smp 8 -q jobqueue
sge_option_la = -pe smp 2 -q jobqueue
sge_option_pda = -pe smp 8 -q jobqueue
sge_option_pla = -pe smp 2 -q jobqueue
sge_option_fc = -pe smp 24 -q jobqueue
sge_option_cns = -pe smp 8 -q jobqueue

pa_concurrent_jobs = 32
ovlp_concurrent_jobs = 32

pa_HPCdaligner_option =  -v -dal4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 15 --bestn 10
```

thanks
Luigi

**Comment by pb-jchin** [comment]
What is the sequence coverage? (If you like you can show the DBstats output of your raw read data by

**Comment by lfaino** [comment]
i`m testing several datasets with incremental genome coverage. this particular dataset has a coverage of about 96x. the stats from DB stats are:
Statistics for all wells in the data set

        489,271 reads       out of         501,568     2.5% loss
  3,415,982,528 base pairs  out of   3,458,245,954     1.2% loss

Base composition: 0.259(A) 0.254(C) 0.241(G) 0.246(T)

          6,981 average read length
          4,460 standard deviation

Distribution of Read Lengths (Bin size = 1,000)

    Bin:      Count  % Reads  % Bases   Average
 31,000:          3      0.0      0.0    31678
 30,000:         12      0.0      0.0    30636
 29,000:         13      0.0      0.0    30062
 28,000:         22      0.0      0.0    29338
 27,000:         59      0.0      0.1    28271
 26,000:        105      0.0      0.2    27371
 25,000:        138      0.1      0.3    26619
 24,000:        258      0.1      0.5    25700
 23,000:        459      0.2      0.8    24728
 22,000:        699      0.4      1.2    23829
 21,000:      1,124      0.6      1.9    22912
 20,000:      1,668      0.9      2.9    22017
 19,000:      2,434      1.4      4.3    21132
 18,000:      3,548      2.2      6.2    20237
 17,000:      4,774      3.1      8.7    19375
 16,000:      6,470      4.5     11.8    18514
 15,000:      8,456      6.2     15.6    17666
 14,000:     10,405      8.3     20.1    16851
 13,000:     13,214     11.0     25.3    16024
 12,000:     16,239     14.3     31.2    15204
 11,000:     19,489     18.3     37.8    14394
 10,000:     23,050     23.0     44.8    13594
  9,000:     26,776     28.5     52.3    12805
  8,000:     31,223     34.9     60.0    12015
  7,000:     36,076     42.2     67.9    11225
  6,000:     40,365     50.5     75.6    10451
  5,000:     44,971     59.7     82.8     9687
  4,000:     47,494     69.4     89.1     8961
  3,000:     49,275     79.5     94.1     8268
  2,000:     50,182     89.7     97.8     7609
  1,000:     50,270    100.0    100.0     6981

Luigi

**Comment by pb-jchin** [comment]
The read length distribution looks good. If the genome is very repetitive, you might want to reduce the `-s400` to `-s100` to increase sensitive detecting overlaps
```
pa_DBsplit_option = -x500 -s100
ovlp_DBsplit_option = -x500 -s100
```
This will create a lot more files. Or, you can increase the number for `-t` here:
```
pa_HPCdaligner_option =  -v -dal4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal4 -t32 -h60 -e.96 -l500 -s1000
```
It might use more memory pre daligner job.

Theoretically, you can set `length_cutoff` to 8000 such that you still have 57x seed reads or to 10000 (42x seed reads).  However, we should not exclude the possibility the genome size estimation may be off or the sample many contain more than the genome we expect.

**Comment by lfaino** [comment]
I`m finalizing a paper on PacBio sequencing applied to fungal pathogens. I already tested HGAP and MHAP and both software perform good with this dataset. The genome size is correct. The amount of repeats is about 10%. Do you think that this is a lot?

Luigi

**Comment by pb-jchin** [comment]
The repeat content is OK. Since you get HGAP / MHAP going through, the problem is more about configuration and parameters.  Do you mind to show the assembly stats from p_ctg.fa and a_ctg.fa?  Or, if you like, I can run the assembly from my end to check what is going on.

**Comment by lfaino** [comment]
I

**Comment by lfaino** [comment]
I changed some parameters in the cfg file. i will wait for the assembly result and i will let you know. HOw can you run the assembly? i need to provide you with the data and these are quite a lot.

**Comment by pb-jchin** [comment]
If you can dump the fasta files in DropBox, I can get it. Do you have a twitter handle? If so, following @infoecho so I can DM you my email address.

**Comment by pb-jchin** [comment]
Ifalno, since I was able to generate the assembly of the expected size of the genome, so the data and the pipeline is fine.  If you can figure out what might be wrong in your installation, that will be helpful information.
