### ISSUE TITLE
what are all these " fc_run - WARNING - block: 1, las_path: /..."

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#286]
hundreds (thousands?) of them
they don't say what the warning is.  For example:

2016-02-19 02:32:22,207 - fc_run - WARNING - block: 1, las_path: /net/eichler/vol20/projects/whole_genome_assembly/nobackups/mchaisso/ABP/BACs/reads/150220_EEE_SC_LH_20kb_P6_G1/falcon_assembly/0-rawreads/job_0000/L1.1.1.las

What does this mean and is it a concern?

**Comment by pb-jchin** [comment]
well. Chris might know better, but  I think is just information rather than warning.

**Comment by pb-cdunn** [comment]
I think that slipped in accidentally as a way to debug our parsing of the output of **HPCdaligner**. It was removed with this commit:

    b829e68b (Christopher Dunn 2015-12-24 340)             #fc_run_logger.warning('block: %s, las_path: %s' %(block, las_path))

Gosh, I was working on xmas eve?

**Comment by pb-jchin** [comment]
well.. xmas eve is time to prepare xmas gift last minute :)

**Comment by dgordon562** [comment]
Thanks for all your help, Chris.
