### ISSUE TITLE
Different block sizes yield different results

### ISSUE THREAD

**Issue by zyndagj** [PacificBiosciences/FALCON#287]
Using the recommended parameters [fc_run_ecoli_2.cfg](https://github.com/PacificBiosciences/FALCON/blob/master/examples/fc_run_ecoli_2.cfg) yields a final p_ctg.fa with a single 4635638 bp contig. Changing the block size to 250 Mbp (-s 250) yields 4 contigs of sizes
```
000000F 3370588
000001F 817975
000002F 370764
000003F 33640
```
Changing the block size to 300 Mbp (-s 300) yields a single contig yet again, but with only 4635460 bp.

Should the block size have such an effect on the final output? I started by looking at the blocks in DBstats. Summing together all the bins in each block yielded the same count between versions raw_reads. I then moved on to the las files in `0-rawreads/las_files`, where I merged all the las files with LAcat and then output all the alignments with LAshow for each version of the run. This yielded the following.

```
==> s200.txt <==

s200: 24,540,600 records
      2      139 c   [ 6,443..12,278] x [     0.. 5,615] :   <  1,277 diffs  (13 trace pts)

==> s250.txt <==

s250: 23,945,795 records
      2      139 c   [ 6,443..12,278] x [     0.. 5,615] :   <  1,277 diffs  (13 trace pts)

==> s300.txt <==

s300: 22,533,518 records
      2      139 c   [ 6,443..12,278] x [     0.. 5,615] :   <  1,277 diffs  (13 trace pts)
```

While many of the records are the same, there is a large discrepancy in the number of records. Has anyone else encountered this? Do you have any recommendations for choosing an optimal `s` parameter apart from the memory footprint?

Thanks,
Greg Zynda

**Comment by pb-cdunn** [comment]
With unlimited memory, the block-size would not matter. As it is, **daligner** has heuristics. See [`-t` and `-M` parameters](https://dazzlerblog.wordpress.com/command-guides/daligner-command-reference-guide/).

We plan to calculate some of these things automatically someday, but it's non-trivial. Our first goal will be to auto-calculate a decent `length_cutoff`, but that will be part of a larger HGAP workflow (which will include polishing), not FALCON proper.

Gene's las_files are quite easy to examine, aren't they? Very simple. I like that about his architecture.
