### ISSUE TITLE
assembly of error-corrected reads

### ISSUE THREAD

**Issue by juroscito** [PacificBiosciences/FALCON#29]
Hi Jason,
I'm trying to assemble pacbio reads previously corrected with proovread. The genome is ~2Gb, and I used fc_run_LG.py.

All the jobs run through, but the output is really strange: all contigs I get (p_cgt.fa) are repetitions of the short k-mers TAACCC and TTAGGG (for ex.TTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGG......)

The preads4falcon.fasta looks fine, so I grep'ed the seqs present in sg_edges_list from the preads4falcon, and they correspond exactly to these repeats. Thus, it seems that fc_ovlp_to_graph.py is printing only the bad stuff.

Would you have any ideas on why that is happening?

Thanks a lot!

PS. I have ~10.5mi sequences in preads4falcon.fasta, but only 252 entries in sg_edges_list

**Comment by pb-jchin** [comment]
It seems to the overlap stage for the final assembly does not go well.  In the current setting, the final overlap needs to be proper overlaps. I have not seen reads using proovread. One question is, does it have uniform accuracy from end to end after proovread, it not, you will need to relax some of the overlapping criteria.  Sometimes, I dump the overlapping information from .las files to count the average overlapping per read.  It will give useful information about the structure of the genome and how it affects the overlapping calculation.

**Comment by juroscito** [comment]
Hum, accuracy of these proovread-EC pacbios might not be entirely uniform...it might just not correct the most problematic regions (repeats/low cov).
I'll try the ovlp_HPCdaligner with lower -e, is that what you meant?

How do you "dump the overlapping information from .las files to count the average overlapping per read"? I tried looking into the .las files with LAshow, but I cannot trace the ovl information to the reads themselves.

Thanks
