### ISSUE TITLE
filtered or non filtered raw sub reads as input for falcon

### ISSUE THREAD

**Issue by JeanQin** [PacificBiosciences/FALCON#296]
We know that falcon expects raw subreads as its input files and wonder if they should be filtered (quality score => 0.75) or non filtered raw reads (<= 0.5, can be very low)?  I believe it should be filtered sub reads but just to be sure. Thanks. JQ

**Comment by pb-jchin** [comment]
I won't recommend using RQ<0.75 reads. While you will get some possible useful results, the extra noise just make the process more complicated and less efficient.  More data may not be always better. This is one of the cases.

**Comment by JeanQin** [comment]
Makes sense. Thank you so much, Jason for your quick response. JQ

**Comment by JeanQin** [comment]
For some reason, the falcon job failed when using the "filtered subreads" our pacbio vendor sent us. falcon runs successfully with the subreads under Analysis_Result folder. Since the vendor is new to pacbio, we'd like to confirm if the subreads under .../run/cell_id/Analysis_Results/ are the unfiltered subreads. There are 3 files for each smrt cell. They also sent us one filtered subread file for each smrt cell, named after job id.
