### ISSUE TITLE
Solving error to run FALCON 

### ISSUE THREAD

**Issue by lbien** [PacificBiosciences/FALCON#300]
Hello!

I installed FALCON-integrate following the manual (https://github.com/PacificBiosciences/FALCON/wiki/Setup%3A-Installation-and-Environment), and ran successfully the example with ecoli_test (https://github.com/PacificBiosciences/FALCON/wiki/Setup%3A-Complete-example), but I haven't succeed to assemble my data. Here is the error I got: 
```
2016-02-26 17:56:16,158 - pypeflow.controller - ERROR - Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
Traceback (most recent call last):
  File "/home/usr/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 522, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/home/usr/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 747, in _refreshTargets
    failedJobCount, succeededJobCount))
LateTaskFailureError: 'Counted a total of 2 failure(s) and 4606 success(es).'
2016-02-26 17:56:16,186 - pypeflow.controller - WARNING - #tasks=4608, #alive=0
```

I used this configuration: 

```
input_fofn = input.fofn
input_type = raw
length_cutoff = 12000
length_cutoff_pr = 12000

job_type = local
jobqueue = your_queue

sge_option_da = -pe smp 8 -q jobqueue
sge_option_la = -pe smp 2 -q jobqueue
sge_option_pda = -pe smp 8 -q jobqueue
sge_option_pla = -pe smp 2 -q jobqueue
sge_option_fc = -pe smp 24 -q jobqueue
sge_option_cns = -pe smp 8 -q jobqueue

pa_concurrent_jobs = 32
ovlp_concurrent_jobs = 32

pa_HPCdaligner_option =  -v -dal4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24
```

I greatly appreciate your help to run the software.

**Comment by pb-jchin** [comment]
do you have a queue called "your_queue", you will need to set up a proper SGE queue for it to work.

**Comment by pb-cdunn** [comment]
`job_type = local`, so this is not (yet) an SGE issue. But you'll need to dive into the log files to see where things went wrong.

> Counted a total of 2 failure(s) and 4606 success(es).

You probably had 2 daligner failures. It is possible -- with a bit of hackery -- to proceed without those, using the 4606 successful jobs.

You should see a 4606 files called `0-rawreads/job_*/job_*_done`. You are missing 2. Figure out the job numbers from the logs, and just `touch` them yourself. You might be able to find them by searching for files called `0-rawreads/job_*/job_*_done.exit`. If you find those, then delete the `_*done.exit` files and create the `*_done files. (In other words, `.exit` may or may not exist for failed jobs. It *never* exists for successful jobs.)

**Comment by mseetin** [comment]
For local job runs, every one of the sge_option_* entries should be blank
after the equals sign.

**Comment by lbien** [comment]
Thank you for your prompt! 

Right! I used the local local job type, so I am running again with all sge options in blank (still waiting). 

I check and couldn't find files called `0-rawreads/job_*/job_*_done.exit`. Is it possible the 2 files have another name or is there another solution? 

Thank you!

**Comment by pb-cdunn** [comment]
@lbien, It's hard to explain this clearly. The `_done.exit` files might be gone already. In that case, just restart. Those 2 missing daligner jobs will run again. If they fail again, then just add the corresponding `_done` files and restart.

@mseetin, For non-grid jobs, the `sge_option_*` entries are ignored.

**Comment by lbien** [comment]
@pb-cdunn Thank you very much for your support!

I ran the software again, and apparently it completed the `daligner`  job; however, I got another error in the merging step, as follow: 

```
File "/home/usr/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 29, in system
    raise Exception(msg)
Exception: Call 'bash /home/usr/TGF/P_oryzae/as/falcon/raw/0-rawreads/m_00079/rp_00079.sh 1> /home/usr/TGF/P_oryzae/as/falcon/raw/0-rawreads/m_00079/rp_00079.sh.log 2>&1' returned 256.

[INFO]Failure ('fail'). Joining 'task://localhost/m_00079_raw_reads'...
[ERROR]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
Traceback (most recent call last):
  File "/home/usr/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 522, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/home/usr/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 737, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'
```

After this, it terminated all the threads and gave this final message:

```
[WARNING]Now, #tasks=32, #alive=3
[INFO]'/home/usr/TGF/P_oryzae/as/falcon/raw/0-rawreads/m_00041/m_00041_done.exit' found.
[INFO]'/home/usr/TGF/P_oryzae/as/falcon/raw/0-rawreads/m_00101/m_00101_done.exit' found.
[INFO]'/home/usr/TGF/P_oryzae/as/falcon/raw/0-rawreads/m_00009/m_00009_done.exit' found.
[WARNING]Now, #tasks=32, #alive=0
Traceback (most recent call last):
  File "/home/usr/fc_env/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.4.1', 'fc_run.py')
  File "/home/usr/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/usr/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/home/usr/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/home/usr/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 624, in main
    main1(*argv)
  File "/home/usr/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 492, in main1
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/home/usr/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 522, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/home/usr/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 737, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
pypeflow.controller.TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'
```

Please, could you provide any suggestion? 

Thank you in advance!

**Comment by pb-cdunn** [comment]
Examine this log:
* `/home/usr/TGF/P_oryzae/as/falcon/raw/0-rawreads/m_00079/rp_00079.sh.log`

**Comment by lbien** [comment]
Thank you @pb-cdunn! 

Here is the log, but I am not sure how to proceed.

```
cd /home/usr/as/falcon/raw/0-rawreads/m_00079
+ cd /home/usr/as/falcon/raw/0-rawreads/m_00079
trap 'touch /home/usr/as/falcon/raw/0-rawreads/m_00079/m_00079_done.exit' EXIT
+ trap 'touch /home/usr/as/falcon/raw/0-rawreads/m_00079/m_00079_done.exit' EXIT
ls -il rp_00079.sub.sh
+ ls -il rp_00079.sub.sh
2814749786479516 -rwxrwxr-x 1 usr usr 5133 2016-03-03 00:53 rp_00079.sub.sh
hostname
+ hostname
Za1.cglab
ls -il rp_00079.sub.sh
+ ls -il rp_00079.sub.sh
2814749786479516 -rwxrwxr-x 1 usr  5133 2016-03-03 00:53 rp_00079.sub.sh
time /bin/bash ./rp_00079.sub.sh
+ /bin/bash ./rp_00079.sub.sh
LAmerge -v L2.79.1 L1.79.1 L1.79.2 L1.79.3 L1.79.4 L1.79.5 L1.79.6 L1.79.7 L1.79.8 L1.79.9 L1.79.10 L1.79.11 L1.79.12 L1.79.13 ; rm L1.79.1.las L1.79.2.las L1.79.3.las L1.79.4.las L1.79.5.las L1.79.6.las L1.79.7.las L1.79.8.las L1.79.9.las L1.79.10.las L1.79.11.las L1.79.12.las L1.79.13.las
+ LAmerge -v L2.79.1 L1.79.1 L1.79.2 L1.79.3 L1.79.4 L1.79.5 L1.79.6 L1.79.7 L1.79.8 L1.79.9 L1.79.10 L1.79.11 L1.79.12 L1.79.13
LAmerge: Cannot open ./L1.79.1.las for 'r'
touch /home/usr/as/falcon/raw/0-rawreads/m_00079/m_00079_done.exit
+ touch /home/usr/as/falcon/raw/0-rawreads/m_00079/m_00079_done.exit
```

Thank you!

**Comment by pb-cdunn** [comment]
I think you've had a failure in a **daligner** job, so you are missing data. There is no automated way to deal with job failures at the moment.

I think you're better off looking at why some job failed. Removing any `.exit` and re-running might pass. Otherwise, you'll need to dive into the specific **daligner** job that failed.

**Comment by mroach-awri** [comment]
i had a similar problem, have you tried removing `--local_match_count_threshold 2` from your configuration file?

**Comment by pb-cdunn** [comment]
>  have you tried removing `--local_match_count_threshold 2` from your configuration file?

Yes, in old code that could help. But in recent code, that has no effect anymore. It's been removed from FALCON's master branch, I think.

**Comment by lbien** [comment]
Now I ran the FALCON successfully in my data. I want to thank you all, Jason, Christopher, @mseetin, and @mroach-awri, for your help.

I removed `--local_match_count_threshold 2` as suggested by @mroach-awri and @pb-cdunn. 

Thank you!

**Comment by emlec** [comment]
Hello, 

I installed FALCON and tried the example with ecoli_test (https://github.com/PacificBiosciences/FALCON/wiki/Setup%3A-Complete-example). 

But the run aborted. As I don't have access to a cluster, I modified the configuration file following your recommendations : 
- job_type=local added
- sge_option_* entries blank after the equals sign
- no --local_match_count_threshold 2

This is the configuration file I used : 
```
job_type= local

input_fofn = input.fofn
input_type = raw

length_cutoff = 12000

length_cutoff_pr = 12000

sge_option_da = 
sge_option_la = 
sge_option_pda = 
sge_option_pla = 
sge_option_fc = 
sge_option_cns = 

pa_concurrent_jobs = 4
ovlp_concurrent_jobs = 4

pa_HPCdaligner_option =  -v -dal4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 4

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 4
```
The `0-rawreads` directory contains the las files. The `1-rawreads` too. But the `2-asm-falcon` is empty. I haven't any information about an assembly graph. 

The software ended with this error message :
```
[INFO]'/media/analyse/Pharmaco_AAV/documents_pharmaco_AAV/Emilie/smrt_assembly/FALCON-integrate/ecoli_test/1-preads_ovl/job_0003/job_0003_done.exit' found.
[WARNING]Now, #tasks=8, #alive=0
Traceback (most recent call last):
  File "/usr/local/bin/fc_run.py", line 5, in <module>
    pkg_resources.run_script('falcon-kit==0.4.1', 'fc_run.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 624, in main
    main1(*argv)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 571, in main1
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/usr/local/lib/python2.7/dist-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 522, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/usr/local/lib/python2.7/dist-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 737, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
pypeflow.controller.TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'
```
Instead of the first line of the message `[INFO]'/media/analyse/Pharmaco_AAV/documents_pharmaco_AAV/Emilie/smrt_assembly/FALCON-integrate/ecoli_test/1-preads_ovl/job_0003/job_0003_done.exit' found.`, I checked and didn't find it.

Could you please help me to find what happened?

**Comment by pb-cdunn** [comment]
This is a different problem. Please do not post into this particular thread again as that may cause notifications for everyone who has posted here.

Please open a *new* Issue, copy your settings into that, and post any other information which might help to diagnose this, e.g. genome-size, number of raw reads, number of raw bases, `DBstats 0-rawreads/raw_reads.db`, sizes of `0-rawreads/preads/*.fasta`, etc.

Then, look for any files called `*.log`. You should be able to find something which indicates where falcon stopped and why.
