### ISSUE TITLE
How to resolve the question: "/bin/bash: bad interpreter: Text file busy"

### ISSUE THREAD

**Issue by fanr123** [PacificBiosciences/FALCON#301]
Hi!
I meet the same question "/bin/bash: bad interpreter: Text file busy" just as https://github.com/PacificBiosciences/FALCON/issues/269, but i do not find an effcient  solution from it. 
my fc_run.cfg is:
```[General]
job_type = local
input_fofn = input.fofn

input_type = raw

length_cutoff = 12000

length_cutoff_pr = 12000

jobqueue = middle.q
sge_option_da = -pe smp 8 -q %(jobqueue)s
sge_option_la = -pe smp 2 -q %(jobqueue)s
sge_option_pda = -pe smp 8 -q %(jobqueue)s
sge_option_pla = -pe smp 2 -q %(jobqueue)s
sge_option_fc = -pe smp 24 -q %(jobqueue)s
sge_option_cns = -pe smp 8 -q %(jobqueue)s

pa_concurrent_jobs = 8
ovlp_concurrent_jobs = 8
cns_concurrent_jobs = 8

pa_HPCdaligner_option =  -v -dal24 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal24 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s200

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6 --output_dformat

overlap_filtering_setting = --max_diff 40 --max_cov 80 --min_cov 5 --bestn 10 --n_core 24
```
I will greatly appreciate your help!

**Comment by pb-jchin** [comment]
As in the discussion inside #269, it seems it might have to do with your NFS system and we have put some workaround.  Would you be able to see if it is an NFS sync issue?

**Comment by fanr123** [comment]
Sorry for late reply. I was told the NFS is sync. I set the concurrent_jobs =1 and successfully got the result. Although it is slow.

**Comment by pb-jchin** [comment]
Some NFS is slow to sync through different nodes. if you like, you can add  some fstat (e.g. ls command) on the directory containing the script before running the script might help.

**Comment by pb-cdunn** [comment]
This happens if `foo.sh` was created very recently in NFS and we do this:

    ./foo.sh

instead of this:

    /bin/sh foo.sh

This should not happen anymore by default, since we now always prefer the latter. If it recurs, please try the latest code in **FALCON-integrate**.
