### ISSUE TITLE
Is there any need to polish the assembly result with quiver?

### ISSUE THREAD

**Issue by liweisdau** [PacificBiosciences/FALCON#304]
Hi!
I have assembled a genome using the newest version of falcon,and I'm wondering if there is any need to polish the result using quiver in the SMRT-analysis.

I greatly appreciate your help!

**Comment by pb-jchin** [comment]
yes. The FALCON code itself only generate draft assembly. You will need to polish the results with quiver.

**Comment by oakeley** [comment]
Dear Jason

What is the best way of running Quiver on the samples? Do we use the BAX.H5 files or can we use the .QUIVA files for this step?

With BAX.H5 it is quite expensive/memory intensive. Not sure how to run with QUIVA files from Gene...

Thanks

Edward

**Comment by pb-jchin** [comment]
The latest development uses BAM files.   

Here is the "old" way I used to do, BAX.H5 -> blasr align -> cmp.h5 -> quiver 

The more updated one (probably not available to every one yet): bax.h5 -> bam -> blasr align -> aligned bam -> quiver.

The machines will generate raw read bam file natively.

**Comment by liweisdau** [comment]
Thanks for your reply,but I'm not familiar the method "BAX.H5 -> blasr align -> cmp.h5 -> quiver".Are all these done by quiver? Could you tell me any details about these?

Thanks!

**Comment by pb-jchin** [comment]
"BAX.H5 -> blasr align -> cmp.h5 -> quiver" happens underneath the hood when you use SMRTAnalysis to run quiver.  (For detail, you can contact PacBio tech support group.)

**Comment by liweisdau** [comment]
Thank you!

**Comment by JeanQin** [comment]
What's the option for blasr to generate cmp.h5?
