### ISSUE TITLE
FALCON on SLURM, node as consumable resource

### ISSUE THREAD

**Issue by jasperlinthorst** [PacificBiosciences/FALCON#307]
Hi all,
On one of the compute clusters I'm running FALCON in combination with SLURM as a scheduler, which works, but I see that every alignment/correction job always gets a reservation on a complete node. Where a node on average has about 32 cores. Therefore, Im not making optimal use of the cluster. Now I know this could be fixed by changing the SLURM configuration, but I'm afraid that that's not a real solution for me. Another solution would be to have multiple alignment/correction tasks combined within a job which are then executed by srun or parallel or something like that.
Do you have any additional ideas for me? Or could you direct me towards the easiest way of fixing something like this in FALCON/Pypeflow?

Thanks!
Jasper

**Comment by pb-cdunn** [comment]
You can set the sge_ options for each stage separately. By default we set the number of processors required, but if you know how much memory your job will take, maybe you can set that too. Maybe slurm assumes max memory because we are not setting a limit? I'm not a slurm expert.

**Comment by pb-jchin** [comment]
@jasperlinthorst you can set the `fc_consensus.py` to use fewer cores, it will take long, but in your case, it might be better.

**Comment by jasperlinthorst** [comment]
Thanks for the reply. For info, see https://computing.llnl.gov/linux/slurm/cons_res.html.

"The advantage of the exclusive mode scheduling policy is that a job gets all the resources of the assigned nodes for optimal parallel performance. The drawback is that jobs can tie up large amount of resources that it does not use and which cannot be shared with other jobs."

So this behaviour apparently is the default for SLURM. To still make use of all the resources in a node, I'm supposed to use a job script that runs multiple instances of (for instance) the daligner scripts using "srun --exclusive":

for (( i=0; i<8; i++)); do
(
  srun --exclusive rp_000$i.sh
)&
done
wait

Anyway I can bundle the daligner jobs somewhere in the FALCON code?

About the consensus jobs, I think I can simply increase the number of cores to 32 to optimise resource usage. Maybe it could actually also be a solution to be able to specify a different number of threads for daligner, but I'm not sure if specifying more threads for daligner really results in a linear increase in performance. Is daligner on 32 threads more or less 8 times faster than daligner on 4 threads? Do you know this?

**Comment by pb-cdunn** [comment]
> Anyway I can bundle the daligner jobs somewhere in the FALCON code?

Not yet. I plan to add a chunking decorator to the new job-distributor layer.

> Is daligner on 32 threads more or less 8 times faster than daligner on 4 threads?

(Note: **daligner** and **fc_consensys.py** are different tools.)

I haven't experimented much with `NTHREADS` in **daligner** yet. Increasing that might scale well, if you are not I/O-bound. You're welcome to try that. (See `DALIGNER/filter.h`.) Maybe running in `/tmp` would help. (That's another thing we will eventually allow via decorator.)

**Comment by jasperlinthorst** [comment]
> Not yet. I plan to add a chunking decorator to the new job-distributor layer.
That would indeed be great! If I can help in realising that, let me know.

> In the meantime, you can at least increase memory utilization by increasing the block-size, the -s parameter to DBsplit. According to Gene Myers, DBsplit -s200 (the default) would consume about 16GB of memory, so scale that to your physical RAM.
Good point, I can indeed do that. Unfortunately the accounting on this cluster is based on the number of reserved CPUs. So I'm afraid that with just that, I wont be able to complete a whole run within the budgeted hours.

>(Note: daligner and fc_consensys.py are different tools.)
I understand that. I'll see if I can experiment with daligner on 32 threads, will let you know.

**Comment by pb-cdunn** [comment]
The chunking thing would run a group of jobs on the same machine serially. It's a weird use-case that some people have.

(I think chunking is helpful when other users are cruel, heartless spendtrhrifts who try to hold their resources for a long time. And the job distributor never gives priority to smaller jobs anyway. So smaller jobs never get to run. That's really just poor Grid management. But chunking is a common request nonetheless.)

What you seem to want is for several jobs to run on the same node *in parallel*. Hmm. That would take a lot of effort to do right -- where our job distributor knows about the size of the machines and sets the submission flags itself. Not a bad idea, but I can't get that to you quickly. (And really, qsub/slurm/etc are supposed to take care of that for you, based on the resources requested for each job.) Yes, try NTHREADS.
