### ISSUE TITLE
Run aborted (no SGE)

### ISSUE THREAD

**Issue by emlec** [PacificBiosciences/FALCON#309]
Hello,

I installed FALCON and tried the e.coli assembling indicated in the documentation (https://github.com/PacificBiosciences/FALCON/wiki/Setup%3A-Complete-example).

But the run aborted. As I don't have access to a cluster, I modified the configuration file following your recommendations :

    job_type=local added
    sge_option_* entries blank after the equals sign
    no --local_match_count_threshold 2

This is the configuration file I used :
```
job_type= local

input_fofn = input.fofn
input_type = raw

length_cutoff = 12000

length_cutoff_pr = 12000

sge_option_da = 
sge_option_la = 
sge_option_pda = 
sge_option_pla = 
sge_option_fc = 
sge_option_cns = 

pa_concurrent_jobs = 4
ovlp_concurrent_jobs = 4

pa_HPCdaligner_option =  -v -dal4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 4

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 4
```
The `0-rawreads` directory contains the las files. The `1-rawreads` too. But the `2-asm-falcon` is empty. I haven't any information about an assembly graph.

The software ended with this error message :
```
[INFO]'/media/analyse/Pharmaco_AAV/documents_pharmaco_AAV/Emilie/smrt_assembly/FALCON-integrate/ecoli_test/1-preads_ovl/job_0003/job_0003_done.exit' found.
[WARNING]Now, #tasks=8, #alive=0
Traceback (most recent call last):
  File "/usr/local/bin/fc_run.py", line 5, in <module>
    pkg_resources.run_script('falcon-kit==0.4.1', 'fc_run.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 624, in main
    main1(*argv)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 571, in main1
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/usr/local/lib/python2.7/dist-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 522, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/usr/local/lib/python2.7/dist-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 737, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
pypeflow.controller.TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'
```
Instead of the first line of the message `[INFO]/media/analyse/Pharmaco_AAV/documents_pharmaco_AAV/Emilie/smrt_assembly/FALCON-integrate/ecoli_test/1-preads_ovl/job_0003/job_0003_done.exit`, I checked and didn't find it.

I didn't find something in the `*.log` of the `0-subreads` directory. 
I have the 20 raw_reads.n.las files. 
I didn't find something in the `*.log` of the `1-subreads` directory. 
I have `*.las`files. 

I don't know why the run stopped.

**Comment by pb-cdunn** [comment]
find . -name '*.log'

There are files named like `foo.sub.sh`, and next to them are `foo.sh.log` (since `foo.sh` calls `foo.sub.sh`). You need to find the one that died.

You can also increase the log-level. It uses Python logging, and you can find a sample `logging.ini` somewhere in the **FALCON-integrate** repository. You can change `INFO` to `DEBUG` in that file, then run

    fc_run fc_run.cfg logging.ini

But usually the bash log-files are enough to explain everything.

**Comment by emlec** [comment]
Thanks. 
I have found the .sh.log that failed (rj_0011.sh.log).
This is the message :
```
Comparing preads.5 to preads.3

   Capping mutual k-mer matches over 10000 (effectively -t100)
   Hit count = 296,460,875
   Highwater of 9.57Gb space
./rj_0011.sub.sh: line 10: 26490 Killed                  daligner_p -v -h60 -t32 -H12000 -e0.96 -l500 -s1000 preads.5 preads.3 preads.4 preads.5
touch /media/analyse/Pharmaco_AAV/documents_pharmaco_AAV/Emilie/smrt_assembly/FALCON-integrate/ecoli_test/1-preads_ovl/job_0011/job_0011_done.exit
+ touch /media/analyse/Pharmaco_AAV/documents_pharmaco_AAV/Emilie/smrt_assembly/FALCON-integrate/ecoli_test/1-preads_ovl/job_0011/job_0011_done.exit
```
I think it's a problem of memory. 
I will run the software using the logging.ini to ensure that.

**Comment by emlec** [comment]
Using `fc_run fc_run.cfg logging.ini` (after `INFO` changed to `DEBUG`) the run aborted too, but later (during the 18th job compared to the 8th job previously). 
The error message is the same : 
```
Comparing preads.7 to preads.5

   Capping mutual k-mer matches over 10000 (effectively -t100)
   Hit count = 299,407,582
   Highwater of 9.66Gb space
./rj_000b.sub.sh: line 10:  6850 Killed                  daligner_p -v -h60 -t32 -H12000 -e0.96 -l500 -s1000 preads.7 preads.4 preads.5 preads.6 preads.7
touch /media/analyse/Pharmaco_AAV/documents_pharmaco_AAV/Emilie/smrt_assembly/FALCON-integrate/FALCON-examples/run/ecoli/1-preads_ovl/job_000b/job_000b_done.exit
+ touch /media/analyse/Pharmaco_AAV/documents_pharmaco_AAV/Emilie/smrt_assembly/FALCON-integrate/FALCON-examples/run/ecoli/1-preads_ovl/job_000b/job_000b_done.exit
```

**Comment by pb-cdunn** [comment]
If you're using `job_type=local`, you might need to limit the job concurrency. The defaults can be found [here](https://github.com/PacificBiosciences/FALCON/blob/master/falcon_kit/run_support.py#L109). I'd suggest starting with:
```
pa_concurrent_jobs = 1
cns_concurrent_jobs = 1
ovlp_concurrent_jobs = 1
```
Typically, if you have too many concurrent jobs, your machine will start swapping memory, becoming unresponsive, but that will not actually kill jobs. Possibly, you have a process on your machine will jobs that cause too much swapping. Or possibly you actually ran out of virtual memory.

If even 1 job is too many, then you need to reduce the `-s` flag for `pa_DBsplit` -- something like `-x500 -s50` [would hold memory to around 4GB](https://dazzlerblog.wordpress.com/command-guides/dazz_db-command-guide/).

**Comment by emlec** [comment]
I followed your recommendations and the run is successful. 

Thank you for your help.
