### ISSUE TITLE
what happens when a (submitted) job fails?

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#321]
Does fc_run.py still terminate (in the latest version)?   So if there are 200 jobs running, and 1 fails, fc_run.py will terminate the other 199?

**Comment by pb-cdunn** [comment]
There is a setting to control this: `stop_all_jobs_on_failure`

By default, it is `False`.

No matter what, if the first job to finish is a failure (i.e. no other jobs have yet succeeded). The theory is that if nothing has succeeded, then the odds are good that nothing will ever succeed. And if that's wrong, then the failure was probably fast, so you can fix it and re-start.

After we implement 're-acquisition', we will make it easier to keep all other jobs running even if the first to finish was a failed job. After you switch to the new code, then we can talk about how soon that feature would be ready.
