### ISSUE TITLE
flock timeout usually too short

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#322]
Hi, Chris,

If I may make another request:

if you are going to hard-code the flock rsync timeout, 10 minutes is way too short for us.  Our filesystem and the size of our files take over 1/2 an hour.  To be safe I use a 1 hour timeout.

Otherwise what happens is this:  the first job on the node grabs the lock and rsync's the huge .bps for the next 30 or 40 minutes.  Meanwhile all other jobs assigned to that node try to get the lock, wait 10 minutes, and then die.  Happens like clockwork.

I used to restart the jobs and was puzzled that they always worked the next time.   The reason is by that time the file was transferred and the first job had released the lock.

Best wishes,
David

**Comment by pb-cdunn** [comment]
Ah! That's interesting.

The tmpdir-copying is actually off in `master`. I know some users need that, but it should be done at the job-distribution level. When we put it back, we'll either use a much longer timeout, or we'll leave the read-only files in the network filesystem. It would be good to see benchmarks from various systems, but I suspect that we don't really need to copy the DB to /tmp. *Writing* to /tmp and copying to the network is probably the biggest win.

**Comment by dgordon562** [comment]
I'm guessing you mean to have fasta2DB write directly to /tmp?  Interesting idea, but:

Bear in mind that there are dozens' of different /tmp's--one for each node.   So you still need to copy
to all the other /tmp's.

**Comment by pb-cdunn** [comment]
The idea would be for a job to write its output into /tmp,  and then to copy all that into NFS before the next job. I listened to a podcast by the author of lustre filesystem, and for lustre that is *definitely* a good approach. Lustre likes to work with large files all at once. For other NFS, the advantage is less, but it matters more because NFS is so much slower for large amounts of data.
