### ISSUE TITLE
auto cutoff calculation

### ISSUE THREAD

**Issue by onabluemoon** [PacificBiosciences/FALCON#328]
Let me first thank for the providing the community with this nice assembler and for its continued development.

I am currently assemblying a eukaryotic genome of around 1Gb for which I have ~70X raw read coverage. Recently I have seen it mentioned that Falcon now supports "auto-calculation of length_cutoff", however due to the lack of documentation on this function I am bit confused with some of the parameters that should be used. 

Would it be necessary to specify a value for "length_cutoff_pr" or would it also be automatically calculated? Below is the relevant part of config file I would use.
```
#The length cutoff used for seed reads used for initial mapping
#length_cutoff = -1
seed_coverage = 20
genome_size = 1000000000

#The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 1
```
Thank you kindly for the help.

**Comment by pb-cdunn** [comment]
`length_cutoff_pr` is not currently auto-calculated. However, it is used only to further reduce the number of seed reads after correction.

`length_cutoff` (without `_pr`) is auto-calculated only if set to `-1`.

**Comment by onabluemoon** [comment]
Thank you for the quick answer, that solves my question.
