### ISSUE TITLE
Symlinking from bash takes too long on NFS

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#332]
Hi, Chris,
> 5 hours of spewing such messages: [WARNING]block: 845, las_path:

I believe this warning is coming from  the code below the comment "# Symlink all daligner *.las."
in run.py

I'm concerned that the 5 hours this has been running may be just a prelude to days of this before it can continue.  Why emit a warning for each symlink generated?   Do you have a problem if I just comment out the warning and restart?
(By the way, pypeflow.log is now 300GB which is a little excessive, so I don't want to just put the warnings there instead.)

Thanks,
David

**Comment by pb-cdunn** [comment]
Of course you can comment that out. But I don't think the warnings are the main problem.

I think you might be using old code, which produced *way* too many symlinks. Maybe you can search for that fix and cherry-pick it.

**Comment by dgordon562** [comment]
Wasn't the old code the one that you and I found back in November and you fixed immediately?  This code is Feb 1.  Wasn't that fixed code?

**Comment by dgordon562** [comment]
Does this look like unnecessary symlinks to you?  It doesn't to me--it looks as though it creates just one symlink for each las file in each job dir, no?

    # Symlink all daligner *.las.                                               
    for block, las_path in support.daligner_gather_las(job_rundirs):
    # commented out DG April 15, 2016                                               
    #            fc_run_logger.warning('block: %s, las_path: %s' %(block, las_path)\
)                                                                               
            mdir = os.path.join(main_dir, 'm_%05d' %block) # By convention. pbs\
mrtpipe works differently.                                                      
            las_path = os.path.relpath(las_path, mdir)
            cmd = 'ln -sf {} {}'.format(las_path, mdir)
            system(cmd)

(all lines under the for should be indented)

**Comment by dgordon562** [comment]
However, your general point is correct.  Even after I eliminated the chatty output, my calculations show that it will continue generating symlinks for another 1.5 days.  ugg!  (I sure wish you guys at PacBio would run into these kinds of IO issues, too--if you felt the pain, I would think they would be fixed in short order (grin)).  In this particular case perhaps a better way would be to create the symlinks as part of the LAsort/merge step when the L1 las were created.  That way the filesystem would not be saturated.  But beware of the "mkdir -p m_*"--remember, that was a killer because it was done over and over for the same m_ directory.   Perhaps creating the m_* directories could be done before the LAsort/merge step as a fc_run.py task.

**Comment by pb-cdunn** [comment]
I can't believe we need 1.5 days worth of symlinks. There is something wrong.

Do you still have the tiny 5k testcase? You can run DBsplit with a small value to get a large number of jobs. Start with `-s.065536` and eventually reduce to `-s.00065536`. You should have a huge number of extremely fast jobs. That's a better way to debug your problem.

When you paste code, use triple-backticks so GitHub can format it.
* https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by dgordon562** [comment]
I tried my old bash script that creates the symlinks.  A rough estimate shows it would take about 9 hours (roughly the same).  Our system admin says "Falcon doesn't like nfs."  
```
So I switched to a node that mounts the same disk via gpfs and now it is on track for 4 hours of creating symlinks.  A lot better, but still bad, wouldn't you say?
```

Thanks for the triple-backticks tip.

**Comment by pb-cdunn** [comment]
How many .las files are we talking about? Maybe we just need to delete the ones that have been merged already.

**Comment by dgordon562** [comment]
Around 1.1 million.  They are all L1 las files.  Those all need symlink from m_ directories, no?

(5022 job_ directories and each has around 220 L1 las files in them.)

Anything fishy about that?

**Comment by pb-cdunn** [comment]
We could use something other than symlinks. But I'm curious about your stats.
* How many subreads?
* How many bytes in .fasta subread files? (Or how big is your dazzler db?)
* How big is a typical .las file?
* What are your falcon cfg settings?

**Comment by pb-jchin** [comment]
@pb-cdunn, the sym-link part does take a long time in our system too (maybe more than 8 or 10hrs). The `os.system` call in the loop has a lot overhead. In some assembly work, I had modified my local code to generate a bash script for all symlinks to avoid the overhead. One possible improvement is to output bash script and sym-link for each `m-*` block separately. Then we won't be block by one big sym-link job. What do you think?

**Comment by pb-cdunn** [comment]
I don't think we need symlinks at all. I'll fix that next week.

**Comment by dgordon562** [comment]
Wow!  The wonder man!  What are you going to do?  One fof for each m_ directory?  that would cut io down by a factor of ~200...   (just an idea...)

**Comment by dgordon562** [comment]
Our system admin guy suggested replacing system with os.symlink.  I tried that and WOW!!!  It processed 663 job directories per minute.  So all are done in less than 10 minutes.  That is plenty fast.  Any reason for Falcon to not just do that?  Seems so simple...

**Comment by pb-cdunn** [comment]
> What are you going to do? One fof for each m_ directory? that would cut io down by a factor of ~200... (just an idea...)

Exactly.

> replacing system with os.symlink

Even simpler! We can implement that more quickly. Thanks for the benchmark.

**Comment by dgordon562** [comment]
Chris:  here is the code that works much faster (60x ?) for creating symlinks:

```
    # Symlink all daligner *.las.
    for block, las_path in support.daligner_gather_las(job_rundirs):
        
# commented out DG April 15, 2016
#            fc_run_logger.warning('block: %s, las_path: %s' %(block, las_path))
        las_file = os.path.basename( las_path )


        mdir = os.path.join(main_dir, 'm_%05d' %block) # By convention. pbsmrtpipe works differently.
        las_path = os.path.relpath(las_path, mdir)
        #cmd = 'ln -sf {} {}'.format(las_path, mdir)
        # DG, April 15, 2016  change this system to os.symlink 
        

        os.symlink( las_path, mdir + "/" + las_file )
        # system(cmd)
    system("touch %s" %da_done)
```

Best wishes,
David

**Comment by pb-cdunn** [comment]
Yes, that was a good idea. It's in `0.5.0` now.

**Comment by dgordon562** [comment]
I should have mentioned--this code has been tried out.

**Comment by pb-jchin** [comment]
if `os.symlink` is faster, it is the way to go.  I do find recently that it is useful to have the symlink dumped out for fixing some run. Our systems may have problem to do all sym-link. It dropped out some and the run fails.  In my own version, I dump all symlinks to one file, I was able to find missing symlinks and patch it fast.  Ultimately, a reliable file system is the solution. Add very small time delay with `os.symlink` might help stability.

**Comment by dgordon562** [comment]
os.symlink is faster than system( "ln -s" ) by more than two orders of magnitude.  

Here are my notes:

 It was so blazingly fast that it was difficult to measure,
but while Falcon processed about 5-10 or so job directories per
minute, my python script using subprocess processed 14 job directories
per minute,

BRIAN'S OS.SYMLINK METHOD PROCESSED 663 JOB DIRECTORIES PER MINUTE!!!!

**Comment by pb-jchin** [comment]
yes. I just like to point out different file systems might handle fast symlink request at kernel level very differently.

**Comment by pb-cdunn** [comment]
>  I do find recently that it is useful to have the symlink dumped out for fixing some run.

In `0.5.0`, we log the paths before we call `os.symlink()`.

* https://github.com/PacificBiosciences/FALCON/commit/c471b9430cb413abac9a239caf4486a155009035

**Comment by dgordon562** [comment]
Logging is fine.  Having it spew to stdout is not, and I don't want to have to shut off all INFO messages just to prevent these from going to stdout.  You could have run.py write a single bash script or python script and run that in order to create all of the symlinks.    Later to fix things you could run that script.  I personally have a script that will check/recreate all links.  It isn't something that needs to be rewritten for each assembly--it is a pretty simple.

**Comment by dgordon562** [comment]
Here is my script, in case it benefits anyone.   My point is that it doesn't require logging in order to determine the correct symlinks.

 ```
#!/usr/bin/env python

import glob
import sys
import os
import subprocess

import time
import re

# must be run from 0-rawreads

szTopDirectory = os.getcwd()

if ( not re.search( r"0-rawreads$", szTopDirectory ) ):
    sys.exit( "you must be in 0-rawread but are in " + szTopDirectory )


#szCommand = "rm -f m_*/m_*done"
#print "executing " + szCommand
#subprocess.call( szCommand, shell = True )

#szCommand = "rm -f  rm p_merge_done"
#subprocess.call( szCommand, shell = True )


print "finding job_*"
aJobDirs = glob.glob( "job_*" )

nCount = 0

for szJobDir in aJobDirs:
    nCount += 1

    print szJobDir + " " + str(nCount) + " out of max " + str( len( aJobDirs ) )

    os.chdir( szTopDirectory )
    os.chdir( szJobDir )

    szGlob = "L1.*.las"

    nExists = 0
    nCreated = 0
    for szFile in glob.glob( szGlob ):
        aWords = szFile.split( "." )

        nMNumber = int( aWords[1] )

        szMDir = "m_{:05d}".format( nMNumber )

        szTarget = szTopDirectory + "/" + szJobDir + "/" + szFile
        szSource = "../" + szMDir + "/" + szFile

        if ( os.path.exists( szSource ) ):
            nExists += 1
            continue

        #szCommand = "ln -s " + szTarget + " " + szSource
        #print "about to execute: " + szCommand
        #subprocess.call( szCommand, shell = True )
        os.symlink( szTarget, szSource )
        nCreated += 1

    print "in this job directory, created: {:d} and already existed: {:d}".format( nCreated, nExists )
```

**Comment by pb-cdunn** [comment]
> I don't want to have to shut off all INFO messages just to prevent these from going to stdout.

It writes one long line at INFO level, so it will be buffered. And it isn't all that long.

**Comment by dgordon562** [comment]
If there are 1000 blocks, doesn't that mean a million symlinks?  And if 5000 blocks, 25 million symlinks?    All that goes to the screen, one line or millions, doesn't that mean it will slow down falcon from my 10 job directories per second?   Anyway, at least please make it easy for me to comment this out if it turns out to be a problem...

Thanks!
David

**Comment by pb-cdunn** [comment]
You're right. We don't really need to write all that to INFO. I'll print a truncated version or something.

It's easy to find. See `falcon_kit/util/system.py` in the latest code. Within about a week, we should have local-disk jobs working. Then you can update your code-base.
