### ISSUE TITLE
Where can I find a detailed introduction to the parameters? 

### ISSUE THREAD

**Issue by Syaoran-Tang** [PacificBiosciences/FALCON#333]
I am learning the gene assembly, and I'm confused about the parameters in fc_run_*.cfg. So where can I find a detailed introduction to the parameters? (Especially on the parameters of SGE...)
Thanks!

**Comment by mseetin** [comment]
Hi Sayoran,

The sge_option flags are essentially the flags you'd use when using qsub to
submit a job to your cluster.  Exactly which to choose may depend on your
setup, but as a first guess, try just using whatever you use when you
submit a job.

The remaining parameters are discussed here:
https://github.com/PacificBiosciences/FALCON/wiki/Manual
Gene Meyer's blog is a great resource for the full details of the
HPCdaligner options: dazzlerblog.wordpress.com

Matt

**Comment by Syaoran-Tang** [comment]
Thank you very much~!
