### ISSUE TITLE
Which version of rdflib

### ISSUE THREAD

**Issue by ebioman** [PacificBiosciences/FALCON#339]
Hello
I am trying to install FALCON on our cluster and running in a few issues. I started from FALCON-integrate and installed all gits manually. This is necessary as we generate RPMs and the final step includes generation of the package in an environment which is not connected to the internet. Generating and installing the RPM package succeeded but executing FALCON I am running in a few issues.
Which rdflib version are you actually using as I receive the following error ? :

<pre><code>
! Please wait for all threads / processes to terminate !
! Also, maybe use 'ps' or 'qstat' to check all threads,!
! processes and/or jobs are terminated cleanly.        !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[WARNING] #tasks=0, #alive=0
Traceback (most recent call last):
  File "/software/UHTS/PacBio/FALCON-integrate/0.4.0/bin/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/software/UHTS/PacBio/FALCON-integrate/0.4.0/lib64/python2.7/site-packages/falcon_kit/mains/run.py", line 624, in main
    main1(*argv)
  File "/software/UHTS/PacBio/FALCON-integrate/0.4.0/lib64/python2.7/site-packages/falcon_kit/mains/run.py", line 447, in main1
    wf.refreshTargets([fofn_abs_task])
  File "/software/UHTS/PacBio/FALCON-integrate/0.4.0/lib/python2.7/site-packages/pypeflow/controller.py", line 522, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/software/UHTS/PacBio/FALCON-integrate/0.4.0/lib/python2.7/site-packages/pypeflow/controller.py", line 555, in _refreshTargets
    tSortedURLs = self.getSortedURLs(rdfGraph, objs)
  File "/software/UHTS/PacBio/FALCON-integrate/0.4.0/lib/python2.7/site-packages/pypeflow/controller.py", line 383, in getSortedURLs
    tSortedURLs = PypeGraph(rdfGraph, connectedPypeNodes).tSort( )
  File "/software/UHTS/PacBio/FALCON-integrate/0.4.0/lib/python2.7/site-packages/pypeflow/controller.py", line 108, in __init__
    for row in self._RDFGraph.query('SELECT ?s ?o WHERE {?s pype:prereq ?o . }', initNs=dict(pype=pypeNS)):
  File "/software/lib/python2.7/site-packages/rdflib/graph.py", line 1071, in query
    result = plugin.get(result, query.Result)
  File "/software/lib/python2.7/site-packages/rdflib/plugin.py", line 104, in get
    return p.getClass()
  File "/software/lib/python2.7/site-packages/rdflib/plugin.py", line 66, in getClass
    module = __import__(self.module_path, globals(), locals(), [""])
ImportError: No module named rdfextras.sparql.query
</code></pre>

I am a little bit suprised as we have rdflib 4.2 on the cluster which loads correctly and which
according to their git [https://github.com/RDFLib/rdflib](url) should make rdfextras obsolete :
 from rdfextras [https://github.com/RDFLib/rdfextras](url) : 

Note: this project is deprecated.
In RDFLib >= 4.0, rdfextras is no longer required, SPARQL support and the utilities from this project are included in core.

<pre><code>
python -c 'import rdflib'
INFO:rdflib:RDFLib Version: 4.2.0
</code></pre>

Thanks

**Comment by ebioman** [comment]
Okay I found it myself in the pypeflow-0.1.1-py2.7.egg-info

rdflib == 3.4.0
rdfextras >= 0.1

So I guess I have to install these specific versions, or did you try any more recent ?

**Comment by pb-cdunn** [comment]
Sorry. We haven't had time to update our rdflib usage. A few lines of our code would need to change. I'll try today, to see if it turns out to be reasonably easy.

Would RPMs require a single version of each installed package?

@pb-jchin, if I change this in **FALCON**, I will need to update **FALCON-unzip** also. Any objection?

**Comment by pb-jchin** [comment]
No. The rdflib has some big changes since I used it.  I did try to update it to more recent one but it did not work well so it is kinda stuck in the old version.  Ideally, I will like to remove the dependency. However, it will need some big time block for me to do it.  Currently, my job queue to solve various assembly problems from some collaborator is getting too long....

**Comment by pb-jchin** [comment]
on the other hand, last time I evaluate the updated RDFlib was a while ago. Maybe there is a simpler to make the newer one working...

**Comment by ebioman** [comment]
@pb-cdunn no not really. We have RPMs for many of the dependencies and load them dynamically according to the need. The problem is e.g. for python libraries that we cant keep many different version easily (unlike for programs). Normally this does is not that bad as many programs are backwards compatible. For rdflib it is different though as they changed quite a lot of things between v 3.4 and > 4.0 as @pb-jchin  pointed out and the old commands do not all work anymore. Therefore it might indeed be quite a piece of work to change it.
I managed to overcome this by packaging the particular rdflib version within the RPM instead
