### ISSUE TITLE
rp_ (LAmerge) jobs fail over and over again

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#349]
Hi, Chris,

I'm moving this from an enhancement to a new issue.  I've now determined how this happens:

Some of the LAmerge commands succeed, and then the rm command runs deleting some of the L1.*.las files.
More LAmerge, more rm, ...

Finally something interrupts the job.  It could be a number of things:  the node going down, the filesystem being overwhelmed putting the job in error state, nfs/gpfs not responding, whatever...

Eventually I restart fc_run.py which notices that the done flag is not set so it restarts this job.  Except now some of the L1.*.las files are missing, so the job fails.  Further restarts of fc_run.py give the same result.

So I must recreate all the links and restart fc_run.py.  But this process is repeated for some jobs.

Therein lies madness.

The solution to this is to not rm any files until all LAmerge have successfully completed and the done flag is set.  This is critical so I will probably do it today, unless you have time.  

Let me know.

Best wishes,
David

**Comment by pb-cdunn** [comment]
Yes, I can work on this right away. But only `master`, which is now version `0.5.0`. Is that ok?

**Comment by pb-cdunn** [comment]
I don't see anything which removes the .las files, except in the daligner jobs (`rj_*`, not `rp_*`). Maybe this is old code? Could you post something which removes those files? Here is an example for me:
```
$ cat 0-rawreads/m_00001/rp_00001.sub.sh
#!/bin/bash
set -vex
LAmerge -v raw_reads.1 L1.1.1 L1.1.2 L1.1.3 L1.1.4 L1.1.5 L1.1.6 L1.1.7 L1.1.8 L1.1.9 L1.1.10 L1.1.11 L1.1.12 L1.1.13
mkdir -p ../las_files
ln -sf ../m_00001/raw_reads.1.las ../las_files
ln -sf ./m_00001/raw_reads.1.las ..
```
```

**Comment by dgordon562** [comment]
That's great!  Thanks!

I might need some help installing--it takes me a 1/2 day to a day to install, and each time there are different problems.  Otherwise I could download your bash.py changes and put those into the version I've already installed.

If you are doing this, could you also do the copy to /var/tmp/falcon so LAmerge runs on local disk?  That would speed it up quite a bit (I could look up my timing results if you want numbers).

Oh, also please eliminate the set -v, set -x, and LAmerge -v --it causes way too much output to sge_log which is a big part of the problem in the first place.  nfs/gpfs gets overwhelmed, times out, and thus sets the job in error state.

**Comment by pb-cdunn** [comment]
> That's great! Thanks!

I think you missed my last message. I don't see the problem you are having. I don't see those files being deleted.


> If you are doing this, could you also do the copy to /var/tmp/falcon so LAmerge runs on local disk?

I have to do something else first.

**Comment by dgordon562** [comment]
Yes,  I missed it (wasn't there until now).  Anyway, here is an example:
This is

0-rawreads/m_00063/rp_00063.sub.sh

(the rm's are buried within the line--you need to hunt to find them...)


#!/bin/bash
set -vex
LAmerge -v L2.63.1 L1.63.1 L1.63.2 L1.63.3 L1.63.4 L1.63.5 L1.63.6 L1.63.7 L1.63.8 L1.63.9 L1.63.10 ; rm L1.63.1.las L1.63.2.las L1.63.3.las L1.63.4.las L1.63.5.las L1.63.6.las L1.63.7.las L1.63.8.las L1.63.9.las L1.63.10.las
LAmerge -v L2.63.2 L1.63.11 L1.63.12 L1.63.13 L1.63.14 L1.63.15 L1.63.16 L1.63.17 L1.63.18 L1.63.19 L1.63.20 L1.63.21 ; rm L1.63.11.las L1.63.12.las L1.63.13.las L1.63.14.las L1.63.15.las L1.63.16.las L1.63.17.las L1.63.18.las L1.63.19.las L1.63.20.las L1.63.21.las
LAmerge -v L2.63.3 L1.63.22 L1.63.23 L1.63.24 L1.63.25 L1.63.26 L1.63.27 L1.63.28 L1.63.29 L1.63.30 L1.63.31 L1.63.32 ; rm L1.63.22.las L1.63.23.las L1.63.24.las L1.63.25.las L1.63.26.las L1.63.27.las L1.63.28.las L1.63.29.las L1.63.30.las L1.63.31.las L1.63.32.las
LAmerge -v L2.63.4 L1.63.33 L1.63.34 L1.63.35 L1.63.36 L1.63.37 L1.63.38 L1.63.39 L1.

**Comment by pb-cdunn** [comment]
Oh! I see. When there are enough levels of merging, there are trailing `rm` on the same line. Ok, I'll take care of that.

**Comment by pb-cdunn** [comment]
There are a lot of things that can go wrong here. I think it makes more sense to do the merge in `/tmp` and then consider the whole thing either done or not done.

But #351 will at least eliminate the problem at hand -- by no longer running **rm** on `*.las`.
