### ISSUE TITLE
LAmerge: Did not write all records

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#350]
anybody have this error and know the cause?  Otherwise I'm going to have to did into Gene Myer's code...

**Comment by pb-jchin** [comment]
Do you mean the total record numbers are different before and after? If that is the case, it might be best to build a test so Gene can trace what is going on... (No, I have not seen it before.)

**Comment by pb-cdunn** [comment]
Possibly a dup. That could happen if you merge the same file twice.

**Comment by dgordon562** [comment]
I tracked this down to 2 corrupted L1 las files.  (I'm recreating to see if daligner again creates them corrupted, but let's suppose it does.)  What would the consequence of just removing those 2 files from the LAmerge step so that the L2 las files contain all but those 2 L1 las files?

**Comment by pb-jchin** [comment]
if there are some missing overlap for error correction, as long as the mount of missing overlap is not much, theoretically, the impact could be small.

**Comment by pb-cdunn** [comment]
Gene actually recommends running **LAcheck**, and he includes that in his **HPCdaligner** output. Since this actually occurred for you, I'll add that back somehow. I guess we'll have to avoid crashing in those cases.

If you have not updated **DALIGNER** lately, we found a bug that Gene fixed recently. Empty files lead to corrupt `.las`. That could be it.

Btw, it's not a good idea to contact thegenemyers if you haven't actually updated to the latest version. That would waste his time, and it's freeware. You can bug us because we actually get paid, in one way or another.

Thanks for tracking down the cause of failure. That's always good to know.

**Comment by dgordon562** [comment]
Thanks to both of you!    OK, Chris, on the rev'up and LAcheck  before contacting Gene...

**Comment by pb-cdunn** [comment]
Well, there is a problem. We do not yet have the 'run-in-tmpdir' behavior that you require (though it is a high priority for us). You could update *only* **DALIGNER** and **DAZZ_DB** (from PacificBiosciences, not from thegenemyers). I'm trying to think of any backward-incompatible changes there... Oh, I know one: **HPCdaligner** was renamed to **HPC.daligner**. I think you're better off sticking with what you have.

But you *could* install the latest **DALIGNER** separately, and you could run **DALIGNER** and **LAmerge** from that to test whether it's fixed. The bug I'm thinking of would be the output of **DALIGNER** itself, so no matter what, finding a small test-case that reproduces the behavior might be awkward for you.

**Comment by dgordon562** [comment]
The LAcheck suggestion was very helpful!  There were many corrupt L1.las files, all from the same job_* directory.  I suspect there was a problem with the cluster at that point.  I re-ran that job_* job and all the L1.las are fixed, and now LAmerge works.

However...lot's more problems, generally caused by the rm within the rp_ jobs.  (There is a similar problem with rm's in the rj_ jobs.)

So it is time to do major surgery.  Details are below but my biggest question is what the advantages are of  rev'ing up first.    I'm running right now with the version of Falcon as of Feb 1, 2016.  I'm getting a lot of pressure here to stick with that since there are always new problems installing/running the newest Falcon, as with any large piece of software.  What  advantages of the current tip of master vs that on Feb 1?  Will I get better assemblies?   Will anything about Falcon be more reliable?  Will it be easier to modify?  If I have to run some programs (such as a daligner job) directly rather than under fc_run.py, will fc_run.py recognize that or will I have to edit some file?

Here are the changes I plan to make (some you used to have but took out): I'm going to take all of the LAsort/merge off of the network disk and run them on /var/tmp (including the LAsort/merge in the daligner jobs).  Note that as you've pointed out, there is no need to have daligner read .raw_reads.bps from  /var/tmp  (since daligner is cpu bound) and thus there is no need to copy  to copy these big files (.raw_reads.bps) to /var/tmp--just make a symlink ln -s /net/vol/.raw_reads.bps /var/tmp/falcon/.raw_reads.bps.  daligner will create all of the \*N.las and \*C.las files on /var/tmp and I'll run LAsort/merge there and copy the L1\*.las files back to the network disk.  Then create symlinks in m_\* directories, copy to /var/tmp and run LAmerge on /var/tmp.  Then copy the raw_read\*.las back to network disk.  Then I *will* copy .raw_reads.bps to /dev/shm on some specific nodes and run LA4Falcon only on these nodes.

Any cautions/suggestions with this?


Thanks!
David

**Comment by pb-jchin** [comment]
My recommendation is that if you are under pressure, you should try to get what already working for you and keep a branch of the repository.  I do the same here. Currently, we are working on a diploid assembly paper. I only instal newer version for testing reason. For the research work, I stick with older version as I need to track the version of the software used for writing it up.

**Comment by pb-cdunn** [comment]
>  I'm getting a lot of pressure here to stick with that since there are always new problems installing/running the newest Falcon, as with any large piece of software.

I'm thinking of dropping **virtualenv**. It seems to be your main problem. We could install into HOME with `--user` or maybe PYTHONUSERSITE. But if we can solve your specific problems with **virtualenv**, that would be worth doing. I think your biggest problem was a lack of GitHub access. Is that solved?

Ignore Jason's suggestion. He's under some pressure, and he and I will sync up later, no problem.

But you are a different case. I cannot easily support you if you remain on an old branch. If you are modifying FALCON, you need to work with me directly, via GitHub. Embrace the 21st Century!

However, if you are worried about losing current data, then you will need a different run directory and a separate FALCON installation. 


>  What advantages of the current tip of master vs that on Feb 1?

There are some bug-fixes, and there will be more. Plus ongoing enhancements. Check the release notes in **FALCON-integrate**.

> Will I get better assemblies?

For now, just slightly. Additionally, I soon will try Gene's new repeat-masking, which *might* lead to significant improvements. And eventually we'll have another package to provide alignment and final polishing as part of a higher-level workflow.

> Will anything about Falcon be more reliable?

Yes! The new process-watcher is way better than wondering whether a job is still running.

> Will it be easier to modify?

Yes, the code is always getting cleaner, with much better separation of concerns. And if you want to work with me, you need to be near my branch.

> If I have to run some programs (such as a daligner job) directly rather than under fc_run.py, will fc_run.py recognize that or will I have to edit some file?

If you modify and run the generated bash scripts, then you will get the needed `done` files, so yes, you will be able to restart using your manual outputs.


Unfortunately, the `/tmp` stuff is not ready yet, so you might not be able to rev-up just yet. I'll let you know when that's done. Maybe in a week? (The tough part is dealing with our internal workflow system.) If you don't mind throwing your work away later, then yes, your ideas sound good. Running LAmerge in `/var/tmp` could allow your jobs to survive.

**Comment by dgordon562** [comment]
Hi, Chris,
Everything you say makes perfect sense to me.  And I can use github.  Unfortunately the decision about which version was taken out of my hands--I'm supposed to stick with the version we've used.  But I'm sure at some point I'll be allowed to rev up.  I hope you can still help me now and then in the meantime.

Best wishes,
David

**Comment by pb-cdunn** [comment]
We're not changing the algorithm, aside from optionally. It's just the workflow. Since we too need it immediately, I was going to implement the `/tmp` stuff tomorrow morning. (My fiance has a show tonight.)
