### ISSUE TITLE
Output files and quality assesment 

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [PacificBiosciences/FALCON#352]
I have been playing around with Falcon parameters assembling a heterodikaryotic fungus based on the recommendation here on github and the wiki. I am especially interested in the heterozygous part of the genome, because we think a lot of it biology is hiding there. I had great success getting down to ~300-500 p_ctg and N50 of 1.5-0.5 Mb depending on the setting. Previous illumina assemblies gave more like 10000+ contigs. So thanks for that.
I still have have some questions.

#1 What's the difference between the a_ctg_all.fa, a_ctg_base.fa and, a_ctg.fa files. I understand these are all the alternative contigs aka bubbles.

#2 Is there an easy way to map the alternative contigs on the primary contigs on a per base basis. The headers of the a_ctg.fa provide the nodes of the graph but is there an easy way to get the start and end point in relation to the p_ctg.fa file?

#3 Are you recommending to use Quiver to polish the 'total' geome (p_ctg.fa + a_ctg.fa)?

Thanks!

**Comment by pb-jchin** [comment]
For #1, there are some write up here: https://github.com/PacificBiosciences/FALCON/wiki/Manual
please also see some of the picture for the concept in this slide deck (just for the FALCON but not the FALCON-Unzip part):
 https://speakerdeck.com/jchin/de-novo-diploid-genome-assembly-and-haplotype-sequence-reconstruction

For #2, I typically use nucmer for the mapping.

For #3, There is pro-and-con to includes the a_ctg.fa in Quvier. I typically do quiver for both p_ctg.fa + a_ctg.fa in hoping a_ctg.fa to recruit some noisy reads to make quiver on p_ctg.fa cleaner. However, if you have true diploid genome, this will generate haplotype clean consensus. Part of FALCON-Unzip work is to solve the problem.
