### ISSUE TITLE
empty m_*/rp_*.sub.sh scripts

### ISSUE THREAD

**Issue by mroach-awri** [PacificBiosciences/FALCON#355]
not sure if this is only a problem at my end but I downloaded and installed the current master branch of FALCON this morning, I went to rerun an old assembly, the daligner steps finished without a hitch but it crashed after that. The rp_*.sub.sh scripts were all missing the script section and only contain:
 ```
#!/bin/bash
 set -vex
```
I tried using the new feature `use_tmpdir=1` and the rp sub.sh scripts had the updated headers but were still missing the LAmerge bit of the script so of course again no raw reads las files were generated in the m* folders and falcon crashed. went back to 345117a and it's currently running fine.

**Comment by pb-cdunn** [comment]
Sorry. Accidental deletion.

**Comment by mroach-awri** [comment]
yep this is working well now, thanks!
