### ISSUE TITLE
In 1-preads_ovl, preads.*.las versus L1.*.las

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#358]
Hi, Chris,

Quick question:

On smaller genomes (e.g., ecoli) this appears to be preads.\*.las
But on larger genomes, this appears to be several L1.\*.las

Am I correct?

How about the output of 0-rawreads rj_ jobs?  Isn't that *always* some L1.*.las files?

Thanks!
David

**Comment by pb-jchin** [comment]
yes. The number of "layers" is determined by HPCaligner (or the updated one).  FALCON current does not manage the merging job planning, it just takes the HPCaligner output and dispatch the jobs. For larger genome, there can be more layer of merge sort for efficiency in Gene's design.
