### ISSUE TITLE
IO Error during fasta2fasta.py

### ISSUE THREAD

**Issue by chkcole** [PacificBiosciences/FALCON#359]
Hello, 
I am currently attempting to assemble the Human genome using FALCON and the PacBio reads available at:
 ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/NA12878/NA12878_PacBio_MtSinai/sorted_final_merged.bam
The assembly process worked fine for the example data sets(Ecoli, Lambda) you provided, however I am encountering an error when assembling these Human reads. Here is the output from the sge_log/prepare_rdb.sh-task_build_rdb-task_build_rdb.o:

[prepare_rdb.sh-task_build_rdb-task_build_rdb.txt](https://github.com/PacificBiosciences/FALCON/files/255646/prepare_rdb.sh-task_build_rdb-task_build_rdb.txt)

It looks like the computer cluster I am working on doesn't like the number of files being opened. I'm looking at the 0-rawreads folder and I'm noticing that one of the programs is producing a separate file for each read.
Is there a way to limit this using parameters in the cfg file?

Here's the cfg file in case you are curious:
[fc_run_NA12878.txt](https://github.com/PacificBiosciences/FALCON/files/255652/fc_run_NA12878.txt)

the cluster I'm using is being shared so I'm trying to minimize the amount of memory/# of cores I'm using at any given time.

Thank you for your time

**Comment by pb-cdunn** [comment]
We produce a file per zmw because **fasta2DB** cannot currently handle an input with multiple zmws. I guess you have weird input, possibly caused by your bam2fasta converter. The zmw number is after the first slash in each fasta header. Grep for `>` in your fasta files and see if there are too many zmws for some reason.

**Comment by pb-cdunn** [comment]
Oh, I wrote that wrong. **fasta2DB** requires a single *movie* per fasta. I'll edit my other comment.

**Comment by pb-cdunn** [comment]
We *could* process each input N times for N movies. But first, can you try to figure out how many movies there? And how many fasta input files?

**Comment by chkcole** [comment]
There is one fasta file.
I think I see the issue, none of the headers contain a forward slash.
Based on the `grep -c ">"` results, there are 40820702 records in the file.
I'll reprocess the files to see if I can preserve the movie information.

**Comment by pb-cdunn** [comment]
> none of the headers contain a forward slash

Oh. In that case, these would fail as input for **fasta2DB** later anyway.

For my curiosity, how did you process the bam, and what are you trying differently?

**Comment by chkcole** [comment]
I converted the bam to fastq using picardtools SamToFastq
and then converted fastq to fasta using:
`sed -n '1~4s/^@/>/p;2~4p' in.fq > out.fa`
I don't think the sed command is the issue, so I'm going to try a different bam2fastq converter and see if that works.

**Comment by chkcole** [comment]
It looks like the group who uploaded the raw and aligned reads on the NIH FTP stripped the movie information from all the headers.
Is there a quick workaround for this or should I start hunting for other data sets?

**Comment by pb-cdunn** [comment]
Easiest might be to modify `fasta2fasta.py`. You can choose an arbitrary moviename, and sequentially increase the zmw number.

    >mymovie/0/0_0
    ...
    >mymovie/1/0_0

The `0_0` could be `0_<length>` or `<beg>_<end>` if you want, but it's ignored.
