### ISSUE TITLE
length_cutoff or genome_size are >0 in my config file, but I still get an error

### ISSUE THREAD

**Issue by wdlngtn** [PacificBiosciences/FALCON#365]
Hi,
I’m having an issue with an exception being raised in FALCON, but I don’t see what is causing the exception?  
The error raised is “Exception('Must specify either length_cutoff>0 or genome_size>0')”, but I don’t see how my config file violates that.
```ini
[General]
input_fofn = /share/Public/Genome/Falcon/tst.fofn
job_type= local
genome_size = 1000000000
length_cutoff = -1
input_type = raw
length_cutoff_pr = 8500
```
Can you tell the fix to be made here? I have tried with different numbers for length_cutoff, and also tried omitting genome_size or length_cutoff in some trial runs.
Thank you
Will

**Comment by pb-cdunn** [comment]
I suspect that it's not actually reading that cfg. What is your command-line?

**Comment by wdlngtn** [comment]
I think you are right.  Seems my server was wiping all the data from my cfg file when I was uploading it, for some reason. 

I ran it  again with a cfg file with all the data, all systems go.
Thank you for your time.
