### ISSUE TITLE
FALCON assemble corrected reads generated from canu

### ISSUE THREAD

**Issue by tangerzhang** [PacificBiosciences/FALCON#366]
Hello, 
I previously corrected Pacbio reads using canu correction and I hope to feed FALCON with these preads.
However, I got some errors which told me that the head lines of corrected reads from canu were not compatible with FALCON.
Could I simply modify the header line and make them looks like: prolog/000001250/0_3186?
Does the header line of FALCON preads record specific messages which are useful in assembly step?
Thanks!

**Comment by pb-cdunn** [comment]
Try `fasta2fasta`. I think that's available on branch `master`.

**Comment by tangerzhang** [comment]
Thanks for your quick response.
The fasta2fasta might be the latest FALCON package but not in my copy.
Could you please show me a simple command line to update my copy to the latest FALCON version since I am not familiar with git command lines.
Thanks again!

**Comment by pb-cdunn** [comment]
You could try a fresh checkout in another directory and copy fasta2fasta from there. In fact, you could just re-install a fresh copy from scratch. Or install from **pitchfork**, which will give you latest FALCON. We cannot support every use-case.
* https://github.com/PacificBiosciences/pitchfork/wiki
