### ISSUE TITLE
gcc 4.9.2 and FALCON

### ISSUE THREAD

**Issue by yingzhang121** [PacificBiosciences/FALCON#38]
Hi, 

My default gcc is version 4.9.2.

When I tried to compile the FALCON code, I got the following error:

$ python setup.py install --prefix=$HOME/src/FALCON
running install
/home/support/yzhang/.local/lib/python2.7/site-packages/setuptools-12.0-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'enstaller (4.7.0.dev1-55c9a8e)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/home/support/yzhang/.local/lib/python2.7/site-packages/setuptools-12.0-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'supplement (0.5dev.dev202)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
running bdist_egg
running egg_info
creating falcon_kit.egg-info
writing requirements to falcon_kit.egg-info/requires.txt
writing falcon_kit.egg-info/PKG-INFO
writing top-level names to falcon_kit.egg-info/top_level.txt
writing dependency_links to falcon_kit.egg-info/dependency_links.txt
writing requirements to falcon_kit.egg-info/requires.txt
writing falcon_kit.egg-info/PKG-INFO
writing top-level names to falcon_kit.egg-info/top_level.txt
writing dependency_links to falcon_kit.egg-info/dependency_links.txt
writing manifest file 'falcon_kit.egg-info/SOURCES.txt'
reading manifest file 'falcon_kit.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'falcon_kit.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/falcon_kit
copying src/py/FastaReader.py -> build/lib.linux-x86_64-2.7/falcon_kit
copying src/py/__init__.py -> build/lib.linux-x86_64-2.7/falcon_kit
copying src/py/falcon_kit.py -> build/lib.linux-x86_64-2.7/falcon_kit
copying src/py/fc_asm_graph.py -> build/lib.linux-x86_64-2.7/falcon_kit
running build_ext
building 'falcon_kit.DW_align' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
creating build/temp.linux-x86_64-2.7/src/c
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -O2 -fPIC -I/soft/python-epd/canopy/1.4.1/appdata/canopy-1.4.1.1975.rh5-x86_64/include/python2.7 -c src/c/DW_banded.c -o build/temp.linux-x86_64-2.7/src/c/DW_banded.o
src/c/DW_banded.c: In function 'align':
src/c/DW_banded.c:135:5: internal compiler error: Illegal instruction
     max_d = (int) (0.3*(q_len + t_len));
     ^
0x87a75f crash_signal
	../../gcc-4.9.2/gcc/toplev.c:337
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
error: command 'gcc' failed with exit status 1

I thought you might be interesting in knowing this.

For my installation, I reverted to gcc/4.8.2 after this failure, and installed FALCON.

Best,
- Ying

**Comment by pb-jchin** [comment]
@yingzhang121 Thanks.  Once I have chance to back to work on the C code, I will take a deeper look.  The statement seems so innocent.

**Comment by pb-cdunn** [comment]
My [Travis build](https://travis-ci.org/pb-cdunn/FALCON/builds/68337842) passed with gcc-4.92, but we [changed how extension modules are created](411c0db0ec8da283173f14abf552e8931bed5894). That might be the difference.
```sh
gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/python/2.7.9/include/python2.7 -c src/c/DW_banded.c -o build/temp.linux-x86_64-2.7/src/c/DW_banded.o
```
You can experiment in Travis using pb-cdunn/FALCON@d58eaef816f6c72d4b7daa334c76e880a8a087ef on my `gcc-4.9` branch. Re-open if you find something we can repro in Travis.
