### ISSUE TITLE
LA4Falcon / fc_consensus.py stalled

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#39]
These have been running for 2 days not using, according to top <0.5% cpu time.  LA4Falcon is usually in D state (which I believe usually indicates it is waiting on a system resource).  It is unlikely there is any disk or memory contention.  

Any thoughts about how to find out what the problem is?

**Comment by pb-jchin** [comment]
This part has a lot of random access. If your file system is not designed for such load, there will be many "D" state. It happens in our cluster.  I did two thing before. For very large project, I did copy the relevant file to local disk and fetch the data from local.  Later, I found modify all "fopen" in daligner and DAZZ_DB code to use "mmap" I/O helps to OS to cache the data locally.  (`fopen` with "rm" mode, check `man fopen`) This will helps if you node is dedicated for assembly for a while (otherwise the cached data can be swapped out.)  If you need more, ask MC my phone number, we can chat more in phone.

**Comment by dgordon562** [comment]
I will pursue this.  I did move files to /var/tmp (a local rather than network disk) and LA4Falcon didn't speed up.  I noticed that I need to move all of the following files to the local drive in addition to the one that is an argument to LA4Falcon:

-rw-rw-r-- 1 dgordon dgordon_g 126747 Mar 26 10:19 raw_reads.db
-rw-rw-r-- 1 dgordon dgordon_g 955M Mar 26 10:19 .raw_reads.idx
-rw-rw-r-- 1 dgordon dgordon_g 43G Mar 26 10:19 .raw_reads.bps

Please confirm.

Are these files all read-only by LA4Falcon?  So it is ok to have multiple copies of them on different nodes?  Or do I need to keep any of them on the network drive?

Regarding changing from fopen to mmap, I believe I only need to fopen "rm" and don't explicitly need an mmap call, correct?

The fopen calls that I must change are (please put "yes" and "no" next to them to indicate necessary or not necessary):

in DAZZ_DB:

Catrack.c:    aout = fopen(Catenate(prefix,argv[2],".","anno"),"r");
Catrack.c:    dout = fopen(Catenate(prefix,argv[2],".","data"),"r");
Catrack.c:        afile = fopen(Numbered_Suffix(prefix,nfiles+1,Catenate(".",argv[2],".","anno")),"r");
Catrack.c:        dfile = fopen(Numbered_Suffix(prefix,nfiles+1,Catenate(".",argv[2],".","data")),"r");
DB.c:  if ((f = fopen(name,mode)) == NULL)
DB.c:  afile = fopen(Catenate(db->path,".",track,".anno"),"r");
DB.c:  dfile = fopen(Catenate(db->path,".",track,".data"),"r");
DBdust.c:    if ((afile = fopen(fname,"r+")) == NULL || db->part > 0)
fasta2DB.c:    istub  = fopen(dbname,"r");

in DALIGNER:

DB.c:  if ((f = fopen(name,mode)) == NULL)
DB.c:  afile = fopen(Catenate(db->path,".",track,".anno"),"r");
DB.c:  dfile = fopen(Catenate(db->path,".",track,".data"),"r");
HPCdaligner.c:      { file = fopen(Catenate(root,Numbered_Suffix(".",fblock-1,".las"),"",""),"r");
HPCdaligner.c:    file = fopen(Catenate(root,Numbered_Suffix(".",fblock,".las"),"",""),"r");
LAcat.c:        if ((input = fopen(name,"r")) == NULL) break;
LAcat.c:        if ((input = fopen(name,"r")) == NULL) break;
LAsplit.c:        dbvis = fopen(Catenate(pwd,"/",root,".db"),"r");

(MC out of town.)

**Comment by pb-jchin** [comment]
@dgordon562, my patch is to change `Fopen` directly, see below,
```
$ git diff
diff --git a/DB.c b/DB.c
index 92b3c9f..9888d0c 100644
--- a/DB.c
+++ b/DB.c
@@ -111,10 +111,16 @@ char *Strdup(char *name, char *mesg)

 FILE *Fopen(char *name, char *mode)
 { FILE *f;
+  char newmode[3];

   if (name == NULL || mode == NULL)
     return (NULL);
-  if ((f = fopen(name,mode)) == NULL)
+  if (strcmp(mode, "r") == 0) {
+      strcpy(newmode,"rm");
+  } else {
+      strcpy(newmode,mode);
+  }
+  if ((f = fopen(name,newmode)) == NULL)
     fprintf(stderr,"%s: Cannot open %s for '%s'\n",Prog_Name,name,mode);
   return (f);
 }
```

```
$ git diff
diff --git a/DB.c b/DB.c
index 92b3c9f..9888d0c 100644
--- a/DB.c
+++ b/DB.c
@@ -111,10 +111,16 @@ char *Strdup(char *name, char *mesg)

 FILE *Fopen(char *name, char *mode)
 { FILE *f;
+  char newmode[3];

   if (name == NULL || mode == NULL)
     return (NULL);
-  if ((f = fopen(name,mode)) == NULL)
+  if (strcmp(mode, "r") == 0) {
+      strcpy(newmode,"rm");
+  } else {
+      strcpy(newmode,mode);
+  }
+  if ((f = fopen(name,newmode)) == NULL)
     fprintf(stderr,"%s: Cannot open %s for '%s'\n",Prog_Name,name,mode);
   return (f);
 }
```

yes, this part is read-only, and you need the three DB files (for all jobs) + one las file (for single job) to work.

**Comment by dgordon562** [comment]
Worked beautifully!  (53 minutes for the 12 jobs that have been hanging around for 3 days).

So now I will kill the worthless sge jobs, copy the fasta files back to preads and set the _done files and hopefully fc_run.py will think that its jobs completed and will finish the assembly.

**Comment by pb-jchin** [comment]
Great. This part is very I/O intensive, as it involves many random access to the disk for fetching sequencing used for error correction.  There are a couple of ideas (with proper hardware) that might help. Moving data to local is one of them but the right way to do it typically dependent on the infrastructure.

**Comment by dgordon562** [comment]
Assembly quality was poor, unfortunately:

the sum of all contig lengths is only
234,209,171 bp and the N50 is 37,733bp with the largest contig being
613,608 bp.  This compares with advertised Falcon N50 values from 1 to
11 Mb.

Here is my cfg file.   Any suggestions?

input_fofn = input.fofn

input_type = raw

length_cutoff = 20000

length_cutoff_pr = 17000


sge_option_da = -pe orte 1 -l mfree=30G
sge_option_la = -pe orte 6 -l mfree=6G
sge_option_pda = -pe orte 1 -l mfree=33G


sge_option_pla = -pe orte 2 -l mfree=6G
sge_option_fc = -pe orte 6 -l mfree=6G
sge_option_cns = -pe orte 6 -l mfree=6G

pa_concurrent_jobs = 100
ovlp_concurrent_jobs = 100
cns_concurrent_jobs = 100


pa_HPCdaligner_option =  -v -dal128 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal128 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6

overlap_filtering_setting = --max_diff 60 --max_cov 60 --min_cov 2

**Comment by pb-jchin** [comment]
Not sure what data you have. You read length cut is likely too big.  You will have to use smaller one to get enough coverage for generating an assembly. You can check https://github.com/PacificBiosciences/FALCON/issues/28 to see how to check the length distribution with DBstat.

**Comment by nottwy** [comment]
What does the -H option of LA4Falcon mean? I check the sequences in the output of LA4Falcon and find that there are some sequences whose length is less than the CUTOFF I set.
