### ISSUE TITLE
Incremental daligner

### ISSUE THREAD

**Issue by rhallPB** [PacificBiosciences/FALCON#393]
For a large sequencing / assembly effort is there any practical way to run daligner incrementally within the falcon job framework. Dazzlers fasta2DB and HPC.daligner support incrementally adding data, but I'm having a hard time fitting this with the falcon job structure.
Thanks.

**Comment by pb-jchin** [comment]
The implementation is actually more complicated and can break the automatic workflow in some way. We had some experimental code but I think it got removed. If there is some good solution and PR, we will hope to incorporate it.

**Comment by pb-cdunn** [comment]
@rhallPB, 

Let's not bug Jason with this. Nothing will happen right away, but if you want to have a deeper discussion sometime, you can post ideas here:
* https://github.com/pb-cdunn/FALCON/issues/3
