### ISSUE TITLE
Failed to run in SGE, no module named future.

### ISSUE THREAD

**Issue by lamz138138** [PacificBiosciences/FALCON#399]
Hi!

I tried to use a cluster machine to run falcon, and there are three nodes named smp01, smp02, smp03 in the machine. First I installed FALCON-integrate in console node, and could run related scripts in this node. Then I logged in smp01, but it failed to run related scripts. Any suggestion would be grateful!

1.  Run script in console node
```
export workPath="/PacBio"
export toolsPath="/tools"
. $toolsPath/FALCON-integrate/fc_env/bin/activate
fc_consensus.py -h
```
```
> usage: fc_consensus.py [-h] [--n_core N_CORE]
>                        [--local_match_count_window LOCAL_MATCH_COUNT_WINDOW]
>                        [--local_match_count_threshold LOCAL_MATCH_COUNT_THRESHOLD]
>                        [--min_cov MIN_COV] [--min_cov_aln MIN_COV_ALN]
>                        [--min_len_aln MIN_LEN_ALN] [--max_n_read MAX_N_READ]
>                        [--trim] [--output_full] [--output_multi]
>                        [--output_dformat] [--output_simple_fasta_header]
>                        [--min_idt MIN_IDT] [--edge_tolerance EDGE_TOLERANCE]
>                        [--trim_size TRIM_SIZE]
> 
> a simple multi-processor consensus sequence generator
> 
> optional arguments:
>   -h, --help            show this help message and exit
>   --n_core N_CORE       number of processes used for generating consensus; 0
>                         for main process only (default=24)
>   --local_match_count_window LOCAL_MATCH_COUNT_WINDOW
>                         local match window size (obsoleted, no effect)
>   --local_match_count_threshold LOCAL_MATCH_COUNT_THRESHOLD
>                         local match count threshold (obsoleted, no effect)
>   --min_cov MIN_COV     minimum coverage to break the consensus
>   --min_cov_aln MIN_COV_ALN
>                         minimum coverage of alignment data; an alignment with
>                         fewer reads will be completely ignored
>   --min_len_aln MIN_LEN_ALN
>                         minimum length of a sequence in an alignment to be
>                         used in consensus; any shorter sequence will be
>                         completely ignored
>   --max_n_read MAX_N_READ
>                         maximum number of reads used in generating the
>                         consensus
>   --trim                trim the input sequence with k-mer spare dynamic
>                         programming to find the mapped range
>   --output_full         output uncorrected regions too
>   --output_multi        output multi correct regions; implies
>                         --output_dformat, unless --output-simple-fasta-header
>   --output_dformat      output daligner compatible header, only work with
>                         --output_multi; DEPRECATED and ignored, as this is the
>                         default now
>   --output_simple_fasta_header
>                         Turn off --output_dformat. This was for older (pre
>                         spring 2015) DALIGNER. Never needed now.
>   --min_idt MIN_IDT     minimum identity of the alignments used for correction
>   --edge_tolerance EDGE_TOLERANCE
>                         for trimming, the there is unaligned edge leng >
>                         edge_tolerance, ignore the read
>   --trim_size TRIM_SIZE
>                         the size for triming both ends from initial sparse
>                         aligned region
```
2. Then, I logged in smp02 and run the above code, it encountered following error
```
ssh smp02
export workPath="/PacBio"
export toolsPath="/tools"
. $toolsPath/FALCON-integrate/fc_env/bin/activate
```
```py
> fc_consensus.py -h
> Traceback (most recent call last):
>   File "/tools/FALCON-integrate/fc_env/bin/fc_consensus.py", line 4, in <module>
>     __import__('pkg_resources').run_script('falcon-kit==0.4.0', 'fc_consensus.py')
>   File "/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 17, in <module>
>     from __future__ import absolute_import
> ImportError: No module named __future__
> 
```

3. In fact, I logged in smp02 to check why the job that I submitted exited after running a few of minutes, following is what had I done in console node and related information
1) Submitted job in console node
```
export workPath="/PacBio"
export toolsPath="/tools"
. $toolsPath/FALCON-integrate/fc_env/bin/activate
fc_run.py fc_run.cfg >fc_run.log 2>fc_run.err
```

2) The context in fc_run.cfg
```ini
> [General]
> #job_type = local
> 
> # list of files of the initial bas.h5 files
> input_fofn = input.fofn
> #input_fofn = preads.fofn
> 
> input_type = raw
> #input_type = preads
> 
> # The length cutoff used for seed reads used for initial mapping
> length_cutoff = 5000
> 
> # The length cutoff used for seed reads usef for pre-assembly
> length_cutoff_pr = 5000
> 
> 
> jobqueue = smp.q
> sge_option_da = -pe orte2 8 -q %(jobqueue)s
> sge_option_la = -pe orte2 2 -q %(jobqueue)s
> sge_option_pda = -pe orte2 8 -q %(jobqueue)s
> sge_option_pla = -pe orte2 2 -q %(jobqueue)s
> sge_option_fc = -pe orte2 24 -q %(jobqueue)s
> sge_option_cns = -pe orte2 8 -q %(jobqueue)s
> 
> pa_concurrent_jobs = 32
> ovlp_concurrent_jobs = 32
> 
> pa_HPCdaligner_option =  -v -dal4 -t16 -e.70 -l1000 -s1000
> ovlp_HPCdaligner_option = -v -dal4 -t32 -h60 -e.96 -l500 -s1000
> 
> pa_DBsplit_option = -x500 -s50
> ovlp_DBsplit_option = -x500 -s50
> 
> falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6
> 
> overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24
> 
```

3) Then the job exited after running a few of minutes, and the information in fc_run.err which I think would be useful were list below:
```
> 2016-06-15 14:19:23,074 - fc_run - INFO - '/PacBio/falcon/demo/0-rawreads/preads/c_00010_done.exit' generated. job: 'c_00010.sh-ct_00010-ct_00010' exited.
> 2016-06-15 14:19:23,074 - fc_run - INFO - '/PacBio/falcon/demo/0-rawreads/preads/c_00010_done.exit' generated. job: 'c_00010.sh-ct_00010-ct_00010' exited.
> 2016-06-15 14:19:23,590 - pypeflow.controller - INFO - message for task://localhost/ct_00010: 'fail'
> 2016-06-15 14:19:23,590 - pypeflow.controller - INFO - message for task://localhost/ct_00010: 'fail'
> 2016-06-15 14:19:23,590 - pypeflow.controller - INFO - Failure ('fail'). Joining 'task://localhost/ct_00010'...
> 2016-06-15 14:19:23,590 - pypeflow.controller - INFO - Failure ('fail'). Joining 'task://localhost/ct_00010'...
> 2016-06-15 14:19:23,593 - pypeflow.controller - ERROR - Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
> 
```

4) Also, I found related files in preads director:
`cat 0-rawreads/preads/c_00010.sh `

```
> export PATH=/tools/FALCON-integrate/fc_env/bin:/myUser/bin:/myUser/script:/myUser/tools/root/bin:/opt/openmpi/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/eclipse:/opt/ganglia/bin:/opt/ganglia/sbin:/usr/java/latest/bin:/opt/maven/bin:/opt/rocks/bin:/opt/rocks/sbin:/opt/gridengine/bin/lx26-amd64:/myUser/bin:${PATH}
> export PYTHONPATH=:${PYTHONPATH}
> export LD_LIBRARY_PATH=/opt/gridengine/lib/lx26-amd64:/opt/openmpi/lib:/myUser/tools/root/lib/:${LD_LIBRARY_PATH}
> set -vex
> cd /PacBio/falcon/demo/0-rawreads/preads
> hostname
> date
> time bash cp_00010.sh
```

5) At last, I review the related files in sge_log:
`cat sge_log/c_00010.sh-ct_00010-ct_00010.o4343 `

```
> cd /PacBio/falcon/demo/0-rawreads/preads
> + cd /PacBio/falcon/demo/0-rawreads/preads
> hostname
> + hostname
> smp02.local
> date
> + date
> Thu Jun 16 06:07:06 CST 2016
> time bash cp_00010.sh
> + bash cp_00010.sh
> trap 'touch /PacBio/falcon/demo/0-rawreads/preads/c_00010_done.exit' EXIT
> + trap 'touch /PacBio/falcon/demo/0-rawreads/preads/c_00010_done.exit' EXIT
> cd ..
> + cd ..
> LA4Falcon -H5000 -fo raw_reads las_files/raw_reads.10.las |  fc_consensus.py --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6 > /PacBio/falcon/demo/0-rawreads/preads/out.00010.fasta
> + fc_consensus.py --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6
> + LA4Falcon -H5000 -fo raw_reads las_files/raw_reads.10.las
> Traceback (most recent call last):
>   File "/tools/FALCON-integrate/fc_env/bin/fc_consensus.py", line 4, in <module>
>     __import__('pkg_resources').run_script('falcon-kit==0.4.0', 'fc_consensus.py')
>   File "/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 17, in <module>
>     from __future__ import absolute_import
> ImportError: No module named __future__
> touch /PacBio/falcon/demo/0-rawreads/preads/c_00010_done.exit
> + touch /PacBio/falcon/demo/0-rawreads/preads/c_00010_done.exit
```

**Comment by pb-cdunn** [comment]
Check your Python version. Might be quite old.
* https://docs.python.org/2/library/__future__.html

**Comment by lamz138138** [comment]
Hi, pb-cdunn, thank you for your reply!

I think the problem was solved, and I leave my solution here. Also, I hope someone would give me a better solution, considering I have little knowledge of python.

In general, the missing of "future" was caused by old python version. Although my python in console node is higher than 2.6, the version in smp01 node is 2.6, which lack of "future". Since I didn't have "root" privilege and it would need more time to update python in each smp node, I install python2.7 by myself.

Then, I tried to let python know where to find the module of "future" (suppose I install new python2.7 in /myPython, and '\__future__.py' in director of /myPython/Lib). 

\1. I add PYTHONPATH to my bashrc (it must be exported). 

`vi ~/.bashrc`

> export PYTHONPATH=/myPython/Lib

\2. But I encounter following error:
```
export workPath="/PacBio"
export toolsPath="/tools"
. $toolsPath/FALCON-integrate/fc_env/bin/activate
python
```

> (fc_env)user@smp01 $ python
> Traceback (most recent call last):
>   File "/myPython/Lib/site.py", line 548, in <module>
>     main()
>   File "/myPython/Lib/site.py", line 530, in main
>     known_paths = addusersitepackages(known_paths)
>   File "/myPython/Lib/site.py", line 266, in addusersitepackages
>     user_site = getusersitepackages()
>   File "/myPython/Lib/site.py", line 241, in getusersitepackages
>     user_base = getuserbase() # this will also set USER_BASE
>   File "/myPython/Lib/site.py", line 231, in getuserbase
>     USER_BASE = get_config_var('userbase')
>   File "/myPython/Lib/sysconfig.py", line 520, in get_config_var
>     return get_config_vars().get(name)
>   File "/myPython/Lib/sysconfig.py", line 472, in get_config_vars
>     _init_posix(_CONFIG_VARS)
>   File "/myPython/Lib/sysconfig.py", line 356, in _init_posix
>     from _sysconfigdata import build_time_vars
> ImportError: No module named _sysconfigdata

\3. I though the python find /myPython/Lib first, which lead to these error, and I had to re-initiation of it
```
unset PYTHONPATH
python
import sys
print sys.path
```

> ['', '/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg', '/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/rdfextras-0.4-py2.7.egg', '/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/rdflib-3.4.0-py2.7.egg', '/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/pyparsing-1.5.7-py2.7.egg', '/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/html5lib-1.0b8-py2.7.egg', '/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/isodate-0.5.4-py2.7.egg', '/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/six-1.10.0-py2.7.egg', '/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg', '/tools/FALCON-integrate/FALCON/.eggs/networkx-1.11-py2.7.egg', '/tools/FALCON-integrate/FALCON/.eggs/decorator-4.0.10-py2.7.egg', '/tools/FALCON-integrate/fc_env/lib/python27.zip', '/tools/FALCON-integrate/fc_env/lib/python2.7', '/tools/FALCON-integrate/fc_env/lib/python2.7/plat-linux2', '/tools/FALCON-integrate/fc_env/lib/python2.7/lib-tk', '/tools/FALCON-integrate/fc_env/lib/python2.7/lib-old', '/tools/FALCON-integrate/fc_env/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7', '/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages']

\4. I re-export PYTHONPATH by changing above ouput path followed by /myPython/Lib
`vi ~/.bashrc`

> export PYTHONPATH=/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg":"/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/rdfextras-0.4-py2.7.egg":......:"/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages":/myPython/Lib

\5. Everything works well until now.  It seemed when starting up python, it would look for module in PYTHONPATH first, then in sys.path, so I had to look for the output of sys.path to give the right PYTHONPATH, is it a more simple way? @pb-cdunn

**Comment by pb-cdunn** [comment]
Python start-up is complicated, but basically your `PYTHONPATH` will precede standard Python modules.

I understand that things are a bit difficult to install, but there is no way around that. PyPI could be used to install the Python parts, but we have non-Python code too. You have to be able to install Python modules from source-code in order to use FALCON. There is no way around that.

It's good that you hit the `future` problem. Otherwise, your jobs would have failed later, since python-2.7 is required for other lines of code too.

**Comment by lamz138138** [comment]
Hi, thanks for your reply again!

The process had finished without error, and I hope this would be useful to anyone with the same problem!
