### ISSUE TITLE
enhancement request:  complete set of *concurrent_jobs parameters

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#401]
Hi, Chris,

I mentioned this before, but just to keep it on your radar.  There should be 6 "concurrent" parameters--not just 3.  The user should be able to set the # of concurrent jobs corresponding to each of the below stages:

``` ini
sge_option_da
sge_option_la
sge_option_pda
sge_option_pla
sge_option_fc
sge_option_cns
```

For example, I should be able to set a different number of rawreads daligner jobs than rawreads LAmerge jobs.

Just to keep this on your to-do list...

Best wishes,
David

**Comment by pb-cdunn** [comment]
Right. Thanks for reminding me.... Whoa! Lightning across the street! Loud! :zap:

**Comment by pb-cdunn** [comment]
We've added corresponding `*_concurrent_jobs` settings, in 5f250882ffba0a77b3231000344efc7bc7bd9bb4, and we've deprecated `pa_` and `_ovlp_`. The warning messages should make this clear. Thanks for the suggestion.

Unfortunately, we've moved our software workflow to an internal Git host, so the pull-requests will no longer show up in GitHub. We'll try to keep GitHub up-to-date though.

**Comment by dgordon562** [comment]
Thanks!  Makes my day!

Have a nice day.
