### ISSUE TITLE
pread fasta headers no longer conform to expected format, breaks building of pread database

### ISSUE THREAD

**Issue by rhallPB** [PacificBiosciences/FALCON#404]
pread fasta headers are not in the `prolog/000000130/0_6871` format breaks bulding of the pread database:
```
+ fasta2DB -v preads /<redact>/0-rawreads/preads/out.00001.fasta
Adding 'out.00001.fasta' ...
File out.00001.fasta, Line 1: Pacbio header line format error
```

**Comment by pb-cdunn** [comment]
Could you post the first line (the first header) of `out.00001.fasta`?

**Comment by rhallPB** [comment]
Approx:
>0000000000
I.e no _ or /


On Jul 1, 2016, at 3:03 PM, Christopher Dunn <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you post the first line (the first header) of out.00001.fasta?

-

**Comment by pb-jchin** [comment]
@rhallPB the ID is likely from another older version. We have switched the new id for a while.

**Comment by rhallPB** [comment]
Thanks, will check versions.

On Jul 1, 2016, at 4:46 PM, Jason Chin <notifications@github.com<mailto:notifications@github.com>> wrote:


@rhallPB<https://github.com/rhallPB> the ID is likely from another older version. We have switched the new id for a while.

-

**Comment by pb-cdunn** [comment]
```
>00000000
CTTGGGTGAG...
```

**Comment by pb-jchin** [comment]
actually, the preads generated by 0- stage has the `>prolog/...` format. The preads generated by 1- has the ides `[0-9]+`.  same sequences, need different heads for different purpose.

**Comment by pb-cdunn** [comment]
Jason, we can't debug this without a reference to the code which produced. He has updated the code. Let's see if it happens again, rather than spending more time on it.

**Comment by rhallPB** [comment]
This wasn't a problem with old versions, just that ` --output_multi` was missing from the `falcon_sense_option` in the config file.
