### ISSUE TITLE
LAcheck - Trace point sum != aligned interval

### ISSUE THREAD

**Issue by rhallPB** [PacificBiosciences/FALCON#405]
From a recent Falcon run, I get a LAcheck failure that isn’t fixed by rerunning:
L1.117.137: Trace point sum != aligned interval
I worked around the failure and had no further issues. 
LAcheck -v raw_reads *.las > LAcheck.log
/lustre/hpcprod/rhall/<emailed directly>/0-rawreads/job_022e/LAcheck.log

**Comment by pb-jchin** [comment]
good to know. We will pass this new LACheck problem to Gene.

**Comment by pb-cdunn** [comment]
Copied internally and verified:
```
$ cd /lustre/hpcprod/cdunn/data/fail/lacheck
$ LAcheck -v raw_reads.db L1.117.137.las
  L1.117.137: Trace point sum != aligned interval
```

**Comment by pb-cdunn** [comment]
This is a DALIGNER bug, not FALCON. So I will move this there. (Issue 21 in PacBio/Daligner if you want to track it.) Thanks for reporting it.
