### ISSUE TITLE
Assembly 800 M diaploid genome using FALCON

### ISSUE THREAD

**Issue by RobinQi** [PacificBiosciences/FALCON#409]
Hi Jason,
Sorry to trouble you.
Bad assembly result was obtained for a 800 M diaploid insect genome. The genome size, heterozygous rate and repeat were evaluated with 50X illumina short reads. Results was listed as below, 
K-mer	K-mer Depth	Genome size(M)	Heterozygous rate	Repeat
17	37.22	1130.22	0.60%	56.67%
19	36.18	1137.70	0.61%	48.63%
The kmer plots were attached for 17 kmer and19 kmer.
![17kmer](https://cloud.githubusercontent.com/assets/6779816/16681273/37de85d4-4526-11e6-9256-95122d69eefb.png)
![19kmer](https://cloud.githubusercontent.com/assets/6779816/16681274/38d5837a-4526-11e6-9be4-d177f762deeb.png)

![subreads length distribution](https://cloud.githubusercontent.com/assets/6779816/16681301/7004a4b6-4526-11e6-9732-7869716791b3.png)

Then almost 100X coverage PacBio data was obtained (80G).  And assemled use FALCON with length_cutoff =10k and length_cutoff_pr=8k. Finally, only 11M assembled genome was obtained.
Checked the preassembly reads, found that only 8.3 G preassembled based was used for assembly.
So, confused with this result. Can you give me some instructions about parameters tunning?
Thanks.

**Comment by pb-jchin** [comment]
We will need to know your configuration file to be able to know what is probably going on.

**Comment by RobinQi** [comment]
Thanks.
Below is the configuration file contents,
----------------------------------------------------------------------------------------------------
[General]
job_type = local

# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 10000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 10000


jobqueue = your_queue
sge_option_da = -pe smp 8 -q %(jobqueue)s
sge_option_la = -pe smp 2 -q %(jobqueue)s
sge_option_pda = -pe smp 8 -q %(jobqueue)s
sge_option_pla = -pe smp 2 -q %(jobqueue)s
sge_option_fc = -pe smp 24 -q %(jobqueue)s
sge_option_cns = -pe smp 8 -q %(jobqueue)s

pa_concurrent_jobs = 20
ovlp_concurrent_jobs = 20

pa_HPCdaligner_option =  -v -dal28 -t16 -e.70 -l1000 -s1000 -M40
ovlp_HPCdaligner_option = -v -dal28 -t32 -h60 -e.96 -l500 -s1000 -M40

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6 --output_dformat

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 2 --bestn 10 --n_core 24

**Comment by RobinQi** [comment]
Thanks.
Below is the configuration file contents,
----------------------------------------------------------------------------------------------------
[General]
job_type = local

# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 10000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 10000


jobqueue = your_queue
sge_option_da = -pe smp 8 -q %(jobqueue)s
sge_option_la = -pe smp 2 -q %(jobqueue)s
sge_option_pda = -pe smp 8 -q %(jobqueue)s
sge_option_pla = -pe smp 2 -q %(jobqueue)s
sge_option_fc = -pe smp 24 -q %(jobqueue)s
sge_option_cns = -pe smp 8 -q %(jobqueue)s

pa_concurrent_jobs = 20
ovlp_concurrent_jobs = 20

pa_HPCdaligner_option =  -v -dal28 -t16 -e.70 -l1000 -s1000 -M40
ovlp_HPCdaligner_option = -v -dal28 -t32 -h60 -e.96 -l500 -s1000 -M40

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6 --output_dformat

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 2 --bestn 10 --n_core 24

**Comment by RobinQi** [comment]
[General]
job_type = local
# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn
input_type = raw
#input_type = preads
# The length cutoff used for seed reads used for initial mapping
length_cutoff = 10000
# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 10000
jobqueue = your_queue
sge_option_da = -pe smp 8 -q %(jobqueue)s
sge_option_la = -pe smp 2 -q %(jobqueue)s
sge_option_pda = -pe smp 8 -q %(jobqueue)s
sge_option_pla = -pe smp 2 -q %(jobqueue)s
sge_option_fc = -pe smp 24 -q %(jobqueue)s
sge_option_cns = -pe smp 8 -q %(jobqueue)s
pa_concurrent_jobs = 20
ovlp_concurrent_jobs = 20
pa_HPCdaligner_option =  -v -dal28 -t16 -e.70 -l1000 -s1000 -M40
ovlp_HPCdaligner_option = -v -dal28 -t32 -h60 -e.96 -l500 -s1000 -M40
pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6 --output_dformat
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 2 --bestn 10 --n_core 24

**Comment by RobinQi** [comment]
[fc_run_configuration.txt](https://github.com/PacificBiosciences/FALCON/files/356375/fc_run_configuration.txt)

**Comment by RobinQi** [comment]
Thank you very much!
[fc_run_configuration.txt](https://github.com/PacificBiosciences/FALCON/files/356376/fc_run_configuration.txt)

The attachment is the falcon configuration file.

**Comment by pb-jchin** [comment]
Your configuration seems ok although it indicated you might use some older code. I encourage using newer code and take a look at https://github.com/PacificBiosciences/FALCON/wiki/Somethings-to-think-about-for-tuning-assembly-parameters to think about some parameter turning discussion. You question is probably beyond the scope of this github discussion. To understand what might be going on, one will need to understand the nature of the sample preparation and examine the data deeper.  Please contact your local region PacBio field scientists, they might be able to help beyond what we can discuss here.

**Comment by RobinQi** [comment]
OK. Thanks a lot.
