### ISSUE TITLE
LAcheck fails when level-1 is missing

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/FALCON#411]
```sh
[INFO] 2016-07-08 10:40:20,953Z Extracted from stderr
[INFO] 2016-07-08 10:40:20,954Z + LAsort -v raw_reads.1.raw_reads.1.C0 raw_reads.1.raw_reads.1.N0 raw_reads.1.raw_reads.1.C1 raw_reads.1.raw_reads.1.N1 raw_reads.1.raw_reads.1.C2 raw_reads.1.raw_reads.1.N2 raw_reads.1.raw_reads.1.C3 raw_reads.1.raw_reads.1.N3
[INFO] 2016-07-08 10:40:20,954Z + LAmerge -v L1.1.1 raw_reads.1.raw_reads.1.C0.S raw_reads.1.raw_reads.1.N0.S raw_reads.1.raw_reads.1.C1.S raw_reads.1.raw_reads.1.N1.S raw_reads.1.raw_reads.1.C2.S raw_reads.1.raw_reads.1.N2.S raw_reads.1.raw_reads.1.C3.S raw_reads.1.raw_reads.1.N3.S
[INFO] 2016-07-08 10:40:20,954Z LAcheck -vS raw_reads raw_reads.1
[INFO] 2016-07-08 10:40:20,954Z + LAcheck -vS raw_reads raw_reads.1
[INFO] 2016-07-08 10:40:20,954Z Usage: LAcheck [-vS] <src1:db|dam> [ <src2:db|dam> ] <align:las> ...
```
Obviously, we should run
  LAcheck -vS raw_reads L1.1.1

* https://bugzilla.nanofluidics.com/show_bug.cgi?id=33690
* http://jenkins:8080/job/Ubuntu1404_Mainline_SA3_hgap4_pipe_falcon_fake/306/console

**Comment by pb-cdunn** [comment]
This happens in that test but not in a similar test on the same 5k input because that one has 2 small blocks instead of 1.
```
# good
$ DBsplit -x5 -s50 -a raw_reads
$ cat raw_reads.db
files =         1
         50 reads TestMovie
blocks =         1
size =   50000000 cutoff =         5 all = 1
         0         0
        50        50
$ grep LAmerge ...
...  && LAmerge -v raw_reads.1 raw_reads.1.raw_reads.1.C0.S ...

# bad
$ DBsplit -x5 -s.065536 -a raw_reads
$ cat raw_reads.db
files =         1
         50 synth0 m000_000
blocks =         2
size =      65536 cutoff =         5 all = 1
         0         0
        33        33
        50        50
$ grep LAmerge ...
...  && LAmerge -v L1.1.1 raw_reads.1.raw_reads.1.C0.S ...
```
The two-block run works fine in hgap5. The difference is in pbsmrtpipe "scattering", so I have to look closer at more pbsmrtpipe code-paths...

**Comment by pb-cdunn** [comment]
Actually, I think the 1-block pbsmrtpipe run is fine. The problem is only for the 2-block pbsmrtpipe job, which in theory is just like the non-pbsmrtpipe job which passes.

We start with this:
```
# Daligner jobs (2)
daligner -v -h1 -t16 -H2000 -e0.7 -l1 -s1000 raw_reads.1 raw_reads.1
daligner -v -h1 -t16 -H2000 -e0.7 -l1 -s1000 raw_reads.2 raw_reads.1 raw_reads.2
# Initial sort jobs (4)
LAsort -v raw_reads.1.raw_reads.1.C0 raw_reads.1.raw_reads.1.N0 raw_reads.1.raw_reads.1.C1 raw_reads.1.raw_reads.1.N1 raw_reads.1.raw_reads.1.C2 raw_reads.1.raw_reads.1.N2 raw_reads.1.raw_reads.1.C3 raw_reads.1.raw_reads.1.N3 && LAmerge -v L1.1.1 raw_reads.1.raw_reads.1.C0.S raw_reads.1.raw_reads.1.N0.S raw_reads.1.raw_reads.1.C1.S raw_reads.1.raw_reads.1.N1.S raw_reads.1.raw_reads.1.C2.S raw_reads.1.raw_reads.1.N2.S raw_reads.1.raw_reads.1.C3.S raw_reads.1.raw_reads.1.N3.S
...
```
But with pbsmrtpipe, we must first "scatter". The input is a daligner run-script (output of HPC.daligner). The output is another, but only the parts which should run on a single machine. We want the actually runner to work with and without scattering, so it does not know whether the run-script is directly from HPC.daligner or intermediately from scattering. At the moment, the scattered file looks like this:
```
daligner -v -h1 -t16 -H2000 -e0.7 -l1 -s1000 raw_reads.1 raw_reads.1
LAcheck -v raw_reads *.las
LAsort -v raw_reads.1.raw_reads.1.C0 raw_reads.1.raw_reads.1.N0 raw_reads.1.raw_reads.1.C1 raw_reads.1.raw_reads.1.N1 raw_reads.1.raw_reads.1.C2 raw_reads.1.raw_reads.1.N2 raw_reads.1.raw_reads.1.C3 raw_reads.1.raw_reads.1.N3 && LAmerge -v L1.1.1 raw_reads.1.raw_reads.1.C0.S raw_reads.1.raw_reads.1.N0.S raw_reads.1.raw_reads.1.C1.S raw_reads.1.raw_reads.1.N1.S raw_reads.1.raw_reads.1.C2.S raw_reads.1.raw_reads.1.N2.S raw_reads.1.raw_reads.1.C3.S raw_reads.1.raw_reads.1.N3.S
LAcheck -vS raw_reads L1.1.1
```
See? It uses the `L-` prefix (e.g. `L1.1.1`) even though there is only 1 "pair" (`1.1`) in the entire file. Contrary to Jason's comment [("# JC, personally don't like such special case no blocking should be the same as nblock = 1")](https://github.com/PacificBiosciences/FALCON/commit/2b7528225f28f729af394078530b5708d7e6641e), I think we should look at the actual number of blocks in the DB, rather than at the number of pairs.

Thus, we need to pass `nblocks` into this function.

**Comment by pb-jchin** [comment]
@pb-cdunn I am confused, is the nblock=1 problem specific to pbsmrtpipe jobs?

**Comment by pb-cdunn** [comment]
> Thus, we need to pass nblocks into this function.

Well, technically what matters is the number of daligner jobs. If `>1`, then there will always be a level-1 merge. But since the first block always gets its own job, a single daligner-job always implies a single block.

(This would all be simpler if we re-wrote HPC.daligner, which we plan to do some day.)

Passing that in would require changes all through the code. In particular, the scatterer task would need to depend on the DB, in addition to the HPC.daligner output (a bash run-file). Or, it could assume that the file is next to the run-file, with an assumed file-name, which I think is too implicit.

Because of the difficulty of working with pbsmrtpipe, the easier solution is to switch to HGAP5 only. I've been planning on that for months anyway, partly to reduce my maintenance burden. Since we are about to switch to Continuous Deployment, that no longer suffers the severe risk of a problem at a site with an unusual batch-submission system. So I will just do that, this week.

But I will first add a parameter to `get_daligner_job_description()` to specify the number of blocks, when known.

**Comment by pb-cdunn** [comment]
> is the nblock=1 problem specific to pbsmrtpipe jobs? Is the difference from the HPC.daligner vs. pbsmrtpipe scatter-gather?

In practice, yes. Your if-statement happens to work here because we are parsing the entire output of **HPC.daligner**.

However, the **pbsmrtpipe** version first separates the bash-script into scripts for each group of chunks (where each group can run on a single machine). Then, when we run a "chunked task", it is possible that the derived bash-script for that group has only 1 daligner job, even thought the DB has multiple blocks.

I will drop the pbsmrtpipe version this week, switching to HGAP5 (our pypeflow version) permanently. It is better to fix whatever problems occur there iteratively than to maintain two workflows, and I've been told for months that this is ok. It's time to pull the trigger.

I'm also about to push a messy change which fixes this specific problem in pbsmrtpipe.
