### ISSUE TITLE
How is an alternative contig similarity computed?

### ISSUE THREAD

**Issue by ebioman** [PacificBiosciences/FALCON#413]
Hello
I watch the slide-decks and explanations regarding alternative contig generation in the FALCON
pipeline. In general the idea sounds very intuitive and we have great results so far with the program.
Today I stumbled though over an alternative contig which makes me wondering how divergence between alternative and primary contig is computed:

>000000F-023-01 007646556:E 005343597:E 1112 39073 2 -1 0.00 0.00|quiver

This is an alternative contig which I received and according to the different explanations I found it should describe the following:

 1. start of the alternative edge in the path is 007646556
 2. end of the alternative edge is 005343597
 3. the length difference is -1 bp
 4. alignment part identity is 0%
 5. the aligned part is only 0% 

1,2 and 3 I understand, but I have more difficulties with 4 and 5. It means essentially that the alternative contig has 0% similarity to the primary contig in that region and that the region is 0% of the entire primary contig length ? How is 0% even possible? I guess it is rounded as the contig is **very** large (33Mbp).

What are the columns 4,5 and 6 (1112 39073 2) respectively ?

**Comment by pb-jchin** [comment]
Here is how the internal works:

```
                    delta_len = len(seq) - len(base_seq)
                    idt = 0.0
                    cov = 0.0
                    if len(base_seq) > 2000 and len(seq) > 2000:
                        aln_data, x, y = get_aln_data(base_seq, seq)
                        if len( aln_data ) != 0:
                            idt =  1.0-1.0*aln_data[-1][-1] / aln_data[-1][-2]
                            cov = 1.0*(aln_data[-1][3]-aln_data[-1][2])/aln_data[-1][4]

                    atig_output.append( (v, w, atig_path, total_length, total_score, seq, atig_path_edges, delta_len, idt, cov) )
``` 

If both the primary and associated paths of the same bubble are short, or the alignment fail due to low identity, we simply output  0 for those two numbers.   

In `1112 39073 2 -1 0.00 0.00`, `1112` is `total_length`, `total_score`, `len(atig_path_edges)`, `delta_len`, `a_idt, cov`.  So, in your case, the bubble is small.  We do need to do a little more study how to handle this better in the future.

**Comment by ebioman** [comment]
Thanks, that makes sense now.
Cheers
