### ISSUE TITLE
DBshow Headers Do Not Match Raw Fasta File Headers

### ISSUE THREAD

**Issue by malonge** [PacificBiosciences/FALCON#415]
While debugging an error generated by FALCON-Unzip, I have identified a potential source for the error which involves file header inconsistency between the DAZZ DB and the raw fasta files.

When I dump out the fasta headers in 0-rawreads/raw_reads.db, none of them match the headers in the original fasta headers. I ran the following script to test this.

    #!/bin/bash

    # Dump the headers from the database.
    DBshow -n raw_reads.db > db_show_headers.txt

    # Check that each header is in the original fasta files.
    grep ">" ../data/*.fasta > all_raw_fasta_headers.txt
    >header_match.txt
    cat db_show_headers.txt | while read line
     do
    grep -F "$line" all_raw_fasta_headers.txt >> header_match.txt

    WC1=$(wc -l db_show_headers.txt | cut -d " " -f 1)
    WC2=$(wc -l header_match.txt | cut -d " " -f 1)

    if [ "$WC1" == "$WC2" ]
    then
      echo "Headers from DBshow match original fasta headers"
    fi
    done

What I am testing here is that every fasta header dumped out of the databse should be found in the original fasta files. 

When running this on the database for my run, none of the fasta headers match the raw fasta headers.  The movie names are consistent, but the header suffixes do not match.

To test if this was just the behavior of FALCON, I did the same analysis on your E. coli genome example. In this case, every header dumped from the database was found in the raw fasta files, just as I would expect.

Is there any reason why the fasta header files in the database would not match the original fasta headers? I believe this is the reason why FALCON-unzip is causing errors, as it is not able to find reads in my raw fasta files.

**Comment by pb-cdunn** [comment]
> When running this on the database for my run, none of the fasta headers match the raw fasta headers. The movie names are consistent, but the header suffixes do not match.

Could you provide an example? I want to avoid confusion before looking into this deeper.

You might also try `DB2fasta`.

**Comment by pb-jchin** [comment]
when you say "none of the fasta headers match the raw fasta headers", do you mean the read ids are totally different or just in different order?

**Comment by malonge** [comment]
Given the pacbio header format of:

    >movie_name/uniqueint/x_y RQ=z

The movie name matches the raw reads as I would expect, but the uniqueint and the x_y numbers do not match (it appears that the RQ score is neglected anyways).

To provide a specific example, I ran the FALCON pipline on a list of fasta files, and the pipeline ran to completion yielding an assembly. After unsuccessfully running FALCON-unzip and doing some debugging, I realized the problem was that none of the fasta headers dumped from the raw_reads.db were matching the raw fasta file headers. This led me to perform the analysis I described above, which was in the 0-rawreads directory of the FALCON run.

**Comment by pb-jchin** [comment]
will you be able to create a testing case using a small amount of fasta files? just create the DB and runs `DBshow` to see if one gets consistent results.

**Comment by malonge** [comment]
Doing a little bit of searching, it appears that the x_y RQ=z score is found, but the read header has been assigned a new uniqueint. So is there a step in the pipeline where the uniqueint of a header is changed?

To answer your latest question, I did test this on the example E. coli data set and the headers matched just fine. I did just look at the headers, however, so I can use DBshow to look at the whole fasta file.

**Comment by pb-cdunn** [comment]
Again, please try `fasta2DB`. You might be looking at the "trimmed" DB.

**Comment by malonge** [comment]
DB2fasta did recreate the original fasta files exactly, so it appears that I was accessing the trimmed database before, which I suppose may change the header id value. Looking at the E. coli assembly example that you provide, the trimed read headers and the original headers look the same, while in my example they are different. Why might that be?

**Comment by pb-cdunn** [comment]
Thanks. That's what I suspected. `DBsplit` can exclude reads in two ways:

1. Without `-a`, it will exclude all but the first (longest) read for a given zmw (as long as they are ordered).
2. The `-x` flag will exclude reads shorter than that.

There are ways to view the untrimmed DB with some of the tools. And don't feel bad; most of us have misunderstood all of this at some point. Sometimes, I have to run an experiment just to remind myself how it works. But Gene's ideas are fairly elegant once you see his logic.

**Comment by malonge** [comment]
Ok, thank you both for taking the time to answer my questions.
