### ISSUE TITLE
Memory bug in get_aln_data() in graph_to_utgs

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/FALCON#416]
(Possibly `graph_to_utgs.py` is not needed anymore, but we should either fix it or delete it. Anyway, I think the same issue exists for `graph_to_contig.py`.)

In [`graph_to_utgs.py:get_aln_data()`](https://github.com/PacificBiosciences/FALCON/blob/master/falcon_kit/mains/graph_to_utgs.py#L9),
```py
    K = 8
    seq0 = t_seq
    lk_ptr = kup.allocate_kmer_lookup( 1 << (K * 2) )
    sa_ptr = kup.allocate_seq( len(seq0) )
    sda_ptr = kup.allocate_seq_addr( len(seq0) )
    kup.add_sequence( 0, K, seq0, len(seq0), sda_ptr, sa_ptr, lk_ptr)
```
So `lk_ptr` has length `65536` always. But in [`add_sequence`](https://github.com/PacificBiosciences/FALCON/blob/master/src/c/kmer_lookup.c#L140),
```c
  kmer_bv = get_kmer_bitvector( sa + start, K);
  ...
  if (lk[kmer_bv].start == INT_MAX) {
```
`kmer_bv` is `4194303` (because `sa_ptr` is initialized with `255`), which is much larger than the size of `lk`. Here is `get_kmer_bitvector()`](https://github.com/PacificBiosciences/FALCON/blob/master/src/c/kmer_lookup.c#L121):
```c
seq_coor_t get_kmer_bitvector(seq_array sa, unsigned int K) {
    unsigned int i;
    seq_coor_t kmer_bv = 0;
    seq_coor_t kmer_mask;

    kmer_mask = 0;
    for (i = 0; i < K; i++) {
        kmer_mask <<= 2;
        kmer_mask |= 0x00000003;
    }

    for (i = 0; i < K; i++) {
        kmer_bv <<= 2;
        kmer_bv |= (unsigned int) sa[i];
    }

    return kmer_bv;
}
```
Note that `kmer_mask` is unused.

Possibly `sa` should have been initialized to `3` instead of `255`, or only the bottom 2 bits should be used for kmer_bv.

**valgrind**  is not very useful on the Python apps, so I don't know how this could be discovered generally. I found it because I am porting these apps to another language. (Just an idea. I'll show you next time I am in Menlo Park.)

**Comment by pb-jchin** [comment]
@pb-cdunn, thanks. I will look into once I fulfill other obligation I need to do today. Quick thing about the `kmer_mask`. It was used when I use the same code for an overlapper (pre-date daligner.) The `kmer_mask` is used to implement roughly same idea about the `-t` or `-M` option in `daligner` to suppress excessive repetitive k-mer.  It is not used for simple pairwise alignment cases.

**Comment by pb-jchin** [comment]
ok. I see. the proper "safty-net" is the do `sa[i] &= 0x00000011`.  `sa[i]` should be never bigger than 3 in the current way.  I did not really use all bits to store the sequences.

**Comment by pb-cdunn** [comment]
We can alter it together after I translate it. You'll see. Please don't change it too much until then. I'm only noting what I've found. This doesn't really need to be addressed immediately.

**Comment by pb-jchin** [comment]
no. I won't change the code now. I do remember that I did pack 4 bases into one bytes because I was thinking to user other bits for non-ACGT letter.

**Comment by pb-cdunn** [comment]
Oh, that's smart. Forward-thinking.
