### ISSUE TITLE
Error when running Falcon

### ISSUE THREAD

**Issue by spiderman0327** [PacificBiosciences/FALCON#417]
Hi all, I was running FALCON and got warnings as this:

>  ## warnings.warn(shutdown_msg)
> [WARNING]#tasks=1, #alive=0
> Traceback (most recent call last):
>   File "/home/guanq/Downloads/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
>     exec(compile(open(__file__).read(), __file__, 'exec'))
>   File "/home/guanq/Downloads/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
>     main(sys.argv)
>   File "/home/guanq/Downloads/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 561, in main
>     main1(argv[0], args.config, args.logger)
>   File "/home/guanq/Downloads/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 327, in main1
>     setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
>   File "/home/guanq/Downloads/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 384, in run
>     wf.refreshTargets([rdb_build_done])
>   File "/home/guanq/Downloads/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 548, in refreshTargets
>     raise Exception('Caused by:\n' + tb)
> Exception: Caused by:
> Traceback (most recent call last):
>   File "/home/guanq/Downloads/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 523, in refreshTargets
>     rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
>   File "/home/guanq/Downloads/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 740, in _refreshTargets
>     raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
> TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'

The assemble was failed. Does anyone know what is the problem and the solution? Thank you.

**Comment by spiderman0327** [comment]
The problem has been solved. The problem is the jobqueue. I simply deleted all of the jobqueue in the configure file like this:

#job_type= local
#jobqueue = local
sge_option_da = 
sge_option_la = 
sge_option_pda = 
sge_option_pla = 
sge_option_fc = 
sge_option_cns =

**Comment by pb-cdunn** [comment]
If you can post the error message from the job submission, that could help others to avoid a similar problem in the future. Glad you found a solution.
