### ISSUE TITLE
something is wrong between daligner jobs and 1_ovlp_preads

### ISSUE THREAD

**Issue by StefanReuscher** [PacificBiosciences/FALCON#418]
Hi all,

As the title says, something is holding up the assembly, my 1_pread_ovlp is empty except the input_preads.fofn. When dbDUMP ran it exited and complained about an invalid .fasta entry in 0-rawreads/preads. All out.fasta looked normal and were about 100 MB. I did have some problems, in that some mjobs would stop, but I kept rerunning falcon and eventually all out.fasta were filled up. I might have had two running falcon intances at a time...my bad.
I tried to solve this by deleting 0-rawreads/preads and mypwatcher, but the problem persisted, invalid fasta file. Then I removed both preads and all the m_XXXXX dirs. This didnt work

`IOError: [Errno 2] No such file or directory: '/lustre3/home/ol-assembler/IRGC110404_PacBio/0-rawreads/m_00077/rp_00077.sub.sh'` 

Then I restored the m_XXXX dirs from my backup and deleted only the sentinel? files and the final .las

`find -name m*done* | xargs rm`
`find -name raw*las | xargs rm`

Rerunning that resulted in random memory allocation errors from LAmerge. This is strange as I did not get memory errors in the first place. Also allocating more (32G -> 64G) did not solve the problem.

My question is: Can I somehow salvage this run ? I thing my dalinger job are fine, but the m_XXXX might be wrong. How to properly regenerate falcon from immediatly after daligner jobs finished. Alternatively, how can I find out which of the m_XXXX dirs is faulty ?

Your support is most welcome.

Gruß,

Stefan

**Comment by pb-jchin** [comment]
This looks the filesystem latency issue.   I think some of the `daligner` output might be also corrupted.  What I used to do is to identify a couple faulty jobs and manually run the block to block to patch the corrupted file and restart.    (I recalled in one cases, I can find all corrupted daligner output by finding `las` files with usually smaller sized.)

**Comment by StefanReuscher** [comment]
What do you mean by block to block ?
And how much smaller should/can a las file be if it is corrupted ? For me their sizes seem normal distributed between 10 and 20 MB, but I did not check every single one

**Comment by pb-jchin** [comment]
each job directory bundles many block-block comparison (see https://dazzlerblog.wordpress.com/command-guides/dazz_db-command-guide/#DBsplit for the concept of "block"). If only some block-block comparison fail, you can potentially just recompute the failed blocks.  If you are not sure how to do that, you might want to re-run for the whole job, it will consume more CPU time than necessary though.

**Comment by StefanReuscher** [comment]
so rerunning a daligner job can be done by removing the _done and _done.exit files, right ?
I was able to rerun all merge jobs without error this morning for I dont know what reason. The first thing that throws an error is actually a consensus job.

```
[WARNING]DEAD` job? 1468894372.0 + 3*10.0 + 120.0 < 1468894523.01 for '/lustre3/home/ol-assembler/IRGC110404_PacBio/mypwatcher/heartbeats/heartbeat-Je71c359dabda0dc0403a0097b
4fc764b3f32d790195ea1ea7694b005e135437f'
[WARNING]  File "/lustre3/home/ol-assembler/fc_env/bin/fc_run.py", line 5, in <module>
    pkg_resources.run_script('falcon-kit==0.7-git.85e41a6ab3bbeaece25f43e47c8f9a2cb9feb31a-', 'fc_run.py')
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pkg_resources.py", line 1434, in run_script
    execfile(script_filename, namespace, namespace)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/falcon_kit-0.7_git.85e41a6ab3bbeaece25f43e47c8f9a2cb9feb31a_-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc
_run.py", line 5, in <module>
    main(sys.argv)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/falcon_kit-0.7_git.85e41a6ab3bbeaece25f43e47c8f9a2cb9feb31a_-py2.7-linux-x86_64.egg/falcon_kit/mains/ru
n1.py", line 561, in main
    main1(argv[0], args.config, args.logger)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/falcon_kit-0.7_git.85e41a6ab3bbeaece25f43e47c8f9a2cb9feb31a_-py2.7-linux-x86_64.egg/falcon_kit/mains/ru
n1.py", line 327, in main1
    setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/falcon_kit-0.7_git.85e41a6ab3bbeaece25f43e47c8f9a2cb9feb31a_-py2.7-linux-x86_64.egg/falcon_kit/mains/ru
n1.py", line 445, in run
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 657, in _refreshTargets
    numAliveThreads = self.thread_handler.alive(task2thread.values())
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/pwatcher_bridge.py", line 198, in alive
    fred.endrun(status)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/pwatcher_bridge.py", line 73, in endrun
    log.warning(''.join(traceback.format_stack()))

[ERROR]Task Fred{'URL': 'task://localhost/ct_00076'}
 is DEAD, meaning no HEARTBEAT, but this can be a race-condition. If it was not killed, then restarting might suffice. Otherwise, you might have excessive clock-skew.
[INFO]Failure ('fail'). Joining `'task://localhost/ct_00076'...
```

There no jobs in the queue now, but fc_run.py is still running and occasionally submits a job. I will just have it running for a while and see if it completes. It might really be an issue with the load on the filesystem on my cluster.

**Comment by StefanReuscher** [comment]
To close this issue. The fc_consensus.py would not run if I submitted it via fc_run.py and qsub. I worked around this by

```
rm -rf mypwatcher
cd 0-rawreads/preads
rm *.fasta
rm *done*
```

then run this directly on the login node (I had .sub.sh from 1 to 92)
```
#!/bin/bash
for i in $( printf "%05d " {1..92} ); do
	if [ -s out."$i".fasta ]
	then
		echo "Skipping fasta '$i' because it exists already."
	else
		./c_"$i".sub.sh
		touch ./c_"$i"_done.exit
		touch ./c_"$i"_done
	fi
done
```
Basically run all .sub.sh manually.
After I got all .fasta I restarted fc_run and got jobs in 1-preads_ovl.

**Comment by pb-cdunn** [comment]
Please post the qsub line which was executed by a job which was called DEAD. That should be logged somewhere, along with stderr. That is the only way we can diagnose the problem with your system.

Another solution is to set `job_type = local` in the `.cfg`. Then you will be running all jobs on your login node, instead of using qsub.

**Comment by StefanReuscher** [comment]
I was able to reproduce the error by removing everything (and including) preads and later. Then rerun with the same parameters. In stderr for fc_run.py, the first error I see is:

``
[ERROR]Task Fred{'URL': 'task://localhost/ct_00060'}
 is DEAD, meaning no HEARTBEAT, but this can be a race-condition. If it was not killed, then restarting might suffice. Otherwise, you might have excessive clock-skew.
[INFO]Failure ('fail'). Joining 'task://localhost/ct_00060'...
[WARNING]DEAD job? 1469414934.0 + 3*10.0 + 120.0 < 1469415084.22 for '/lustre3/home/ol-assembler/IRGC110404_PacBio/mypwatcher/heartbeats/heartbeat-Je64de1cdf88ee10e32696cb5b4a73c02eab7ed57d0a74b03f4d03e333bad89ec'
[WARNING]  File "/lustre3/home/ol-assembler/fc_env/bin/fc_run.py", line 5, in <module>
    pkg_resources.run_script('falcon-kit==0.7-git.85e41a6ab3bbeaece25f43e47c8f9a2cb9feb31a-', 'fc_run.py')
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pkg_resources.py", line 1434, in run_script
    execfile(script_filename, namespace, namespace)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/falcon_kit-0.7_git.85e41a6ab3bbeaece25f43e47c8f9a2cb9feb31a_-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/falcon_kit-0.7_git.85e41a6ab3bbeaece25f43e47c8f9a2cb9feb31a_-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 561, in main
    main1(argv[0], args.config, args.logger)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/falcon_kit-0.7_git.85e41a6ab3bbeaece25f43e47c8f9a2cb9feb31a_-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 327, in main1
    setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/falcon_kit-0.7_git.85e41a6ab3bbeaece25f43e47c8f9a2cb9feb31a_-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 445, in run
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 657, in _refreshTargets
    numAliveThreads = self.thread_handler.alive(task2thread.values())
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/pwatcher_bridge.py", line 198, in alive
    fred.endrun(status)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/pwatcher_bridge.py", line 73, in endrun
    log.warning(''.join(traceback.format_stack()))
``

Further up in stderr I found the relevant qsub line:
``
[INFO]script_fn:'/lustre3/home/ol-assembler/IRGC110404_PacBio/0-rawreads/preads/c_00060.sh'
[INFO]starting job Job(jobid='J4017656ad0e170b7d07d854ddb003e9fae7f3919a94f2e93ba1bcfb3a9740312', cmd='/bin/bash c_00060.sh', rundir='/lustre3/home/ol-assembler/IRGC110404_PacBio/0-rawreads/preads', options={'sge_option': '-pe mpi 16 -l short -l s_vmem=32G -l mem_req=32G', 'job_type': None})
[INFO]Submitted backgroundjob=MetaJobSge(MetaJob(job=Job(jobid='J4017656ad0e170b7d07d854ddb003e9fae7f3919a94f2e93ba1bcfb3a9740312', cmd='/bin/bash c_00060.sh', rundir='/lustre3/home/ol-assembler/IRGC110404_PacBio/0-rawreads/preads', options={'sge_option': '-pe mpi 16 -l short -l s_vmem=32G -l mem_req=32G', 'job_type': None}), lang_exe='/bin/bash'))
``
and grepping for the jobid I found
``
grep J4017656ad0e170b7d07d854ddb003e9fae7f3919a94f2e93ba1bcfb3a9740312 FALCON_Ol_asm.e7252460
[INFO]!qsub -N J4017656ad0e170 -pe mpi 16 -l short -l s_vmem=32G -l mem_req=32G -V -cwd -o stdout -e stderr -S /bin/bash /lustre3/home/ol-assembler/IRGC110404_PacBio/mypwatcher/wrappers/run-J4017656ad0e170b7d07d854ddb003e9fae7f3919a94f2e93ba1bcfb3a9740312.bash
``
Setting job to local is great advice, I will use that when ever the execution nodes are too busy.
 I hope I can help you to spot a bug, but as I said above, I worked around the problem, so I dont expect specific advice on that case, for now. It does seem that I get similar errors for daligning the preads, but I havent looked into that enough.

Gruß,

Stefan

**Comment by pb-cdunn** [comment]
qsub -N J4017656ad0e170 -pe mpi 16 -l short -l s_vmem=32G -l mem_req=32G -V -cwd -o stdout -e stderr -S /bin/bash /lustre3/home/ol-assembler/IRGC110404_PacBio/mypwatcher/wrappers/run-J4017656ad0e170b7d07d854ddb003e9fae7f3919a94f2e93ba1bcfb3a9740312.bash

You can run that command directly. Then, you can use `qstat` etc. to figure out what's going on. It's possible that your job was not getting any CPU cycles, possibly because the host was swapping, which could happen if jobs on that machine are using too much memory. E.g. *your* job might need more than 32GB, and it might compete with other jobs on the same node. It's also possible that your network was experiencing high latency, which could have a variety of causes. E.g. if *your* job is causing the network latency by writing large random access files, you can try `use_tmpdir=/tmp`.

Thanks for the details and good luck.

**Comment by StefanReuscher** [comment]
Thanks for the advice. I will proceed step by step and hopefully get a genome at the end.

Gruß,

Stefan
