### ISSUE TITLE
Where is stored the diploidy information in Falcon's output ?

### ISSUE THREAD

**Issue by RxLoutre** [PacificBiosciences/FALCON#423]
Hi everyone !

I've a Falcon assembly results, stored in two differents files : pb_268_p_ctg.fa and pb_268_a_ctg.fa (which is the file that contains the alternative of the Structural Variant).

So, as the principal file is almost twice as big as the genome size I was expectiong, I was wondering how the diploidy information is stored. Is the principal file itself a haploid genome assembly, and then if we considered the alternative file (with falcon unzip maybe?) it become diploid ?

Thanks for your answers !

Cheers,

Roxane

**Comment by pb-jchin** [comment]
@RxLoutre  it depends on many scenario of a diploid genome. If you check the bioarixv preprint (http://biorxiv.org/content/early/2016/06/03/056887) carefully, you will the three diploid genomes we assemble represent somehow very different scenario. Also, it does depend on how sample is prepared and couple algorithm related parameters.  The preprint and supplementary material might answer some of you question. Please take a look if you have a chance.  You can get rough SVs by comparing the sequences in a-ctg to those in p-ctg, but a-ctg dose on contains sequence inserted or deleted before or after the sequences.

**Comment by RxLoutre** [comment]
Hi Jason,

Well, I already read it, but I may have miss the information... But I'm confused, so the p-ctg is haploid then ? Sorry but I didn't really understand your answers.

**Comment by pb-jchin** [comment]
no. check the supplementary figure 1. The FALCON is only the left side, you need you using FALCON-Unzip to separate the hapotypes to get haplotig.  About my answer, you need to see how those "branch" in the assembly graph is formed. The different can be at the junction and SV could be hidden between the connection. If you are not familiar with the assembly theory, you may want to hold a bit for now until we get change to build more material to help the community to under such theory more.

**Comment by pb-jchin** [comment]
About the paper, you can see the grape genome assembly is larger than the expected haploid genome size, and we find weak synteny between some primary contigs. What happens is that the two haplotyes are very different and the assembler simply treat the like different chromosomes as the reads from different haplotypes do not even overlap with each other.

**Comment by RxLoutre** [comment]
Okay, thanks for your answers. So as I understand, when there is a high level of polymorphism, as the two haplotypes are very different, Falcon could produce two outputs that have a similar length, but if the two haplotypes ar enot that different, the p-ctg file will be bigger than expected (so not totally haploid ?) and the a-ctg file will contains the SV, that's right ?

**Comment by pb-jchin** [comment]
just to reiterate, 

high polymorphism -> the two haplotypes can like almost different genomes -> bigger assembly size (in compare to the haploid genome size)

low polymorphism -> the two haplotypes will behave like one single genome but two identical copy -> assembly size close to haploid genome size.  

Where there is SVs between the haplotypes -> creating "bubble" in the assembly graph -> associated contigs are generated to encode two possible different haplotypes

While you may use the difference between the associated contigs to the primary contigs to find SVs, there are some case you will miss by simple alignment if the insertion or deletion is before of after the associated contigs

**Comment by RxLoutre** [comment]
When you say "assembly size", you mean p-ctg.fa + a-ctg.fa ? 

As an example, here attached a quast output in order to compare a Falcon assembly for the D. suzukii genome (high polymorphism), compared to an assembly made with some Illumina data.

So, we can see that p-ctg.fa is slighty bigger than Illumina assembly, and then it will be bigger when considering the a-ctg.fa file.

My big remaing question is that I don't really understand what's on the p-ctg.fa file. 

I tried BUSCO on p-ctg.fa file, and 91% of the set was single, and almost 9% was multi. So, could that means ? Why there is still a size different between this two kind of assembly ?

I'm sorry to repeat the same question, I really read the paper, but maybe I'm not that used to genome assembly theory as you said, and some informations are missing in my head and I can't really understand for now. But well, thanks for trying to explain me !

Here the quast report :
[report.tar.gz](https://github.com/PacificBiosciences/FALCON/files/384028/report.tar.gz)

**Comment by pb-jchin** [comment]
Assuming the haploid genome size is "S".  If the two haplotypes are "identical", then the assembly size will be approximate "S".  If there are 20% of genomes with very high polymorphism when the reads from different haplotypes do not overlap, the total p_ctg will be like "1.2 S".   The 'a_ctg.fa' size will depending on the kind of polymorphism of the rest 80% lower polymorphism regions. If the only different are SNP / 1000bp, theoretically, there will be no associate contigs.  However, if there is no SNPs, but insertion and deletion > 200bp every 10kb, the a_ctg.fa can be as big as the primary contigs.

Again, FALCON does not fully separated haplotype by SNPs, so the size of a_ctg depends on the number and density of the structural variations.

**Comment by RxLoutre** [comment]
Okay ! That was exactly the point  was missing thank you ! I understand now. So, the tool that separate 2 haplotypes is Falcon Unzip right ?
