### ISSUE TITLE
What to do once Falcon is done?

### ISSUE THREAD

**Issue by ademcan** [PacificBiosciences/FALCON#425]
Dear dev, thank you for this tool. I managed to install Falcon and run it on my PacBio data. However, there is no clear description on the wiki of what to do once Falcon is finished. 
According to the other issues that I read, one can already perform some statistiscs with the DBstats commands and have a look at the p_ctg.fa and a_ctg.fa files. I was just wondering if there is an easy way to get a nice summary of the assembly obtained with Falcon, i.e. assembly size, N50... or is there any specific tool that we can use to get some statistics?
Thank you

**Comment by gconcepcion** [comment]
There are numerous scripts online that you can use to get basic statistics out of a fasta file. Personally I like to use 'summarizeAssembly.py' from PBSuite that gives you an output like this:

2-asm-falcon$ summarizeAssembly.py p_ctg.fa 
====================
Scaffolds | withGaps | withoutGaps
====================
#Seqs  |        116
Min    |        486
1st Qu.|     23,585
Median |    115,082
Mean   |    373,715
3rd Qu.|    357,170
Max    |  4,361,630
Total  | 43,350,956
n50    |  1,035,279
n90    |    196,152
n95    |    116,167

**Comment by ademcan** [comment]
Thank you for this tool, it works well.
