### ISSUE TITLE
enhancements I made--happy to share

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#43]
Summary of modifications to Falcon to improve performance and
debugging:

1)  Created a log for fc_run.py which logs:
    1)  when a job is qsub'd (with the time and full qsub command)
    2)  when a job's "done" file is found (with the time and job name)
    3)  when it is waiting on the done file of a job (just logs this
    every 100 seconds)

    This logging information helps in debugging when a process has
    died (which happens for a variety of reasons).  When a process
    dies, fc_run.py will wait forever for the done flag.  By looking
    in this log file at the jobs that have been qsub'd but not yet
    finished with "done", and then looking with qstat at the running
    jobs, it is easy to find the jobs that have failed.  Using the
    qsub line gives you the sh script which gives you the log files so
    you can then find why they failed.

    I've written a python program (happy to share) that does all of
    this and prints out a list any failed processes and their
    stderr's.

    Having the full qsub command allows you the ability to restart
    from the command line the particular job that failed, without
    having to restart the entire assembly.  Since fc_run.py is simply
    looking for a done file, and doesn't care whether the done file is
    created by the job it qsub'd or the one you qsub'd from the
    command line, when your job completes, fc_run.py will carry on as
    though there had been no problem.

2)  Rewrote the portion of fc_run.py that qsub's the LA4Falcon jobs.
    Instead it runs a python script I wrote which copies the needed
    files to /var/tmp on the host, runs LA4Falcon, writes the output
    back to the network drive and sets the done file.

3)  Modified (per Jason's instructions) LA4Falcon so it uses mmap
    reads instead of normal reads.  

    The combination of 2 and 3 usually speeds up LA4Falcon by a factor of
    between 10 and 100.  However, there are times when copying the
    needed files (around 50GB) can itself take a long time (on the
    order of a day) for reasons I don't understand (perhaps other
    disk/network contention?)

4)  Modified LA4Falcon so it reports its progress to stderr.  This enables me to
    estimate how quickly it is running and when it will complete.

**Comment by pb-jchin** [comment]
@dgordon562  Thanks a lot for the suggestion.  I will be focusing a couple of algorithm stuff first. Once those are done, I will come back to improve a couple workflow related stuff. I will setup the wiki in github to track tips and hints.

**Comment by pb-jchin** [comment]
@dgordon562 I have added logging  SGE job submission in the file `fc_run.py` in the last commit (https://github.com/PacificBiosciences/FALCON/commit/b9257cb6579c0654fe7398d37984f503e5f47fac) of master branch.

**Comment by HenrivdGeest** [comment]
Any ideas when we can see option "2) Rewrote..." in the source code?
Or dgordon562, is there any other way that we can use you additions?

**Comment by pb-cdunn** [comment]
@dgordon562, if you push your changes into your own repo, I will pull, rebase to our current development branch, and cherry-pick. Then it would go through our review and test process.

@HenrivdGeest, we would measure `/var/tmp` interactions before making that the default behavior. Is that potential speed-up your main interest? Or are you looking for something else?

Personally, I am very interested in `mmap`, but I will concentrate on debugability first. What are your immediate needs?

**Comment by HenrivdGeest** [comment]
Any nfs speed approvement would be great. Since our nfs is shared over all users/nodes.
However, I have to say that I did not encounter any issues here.
What about replacing the max number of jobs to submit with an array job?
Or as an addition, you can use array jobs with specifying the max concurrent jobs to run. But this is beyond the start post.

About mmap, I also tried this, but I believe the dazzler part is still faster. (no idea about accuracy and coverage requirements)

**Comment by pb-jchin** [comment]
@HenrivdGeest , I did run into this issue a couple days ago. While our lustre system is ok for sometimes, it is not quite predictable. This time, my jobs stuck at 10% (out 48 virtual cores) I/O wait and maybe < 5% computation with the lustre file system. I have to manually copy the `rawreads.db` and `.rawreads.*` to our local disk `/scratch/CHM1_data` manually and modify a couple lines of code in `fc_run.py` to fetch the data locally. Here is the diff (on a development code base) for you to take a look.


```
--- a/fc_run.py      2015-05-20 00:03:52.493857000 -0700
+++ b/fc_run.py   2015-05-22 14:24:28.000000000 -0700
@@ -307,11 +307,13 @@
     with open( os.path.join(cwd, "cp_%05d.sh" % job_id), "w") as c_script:
         print >> c_script, "source {install_prefix}/bin/activate\n".format(install_prefix = install_prefix)
         print >> c_script, "cd .."
+        print >> c_script, """cp las_files/%s.%d.las /scratch/CHM1_data/""" % ( prefix, job_id)
         if config["falcon_sense_skip_contained"] == True:
-            print >> c_script, """LA4Falcon -H%d -fso %s las_files/%s.%d.las | """ % (length_cutoff, prefix, prefix, job_id),
+            print >> c_script, """LA4Falcon -H%d -fso /scratch/CHM1_data/%s.db /scratch/CHM1_data/%s.%d.las | """ % (length_cutoff, prefix, prefix, job_id),
         else:
-            print >> c_script, """LA4Falcon -H%d -fo %s las_files/%s.%d.las | """ % (length_cutoff, prefix, prefix, job_id),
+            print >> c_script, """LA4Falcon -H%d -fo /scratch/CHM1_data/%s.db /scratch/CHM1_data/%s.%d.las | """ % (length_cutoff, prefix, prefix, job_id),
         print >> c_script, """fc_consensus.py %s > %s""" % (falcon_sense_option, fn(self.out_file))
+        print >> c_script, """rm /scratch/CHM1_data/%s.%d.las""" % ( prefix, job_id)

     script = []
     script.append( "set -e" )
```

**Comment by pb-jchin** [comment]
Ultimately, if the share file system is not work, we will need add configuration to inform the code the host names of the computation and automatically copying the data. The painful part is different clusters will have different policy for local storage. I don't believe there is an universal way to do it at this moment unless the cluster environment can be 100% controlled.

**Comment by pb-cdunn** [comment]
If you rebase your changes to the *master* branch and submit a pull-request, that could help us a bit.
