### ISSUE TITLE
How much disk space is needed?

### ISSUE THREAD

**Issue by kstaderm** [PacificBiosciences/FALCON#434]
Hi,
I am trying to assemble a ~150 Mbp genome using data from 25 SMRT cells on our cluster. I am running into disk space problems, the 0-rawreads step is easily filling 3 TB of disk space. Is this a normal behavior of Falcon and if so, how much disk space will I need in the end?
I am currently using the FALCON-integrate 1.7.4 version.

Thank you for your help,
Kai

**Comment by pb-jchin** [comment]
Your genome might be really repeatitive. In such case, many overlaps are from repeats not genomic overlaps. If you have good read lengths, then you can adjust the daligner parameters to avoid storing short alignments that are typically from the repeats. Check this for more information: https://github.com/PacificBiosciences/FALCON/wiki/Somethings-to-think-about-for-tuning-assembly-parameters

**Comment by pb-cdunn** [comment]
You could try the auto-cutoff calculator:

    length_cutoff = -1
    seed_coverage = 30
    genome_size = 150000000

**Comment by kstaderm** [comment]
Thank you for your answers.

I started another run using the setting suggested by @pb-cdunn . This time "only" 2.5 TB disk space are used so far (some jobs in 0-rawreads step are still running).
In a second run I will try to adjust the parameters @pb-jchin pointed out. So far I only adjusted -M to 28, but adjusting the -t parameter seems to be promising to save disk space and computation time.

I will give you feedback, as soon as the runs succeed.

**Comment by kstaderm** [comment]
Adjusting the -t parameter did the trick. I was able to generate an assembly.

Thanks for your help again.

**Comment by pb-cdunn** [comment]
Could you tell us what `-t` you used? Also, when you use `-t`, the log should tell you the equivalent `-M`. Could you post that?

**Comment by kstaderm** [comment]
I adjusted `-t` as well as `-M` manually:
`pa_HPCdaligner_option =  -v -t12 -B128 -e.70 -l1000 -s100 -M28 -T8`

I attached the complete configuration file that I used:
[config.txt](https://github.com/PacificBiosciences/FALCON/files/495054/config.txt)

**Comment by pb-cdunn** [comment]
Thanks! And could you post the blurb from the daligner output log? That would show its own calculations, e.g.
```
Building index for raw_reads.1

 Kshift=32
 BSHIFT=8
 TooFrequent=2147483647
 (Kshift-1)/BSHIFT + (TooFrequent < INT32_MAX)=3
 sizeof(KmerPos)=16
 nreads=50
 Kmer=16
 block->reads[nreads].boff=100050
 kmers=99250
 sizeof(KmerPos)*(kmers+1)=1588016
 Allocated 99251 of 16 (1588016 bytes) at 0x2b8b9f260010
   Kmer count = 99,250
   Using 0.00Gb of space
   Index occupies 0.00Gb

Comparing raw_reads.1 to raw_reads.1

   Capping mutual k-mer matches over 10000 (effectively -t100)
   Hit count = 967,245
   Highwater of 0.03Gb space

     967,245 16-mers (9.672450e-05 of matrix)
         972 seed hits (9.720000e-08 of matrix)
       1,940 confirmed hits (1.940000e-07 of matrix)
```

**Comment by kstaderm** [comment]
Here it is:
```
Building index for raw_reads.124

 Kshift=28
 BSHIFT=8
 TooFrequent=12
 (Kshift-1)/BSHIFT + (TooFrequent < INT32_MAX)=4
 sizeof(KmerPos)=16
 nreads=14604
 Kmer=14
 block->reads[nreads].boff=100014867
 kmers=99810411
 sizeof(KmerPos)*(kmers+1)=1596966592
 Allocated 99810412 of 16 (1596966592 bytes) at 0x2b0927ba0010
   Kmer count = 99,810,411
   Using 2.97Gb of space
   Revised kmer count = 89,609,901
   Index occupies 1.34Gb

Building index for raw_reads.1

 Kshift=28
 BSHIFT=8
 TooFrequent=12
 (Kshift-1)/BSHIFT + (TooFrequent < INT32_MAX)=4
 sizeof(KmerPos)=16
 nreads=16157
 Kmer=14
 block->reads[nreads].boff=100018421
 kmers=99792223
 sizeof(KmerPos)*(kmers+1)=1596675584
 Allocated 99792224 of 16 (1596675584 bytes) at 0x2b0987ea5010
   Kmer count = 99,792,223
   Using 2.97Gb of space
   Revised kmer count = 89,489,588
   Index occupies 1.33Gb

Comparing raw_reads.124 to raw_reads.1

   Capping mutual k-mer matches over 10000 (effectively -t100)
   Hit count = 113,771,236
   Highwater of 4.73Gb space

     113,771,236 14-mers (1.137684e-08 of matrix)
          73,193 seed hits (7.319115e-12 of matrix)
          46,272 confirmed hits (4.627083e-12 of matrix)
```
I randomly selected one of the `job_` directories under `0-rawreads` and pulled the information out of the `stdout` file in the `pwatcher.dir` directory.

**Comment by pb-cdunn** [comment]
Thanks.
