### ISSUE TITLE
SGE grid permissions

### ISSUE THREAD

**Issue by kevlim83** [PacificBiosciences/FALCON#439]
Hi,

I have been trying to run falcon, it seems that everytime the pipeline creates a shell file e.g. "prepare_rdb.sh" and submits it to the cluster, it does not change the file permissions to executable. As a result, the job automatically fails.

I can change the permissions manually each time it fails and restart falcon. But this is inefficient as I have to check back everytime. Is this because I am not setting the configuration file correctly? Is there a workaround for this?

Thanks.
K

**Comment by pb-cdunn** [comment]
This is odd. We can change the permissions upon creation. That's easy.

But I'm curious why this affects only you. Normally, these files are not "executed". The executable is **bash**, and these files are the input scripts. In other words, we normally ignore the "shebang" lines and run `bash prepare_rdb.sh` instead of `./prepare_rdb.sh`. That's why nobody else has a problem.

Could you post the **qsub** command that is being run for you? Hopefully you can find that in a log. And what SHA1s of FALCON-integrate/FALCON/pypeFLOW are you using? (`git rev-parse HEAD` in each repo can tell you that.)

**Comment by kevlim83** [comment]
Here are the SHA1s of:
1\ FALCON-integrate
3547dfc22ab48a61c9fa5449a379248fc7ff6121
2\ FALCON
9769c6f8cdaf460f8c333b811cde5f543270523d
3\ pypeFLOW
224c1930e24cea8fb79dbc3850fae27b479e6950

Could I find out where is the log file that keeps track of the qsub command? In the sge_log folder, there is a file named prepare_rdb.sh-task_build_rdb-task_build_rdb.o51 with the following error logged:
-bash: ......./0-rawreads/prepare_rdb.sh: Permission denied

Thanks for your help.

**Comment by pb-cdunn** [comment]
```
commit 9769c6f8cdaf460f8c333b811cde5f543270523d
Date:   Wed Dec 9 15:59:14 2015
```
```
commit 224c1930e24cea8fb79dbc3850fae27b479e6950
Date:   Tue Dec 8 14:24:30 2015
```
You are far out of date. Management doesn't like us to spend much time on GitHub issues anyway. We certainly cannot respond to something this old.

**Comment by kevlim83** [comment]
Sorry about the outdated version. I have updated to the latest version on git. The SHA1 is now 78e1569f8a88c28f6eca7554ed2237c964ad515d, Date: 28 Aug 2016

I was hoping the update would solve the problem, but apparently, it does not.
Here is the problem once again:
In the mypwatcher/jobs folder, there is an stderr file with the message 
`-bash: ....../mypwatcher/wrappers/run-Jca870656594c4baec7832f74d60bf480ca97729478e1c533d5fc97922fb29f9e.bash: Permission denied`, accordingly fasta2DB did not even start.

This is strange because when I manually did bash run-Jca870656594c4baec7832f74d60bf480ca97729478e1c533d5fc97922fb29f9e.bash, the command worked and fasta2DB seem to be working now. 

I cant figure out what is the problem, please help.

**Comment by pb-cdunn** [comment]
Yeah, if your filesystem is slow enough, then the new attributes might not be immediately visible in another process.

But we need to see the actual qsub command. You might need to adjust the logging level for the main program. If you provide a logging-config to `fc_run`, you can control all that yourself. The file is standard Python logging-config. And example is here:
* https://github.com/pb-cdunn/FALCON-examples/blob/master/logging.ini

I might be able to help more in a week...

**Comment by pb-cdunn** [comment]
For example, when I run `synth0` in FALCON-examples (which should always be the first thing you do), I see lines like this in the resulting log-file:
```
[2016-08-29 06:50:22,611 pwatcher.fs_based:511[INFO] !qsub -N J9a93c8967f8da5 -pe smp 8 -q production -V -cwd -o stdout -e stderr -S /bin/bash /home/UNIXHOME/cdunn/repo/gh/FALCON-integrate/FALCON-examples/run/synth0/mypwatcher/wrappers/run-J9a93c8967f8da5d443086e5e9e018dac64385052123747a6c96b76e98f82965f.bash
```
That's what we need to see. Observe that in our case, **qsub** gets `-S /bin/bash scriptfilename`. In that case, the execute bit on the script is irrelevant, as qsub will execute bash. There must be a reason why something is trying to execute your wrapper directly. You need to investigate that.

What is your `job_type`? `sge`?
