### ISSUE TITLE
LAcheck: Duplicate overlap

### ISSUE THREAD

**Issue by lijingjing1** [PacificBiosciences/FALCON#444]
Hi

when i rerunning falcon once time there have a fail message,while the first running is ok.A daligner job failed and the stderr show LAcheck message is "Duplicate overlap".
I just change the daligner args " pa_HPCdaligner_option =  -v -B128 -t12 -e0.75 -k16 -h160 -l1000 -s1000 " to "pa_HPCdaligner_option =  -v -B128 -t32 -e0.70 -k14 -l500 -s1000" for testing.

**Comment by pb-jchin** [comment]
it is a known bug.  see related discussion https://github.com/thegenemyers/DALIGNER/issues/43

you can try to use "-s100" to avoid that. It will increase the `las` file sizes.

**Comment by pb-cdunn** [comment]
As noted in #445, that bug reportedly has been fixed already, and I am no longer able to reproduce the problem. You probably need to update **DALIGNER** (or **FALCON-integrate**). If that does not help, please re-open and post the SHA1 of your **DALIGNER**.

**Comment by fbemm** [comment]
"raw_reads.152.raw_reads.65.N3: Duplicate overlap (7586932 vs 2990327)"

Seeing this will Sequel data again. Using skip_check = true (which seems to not have any influence on the tasks failing) and a fast local tmp system.

F
