### ISSUE TITLE
Is there a way to resume a Falcon run once the job hit the walltime?

### ISSUE THREAD

**Issue by yingzhang121** [PacificBiosciences/FALCON#447]
Hi,

I am wondering whether there is an option in Falcon command that could resume the job?

Best,
Ying

**Comment by pb-cdunn** [comment]
`rm -rf mypwatcher/`

Then, restart `fc_run`. That should work.

**Comment by pb-cdunn** [comment]
Did that work for you?

**Comment by yingzhang121** [comment]
Yes, it did the trick.

- Ying
