### ISSUE TITLE
how much damage have I done with this change?

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#449]
Hi, Jason and Chris,

See contig_to_graph.py

I inadvertently changed line 162 of:

https://github.com/PacificBiosciences/FALCON/blob/master/falcon_kit/mains/graph_to_contig.py

from:

if type_ == "simple":
to
 if type_ == "simple" or type_ == "contained":

(I was developing a tool for MC and neglected to put the code back before doing several assemblies.)  

My question is "how different would my assemblies have been had I used the original code?"

Thanks,
David

Just so you can see a little context, from:

                if type_ == "simple":
                    if len(one_path) != 0:
                        one_path.extend ( path_or_edges[1:] )
                    else:
                        one_path.extend ( path_or_edges )

to:

                if type_ == "simple" or type_ == "contained":
                # end change
                    if len(one_path) != 0:
                        one_path.extend ( path_or_edges[1:] )
                    else:
                        one_path.extend ( path_or_edges )

**Comment by dgordon562** [comment]
I might add:  I've now checked two BAC assemblies with your original code and my mistaken code, and they give identical results.  However, these BACs might not include all cases.

**Comment by pb-jchin** [comment]
The "contained" path is a simple path but it is usually part of a bubble (collected as the "compound" path.)  Depending on what you like to do, if you want to reconstruct contigs (not use FALCON to generate contig), then you should layout all "simple" and "contained" paths and ignore the "compound" path.  After that, you need to re-examine the assembly graph of "unitigs", and process it.  I guess this might be useful for some of Mark's work. The assembly contiguity will be smaller, total assembly size (of the primary contigs) should be bigger.

However, if you layout the "contained" and "compound" at once, it breaks the basic assumption of the contig layout rule. The results may not make sense.

**Comment by dgordon562** [comment]
I've put it back the way you had it.  My main question though is whether I need to redo several large assemblies that I made while I had the change in place...

**Comment by pb-jchin** [comment]
> I've put it back the way you had it. My main question though is whether I need to redo several large assemblies that I made while I had the change in place...

I look the code again. There might be no side effect. As the utgs is from the laid out contigs, the utgs should be only "simple" or "compound".  They should never be "contained".

**Comment by dgordon562** [comment]
Phew!

I could also redo *only* the last stage of the assembly, after all of the 1-preads_ovl daligner jobs have completed, since my screw-up doesn't affect anything up to that.
