### ISSUE TITLE
difference between fc_run_LG.cfg/fc_run_LG.py and fc_run.cfg/fc_run.py

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/FALCON#45]
Dear Dr. Chin,

Are the *_LG files better for large genome assembly(e.g. human)? Could you please share something about the differences between these two sets of files?

Also, besides these example *.cfg files, do you have some recommended parameter setting for high coverage human genome ? I heard from PacBio's recent AGBT that Falcon can generate 10MB (N50) contigs, but we only got 50 Kbp (N50) contigs from CHM1 data offered with Dr. Chaisson's [paper](http://www.nature.com/nature/journal/v517/n7536/full/nature13907.html).

I really appreciate your help. Thank you very much!

Best,
Yunfei

**Comment by mseetin** [comment]
The LG example has been used for large, human-scale assemblies, but the best choice of parameters depend on your cluster's hardware and software settings.  If you don't have a Lustre filesystem or enough RAM on your nodes, you may need to use settings more like the Arabadopsis or E. coli examples.

**Comment by yunfeiguo** [comment]
Thanks for help!

So this means we should be able to obtain 10M+ contigs with these settings given that data quality and quantity are good? Right now computation speed and memory consumption both look okay.

**Comment by pb-jchin** [comment]
It depends on many factors to get N50=10Mb assembly.   However, with reasonable library and sequencing quality, one probably can get somewhere around 3  - 8Mb without much tuning.   There are still some theory and empirical method needed to be developed for optimizing large genome assemblies.

**Comment by yunfeiguo** [comment]
Thank you! I appreciate it.
