### ISSUE TITLE
some question about quiver

### ISSUE THREAD

**Issue by lijingjing1** [PacificBiosciences/FALCON#452]
Hi guys i have two question about quiver?

1. Can we using fastq/fasta files with bwa/blasr tools just instead of using bax.h5 files when doing pbalign step.Because bax.h5 file size are too big to download,and we add the necessary information like QV and reagent information to bam files by hands.

2.How many coverage should quiver used,is 50X enough or is it necessary to have data more than 50x.

**Comment by sophy7074** [comment]
There is a scripts that converts sam to out.cmp.h5 in smaranalysis, its name is samtoh5. Header in sam files is:
![h1](https://cloud.githubusercontent.com/assets/8351253/19212281/8bc4f5b4-8d80-11e6-84ff-7d426fa51dfa.PNG)
![h2](https://cloud.githubusercontent.com/assets/8351253/19212284/93a33f2a-8d80-11e6-9766-cd231478025a.PNG)

**Comment by rhallPB** [comment]
This is not the correct place for this issue. If it's a problem with quiver please see [https://github.com/PacificBiosciences/GenomicConsensus](url) or for pbalign [https://github.com/PacificBiosciences/pbalign](url)

Although to answer your questions.
1. No.
2. 50X is good, but consensus may still improve with > 50x.
