### ISSUE TITLE
Unable to run Falcon

### ISSUE THREAD

**Issue by agroppi** [PacificBiosciences/FALCON#456]
Hi

Falcon is installed on our cluster : 
`Linux jarvis.cbib.u-bordeaux2.fr 2.6.32-504.30.3.el6.x86_64 #1 SMP Wed Jul 15 10:13:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

python version : 2.7.9

My fc_run.cfg is the following : 

<pre> [General]
job_type = torque

input_fofn = /scratch/ag/Vitireseq_Fasta/input_fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 15000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 15000

# Cluster queue setting
sge_option_da = -l nodes=1:ppn=16,walltime=4:00:00
sge_option_la = -l nodes=1:ppn=16,walltime=4:00:00
sge_option_pda = -l nodes=1:ppn=16,walltime=4:00:00
sge_option_pla = -l nodes=1:ppn=16,walltime=4:00:00
sge_option_fc = -l nodes=1:ppn=16,walltime=4:00:00
sge_option_cns = -l nodes=1:ppn=16,walltime=4:00:00

# concurrency setting
pa_concurrent_jobs = 8
cns_concurrent_jobs = 8
ovlp_concurrent_jobs = 8

# overlapping options for Daligner
pa_HPCdaligner_option =  -v -B128 -e.70 -s400 -M24
ovlp_HPCdaligner_option = -v -B128 -h60 -e.96 -l500 -s400 -M8

pa_DBsplit_option = -x500 -s200
ovlp_DBsplit_option = -x500 -s200

# error correction consensus option
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 2 --max_n_read 200 --n_core 6

overlap_filtering_setting = --max_diff 60 --max_cov 90 --min_cov 2 --bestn 10 </pre>

But when I try to launch Falcon : ( `python /module/apps/falcon/1.0/fc_env/bin/fc_run.py fc_run.cfg` )

<pre> [INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_run.cfg
[INFO] No target specified, assuming "assembly" as target
[INFO]# of tasks in complete graph: 1
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO] Skipping already done task: task:///module/apps/falcon/1.0/FALCON/falcon_kit/mains/run1.py/task_make_fofn_abs_raw
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[INFO]# of tasks in complete graph: 2
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO]tick: 2, #updatedTasks: 0, sleep_time=0.100000
[INFO]Running task from function task_build_rdb()
[INFO]script_fn:'/scratch/ag/Vitireseq_Fasta/0-rawreads/prepare_rdb.sh'
[INFO]jobid=J9f0499c997ed48d7a7cebef9d10b4ae00bc81cf451b32b87e436cac67f121399
[INFO]starting job Job(jobid='J9f0499c997ed48d7a7cebef9d10b4ae00bc81cf451b32b87e436cac67f121399', cmd='/bin/bash prepare_rdb.sh', rundir='/scratch/ag/Vitireseq_Fasta/0-rawreads', options={'job_queue': None, 'sge_option': '-l nodes=1:ppn=16,walltime=4:00:00', 'job_type': None})
[CRITICAL]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
/module/apps/falcon/1.0/pypeFLOW/pypeflow/controller.py:537: UserWarning:
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            "! Please wait for all threads / processes to terminate !"
            "! Also, maybe use 'ps' or 'qstat' to check all threads,!"
            "! processes and/or jobs are terminated cleanly.        !"
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

  warnings.warn(shutdown_msg)
[WARNING]#tasks=1, #alive=1
[WARNING]Now, #tasks=1, #alive=0
Traceback (most recent call last):
  File "/module/apps/falcon/1.0/fc_env/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/module/apps/falcon/1.0/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/module/apps/falcon/1.0/FALCON/falcon_kit/mains/run1.py", line 576, in main
    main1(argv[0], args.config, args.logger)
  File "/module/apps/falcon/1.0/FALCON/falcon_kit/mains/run1.py", line 353, in main1
    setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
  File "/module/apps/falcon/1.0/FALCON/falcon_kit/mains/run1.py", line 410, in run
    wf.refreshTargets([rdb_build_done])
  File "/module/apps/falcon/1.0/pypeFLOW/pypeflow/controller.py", line 548, in refreshTargets
    raise Exception('Caused by:\n' + tb)
Exception: Caused by:
Traceback (most recent call last):
  File "/module/apps/falcon/1.0/pypeFLOW/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/module/apps/falcon/1.0/pypeFLOW/pypeflow/controller.py", line 657, in _refreshTargets
    numAliveThreads = self.thread_handler.alive(task2thread.values())
  File "/module/apps/falcon/1.0/pypeFLOW/pypeflow/pwatcher_bridge.py", line 182, in alive
    result = watcher.run(**watcher_args)
  File "/module/apps/falcon/1.0/pypeFLOW/pwatcher/fs_based.py", line 683, in run
    return cmd_run(self.state, jobids, job_type, job_queue)
  File "/module/apps/falcon/1.0/pypeFLOW/pwatcher/fs_based.py", line 486, in cmd_run
    bjob = MetaJobTorque(mjob)
  File "/module/apps/falcon/1.0/pypeFLOW/pwatcher/fs_based.py", line 381, in __init__
    super(MetaJobTorque, self).__init__(mjob)
TypeError: object.__init__() takes no parameters </pre>

Thanks for your help

Alexis

**Comment by pb-cdunn** [comment]
You have to look into the run-dir for `0-rawreads/prepare_rdb.sh`. Try `0-rawreads/pwatcher.dir/stderr`.

This is typically either an obvious integration problem or a problem with a FASTA input file's precise format.

**Comment by cement-head** [comment]
Were you able to get this running on your cluster with TORQUE as the scheduler?

**Comment by agroppi** [comment]
@cement-head 
It was a long long time ago ...
Finally I was able to run falcon 0.7 on our cluster (centos 7 and slurm as scheduler)
