### ISSUE TITLE
what is overlap_filtering_setting min_cov used for?  what does it mean?

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#459]
is it dangerous to set it to 1?
can it have non-integer values?

**Comment by pb-jchin** [comment]
when the number set to higher, it can reduce the mis-assemblies, however, the "effective" coverage will becomes lower. set to 1 is ok but it does increase mis-assemblies theoretically.  No, non-integer is not allowed.

**Comment by dgordon562** [comment]
thanks, Jason!

**Comment by coreywischmeyer** [comment]
Can we have a better description of min_cov in overlap_filtering_settings?  

As I understand it from documentation, min_cov means minimum corrected reads that participate in a join.

So if I have this situation with min_cov=3 and have 3 reads that overlap like this:

A         -----------------
B----------
C           -------

Would this be collapsed to D?:
D-----------------------

**Comment by pb-jchin** [comment]
@coreywischmeyer , at this stage, we only consider dovetail overlaps.  We only consider the "coverage" on either 5'- or 3'- ends.  I agree that it should be rename to something like `min_ovlp`.

**Comment by coreywischmeyer** [comment]
I think I understand, but to clarify in case other people come by with the same question:

I have a current read, and that read has two other reads that dovetail with it, that's a min_cov of 2 correct?

Do those two reads necessarily align with one another?

**Comment by pb-jchin** [comment]
@coreywischmeyer 
> Do those two reads necessarily align with one another?

IF A -> B , A-> C, then the overlapped part between A.B and A.C should be overlapped but there is B and C may not be fully overlapped as dovetail overlaps.

**Comment by coreywischmeyer** [comment]
Thanks, so when I view the graph in a program like Bandage,  it's possible that I may see a bubble or spur at the point where B and C diverge. 

The final clarification I want to make is that min_cov of 2 involves 3 reads overall, the current read and the two reads that overlap it. 

Thanks for answering my nitpicky questions.

**Comment by pb-jchin** [comment]
@coreywischmeyer , This is a setting for filtering step. The logic is "if a read has only less support on its 5'-end or 3'-end, the read might not be 'reliable'".  Such read is simply removed from consideration.  

> Thanks, so when I view the graph in a program like Bandage,  it's possible that I may see a bubble or spur at the point where B and C diverge. 

if A->B, and A-C, but B and C are not dovetail overlapped, as long as A, B and C are in the final graph, you will see a fork.
