### ISSUE TITLE
Falcon - running example data (e-coli) Need Help!

### ISSUE THREAD

**Issue by MehmetGoktay** [PacificBiosciences/FALCON#460]
Hi eveyone,

I would like to use Falcon in my current project. I fallowed this installation . (https://github.com/PacificBiosciences/FALCON/wiki/Setup:-Complete-example)

I just had to remove --always-copy. form here (virtualenv --no-site-packages  --always-copy   $FC) because it gave me an error. 

After finishing installation I just wanted to run an example data. But looks like still there is a problem. 

I just wanted to try on one computer rather than grid system for the first trial. So I added:
job_type and removed following parameters` values to work on one computer.
job_type=local
sge_option_da =
sge_option_la =
sge_option_pda =
sge_option_pla =
sge_option_fc =
sge_option_cns =

But I keep getting error. I will paste it below. If anyone has any idea how to solve this. Please let me know.

INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_run_ecoli.cfg
[WARNING]HPC.daligner option "-dal" has changed to "-B". Correcting this for you.
[WARNING]HPC.daligner option "-dal" has changed to "-B". Correcting this for you.
[INFO] No target specified, assuming "assembly" as target 
/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/local/lib/python2.7/site-packages/falcon_kit-0.7_git.54779b25532a4e1ace230013fe25f5c51a43ddaa_-py2.7-linux-x86_64.egg/falcon_kit/run_support.py:330: UserWarning: Unexpected keys in input config: set(['jobqueue'])
  warnings.warn("Unexpected keys in input config: %s" %repr(unused))
[INFO]# of tasks in complete graph: 1
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO] Skipping already done task: task:///biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/local/lib/python2.7/site-packages/falcon_kit-0.7_git.54779b25532a4e1ace230013fe25f5c51a43ddaa_-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py/task_make_fofn_abs_raw
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[INFO]# of tasks in complete graph: 2
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO]tick: 2, #updatedTasks: 0, sleep_time=0.100000
[INFO]Running task from function task_build_rdb()
[INFO]script_fn:'/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/ecoli_test/0-rawreads/prepare_rdb.sh'
[INFO]jobid=Jf0f5ae9378437f21a4b046cbd9ce292004c7e391b73136ca08f7f29433bc9318
[INFO]starting job Job(jobid='Jf0f5ae9378437f21a4b046cbd9ce292004c7e391b73136ca08f7f29433bc9318', cmd='/bin/bash prepare_rdb.sh', rundir='/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/ecoli_test/0-rawreads', options={'job_queue': None, 'sge_option': '', 'job_type': None})
[INFO]Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='Jf0f5ae9378437f21a4b046cbd9ce292004c7e391b73136ca08f7f29433bc9318', cmd='/bin/bash prepare_rdb.sh', rundir='/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/ecoli_test/0-rawreads', options={'job_queue': None, 'sge_option': '', 'job_type': None}), lang_exe='/bin/bash'))
[ERROR]Task Fred{'URL': 'task:///biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/local/lib/python2.7/site-packages/falcon_kit-0.7_git.54779b25532a4e1ace230013fe25f5c51a43ddaa_-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py/task_build_rdb'} failed with exit-code=99
[INFO]Queued 'task:///biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/local/lib/python2.7/site-packages/falcon_kit-0.7_git.54779b25532a4e1ace230013fe25f5c51a43ddaa_-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py/task_build_rdb' ...
[INFO]Failure ('fail'). Joining 'task:///biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/local/lib/python2.7/site-packages/falcon_kit-0.7_git.54779b25532a4e1ace230013fe25f5c51a43ddaa_-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py/task_build_rdb'...
[CRITICAL]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/local/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py:537: UserWarning: 
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            "! Please wait for all threads / processes to terminate !"
            "! Also, maybe use 'ps' or 'qstat' to check all threads,!"
            "! processes and/or jobs are terminated cleanly.        !"
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            
  warnings.warn(shutdown_msg)
[WARNING]#tasks=1, #alive=0
Traceback (most recent call last):
  File "/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/bin/fc_run.py", line 5, in <module>
    pkg_resources.run_script('falcon-kit==0.7-git.54779b25532a4e1ace230013fe25f5c51a43ddaa-', 'fc_run.py')
  File "/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.7_git.54779b25532a4e1ace230013fe25f5c51a43ddaa_-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/local/lib/python2.7/site-packages/falcon_kit-0.7_git.54779b25532a4e1ace230013fe25f5c51a43ddaa_-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 576, in main
    main1(argv[0], args.config, args.logger)
  File "/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/local/lib/python2.7/site-packages/falcon_kit-0.7_git.54779b25532a4e1ace230013fe25f5c51a43ddaa_-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 353, in main1
    setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
  File "/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/local/lib/python2.7/site-packages/falcon_kit-0.7_git.54779b25532a4e1ace230013fe25f5c51a43ddaa_-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 410, in run
    wf.refreshTargets([rdb_build_done])
  File "/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/local/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 548, in refreshTargets
    raise Exception('Caused by:\n' + tb)
Exception: Caused by:
Traceback (most recent call last):
  File "/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/local/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/fc_env/local/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 740, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'

**Comment by lijingjing1** [comment]
check the file 0-rawreads/pwatcher.dir/stderr

**Comment by MehmetGoktay** [comment]
I got this error message. 

+ python2.7 -m pwatcher.mains.fs_heartbeat --directory=/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/ecoli_test/0-rawreads --heartbeat-file=/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/ecoli_test/mypwatcher/heartbeats/heartbeat-Jf0f5ae9378437f21a4b046cbd9ce292004c7e391b73136ca08f7f29433bc9318 --exit-file=/biodata/dep_coupland/grp_hancock/MehmetData/FALCON-integrate/ecoli_test/mypwatcher/exits/exit-Jf0f5ae9378437f21a4b046cbd9ce292004c7e391b73136ca08f7f29433bc9318 --rate=10.0 /bin/bash prepare_rdb.sh
/usr/bin/python2.7: No module named pwatcher.mains
+ echo 99

**Comment by pb-cdunn** [comment]
/usr/bin/python2.7: No module named pwatcher.mains

You need to use the same Python on the compute node that you used when you installed **FALCON** and **pypeFLOW**. If you're using **virtualenv**, then you need to "activate" it (`bin/activate`).

We can only offer limited supported on integration problems.
