### ISSUE TITLE
Setup:-Complete-example commands

### ISSUE THREAD

**Issue by tpshea2** [PacificBiosciences/FALCON#461]
Hello-

In following the steps in the [https://github.com/PacificBiosciences/FALCON/wiki/Setup:-Complete-example](url) FALCON wiki I noticed a few potential issues (may be very minor)

Should the line to copy "HPCdaligner " be "HPC.daligner" ?

Also in testing I encountered the following: 

./rj_0005.sub.sh: line 11: LAcheck: command not found

So should LAcheck also be copied over from the DALIGNER area into the fc_env bin?

Thank you.

**Comment by pb-cdunn** [comment]
That is an old wiki. I'd rather delete it. Please look at:
* https://github.com/PacificBiosciences/FALCON-integrate/wiki

**Comment by pb-jchin** [comment]
yes. you might want to check your installation is consistent. The file should be copied during the installation process. And I think if you use the latest code, you can specify `skip_checks` in the configuration file to turn that off.
