### ISSUE TITLE
can we use falcon output without quiver polish if there's high sequencing depth

### ISSUE THREAD

**Issue by JeanQin** [PacificBiosciences/FALCON#462]
I finishes assembly a medium size genome (~500MB). We have smrtanalysis 2.3 but it doesn't work for us (can't handle multiple files to polish assembly). smrtanaysis 3.0 is promised to resolve the issue and hopefully it will be available soon. 

While waiting for 3.0, I wonder if anyone has tested how much improvement that the quiver makes and if high sequencing depth can resolve the errors by itself without quiver to polish since falcon does error correct also and PacBio error is random.  Any thoughts would be greatly appreciated

**Comment by pb-jchin** [comment]
FALCON error correction is aiming on computational speed rather than accuracy.  You will need to run quiver to get the final accuracy high unless you only interested in structural relation genomic information.

**Comment by JeanQin** [comment]
thanks Jason for your quick response. To my understanding, most of pacbio error is indels which are random and should be able to correct by sufficient sequencing depth. We're interested in gene coding prediction. How much will it be impacted without quiver polish? Is there any plan to include polish into falcon workflow so we can have one stop shop. Right now, it has been road block for falcon without smrtanalysis 3.0 available.

**Comment by pb-cdunn** [comment]
The polishing workflow is available externally using Arrow, not Quiver, requiring BAM input. You can use that workflow without the new smrtanalysis-3.2 if you install components using [pitchfork](https://github.com/PacificBiosciences/pitchfork/wiki). However, we cannot offer much support for integration problems, and you would need BAM from a Sequel machine.

**Comment by JeanQin** [comment]
Thanks Chris for your suggestion. Unfortunately our data were from RSII which can't use smrtanalysis-3.2 I believe. We have managed to install quiver and blasr from git outside of smartanalysis suit but blasr produces sam file that needs the tool from smrtanalysis3.0 to convert to bam (can't use samtools) and quiver from outside of smrtanalysis doesn't accept output from the tools from smrtanalysis 2.3 . We're in a big dead end cycle for all data generated from RS II. Any suggestion would be greatly appreciated

**Comment by rhallPB** [comment]
What specifically is the issue with using 2.3? I'm not sure I understand what "can't handle multiple files to polish assembly" refers to. For a 500Mb assembly it should be reasonable straightforward to get quiver correction working. As Jason stated, no matter what the coverage you will need to correct the falcon assembly using quiver to get a reasonable base quality in the final assembly.

**Comment by JeanQin** [comment]
here's description about 2.3 issue https://github.com/PacificBiosciences/pbcore/issues/81

I was told that quiver in smrtanalysis 2.3 can't handle fofn (multiple bam files) and advised to use the quiver on git outside of smrtanalysis.  We did and got stuck  https://github.com/PacificBiosciences/FALCON/issues/462#issuecomment-255621471

**Comment by rhallPB** [comment]
Smrtanalysis can handle quiver correcting a 500Mb genome, at no point do you need bam files. The workflow <baxfile>.fofn -> mapping -> cmp.h5 -> Quiver -> <polished assembly>.fasta can be ran in smrtanalysis 2.3 using the resequencing pipeline and will scale across multiple machines. [https://github.com/PacificBiosciences/GenomicConsensus/blob/master/doc/HowTo.rst#running-a-large-scale-resequencingpolishing-job-in-smrtanalysis-23](url)

**Comment by JeanQin** [comment]
Thanks for your suggestion. I have my genome assembled using falcon, which is not part of smrtsnalysis pipeline. When I used the quiver from smrtanalysis 2.3 to polish the contigs using .fofn for the list of multiple mapped files, it doesn't take it.  According to David, smrtanalysis 2.3 can't support .fofn and only operate on single cmp.h5 file (not multiple bam files) https://github.com/PacificBiosciences/pbcore/issues/81#issuecomment-202162209. smrtanalysis 3.0 is promised to resolve this but it's not available yet

**Comment by rhallPB** [comment]
The input to smrtanalysis 2.3 pipeline is a fofn of the bax data files, and the output is the quiver correct sequence in fasta format, at no point is bam used. You should have no problem correcting a 500Mb genome on a reasonable size compute resource using 2.3 end to end. Davids point was that the quiver algorithm does not accept multiple cmp.h5 files. 
One trick to make things easier is to randomize the order of the contigs in the falcon output, the alignment is split by contigs, if you run on the defult output of falcon (largest contigs first) the first mapping job in smrtanalysis will take much longer than the rest.

**Comment by JeanQin** [comment]
Are you saying that smrtanalysis contains falcon to do de novo assembly and correction by bax raw reads?

**Comment by rhallPB** [comment]
No. Smrtanalysis 2.3 can quiver correct the output of Falcon using the bax files containing raw reads.

**Comment by JeanQin** [comment]
Sorry, are you saying that the quiver inside smrtanalysis can polish falcon output? If so, could you take a look at error I got using the quiver in smrtanalysis 2.3? Any suggestion and help would be greatly appreciated as we have been spent a lot of effort without success!  https://github.com/PacificBiosciences/pbcore/issues/81#issuecomment-202161231
