### ISSUE TITLE
how to set the appropriate config file for larger genome using local mode

### ISSUE THREAD

**Issue by gucascau** [PacificBiosciences/FALCON#466]
I am trying to assemble a large genome(700Mb) using 60X pacbio sequence. Here I used the local server (memory 515G and 70 cores). However, after several jobs of error correction, I always faced with some error like this:

```
[INFO]Failure ('fail'). Joining 'task://localhost/d_000b_raw_reads'...
[INFO]Failure ('fail'). Joining 'task://localhost/d_0008_raw_reads'...
[CRITICAL]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
```

My config file looked like this:

``` ini
[General]
job_type = local

input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads


length_cutoff = 10000

length_cutoff_pr = 10000

sge_option_da =
sge_option_la =
sge_option_pda =
sge_option_pla =
sge_option_fc =
sge_option_cns =


pa_concurrent_jobs = 10
ovlp_concurrent_jobs = 10

pa_HPCdaligner_option =  -v  -B4 -e.70 -l500 -s1000 -M60
ovlp_HPCdaligner_option = -v -B4 -h60 -e.96 -l500 -s1000 -M60

pa_DBsplit_option = -x500 -s700
ovlp_DBsplit_option = -x500 -s700

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6

overlap_filtering_setting = --max_diff 100 --max_cov 500 --min_cov 5 --bestn 10 --n_core 24
```

Can anyone tell me how to adjust the different parameter appropriately ?

And If something wrong with some steps, how can I restart the jobs? Is is OK to restart the jobs after correction of my config file? Thanks

**Comment by pb-cdunn** [comment]
Try to find the failed jobs' directories, and look for `pwatcher.dir/stderr`.

Yes, you can restart with different parameters. (Currently, you need to remove the `mypwatcher` directory first.) But if the changes would lead to completely different job partitioning, then you really need to start over completely. Anyway, you should learn the cause of failure first.

**Comment by pb-jchin** [comment]
```
pa_DBsplit_option = -x500 -s700
ovlp_DBsplit_option = -x500 -s700
```

we never use `-s` more than 400. I am not sure 700 will work.

```
pa_HPCdaligner_option =  -v  -B4 -e.70 -l500 -s1000 -M60
ovlp_HPCdaligner_option = -v -B4 -h60 -e.96 -l500 -s1000 -M60
```

`-M24` should be good for most cases.

**Comment by gucascau** [comment]
Thanks for the help. 

I set the parameter as you suggested (-M24 and -s400). But why did I also face the same problem in the error correction step. 

The following is my parameters:
[General]
job_type = local

# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 10000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 10000

#Cluster queue setting
sge_option_da =
sge_option_la =
sge_option_pda =
sge_option_pla =
sge_option_fc =
sge_option_cns =

#concurrency setting
pa_concurrent_jobs = 10
ovlp_concurrent_jobs = 10

pa_HPCdaligner_option =  -v  -B4 -e.70 -l500 -s1000 -M24
ovlp_HPCdaligner_option = -v -B4 -h60 -e.96 -l500 -s1000 -M24

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6

overlap_filtering_setting = --max_diff 100 --max_cov 500 --min_cov 5 --bestn 10 --n_core 24

**Comment by pb-cdunn** [comment]
Try to find the failed jobs' directories, and look for pwatcher.dir/stderr. The problem could be anything. You have to look at a specific failed job.

**Comment by gucascau** [comment]
Thanks for the reply. I checked the failed job's directories and found that the problem was produced by the "Duplicate overlap"
But we still came across same problems for multiple jobs. 
The setting is following: 
pa_HPCdaligner_option =  -v  -B4 -e.70 -l500 -s1000 -M60
ovlp_HPCdaligner_option = -v -B4 -h60 -e.96 -l500 -s1000 -M60

pa_DBsplit_option = -x500 -s100
ovlp_DBsplit_option = -x500 -s100

Here I download the latest version of FALCON-integrate. Could you please help how to figure out this issue. Thank you so much.

**Comment by pb-cdunn** [comment]
> "Duplicate overlap" ?

In `LAcheck`? If so, you might need to *rebuild* the latest **PacificBiosciences/DALIGNER**. Simply downloading is not enough. If there is still a problem, then submit a bug with **thegenemyers/DALIGNER**. He will want a reproducible test-case that he can download.

**Comment by gucascau** [comment]
Yes, the tricky error is in LAcheck. Thanks for the help.

**Comment by pb-cdunn** [comment]
If you open an issue with thegenemyers, please post that here so we can watch. Also, you should remember to tell Gene precisely which commit of DALIGNER you built, as he will suspect that you are using old, unfixed code.
