### ISSUE TITLE
Variable 'script_fn' referenced before assignment on job_type = local

### ISSUE THREAD

**Issue by norling** [PacificBiosciences/FALCON#47]
I Installed FALCON according to instructions, with the following two changes:

 * Ran `make` before checking out 97b0c27a in DALIGNER to compile DB2Falcon and LA4Falcon
 * Added `job_type = local` to the _e-coli_ test config file.

When running I very quickly run into the following error:

    "fc_env/lib/python2.7/site-packages/falcon_kit-0.2.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 93, in run_script
        fc_run_logger.info( "executing %s locally, start job: %s " % (script_fn, job_name) )
    UnboundLocalError: local variable 'script_fn' referenced before assignment

**Comment by pb-jchin** [comment]
This and the missing "job_name" is addressed in https://github.com/PacificBiosciences/FALCON/commit/58ebe7e7f4632e85a44aaac58ee7bd1778ef3fe4 and https://github.com/PacificBiosciences/FALCON/commit/9f428aa15457614f5c6db21fb4167da8c1bd50a9

Thanks for finding the problem.

**Comment by norling** [comment]
The error is gone!
But sadly - the run breaks after a few minutes (significantly longer than before) with the following error:

    No target specified, assuming "assembly" as target 
    Skipping 'preads_norm', file is empty!
    Exception in thread Thread-379:
    Traceback (most recent call last):
      File "/home/martinn/.pyenv/versions/2.7.6/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/home/martinn/.pyenv/versions/2.7.6/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/home/martinn/temp/FALCON_test2/FALCON/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 317, in __call__
        runFlag = self._getRunFlag()
      File "/home/martinn/temp/FALCON_test2/FALCON/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 147, in _getRunFlag
        runFlag = any( [ f(self.inputDataObjs, self.outputDataObjs, self.parameters) for f in self._compareFunctions] )
      File "/home/martinn/temp/FALCON_test2/FALCON/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 812, in timeStampCompare
        if min(outputDataObjsTS) < max(inputDataObjsTS):
    ValueError: max() arg is an empty sequence

The file `1-preads_ovl/preads_norm.fasta` is empty, and the `0-rawreads/preads/` directory contains 100 files, with the`out.000[01-20].fa` files empty. Any idea what might be causing this?

**Comment by Imoteph** [comment]
I got also the same error message after 3 sec.

file "$PWD/FALCON/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 812, in timeStampCompare
    if min(outputDataObjsTS) < max(inputDataObjsTS):
ValueError: max() arg is an empty sequence

**Comment by pb-jchin** [comment]
This usually means some earlier step was not finished successfully or the job directory has some leftover sentinel files which is not cleaned up even the previous attempt was not working. Try everything with a new directory and take a look for each step to see if the right data is generated for them.


You can check some lengthy trouble shooting for beginner here: 
https://github.com/PacificBiosciences/FALCON/issues/18

Also, this new question is not the same of the issue in the title. I am closing this issue to make sure that we don't mix up things.
