### ISSUE TITLE
Trace assembled and unassembled reads in FALCON

### ISSUE THREAD

**Issue by bostanict** [PacificBiosciences/FALCON#472]
Hi,

I am running some analyses that I need to know which reads were not used in the assembly. Moreover, it is useful for me to know which reads were assembled in which contig.

I know I can use mapping softwares to map back the reads to the assembly using blasr or other tools and see which one is not mapped but I want to know how to recover these info from the FALCON.

I see that there are IDs for each sequence in different files (such as sg_edge_list etc.) but how can I trace it back to the raw reads/subreads or at least corrected preads. 

Cheers,

**Comment by pb-jchin** [comment]
you can run:
```
python -m falcon_kit.mains.get_read_ctg_map
python -m falcon_kit.mains.rr_ctg_track
python -m falcon_kit.mains.pr_ctg_track
mkdir -p 3-unzip/reads/
python -m falcon_kit.mains.fetch_reads
```
There will be `unassigned_reads.fa` file in `3-unzip/reads` for those reads that can not be identified through the `daligner` overlap to a contg.  The `rr_ctg_track` and `pr_ctg_track` may use a lot of memory (10~20G) depending on the size of genome and the amount of data so you might want to make sure if you get one a machine with large RAM available.

**Comment by bostanict** [comment]
Hi json,

thanks for reply.

I have only 2 other questions. 1- for getting the result from these commands, do we need all the folder of falcon to be there or they need a specific file to be completed. If there are some specific files, could you please let me know?

2nd that what is the time expectation for these commands to finalize? I have machine with more than 20 GB ram and quite good I/O. how long should it take normally to finalized? 1 hr? t0 hr? weeks? :)

Thanks alot for the support,

**Comment by pb-jchin** [comment]
> I have only 2 other questions. 1- for getting the result from these commands, do we need all the folder of falcon to be there or they need a specific file to be completed. If there are some specific files, could you please let me know?

it needs all final stage of `.las` files: `0-rawreads/m_*/raw_reads.*.las` and `1-preads_ovl/m_*/preads.*.las` and the `0-rawreads/raw_reads.db` and `1-preads_ovl/preads.db` files.

> 2nd that what is the time expectation for these commands to finalize? I have machine with more than 20 GB ram and quite good I/O. how long should it take normally to finalized? 1 hr? t0 hr? weeks? :)

For human size, data, it takes me about 1 day.  (Low CPU/ IO use for the first two commands a long time as all records have to scan and ranked together at the ends.)

**Comment by bostanict** [comment]
Thanks alot
