### ISSUE TITLE
Insufficient assembly 

### ISSUE THREAD

**Issue by gucascau** [PacificBiosciences/FALCON#476]
Here I used FALCON-integrate to assemble a genome of 600Mb, with around 60X pacbio raw reads. However, I only got 1.6Mb genome. 
There is a large number of sequence lost from stage one to stage two. And the final assembled reads is only 3X reads for assembly. The following is some basic statistics of the reads

The error correction of raw reads step :
      1,911,126 reads        out of      12,003,153  ( 15.9%)
 12,196,405,328 base pairs   out of  35,313,617,494  ( 34.5%) ;
The error correction of preads step:
     501,734 reads        out of         501,734  (100.0%)
  1,300,217,329 base pairs   out of   1,300,217,329  (100.0%)

The following is my config file:
input_type = raw
length_cutoff = 10000
length_cutoff_pr = 10000

pa_concurrent_jobs = 10
ovlp_concurrent_jobs = 10

skip_checks = true ## here I used to avoid the overlap duplicate error 
pa_HPCdaligner_option =  -v  -B4 -e.70 -l500 -s1000 -M60
ovlp_HPCdaligner_option = -v -B4 -h60 -e.96 -l500 -s1000 -M60
pa_DBsplit_option = -x500 -s100
ovlp_DBsplit_option = -x500 -s100

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6
overlap_filtering_setting = --max_diff 100 --max_cov 400 --min_cov 4 --bestn 10 --n_core 24

I set the overlap filtering less stringent (100 max diff, and 400max cov), why still a lot of reads filtered? What parameter should I take into consideration?

**Comment by skingan** [comment]
I am assuming the stats you give at the top are from your dazzler databases of the raw reads and preads. It looks like only 15.9% of your raw reads are longer than 500bp so most of your data are being lost when the raw reads database is created. The length cut off for inclusion in your raw read database is controlled by the -x parameter of the pa_DBsplit_option. But I'm afraid without many long reads, your assembly quality will be poor.

You can reduce your length_cutoff (to, say 1000 or 2000) to include more reads in the initial overlap stage.

**Comment by pb-cdunn** [comment]
And you can find more details in `0-rawreads/report/pre_assembly_stats.json`.
