### ISSUE TITLE
falcon concurrent jobs

### ISSUE THREAD

**Issue by JeanQin** [PacificBiosciences/FALCON#479]
My falcon assembly takes multiple days with most of time on 0-rawreads. I'm looking for suggestion to improve that.  I saw only 8 jobs running concurrently when making 0-rawreads/raw_reads.xx.las files even though there're a lot of unused resources. Is there any setting in the configuration that I can change to increase the number of concurrent jobs for this step?

Below is my configuration 
```ini
sge_option_da = -l h_vmem=125G -pe make 10 -q main.highmem
sge_option_la = -l h_vmem=125G -pe make 5 -q main.highmem
sge_option_pda = -l h_vmem=125G -pe make 10 -q main.highmem
sge_option_pla = -l h_vmem=125G -pe make 5 -q main.highmem
sge_option_fc = -l h_vmem=125G -pe make 24 -q main.highmem
sge_option_cns = -l h_vmem=125G -pe make 10 -q main.highmem

pa_concurrent_jobs = 30
ovlp_concurrent_jobs = 30
```
Thanks so much for your help!

**Comment by rhallPB** [comment]
ovlp_concurrent_jobs sets the number of concurrent daligner jobs sge_option_da sets the submission options for the jobs, by default daligner used 4 threads, is there a reason you request 10? 0-rawreads is by are the most intensive step in the assembly, so it is expected to take by far the most time.

**Comment by JeanQin** [comment]
each of our shared computer nodes ranges from 28 (128G RAM) to 48 (256RAM) CPU. What's the best setting should I request for the both settings you mentioned above?

**Comment by rhallPB** [comment]
There may be a little trial and error to get the maximum use of cpu and memory. For 28 slots on a 128 GB machine each 4 slot job would have ~18Gb of memory, setting -M16 for the `pa_HPCdaligner_option` would be a starting point.

**Comment by JeanQin** [comment]
thanks for your suggestion

**Comment by lamz138138** [comment]
Hi, rhallPB @rhallPB !

I have a related problem, I had used three simulation chromsomes each with 100X coverage (213MB, 47MB and 160MB respectively) and my fc_run.py had running a very long time on 0-rawreads, now it about one months, then it was killed by some reason that I can't figure out. Anyway, It had submit a lot of jobs during the process, then I fell it continue running fc_run.py without submit new jobs (maybe I am wrong here as it still submit according to the log ) , and there are 65636 files in sge_log director. Also, I fell it couldn't take advantage of my SGE, didn't you think it is right for running a such long time with this data, or there are something wrong with my parameters? I had open a issue previously (https://github.com/PacificBiosciences/FALCON/issues/435), hope you can give me some suggestion at that issue.

Any suggestion would be grateful!

**Comment by rhallPB** [comment]
What are the compute resources being used? That size assembly shouldn't take more than a couple of days at the most, on reasonable compute.

**Comment by lamz138138** [comment]
Hi!

There are three node in SGE, one has 32 cpus and two have 64 cpus, and all have 512G memory. I think I can submit 20 concurrent jobs ((64+64+32)/8), so I change following parameters, did you think is it suitable? I am running with -s 100 now, wishes it would be OK.

```
pa_concurrent_jobs = 20
ovlp_concurrent_jobs = 20
```

**Comment by lijingjing1** [comment]
you can running 40 current jobs ,for each job 4 cpus,and the memory is enough.

**Comment by lamz138138** [comment]
Hi, jingjing!

Thanks for your reply, and it help me to understand what pb-cdunn told me in  #435, and  I learn more about SGE!

Best wishes!
