### ISSUE TITLE
Meaning of columns from fc_ovlp_stats.py 

### ISSUE THREAD

**Issue by ebioman** [PacificBiosciences/FALCON#48]
Hello
I wanted to estimate the best coverage for the overlap filtering but am a little
bit confused of the output.

If I execute it <code> fc_ovlp_stats.py --n_core 20 --fofn las.fofn </code> I obtain the following.

    None 13329 1 0     
    000000000 13329 8 8    
    000000002 10096 2 0    
    000000003 11647 5 7    
    000000004 14689 2 1    
    000000005 13854 0 1    

Could you please explain what each column means ?
Thanks

**Comment by pb-jchin** [comment]
The first line is a bug needed to be cleaned up. The columns are "read_identifer length 5'-overlap_count 3'-overlap count'. Only dovetail overlaps are counted. (I prefer to call "dovetail overlap" as "proper overlap" though. Those are overlaps with overhangs as detected by the overlapper.)   I typically do a quick histogram of column 3 or 4 to figure out the coverage filtering parameter to use.  The 2D x-y scatter plot of column 3 or 4 also give some interesting about the genome repeat structures.

**Comment by ebioman** [comment]
Thx
