### ISSUE TITLE
getting new falcon to run with ecoli

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#485]
embarrassing that I can't get this running

OK, I've gotten synth0 running successfully

Here are the symptoms with ecoli:  the prepare_rdb job runs and the fasta2DB does not create the 
holy trinity (.raw_reads.bps, .raw_reads.idx, and raw_reads.db).  Then HPC.daligner runs forever without creating any run_jobs.sh

If I try to run the commands fasta2DB, DBsplit, and HPC.daligner from the command line, the first 2 work fine but then HPC.daligner freaks out and runs forever making run_jobs.sh bigger and bigger (until I kill it and run_jobs.sh is 100+ GB !)

Obviously it is me--not Falcon.  But what?  The question is how to go about debugging this.   Some ideas:  
1)  submit prepare_rdb.sh to the cluster myself instead of under fc_run.py  
2) run prepare_rdb.sh interactively
3) submit *part* of prepare_rdb.sh to the cluster
other ideas?

**Comment by pb-cdunn** [comment]
Weird! Is this with our ecoli data? I would love to reproduce the HPC.daligner problem.

I would definitely try to solve this first on your local machine, rather than on the cluster. Yes, I would individual commands from the command-line.

Are you running the latest FALCON-integrate/1.8.2? That seems to work pretty well.
* https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation

The latest **FALCON-examples** pulls E.coli from the PacBio cloud, compressed with `dexta` from Gene's **DEXTRACTOR**. Are you using that? If so, then you need to update **FALCON** too, and install everything with **FALCON-make** so you have **DEXTRACTOR**. Those are all submodules of **FALCON-integrate**.

**Comment by dgordon562** [comment]
Hi, Chris,

With your great help, I now have 1.8.2 installed and running.  But I am observing the same behavior:

HPC.daligner runs and runs and runs...  run_jobs.sh was 40GB now it is ... 54GB.   It has completed (thank God) the daligner lines of which there are 24 million (!) and now writing the sort/merge commands.

This is to assemble ecoli.  My dataset has 105,451 reads.

The block size is:
> grep block raw_reads.db 
blocks =     13935

The HPC.daligner arguments are:
HPC.daligner -v -B4 -t50 -h1 -e.99 -w1 -l1 -s1000 -H30109 raw_reads 1-13935

It must be something with my parameters:
use_tmpdir = True
job_type = sge
job_queue = eichler-short.q
input_fofn = input.fofn
input_type = raw
length_cutoff_pr = 1
genome_size = 1000000
seed_coverage = 20
pa_concurrent_jobs = 120
cns_concurrent_jobs = 110
ovlp_concurrent_jobs = 120
pa_HPCdaligner_option =   -v -B4 -t50 -h1 -e.99 -w1 -l1 -s1000
ovlp_HPCdaligner_option = -v -B4 -t50 -h1 -e.99 -l1 -s1000
pa_DBsplit_option =   -a -x5 -s.065536
ovlp_DBsplit_option = -a -x5 -s50
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 1 --max_n_read 20000 --n_core 0
overlap_filtering_setting = --max_diff 10000 --max_cov 100000 --min_cov 1 --min_len 1 --bestn 1000 --n_core 0

Anything jump out at you?  Anything you can think of that I should try?

Thanks!
David

**Comment by pb-cdunn** [comment]
Haha! You coped that from `run/synth0`. `-s.065536` is designed to split a tiny test-case into a large number of jobs for testing job-distribution.

Look at `run/ecoli*/*.cfg`

Question: When you kill this, do all the running jobs die? I hope so. It's a bug if not.

**Comment by dgordon562** [comment]
So true!  Thanks!
Regarding your question, I don't think all the jobs die.  I did notice a leftover job from *some* previous run.  I'm closing this because it is embarrassing (grin).
