### ISSUE TITLE
extracting subreads used for constructing preads

### ISSUE THREAD

**Issue by sjin09** [PacificBiosciences/FALCON#486]
Dear @pb-jchin and @rhallPB 

I had success with the BAC de novo assembly as you have recommended. Thank you so much for the previous help.

I wanted to inquire about whether it is possible track the subreads used for pread construction. We performed whole genome sequencing of a male individual using the SMRT platform. We wanted to extract Y-specific reads from this whole genome sequence using female-specific kmers from a whole genome sequence of a female with Illumina platform. In brief, we obtained the female-specific kmers and tried to identify subreads/preads that were not covered by these female-specific kmers. 

We were able to segregate preads that were not covered by female-specific kmers. However, we were not able to perform the same analysis with the subreads probably due to the error rate. 

Do you have any recommendations towards extracting Y-specific subreasds?

Best,
Jin

**Comment by rhallPB** [comment]
This mapping is calculated in the first step of FALCON-unzip, but the code is in FALCON [https://github.com/PacificBiosciences/FALCON/blob/478ec3f783936cace8f32716a0fe722a3673116b/falcon_kit/mains/get_read_ctg_map.py](https://github.com/PacificBiosciences/FALCON/blob/478ec3f783936cace8f32716a0fe722a3673116b/falcon_kit/mains/get_read_ctg_map.py)
