### ISSUE TITLE
AssertionError: Non-unique basename in ...

### ISSUE THREAD

**Issue by msc51** [PacificBiosciences/FALCON#487]
Hi @pb-jchin and @rhallPB,

I am at Stage-0 where Falcon is merging the *.las files. Falcon created a lot of empty "0-rawreads/m_00xxx" folders. And I am getting an error:

File "/labs/dragon/biocore/BIX/resources/software/FALCON-integrate/FALCON/falcon_kit/ut
il/system.py", line 19, in only_these_symlinks
    assert len(base2rel) == len(bases), 'Non-unique basename in {}'.format(repr(paths))
AssertionError: Non-unique basename in ['/path/to/0-rawreads/job_0067/L1.347.354.
las', ...]

Can you give me some advices on how to get over this problem? 

Thanks a lot!

**Comment by pb-cdunn** [comment]
Is this on the latest code?

**Comment by msc51** [comment]
no, I downloaded and installed it early Sep 2016. (btw, how can I check the version of my installed Falcon?)

would you suggest upgrading to the latest version? 
and after upgrade, do I need to start running Falcon from scratch? or can I re-use some of the finished 0-rawreads/jobs_xxxx results? 

thanks!!!

**Comment by pb-cdunn** [comment]
Via GitHub, this code is meant to be run from a FALCON-integrate tree of git submodules, not a system installation. That allows frequent updates and bi-directional code-sharing. It also guarantees a consistent "contour" of versions in all sub-modules. Keeping track of individual versions is not practical for us.

Yes, I recommend upgrading. However, the latest version uses slightly different directories (to solve a specific problem, not just for fun), so I am afraid you might have to start from scratch after that.

**Comment by msc51** [comment]
Thank you @pb-cdunn ! 

I have already upgraded and am ready to start over from scratch again. But I still have a follow up question on re-starting an interrupted run. Just for my own understanding. 

The application kills all the running and pending jobs when I send a Ctrl-C to interrupt the process. So it dies in the middle of generating *.las files in step 1 (inside 0-rawreads). When I re-run Falcon again in the same location (after deleting the "mypwatcher" directory), will Falcon/Daligner pick up from the point when it was interrupted and continue from there?

**Comment by pb-cdunn** [comment]
Each unfinished job will be completely re-run. No single job picks up in the middle. But finished jobs will not be re-run.

Good luck!
