### ISSUE TITLE
Number of concurrent jobs fixed to 24

### ISSUE THREAD

**Issue by graciazhang** [PacificBiosciences/FALCON#488]
I am running FALCON-integrate v1.7.7. It works fine but the number of concurrent jobs was always 24 no matter how I set them in the cfg file. I tried on several different genomes and datasets. Any idea what I may have set wrong?

For example, 
cns_concurrent_jobs = 72
pa_concurrent_jobs = 72
ovlp_concurrent_jobs = 72

Thanks,
Yun Zhang
Dupont Pioneer

**Comment by pb-cdunn** [comment]
Might have been a mistake in that version. Things have changed so much in 1.8.+ that I'm not sure. Can you use the latest FALCON-integrate?

**Comment by graciazhang** [comment]
Thanks, I will try the latest version then.

**Comment by pb-cdunn** [comment]
Thanks. Please re-open if you see this problem there. (Try to follow the FALCON-integrate wiki for installation.)
