### ISSUE TITLE
Raw read alignment LAsort intermediate files

### ISSUE THREAD

**Issue by msc51** [PacificBiosciences/FALCON#489]
Dear Falcon developers, 

In the raw read alignment step, the last two lines in job_xxxx/rj_xxxx.sub.sh remove .las files that has one single digit after C or N:
rm -f *.C?.las *.C?.S.las
rm -f *.N?.las *.N?.S.las

I have just updated to the latest Falcon last week, and I noticed that now there are .las files with two digits after C or N (e.g. raw_reads.1.raw_reads.47.N21.las, raw_reads.1.raw_reads.47.N21.S.las). So the rm lines mentioned above won't remove these. 

Is this intended??? If not, is it safe to manually remove all raw_reads.*.las files after the sentinel file job_xxxx_done is created? 

Thanks!!

**Comment by pb-cdunn** [comment]
Not intended. No, it is not safe to remove all `raw_reads.*.las`, although in your case it would be fine. The problem comes when the there is no level-1 merging because there are so few reads.

I will push a quick fix.

**Comment by msc51** [comment]
With the same input dataset, it wasn't a problem until I updated to the latest version of Falcon-integrate. I think level-1 merging did happen, as there are L1.xx.xx.las files in the job_xxxx folder. Jobs were finished with no explicit error and job_xxxx_done files were also created. raw_reads.*.las files with only one single digit after C or N did get removed, only those with 2 digits following C or N remained. In the pwatcher.dir/stdout, there are lines like this:
"In file ./raw_reads.71.raw_reads.71.N56.S.las, there are 241597 records"
Is it really a problem of having not enough reads?? 

Now I have many of these intermediate raw_reads.*.las files in each job_xxxx folder. Is that an indication something is seriously wrong? Or shall I let Falcon continue?

**Comment by pb-cdunn** [comment]
Oh, wait a minute. With 4 threads per comparison, there should only be `(0...3)` matching `?`. This might be Gene's latest DALIGNER instead of the one in FALCON-integrate. Or maybe you've somehow set a larger number of threads, using `-T` option for `HPC.daligner`.

I hope you can track this down. I haven't seen this before. Please let us know what you learn.

**Comment by msc51** [comment]
I am using -T64 in my pa_HPCdaligner_option. 

I will report back once I have a better understanding on the issue. Right now, I'd like to wait until all the jobs finished properly with the job_xxxx_done sentinel files. Since all the L1.xx.xx.las files in my job folders seem to be valid, I am guessing those with two digits following C and N just didnt get removed as they should be...

**Comment by pb-cdunn** [comment]
> I am using -T64 in my pa_HPCdaligner_option.

Oh! Then yes, you have two digits. The change I pushed to `master` should work for you.
