### ISSUE TITLE
More details about length_cutoff?

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/FALCON#49]
Dear Dr. Chin,

When I am playing with different `length_cutoff` settings, I found that it doesn't seem to be a direct threshold for output. For example, in `0-rawreads/preads/out.00001.fa` (I assume these are error-corrected reads) of the E. Coli example, many reads are shorter than 10,000 bp even though I set `length_cutoff=12000`.

Could you please share some details about how it works?

Thank you very much!

Best,
Yunfei

**Comment by mseetin** [comment]
Prior to error correction, it may be difficult to dovetail some raw reads in to longer preassembled reads.  Sometimes a handful will overlap with each other forming an isolated set that only has a consensus overlapping region covered by a part of the length of each.  They may be isolated for a good reason: perhaps they are noisy reads or reads from a contaminant that aren't good to include.  On the other hand, maybe they were noisy but correctable and could be an important part of the assembly.  You can set the second cutoff shorter than the first cutoff to include these reads in the final assembly or elect to exclude them if you're seeing misassembly.  Rerunning the job using preassembled reads is pretty fast, so you can experiment with the size of the second cutoff to see how including more preassembled reads vs. excluding more dubious preassembled reads affects your assembly.  The ideal choice may depend on each library.

**Comment by yunfeiguo** [comment]
Thanks for help!

While I understand that some reads should be excluded from assembly and I can adjust 2nd cutoff to achieve better assembly quality, I still feel puzzled about why the cutoff isn't a direct filter for read lengths. If it is, how can I find out how many reads are filtered out?

**Comment by pb-jchin** [comment]
@yunfeiguo  the 2nd cutoff exists because if, for any reason, you like to have different cutoff for error corrected read, you can just change that, delete all p-read overlapping data (or move them to different place), and you can restart the assembly from middle without repeat the computational intensive step.  

For lager genome with unknown repeat structure, there is NO simple theory how to choose optimized cutoff. (Who is interested in working out one? let me know...)  Give some flexibility there helps to do some some quick experiment to improve the assembly while the repeat structure can be understood more from the initial overlapping data.

**Comment by yunfeiguo** [comment]
Thank you for your reply!

Now I know I can try different `length_cutoff_pr`(the 2nd cutoff), and it's indeed very fast. However, I still don't know exactly how it works.

Back to the example in my initial posting. In `0-rawreads/preads/out.00001.fa` (I assume these are error-corrected reads) of the E. Coli example, many reads are shorter than 10,000 bp even though I set `length_cutoff=12000` (the first cutoff). Why is it the case?

I tried to read through the code of `daligner.c` and `LA4Falcon.c` where the `length_cutoff` is applied and found that it seems only A-read is filtered by the cutoff. I am not sure if my understanding is correct here.

**Comment by pb-jchin** [comment]
It is described in the original paper. If a read has weak support in the middle, it gets broken. The error corrected reads can be shorter than the pre-specified length cutoff. The relevant files are `fc_consensus.py` and `falcon.c`.

**Comment by yunfeiguo** [comment]
I see. Thank you very much!

On Apr 20, 2015, at 6:12 PM, Jason Chin <notifications@github.com> wrote:

It is described in the original paper. If a read has weak support in the middle, it gets broken. The error corrected reads can be shorter than the pre-specified length cutoff. The relevant files are fc_consensus.py and falcon.c.

**Comment by pb-cdunn** [comment]
@yunfeiguo,

Congratulations on the *Nature* paper!

**Comment by yunfeiguo** [comment]
@pb-cdunn , @pb-jchin 

Thanks for helping us! I really learned a great deal from our conversations.

p.s. it is actually published in Nature Communications.
