### ISSUE TITLE
FALCON 0.3.0 and FALCON 0.5.0 ASSEMBLY STATISTICS DIFFERENCE

### ISSUE THREAD

**Issue by sjin09** [PacificBiosciences/FALCON#491]
Dear @rhallPB 

We have previously performed the whole genome assembly of a male human individual using the P6C4 chemistry with 101X coverage. We saw dramatic improvements in the assembly statistics with change from FALCON 0.2.0 to FALCON 0.3.0 (contig N50 almost tripled from 7.50Mb to 17.9Mb). 

We were wondering whether the current FALCON-integrate has further such improvements to improve the contiguity of the assembly. In addition, we were wondering whether the results from FALCON 0.3.0 is compatible with FALCON_UNZIP as the directory output structure seems to have slightly changed with FALCON 0.5.0. 

Best,
Jin

**Comment by pb-cdunn** [comment]
> We were wondering whether the current FALCON-integrate has further such improvements to improve the contiguity of the assembly.

There are bug-fixes which could make a difference in some cases.

> In addition, we were wondering whether the results from FALCON 0.3.0 is compatible with FALCON_UNZIP as the directory output structure seems to have slightly changed with FALCON 0.5.0.

We release Falcon along with its Python dependencies as **FALCON-integrate**:
* https://github.com/PacificBiosciences/FALCON-integrate/releases

The most recent version of Falcon uses a modified workflow engine which requires all tasks to run in their own unique directories. So in general it will require you to re-run Falcon when data were generated from older versions, unfortunately.
