### ISSUE TITLE
Does FALCON deal with PacBio Sequel data?

### ISSUE THREAD

**Issue by gengyuncong** [PacificBiosciences/FALCON#495]
Hi FALCON group,
I sequenced an animal with both PacBio RS II and PacBio Sequel. I wonder if I can use all data produced by RS II and Sequel to assemble the genome?
Another problem is that FALCON doesn't polish the sequences, so I should use Quiver to polish the RS II data and use Arrow to polish Sequel data. However, the assembled contigs must be a combination of RS II reads and Sequel reads, which is difficult to polish. Do you have any suggestions?
Thank you for your time!
Yuncong Geng

**Comment by pb-cdunn** [comment]
I don't have any experience with mixing RSII and Sequel inputs. If you convert everything to FASTA, then Falcon will work fine. But polishing could be difficult.

Even with only Sequel data, the steps are tricky. We provide a full software suite to Sequel customers, but that is supported through official channels, not through this open-source repo.

If you cannot use the official channel, you *could* try **pitchfork** and look at the **FALCON-polish** package. I use that regularly, but we cannot provide support for that.
