### ISSUE TITLE
How Does FALCON Make Use of DAMASKER

### ISSUE THREAD

**Issue by malonge** [PacificBiosciences/FALCON#498]
I have been using the FALCON assembler for a highly repetitive plant genome. The results are pretty good, but like other assemblies I have created, I believe the repetitive nature of the genome is complicating the assembly graph. I wanted to try manually incorporating repeat masking tracks for the reads database using DAMASKER, and wanted to know if this is already incorporated into the FALCON pipeline. I notice the DAMASKER module is included in the FALCON-integrate package, but I have never copied any of its executables into my virtual environment, and FALCON has never failed as a result. I don't seem to remember seeing any interval tracks produced by DAMASKER in with the raw reads database.

Thank you

**Comment by pb-cdunn** [comment]
Yes, we are investigating that. Unfortunately, there is nothing set up for it yet, and it will definitely require tweaking, as it's very sensitive to parameters.
