### ISSUE TITLE
falcon_overlap on large datasets

### ISSUE THREAD

**Issue by esolares** [PacificBiosciences/FALCON#5]
Hi,

I have a 9.4GB preads fasta file. I have tried running the following paramaters:
--d_core 3 --n_core <int> --min_len 8500 preads.fa > preads.ovl

Where --n_core was set at 64, 32, 24, 20 and all failed with memory error: MemoryError: out of memory

I have tried running it on 16 cores but after a few days, the processes just stay idle with high memory usage for 72hours. Have you guys experienced this?  I am able to successfully execute falcon_overlap and much smaller data sets but not this current one.

I am running this on a centos 6 box with 512GB RAM and 64 cores. the files are stored on nfs ssd raid array.

Thank you,

Edwin

**Comment by zine-el-aabidine** [comment]
Hi,
I'm trying to use Falcon (not in cluster) in local. I set the job_type to local an i comment the sge options. I get this error "ConfigParser.NoOptionError: No option 'sge_option_da' in section: 'General'".

 Do you know what's the problem with my installation!!

Thank you

**Comment by zine-el-aabidine** [comment]
I uncomment sgeotions, and now i have this message " No target specified, assuming "assembly" as target"

Than you
