### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by Imoteph** [PacificBiosciences/FALCON#50]
Hi, 
I was wondering if there is any kind of debug mode? 
Currently I have a run, where I do not get any error-messages but the 2-asm-falcon folder has just dummy files (empty files). I like to try find out, where exactly the run fails. but have no clue where to start.
SGE is not the problem, as I tried it locally mode and I got the same result.
Maybe someone could write how to analyze such situation?  

I first tried FALCON with the ecoli-set and it looks like it finished without any problems. (if this correct that fc_ovlp_to_graph.log should be empty)

**Comment by pb-jchin** [comment]
The most likely thing is the coverage filter is too stringent for your data.  Please see if you can use fc_over_stats.py (https://github.com/PacificBiosciences/FALCON/issues/48) to check out the coverage and the overlap filter section in https://github.com/PacificBiosciences/FALCON/blob/master/doc/falcon_manual.md#overlap-filtering

**Comment by Imoteph** [comment]
Thx for the advise. I will change the parameters and notify if this was the solution!

**Comment by Imoteph** [comment]
Thx a lot!
that helped. I got one step further. Now I have to play a bit with the parameters to achieve a better assembly.

**Comment by pb-jchin** [comment]
If you have lower initial coverage, you might want to use shorter seed length cut. For example, with 80x+ recent human data,  I can use 17kb as cutoff. When I down-sample to assemble 30x, I use 4kb. What really matter is the set of reads which are not contained with each other and cover the whole genome (and hopefully span most of repeats).  In high coverage situation, you only need those very long reads. In low coverage situation, you need to make sure you still cover the whole genome after error correction.

**Comment by dibyendukumar** [comment]
The link mentioned above is not working :(
https://github.com/PacificBiosciences/FALCON/blob/master/doc/falcon_manual.md#overlap-filtering

**Comment by pb-jchin** [comment]
the doc is on wiki now.. https://github.com/PacificBiosciences/FALCON/wiki/Manual
