### ISSUE TITLE
input.fofn effect

### ISSUE THREAD

**Issue by gucascau** [PacificBiosciences/FALCON#500]
I tried to run FALCON using 60 subreads fasta files within 20 single cell. I just wonder:  is there some difference?  if I combined all the 60 subreads files into one fasta files, integrated each subreads according to each single cell, or I used the separated file each line into the Input.fofn instead? Because my data showed a lot of overlap problem to run FALCON.

**Comment by pb-cdunn** [comment]
60 files? Each with a unique zmw number? That should be fine. If you combine them, you will need to use the `-a` flag on DBsplit; otherwise, you would get only one of those.

Google Gene Myers DAZZ_DB. You can use `DBshow` to see what actually ends up in the dazzler-db.

**Comment by gucascau** [comment]
Yes, thank you so much for the help
