### ISSUE TITLE
Re-running FALCON for unsatisfied jobs

### ISSUE THREAD

**Issue by sjin09** [PacificBiosciences/FALCON#501]
Following the issue (https://github.com/PacificBiosciences/FALCON-integrate/issues/103#issuecomment-267886750), I have restarted 11 unsatisfied jobs by running rj*.sh manually.

I have commented all the lines where LAcheck happens as recommended and the jobs completes without any errors. Thereafter, I tried to restart the FALCON by fc_run.py fc_run.cfg. However, the same jobs still seems to be unsatisfied. I have been successful in satisfying the jobs previously with manual run of the rj*.sh scripts. 

What is the method with which to assure that FALCON knows that job has been completed successfully? 

Best
Jin
```

nohup: ignoring input
[INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_run.cfg
[WARNING]HPC.daligner option "-dal" has changed to "-B". Correcting this for you.
[WARNING]HPC.daligner option "-dal" has changed to "-B". Correcting this for you.
[INFO] No target specified, assuming "assembly" as target 
[WARNING]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
[INFO]job_type='SGE', job_queue='pac.q', sge_option='-pe peXMAS 8 -q pac.q'
[INFO]Num unsatisfied: 0, graph: 1
[INFO]Num unsatisfied: 0, graph: 2
[INFO]Num unsatisfied: 0, graph: 3
[INFO]Num unsatisfied: 11, graph: 1604
[INFO]About to submit: Node(0-rawreads/job_0252)
[INFO]About to submit: Node(0-rawreads/job_02fc)
[INFO]About to submit: Node(0-rawreads/job_00b9)
[INFO]About to submit: Node(0-rawreads/job_019e)
[INFO]About to submit: Node(0-rawreads/job_0523)
[INFO]About to submit: Node(0-rawreads/job_062e)
[INFO]About to submit: Node(0-rawreads/job_02b3)
[INFO]About to submit: Node(0-rawreads/job_0104)
[INFO]About to submit: Node(0-rawreads/job_028b)
[INFO]About to submit: Node(0-rawreads/job_02f9)
[INFO]starting job Job(jobid='P92f9a55e3d05b3', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_028b', options={'job_queue': 'pac.q',
[INFO]!qsub -N P92f9a55e3d05b3 -q pac.q -pe peXMAS 8 -V -cwd -o stdout -e stderr -S /bin/bash /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/mypwatcher/wrappers/run-P92f9a55e3d05b3
Your job 3959679 ("P92f9a55e3d05b3") has been submitted
[INFO]Submitted backgroundjob=MetaJobSge(MetaJob(job=Job(jobid='P92f9a55e3d05b3', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_028
[INFO]starting job Job(jobid='P7203f967cffc7f', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_02b3', options={'job_queue': 'pac.q',
[INFO]!qsub -N P7203f967cffc7f -q pac.q -pe peXMAS 8 -V -cwd -o stdout -e stderr -S /bin/bash /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/mypwatcher/wrappers/run-P7203f967cffc7f
Your job 3959680 ("P7203f967cffc7f") has been submitted
[INFO]Submitted backgroundjob=MetaJobSge(MetaJob(job=Job(jobid='P7203f967cffc7f', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_02b
[INFO]starting job Job(jobid='P87e0c3a004a9f7', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_0252', options={'job_queue': 'pac.q',
[INFO]!qsub -N P87e0c3a004a9f7 -q pac.q -pe peXMAS 8 -V -cwd -o stdout -e stderr -S /bin/bash /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/mypwatcher/wrappers/run-P87e0c3a004a9f7
Your job 3959681 ("P87e0c3a004a9f7") has been submitted
[INFO]Submitted backgroundjob=MetaJobSge(MetaJob(job=Job(jobid='P87e0c3a004a9f7', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_025
[INFO]starting job Job(jobid='Peb4eeeeb6eac96', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_062e', options={'job_queue': 'pac.q',
[INFO]!qsub -N Peb4eeeeb6eac96 -q pac.q -pe peXMAS 8 -V -cwd -o stdout -e stderr -S /bin/bash /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/mypwatcher/wrappers/run-Peb4eeeeb6eac96
Your job 3959682 ("Peb4eeeeb6eac96") has been submitted
[INFO]Submitted backgroundjob=MetaJobSge(MetaJob(job=Job(jobid='Peb4eeeeb6eac96', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_062
[INFO]starting job Job(jobid='P269e7a36ba2943', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_02fc', options={'job_queue': 'pac.q',
[INFO]!qsub -N P269e7a36ba2943 -q pac.q -pe peXMAS 8 -V -cwd -o stdout -e stderr -S /bin/bash /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/mypwatcher/wrappers/run-P269e7a36ba2943
Your job 3959683 ("P269e7a36ba2943") has been submitted
[INFO]Submitted backgroundjob=MetaJobSge(MetaJob(job=Job(jobid='P269e7a36ba2943', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_02f
[INFO]starting job Job(jobid='P4e20369184a431', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_02f9', options={'job_queue': 'pac.q',
[INFO]!qsub -N P4e20369184a431 -q pac.q -pe peXMAS 8 -V -cwd -o stdout -e stderr -S /bin/bash /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/mypwatcher/wrappers/run-P4e20369184a431
Your job 3959684 ("P4e20369184a431") has been submitted
[INFO]Submitted backgroundjob=MetaJobSge(MetaJob(job=Job(jobid='P4e20369184a431', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_02f
[INFO]starting job Job(jobid='P8eb4b45de346f6', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_0523', options={'job_queue': 'pac.q',
[INFO]!qsub -N P8eb4b45de346f6 -q pac.q -pe peXMAS 8 -V -cwd -o stdout -e stderr -S /bin/bash /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/mypwatcher/wrappers/run-P8eb4b45de346f6
Your job 3959685 ("P8eb4b45de346f6") has been submitted
[INFO]Submitted backgroundjob=MetaJobSge(MetaJob(job=Job(jobid='P8eb4b45de346f6', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_052
[INFO]starting job Job(jobid='P82d61ac77781d4', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_00b9', options={'job_queue': 'pac.q',
[INFO]!qsub -N P82d61ac77781d4 -q pac.q -pe peXMAS 8 -V -cwd -o stdout -e stderr -S /bin/bash /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/mypwatcher/wrappers/run-P82d61ac77781d4
Your job 3959686 ("P82d61ac77781d4") has been submitted
[INFO]Submitted backgroundjob=MetaJobSge(MetaJob(job=Job(jobid='P82d61ac77781d4', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_00b
[INFO]starting job Job(jobid='P39f11d7a75c100', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_019e', options={'job_queue': 'pac.q',
[INFO]!qsub -N P39f11d7a75c100 -q pac.q -pe peXMAS 8 -V -cwd -o stdout -e stderr -S /bin/bash /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/mypwatcher/wrappers/run-P39f11d7a75c100
Your job 3959687 ("P39f11d7a75c100") has been submitted
[INFO]Submitted backgroundjob=MetaJobSge(MetaJob(job=Job(jobid='P39f11d7a75c100', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_019
[INFO]starting job Job(jobid='Pcd8a5a3607c32f', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_0104', options={'job_queue': 'pac.q',
[INFO]!qsub -N Pcd8a5a3607c32f -q pac.q -pe peXMAS 8 -V -cwd -o stdout -e stderr -S /bin/bash /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/mypwatcher/wrappers/run-Pcd8a5a3607c32f
Your job 3959688 ("Pcd8a5a3607c32f") has been submitted
[INFO]Submitted backgroundjob=MetaJobSge(MetaJob(job=Job(jobid='Pcd8a5a3607c32f', cmd='/bin/bash run.sh', rundir=u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_010
[ERROR]Task Node(0-rawreads/job_028b) failed with exit-code=256
[ERROR]Task Node(0-rawreads/job_02b3) failed with exit-code=256
[ERROR]Task Node(0-rawreads/job_02fc) failed with exit-code=256
[ERROR]Task Node(0-rawreads/job_062e) failed with exit-code=256
[ERROR]Task Node(0-rawreads/job_0252) failed with exit-code=256
[ERROR]Task Node(0-rawreads/job_02f9) failed with exit-code=256
[ERROR]Task Node(0-rawreads/job_0523) failed with exit-code=256
[ERROR]Task Node(0-rawreads/job_00b9) failed with exit-code=256
[ERROR]Task Node(0-rawreads/job_0104) failed with exit-code=256
[ERROR]Task Node(0-rawreads/job_019e) failed with exit-code=256
[INFO]recently_satisfied: set([])
[INFO]Num satisfied in this iteration: 0
[INFO]Num still unsatisfied: 11
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads/job_028b), Node(0-rawreads/job_0252), Node(0-rawreads/job_0523), Node(0-rawreads/job_019e), Node(0-rawreads/job_062e), Node(0-rawreads/job_00b9), Node(0-
[ERROR]ready: set([])
submitted: set([])
[INFO]!qdel -k P92f9a55e3d05b3
The job -k of user(s) sjinlee does not exist
sjinlee has deleted job 3959679
[INFO]!qdel -k P7203f967cffc7f
The job -k of user(s) sjinlee does not exist
sjinlee has deleted job 3959680
[INFO]!qdel -k P87e0c3a004a9f7
The job -k of user(s) sjinlee does not exist
sjinlee has deleted job 3959681
[INFO]!qdel -k Peb4eeeeb6eac96
The job -k of user(s) sjinlee does not exist
sjinlee has deleted job 3959682
[INFO]!qdel -k P269e7a36ba2943
The job -k of user(s) sjinlee does not exist
sjinlee has deleted job 3959683
[INFO]!qdel -k P4e20369184a431
The job -k of user(s) sjinlee does not exist
sjinlee has deleted job 3959684
[INFO]!qdel -k P8eb4b45de346f6
The job -k of user(s) sjinlee does not exist
sjinlee has deleted job 3959685
[INFO]!qdel -k P82d61ac77781d4
The job -k of user(s) sjinlee does not exist
sjinlee has deleted job 3959686
[INFO]!qdel -k P39f11d7a75c100
The job -k of user(s) sjinlee does not exist
sjinlee has deleted job 3959687
[INFO]!qdel -k Pcd8a5a3607c32f
The job -k of user(s) sjinlee does not exist
sjinlee has deleted job 3959688
Traceback (most recent call last):
  File "/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 454, in main
    main1(argv[0], args.config, args.logger)
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 131, in main1
    input_fofn_plf=input_fofn_plf,
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 229, in run
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 210, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 282, in _refreshTargets
    failures, len(unsatg)))
Exception: We had 10 failures. 11 tasks remain unsatisfied.


```

**Comment by sjin09** [comment]
I have attached head and tail for the log from the job_0252, which was unsatisfied, as an example.

nohup: ignoring input

db_dir=/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads
+ db_dir=/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads
ln -sf ${db_dir}/.raw_reads.bps .
+ ln -sf /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/.raw_reads.bps .
ln -sf ${db_dir}/.raw_reads.idx .
+ ln -sf /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/.raw_reads.idx .
ln -sf ${db_dir}/raw_reads.db .
+ ln -sf /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/raw_reads.db .
ln -sf ${db_dir}/.raw_reads.dust.anno .
+ ln -sf /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/.raw_reads.dust.anno .
ln -sf ${db_dir}/.raw_reads.dust.data .
+ ln -sf /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/.raw_reads.dust.data .
daligner -v -t16 -H10000 -e0.7 -s1000 -M32 raw_reads.570 raw_reads.1 raw_reads.2 raw_reads.3 raw_reads.4 raw_reads.5 raw_reads.6 raw_reads.7 raw_reads.8 raw_reads.9 raw_reads.10 raw_reads.11 raw_reads.12 raw_reads.13 raw_reads.14
+ daligner -v -t16 -H10000 -e0.7 -s1000 -M32 raw_reads.570 raw_reads.1 raw_reads.2 raw_reads.3 raw_reads.4 raw_reads.5 raw_reads.6 raw_reads.7 raw_reads.8 raw_reads.9 raw_reads.10 raw_reads.11 raw_reads.12 raw_reads.13 raw_reads.

Building index for raw_reads.570

 Kshift=28
 BSHIFT=8
 TooFrequent=16
 (Kshift-1)/BSHIFT + (TooFrequent < INT32_MAX)=4
 sizeof(KmerPos)=16
 nreads=32131
 Kmer=14
 block->reads[nreads].boff=400044466
 kmers=399594632
 sizeof(KmerPos)*(kmers+1)=6393514128
 Allocated 399594633 of 16 (6393514128 bytes) at 0x7fc14d781010
   Kmer count = 399,594,632
   Using 11.91Gb of space
   Revised kmer count = 340,924,865
   Index occupies 5.08Gb

#LAcheck -vS raw_reads L1.570.95
#LAcheck -vS raw_reads L1.570.96
#LAcheck -vS raw_reads L1.570.97
#LAcheck -vS raw_reads L1.570.98
#LAcheck -vS raw_reads L1.570.99
#LAcheck -vS raw_reads L1.570.100
#LAcheck -vS raw_reads L1.570.101
#LAcheck -vS raw_reads L1.570.102
#LAcheck -vS raw_reads L1.570.103
#LAcheck -vS raw_reads L1.570.104
#LAcheck -vS raw_reads L1.570.105
#LAcheck -vS raw_reads L1.570.106
#LAcheck -vS raw_reads L1.570.107
#LAcheck -vS raw_reads L1.570.108
#LAcheck -vS raw_reads L1.570.109
#LAcheck -vS raw_reads L1.570.110
#LAcheck -vS raw_reads L1.570.111
#LAcheck -vS raw_reads L1.570.112
#LAcheck -vS raw_reads L1.570.113
#LAcheck -vS raw_reads L1.570.114
#
rm -f *.C?.las *.C?.S.las *.C??.las *.C??.S.las *.C???.las *.C???.S.las
+ rm -f raw_reads.100.raw_reads.570.C0.las raw_reads.100.raw_reads.570.C1.las raw_reads.100.raw_reads.570.C2.las raw_reads.100.raw_reads.570.C3.las raw_reads.101.raw_reads.570.C0.las raw_reads.101.raw_reads.570.C1.las raw_reads.1
rm -f *.N?.las *.N?.S.las *.N??.las *.N??.S.las *.N???.las *.N???.S.las
+ rm -f raw_reads.100.raw_reads.570.N0.las raw_reads.100.raw_reads.570.N1.las raw_reads.100.raw_reads.570.N2.las raw_reads.100.raw_reads.570.N3.las raw_reads.101.raw_reads.570.N0.las raw_reads.101.raw_reads.570.N1.las raw_reads.1

touch /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_0252/job_0252_done
+ touch /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/01.assembly/01.AK1/01.FALCON-integrate/0-rawreads/job_0252/job_0252_done

**Comment by lijingjing1** [comment]
Try to mv mypwatcher mypwatcher.bak and restart fc_run.py.

**Comment by pb-cdunn** [comment]
> I have attached head and tail for the log from the job_0252, which was unsatisfied

You don't see any error in that log?

**Comment by pb-cdunn** [comment]
Try

    use_tmpdir = /tmp

(We use `/scratch`, which has more free space.) That can overcome filesystem latency problems. Also, updating FALCON and pypeFLOW might help.

**Comment by sjin09** [comment]
@lijingjing1 

That would approach would did not work for me. It did not register the jobs to be completed and it restarted the unsatisfied jobs. In restarting the unsatisfied job it recreates the rj*.sh scripts and LAcheck is performed. LAcheck when performed produces duplicate overlaps and exists with error 256. 

@pb-cdunn 

I did not see any error log. I manually restarted the rj*.sh job in the directory by `nohup sh rj*.sh & ` and did not see any log in the nohup.out. However, the error is still present in the pwatchdir/stderror.  

I will try some other methods and post if anything works.

**Comment by sjin09** [comment]
I tried 

```
git pull origin master # or whatever version you want 
git submodule update
make -j install
make test # to run a simple one
```

to update the installation for pypeflow. The installation did not successfully run make test, so I reinstalled FALCON. The update in pypeflow did not resolve the problem, so I am trying to find another way :).

**Comment by pb-cdunn** [comment]
How recent is your DALIGNER repo? In theory, the duplicate overlaps problem has been solved.

If you only want to skip the .las files that have problems, you can set `skip_checks`. You would need the latest FALCON and pypeFLOW, which are not in a release of FALCON-integrate yet.

**Comment by sjin09** [comment]
I have reinstalled FALCON-integrate, so I assume that I have the latest stable release (1.8.2).

```
export GIT_SYM_CACHE_DIR=~/.git-sym-cache # to speed things up
git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout master  # or whatever version you want
make init
source env.sh
make config-edit-user
make -j all
make test  # to run a simple one
```

I will try to separately install dalinger and see if that also produces the error. In addition, where would I provide the option skip_checks? I will try to see if any other hacks works.

**Comment by pb-cdunn** [comment]
`skip_checks = true`  goes into your `.cfg` file for `fc_run.py`.

**Comment by sjin09** [comment]
I have separately installed daligner from github, and I still observe the duplicate overlap in my log. I have attached the log for your information. 

I have installed FALCON-integrate version 1.8.6 to use the skip_checks = true option in fc_run.cfg. I have successfully installed it and I am running it at the moment. I hope this resolves the issue for me. I will post an update if it was successful. I hope it doesn't change the assembly statistics too much as a result of losing important information. 

[nohup.txt](https://github.com/PacificBiosciences/FALCON/files/672392/nohup.txt)

**Comment by gucascau** [comment]
I also had this kind of problem.Here I update the latest version of daligner and FALCON. Even if used skip_checks = true, I could still find the LA_check in the rj*.sh and stuck after overlap exists.  

I rerun the failed task of rj*.sh manually, then deleted mypwater file and finally restarted the fc_run.py. But I noticed that why they still executed the daligner and LAcheck process for error files. For the curious, why do the software still perform the same process even since it should pass these steps by manually rerunning?

**Comment by pb-cdunn** [comment]
If you run manually, you need to touch the requisite "done" files.

I still don't understand the problems here. I understand that duplicate overlaps are occurring. That is a bug in DALIGNER, not FALCON. You will need to open an Issue in thegenemyers/DALIGNER and provide Gene Myers with a test-case.

But I don't understand the system problems. Everyone needs to debug that themselves. This is software. You *can* debug it. We cannot debug your systems problems without being on your system.

**Comment by liweisdau** [comment]
You should touch the "run.sh.done" file in the working directories.

**Comment by wsuplantpathology** [comment]
Hi @pb-cdunn :

In Dec 22, 2016, you mentioned `skip_checks = true` goes into your .cfg file for fc_run.py. However, I find the option should be typed as `skip_check = true`, according to this http://pb-falcon.readthedocs.io/en/latest/parameters.html. Am I right?

Thanks,
chongjing

**Comment by wsuplantpathology** [comment]
Now I am pretty sure it should be: `skip_checks = true`. Something must be wrong in the parameters webpage.

**Comment by gooalzqshu** [comment]
> Now I am pretty sure it should be: `skip_checks = true`. Something must be wrong in the parameters webpage.

have you solved this question after you add `skip_checks = true` in your cfg file
