### ISSUE TITLE
unknown reason failed after the program steped into '1-preads-ovl' and can't resume

### ISSUE THREAD

**Issue by nottwy** [PacificBiosciences/FALCON#507]
we meet a problem and this is the stderr. You can find the error information at the end of the file.
[1231.txt](https://github.com/PacificBiosciences/FALCON/files/686757/1231.txt)

I use the pbs version of falcon and it failed after it stepped into the directory "1-preads-ovl" for some time.
Now my problem is:
1. Why does it happen and how to solve it?
2. Can I start the program from the place I stop?

**Comment by nottwy** [comment]
Is there a way to resume a Falcon run once the job hit the walltime? #447

**Comment by nottwy** [comment]
Is there a way to resume a Falcon run once the job hit the walltime? #447
I find the solution there and I try. It doesn't work.
The falcon resume from the beginning rather than where it stopped.

**Comment by pb-cdunn** [comment]
Independent of this problem, we could use your help with PBS. How can we delete these jobs?
```
[INFO]!qdel J0925d72a4ef951
qdel: illegally formed job identifier: J0925d72a4ef951
```

Anyway, here is the failure:
```
[ERROR]Task Fred{'URL': 'task://localhost/d_0005_preads'} failed with exit-code=256
```
You would have to look into the corresponding run-dir to learn the cause.

Yes, it should restart fine after you remove `mypwatcher/`. (Removing that will also remove the evidence of why the preads task failed, so you should view that first.) If it's not skipping the earlier tasks when you restart, maybe you can help us investigate why.

**Comment by nottwy** [comment]
1. When you want to delete a job, you should use:
`qdel job_id`
rather than:
`qdel job_name` #(This is what you do now.)
2. I'm not sure where is the corresponding run-dir?
3. Of course I want to help you solve this problem. You could send me an email to ask for the any files that you need. nottwya@gmail.com.

**Comment by pb-cdunn** [comment]
We don't currently capture the job_id at start-up. If we ever get access to a PBS system, we can work on that. But I'm not convinced that job_name doesn't work. I suspect qdel fails because these jobs are already completed, so it's probably not a real problem.

If you had an up-to-date version of FALCON, the run-dir would be obvious from the `task:://` URI. As it is, you can probably search for a directory that looks like `d_0005_preads`.

**Comment by nottwy** [comment]
OK.
Let me prepare data and provide you the evidences of every problems I mentioned one by one.
Fisrt it's about PBS.

![2017-01-07_174605](https://cloud.githubusercontent.com/assets/4936625/21740868/a19c1188-d501-11e6-8772-82794dbef013.jpeg)

In the picture I submit, you can find that:
1. When I try to qdel by the job_name, it failed and the task is still running. The error information has the same format as shown in falcon error information.
2. When I try to qdel by the job_id, it succeeds.
I know the reason why you give such a long name is you try to avoid a duplicate name. But in fact, a task is recognized by its job_id rather than its name. There can be two tasks which have the same name.

`Job id                    Name             User            Time Use S Queue
------------------------- ---------------- --------------- -------- - -----
523566.mu01                time             wangyu                 0 Q cu
523567.mu01                time             wangyu                 0 Q cu
`

**Comment by nottwy** [comment]
Secondly, it's about run-dir and error information.
According to my understanding, the information "[ERROR]Task Fred{'URL': 'task://localhost/d_001a_raw_reads'} failed with exit-code=256" indicates that it's related about "001a" data.
So it must be related to job_001a in the directory "0-rawreads".
In the directory "0-rawreads/job_001a": total files are listed below:
![2017-01-07_215342](https://cloud.githubusercontent.com/assets/4936625/21742161/f44f9ec8-d523-11e6-9a93-e9014f43bb13.jpeg)

There is no related information about this failure. And because falcon stops before it left 0-rawreads, so I don't find other directory except 0-rawreads. 
My question is: how to determine the reason of this failure?

Thanks for your help!

**Comment by nottwy** [comment]
Finally, it's about "rerun falcon".
I had submitted this sample task presented above before.
At that time falcon stepped into 1-pvreads but failure there. I tried to rerun falcon through deleting `mypwatcher` directory and run `fc_run.py fc_run_pbs.cfg`.
Then falcon stepped into 0-rawreads, create new jobs there. The task falcon submitted is daligner. Nothing happened at 1-pvreads. So I think there is no rerun.
Is what I did correct? How can I rerun falcon?

**Comment by pb-cdunn** [comment]
1. We will need to capture the job-id when the job is submitted in order to execute qdel properly. Unfortunately, any system can return different output that we must process. So we would have to guess at yours, and it might not be the same for others. Basically, we can solve problems when we can login to a system, but otherwise we rely on users to submit pull-requests (in the pypeFLOW repo) which work for them.
2. Look in `0-rawreads/job_001a/pwatcher.dir/stderr`
3. Maybe the old task is still running? You might have to debug this yourself. It's not behavior we have seen before.

**Comment by nottwy** [comment]
Now I know how to solve these problems. 
The reply from you give me some clues.
Thank you for your help.

**Comment by Res2677** [comment]
Hi,nottwy!
I have the same problem,and our server use PBS,when I run falcon,it show the error like this:
`[ERROR]Some tasks are recently_done but not satisfied: set([Node(1-preads_ovl)])
[ERROR]ready: set([])
submitted: set([])
[INFO]!qdel P2382d20dd8a92e
qdel: illegally formed job identifier: P2382d20dd8a92e
`
I don't know how to make falcon compatible with PBS.
Can you tell me the details that how you solve the problem?
Thank you for your help.

**Comment by nottwy** [comment]
I give up solving this problem by oodes. I try another scheduler.
A possible solution is to adjust codes related about 'qdel' in this file:
fc_env_171113/lib/python2.7/site-packages/pwatcher/fs_based.py
Change the command line of qdel into your PBS version.

**Comment by Res2677** [comment]
Oh,it work!
A nice scheduler!
Thank you!

**Comment by pb-cdunn** [comment]
> A possible solution is to adjust codes related about 'qdel' in this file:
> fc_env_171113/lib/python2.7/site-packages/pwatcher/fs_based.py

It is now possible to specify both `submit` and `kill` strings, with either `fs_based` or `blocking` process-watchers. Hopefully, that will enable anyone to work around this problem in the future.

* https://github.com/PacificBiosciences/pypeFLOW/wiki/configuration
* https://github.com/PacificBiosciences/FALCON/wiki/Configuration

**Comment by yingzhang121** [comment]
I tried the setting of kill string, but it didn't work.
In PBS system, it is easy to get the job id. You can use ${PBS_JOBID}, or more simple, if you define, submit=$(qsub -S /bin/bash script.sh), the value of submit is actually the job id, and you can run "qdel ${submit}.
This seems to be an easy fix in the python script, but I am not sure how many persons will do it manually.

**Comment by pb-cdunn** [comment]
In blocking mode, you don't need to kill anything.

In non-blocking, filesystem-based mode, the default kill should be something like:

    qdel ${JOB_NAME}

which should work fine. You should be able to override that with your own `kill` string.

However, without knowing more details, I have to assume that your source-code is way out of date. The code here is GitHub is unfortunately not updated anymore. You can get the latest code by downloading "smrtlink" from the PacBio website (or contact the application engineer with your Sequel account). For open-source code, try our `pb-assembly` recipe in Bioconda, which includes all dependencies for Falcon, Unzip, Phasing, polishing, etc.

**Comment by yingzhang121** [comment]
@pb-cdunn, as mentioned by previous posts, qdel uses job id not job name to identify a job. The main concern is job name might not be unique.  I found in your code, you defined JOB_ID = JOB_NAME, however, this is not a working command in my PBS system. In my PBS, there is even not -W block=T option (https://github.com/PacificBiosciences/pbbioconda/issues/12#issuecomment-422059738). 
I know I could manually modify the code to make it working, but I also think other user might lack the knowledge to do so. Therefore, if you can make this minor change in your release, that will be fantastic.

**Comment by pb-cdunn** [comment]
@yingzhang121 , let's move this PBS discussion to https://github.com/PacificBiosciences/pypeFLOW/issues/54
