### ISSUE TITLE
Running m_ processes (LAsort/LAmerge) on a local disk

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#51]
Hi, Jason,

Falcon's LAsort/LAmerge stage was disrupting everyone else on the cluster that the decision was made to cut back the # of falcon jobs from 100 to 19 (which I think will mean a human assembly will take 10 weeks instead of 2).  So I'm looking for ways to speed up the falcon assembly without disrupting others on the cluster.

Would Falcon speed up by running LAsort/LAmerge on a local disk?  I am seeing that each LAsort/LAmerge job requires a large # of little files:  13,000 in one case of which 12,500 are used just once.  the files used just once (in the cases I looked at) are used by LAsort.  To run LAsort off of local disk would mean copying these files to local disk.  Would the copying itself be as disruptive to other users as running LAsort on them?  Would there be any net speedup for falcon?

Thanks,
david

**Comment by pb-jchin** [comment]
@dgordon562  I did not have a chance to check this out yet.  It is about large data management.  One possibility is to change the way where the file merge happens.  Gene talked about one needed a distributed file system to use this code as it was designed to generate many smaller files quick and merge at the end.  Different merging scheme might help but it will become very cluster configuration specific.   However, if your node have large local disk, you might be able to make this more efficiently. 

Note that I did not design a new merging scheme, all I did is to take Gene's merging scheme and distribute the job across the nodes.  I did have to ask some cluster configuration modification so we can make it running efficient on our side.

**Comment by dgordon562** [comment]
OK, so here is my idea and tell me what you think:  

At the daligner stage in the very beginning, I'll make the output be written to a local disk--not a network disk.  These output files will be used (locally) by LAsort/LAmerge, and LA4Falcon.  At that point the results will be written back to the network drive.

The part of this that I'm hazy about is at what point the following 3 files are created:
raw_reads.db
.raw_reads.idx
.raw_reads.bps

If these are created *after* daligner, then the above won't work.
Your thoughts?

**Comment by pb-jchin** [comment]
@dgordon562 answer the simple question first, `raw_reads.db`, `.raw_reads.idx` and `.raw_reads.bps` are generated as the first step of the whole workflow.  Once they are "split" (by running `DBsplit`), they will not be changed at all, so you can move them around.  They are created before maligner. 

The `LAsort` and `LAmerge` do not use the `raw_reads.db` in general.  The problem is that you will have to build some "merge server", such that the data of all chunks with the same first block ID will go to the same node and then doing the merging locally.  If you do so, you can distribute the file copy through the course computation and it will be less disruptive.   The heavy I/O will be done locally and light weight copying are properly distributed.  (What we do now is simply dependent on the distributed or shared file system to do this for us, but they may not "smart" enough....)

**Comment by dgordon562** [comment]
Thanks for your quick and good response!

**Comment by dgordon562** [comment]
If I have existing copies of the 3 files:

-rw-rw-r-- 1 dgordon dgordon_g      182814 Apr 20 03:49 raw_reads.db
-rw-rw-r-- 1 dgordon dgordon_g  1182210992 Apr 20 03:50 .raw_reads.idx
-rw-rw-r-- 1 dgordon dgordon_g 57475434529 Apr 20 04:07 .raw_reads.bps

on many different nodes, and then I restart fc_run.py, under what circumstances would I need to copy new versions of each of these files?   Would I need to do so if I am only changing various sge parameters such as sge_option_cns?    How about if I am changing the clipping filter length_cutoff = 9000?   (I'm guessing the answers are "no" and "yes"?)

**Comment by pb-jchin** [comment]
@dgordon562  A little bit confused.  the `fc_run.py`  has no concept of local storage. It does not a shared file system to keep track the state.  You can cheat by modify a couple of thing so the scripts actually uses local storage data. However, I am not quite sure about your intent now.  The LAmerge/LAsort is different from the consensus step.  (The consensus does need the raw_reads.db but the LAmerge/LAsort does not.)

**Comment by dgordon562** [comment]
I understand that fc_run.py has no concept of local storage.  I have scripts that do have that concept and these scripts are run by fc_run.py.  The question is suppose I have been running fc_run.py for a while, and then I want to make a change in the config file such as changing sge_option_cns.  So I ^C out of fc_run.py.  All of my jobs that are running on local storage are then terminated.  Fine.  I then make the change to the config file and run fc_run.py again.  My question is:  must the 3 files (above) need to be recreated and recopied to local storage, or can I use the copies from before I ^C'd out of fc_run.py?

**Comment by pb-jchin** [comment]
@dgordon562 check the `0-rawreads/prepare_db.sh`, once the db is built, you can copy it anywhere. You just have to point `LA*` and `DB*` commands to the local path. (I did this tricks sometimes too.)

**Comment by pb-cdunn** [comment]
Rebase to *master* branch and submit a pull-request. We might be able to use some of your code.

In #43, you mention:
> The combination of 2 (using `/var/tmp`) and 3 (using `mmap`) usually speeds up LA4Falcon by a factor of between 10 and 100.  However, there are times when copying the needed files (around 50GB) can itself take a long time (on the order of a day).

If things really goes that much faster on a local disk, then a better solution might be to run LAsort/LAmerge tasks serially on a single node. That way, the cost of copying to/from local disk is incurred only once. This requires more experimentation, and different clusters might have different characteristics.

But please share actual code, via GitHub. Fork FALCON and commit your changes. And try to rebase your changes to the new *master* branch. Git (or any distributed version-control system) greatly facilitates code-sharing over the internet. It's worth learning.
