### ISSUE TITLE
Question about the numbers of symbolic links

### ISSUE THREAD

**Issue by wresch** [PacificBiosciences/FALCON#512]
Hi,

this is really a question, not an issue. I had installed falcon 0.4.1 on our cluster a while back. Worked well for a couple of prokaryotic genomes. But then a user tried to assemble a large eukaryotic genome (3Gb) and ended up murdering our networked file system by creating a pretty sizeable amount of symbolic links. So falcon was put on hiatus. Now a couple of users are requesting falcon again.  Reading through the issues and commit messages i gather that the number of symlinks that get created has been reduced. But I'm not sure by how much. Could you please give me a ballpark estimate how may symlinks are created for assemblies of different genome sizes?

Thanks so much,

Wolfgang

**Comment by pb-cdunn** [comment]
This was something David Gordon helped us fix. The number of symlinks used to be O(n^3) for n blocks, and now it is O(n^2). Roughly.

(We used to symlink all .las files into each merge directory. There are O(n^2) .las files, and roughly O(n) merge jobs. Now we symlink only the .las files needed for each merge job.)

**Comment by wresch** [comment]
Thanks Chris.

On Wed, Jan 18, 2017 at 10:30 AM, Christopher Dunn <notifications@github.com
