### ISSUE TITLE
falcon overlap filtering settings for humans

### ISSUE THREAD

**Issue by sjin09** [PacificBiosciences/FALCON#514]
I have successfully managed to create the p_ctg.fa and a_ctg.fa. I am now trying to optimize the assembly parameters to obtain better assembly statistics with human genome data. I have read your tips on determining the overlap filtering settings here (https://github.com/PacificBiosciences/FALCON/wiki/Tips) and here (https://github.com/PacificBiosciences/FALCON/issues/76). 

I was wondering if you have any particular recommendations for human genome data that has been sequenced to approximately 100X. In particular, I would like to be able to recover highly duplicated genes such as the amylase, or SRGAP2 and recover more of the segmental duplications correctly that are known to be real problems in assemblies. I would be trying to optimize the assembly statistics here as well.

Best,
Jin

**Comment by sjin09** [comment]
I have used the following fc_run.cfg file 

```
[General]
#job_type = local

# list of files of the initial bas.h5 files
#input_fofn = input.fofn
input_fofn = preads.fofn

#input_type = raw
input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 10000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 15000

job_queue = bi.q
sge_option_da = -pe peXMAS 8 -q %(job_queue)s
sge_option_la = -pe peXMAS 2 -q %(job_queue)s
sge_option_pda = -pe peXMAS 8 -q %(job_queue)s
sge_option_pla = -pe peXMAS 2 -q %(job_queue)s
sge_option_fc = -pe peXMAS 24 -q %(job_queue)s
sge_option_cns = -pe peXMAS 8 -q %(job_queue)s

pa_concurrent_jobs = 300
cns_concurrent_jobs = 300
ovlp_concurrent_jobs = 300

pa_HPCdaligner_option =  -v -dal128 -t16 -e.70 -l1000 -s1000 -M32
ovlp_HPCdaligner_option = -v -dal128 -t32 -h60 -e.96 -l500 -s1000 -M32

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 10
falcon_sense_skip_contained = True

overlap_filtering_setting = --max_diff 60 --max_cov 60 --min_cov 2 --n_core 24
```

With these configurations, I was able to obtain an assembly with following results

```
number_of_contigs: 4,142
contig_sum: 2,862,764,913
contig_N50: 16,496,949
contig_minium_length: 86
contig_mean_length: 691,155
contig_maximum_length: 105,221,97
```1

**Comment by sjin09** [comment]
I have been able to use arrive at this configuration for optimizing the human assembly.

```
[General]
#job_type = local

# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 16000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 6000

job_queue = bi.q
sge_option_da = -pe peXMAS 8 -q %(job_queue)s
sge_option_la = -pe peXMAS 20 -q %(job_queue)s
sge_option_pda = -pe peXMAS 6 -q %(job_queue)s
sge_option_pla = -pe peXMAS 16 -q %(job_queue)s
sge_option_fc = -pe peXMAS 20 -q %(job_queue)s
sge_option_cns = -pe peXMAS 8 -q %(job_queue)s

pa_concurrent_jobs = 80
cns_concurrent_jobs = 80
ovlp_concurrent_jobs = 80

pa_HPCdaligner_option =  -v -dal128 -t16 -e0.75 -M24 -l4800 -k18 -h480 -w8 -s100
ovlp_HPCdaligner_option =  -v -dal128  -M24 -k24 -h1024 -e.96 -l2500 -s100 

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 8 
falcon_sense_skip_contained = False

overlap_filtering_setting = --max_diff 60 --max_cov 60 --min_cov 1 --n_core 12
```
```

The assembly statistics from this configuration is shown below:

```
number_of_contigs 904
contig_sum        2892837735
contig_N50        24375051
contig_minimum_length     95
contig_mean_length        740993
contig_maximum_length     109706220
```

I would be quite interested in how others have assembled their human or primates genomes.

**Comment by pb-jchin** [comment]
@sjin09, nice results.  max contig 109Mb is quite impressive.  I only get that for the CHM1 data set.  If this is not the same dataset, it will be real nice!!

**Comment by sjin09** [comment]
@pb-jchin, the data set is from another human diploid genome. I am running FALCON_UNZIP now and I am really excited for the results :)

**Comment by pb-jchin** [comment]
@sjin09 good to know. looking forward to know about it in the future

**Comment by sjin09** [comment]
I am happy to inform other users that the largest contig aligns to the chr2 without any large misassemblies, if they want to use the same configurations for their assembly.

**Comment by pb-jchin** [comment]
@sjin09 great to hear. Thanks for sharing your results.

**Comment by bruc** [comment]
@sjin09 I'm very interested in using your parameters for an assembly that I'm working on. With your length cutoffs, how much coverage of the human genome is present for both your raw reads and corrected reads?

I'd also like to contact you directly by email.

**Comment by sjin09** [comment]
@bruc Hello, the human genome was sequenced to 101X coverage with PacBio RSII platform. However, there were 10% loss of subreads during the conversion of bax to bam files. The conversion was necessary for consensus calling using ARROW.

I, therefore, started the de novo assembly with 90X sequence coverage. With the subread_length cutoff of 16000, I remember having 40X sequence coverage and with the pread_lenth_cutoff of 6000, I remember having 20X sequence coverage. These are, however, rough estimates as I am currently not working for the same company where I have done the de novo assembly. Since I left the company, there also seems to have been a lot of developments recently in the de novo assembly world.

If you can share me your email address, I will send you an email. I hope the answer helped with your assembly problems.

**Comment by bruc** [comment]
@sjin09 Hello! Thanks for answering. My email is [bruc@acm.org](mailto:bruc@acm.org). I'm using a higher raw read coverage but the same pread coverage. My genome has different structure than the human one. I look forward to continuing the conversation. Thank you.

**Comment by bruc** [comment]
@sjin09 Hello again! Did you ever get a chance to send me an email? I would like to learn more about your success with assembling the human genome. Thank you.
