### ISSUE TITLE
Falcon and Falcon Unzip running for LSF

### ISSUE THREAD

**Issue by kassammo** [PacificBiosciences/FALCON#518]
Hello

I installed Falcon and Falcon unzip, unfortunately I tried to change job_type = lsf but it does not work.

Did someone is using Falcon and Falcon unzip on LSF ?

Thanks

**Comment by pb-cdunn** [comment]
You might need to alter pypeflow. Pretty straight-forward. If you get it working, please submit a pull-request there.
