### ISSUE TITLE
os.symlink throws fatal exception if file exists

### ISSUE THREAD

**Issue by bredeson** [PacificBiosciences/FALCON#519]
Hey Chris,

I have installed a more current version of Falcon:

> commit a72f47c4600fb31c993151c1d03c1787ba42b161
> Merge: bc6d6d6 98c2a9f
> Author: Christopher Dunn <cdunn@pacificbiosciences.com>
> Date:   Thu Dec 22 08:56:24 2016 -0600
> 
>     Merge pull request #116 from PacificBiosciences/update
>     
>     Update

and have run into a few problems and think you should be aware of them. Firstly, if Falcon dies at the `0-rawreads/m_*` stage, `0-rawreads/m_*/L1.*.*.las` symlinks to `0-rawreads/job_*/L1.*.*.las` still exist. When attempting to restart these jobs, Falcon attempts to re-symlink these files, but `os.symlink` throws an "OSError: file already exists" exception. This makes it non-trivial to simply resume Falcon when at this stage. Could Falcon attempt catching this exception and pass'ing instead of letting it propagate to the interpreter?

Second, I noticed that if a job exceeds the requested max walltime limit at the daligner step and I change the main config to increase the max walltime limit, and I delete the original task.json file for that long-running task, the changes to the main config are not propagated down to the task.json when Falcon is re-run. I eventually have to run these jobs on the local interactive node (where there is no max walltime limit) to get them to complete. 

And third, I'm seeing the following error at the 1-preads_ovl/preads-fofn-abs step. It's timing out while checking to see if the .fofn file exists? The .fofn and the .fasta file it points to both exist and the path in the .fofn file is already absolute.

> ERROR: Task Node(1-preads_ovl/preads-fofn-abs) failed with exit-code=256
> INFO: recently_satisfied: set([])
> INFO: Num satisfied in this iteration: 0
> INFO: Num still unsatisfied: 1
> ERROR: Some tasks are recently_done but not satisfied: set([Node(1-preads_ovl/preads-fofn-abs)])
> ERROR: ready: set([])
> submitted: set([])
> INFO: !qdel -k Pab2b366971831a
> The job -k of user(s) bredeson does not exist
> job 29389374 is already in deletion
> Traceback (most recent call last):
>   File "my/tools/bin/Falcon/FALCON-integrate/fc_env/bin/fc_run", line 11, in <module>
>     load_entry_point('falcon-kit', 'console_scripts', 'fc_run')()
>   File "my/tools/bin/Falcon/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 461, in main
>     main1(argv[0], args.config, args.logger)
>   File "my/tools/bin/Falcon/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 136, in main1
>     input_fofn_plf=input_fofn_plf,
>   File "my/tools/bin/Falcon/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 323, in run
>     wf.refreshTargets([fofn_abs_task])
>   File "my/tools/bin/Falcon/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 226, in refreshTargets
>     self._refreshTargets(updateFreq, exitOnFailure)
>   File "my/tools/bin/Falcon/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 292, in _refreshTargets
>     raise Exception(msg)
> Exception: Some tasks are recently_done but not satisfied: set([Node(1-preads_ovl/preads-fofn-abs)])
> 

from mypwatcher/jobs/P*/stderr:

> before setpgid: pid=14835 pgid=14597
>  after setpgid: pid=14835 pgid=14835
> In cwd: myassembly/FALCON-20170122/1-preads_ovl/preads-fofn-abs, Blocking call: '/bin/bash run.sh'
> cd myassembly/FALCON-20170122/1-preads_ovl/preads-fofn-abs
> + cd myassembly/FALCON-20170122/1-preads_ovl/preads-fofn-abs
> bash task.sh
> + bash task.sh
> 2017-01-27 07:55:43,237 - root - DEBUG - Running "my/tools/bin/Falcon/FALCON-integrate/pypeFLOW/pypeflow/do_task.py myassembly/FALCON-20170122/1-preads_ovl/preads-fofn-abs/task.json"
> 2017-01-27 07:55:43,239 - root - DEBUG - Checking existence of 'myassembly/FALCON-20170122/1-preads_ovl/preads-fofn-abs/task.json' with timeout=60
> 2017-01-27 07:55:43,240 - root - DEBUG - Loading JSON from 'myassembly/FALCON-20170122/1-preads_ovl/preads-fofn-abs/task.json'
> 2017-01-27 07:55:43,242 - root - DEBUG - {u'inputs': {u'i_fofn': u'myassembly/FALCON-20170122/0-rawreads/raw-fofn-abs/pbdagcon.fofn'},
>  u'outputs': {u'o_fofn': u'pbdagcon.fofn'},
>  u'parameters': {},
>  u'python_function': u'falcon_kit.pype_tasks.task_make_fofn_abs_preads'}
> 2017-01-27 07:55:43,242 - root - DEBUG - CD: 'myassembly/FALCON-20170122/1-preads_ovl/preads-fofn-abs' <- 'myassembly/FALCON-20170122/1-preads_ovl/preads-fofn-abs'
> 2017-01-27 07:55:43,242 - root - DEBUG - Checking existence of u'myassembly/FALCON-20170122/0-rawreads/raw-fofn-abs/pbdagcon.fofn' with timeout=60
> 2017-01-27 07:56:43,537 - root - DEBUG - CD: 'myassembly/FALCON-20170122/1-preads_ovl/preads-fofn-abs' -> 'myassembly/FALCON-20170122/1-preads_ovl/preads-fofn-abs'
> 2017-01-27 07:56:43,537 - root - CRITICAL - Error in my/tools/bin/Falcon/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': 'myassembly/FALCON-20170122/1-preads_ovl/preads-fofn-abs/task.json',\n 'timeout': 60,\n 'tmpdir': None}"
> Traceback (most recent call last):
>   File "python/2.7.10/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "my/tools/bin/Falcon/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 190, in <module>
>     main()
>   File "my/tools/bin/Falcon/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 182, in main
>     run(**vars(parsed_args))
>   File "my/tools/bin/Falcon/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 136, in run
>     run_cfg_in_tmpdir(cfg, tmpdir)
>   File "my/tools/bin/Falcon/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 139, in run_cfg_in_tmpdir
>     wait_for(fn)
>   File "my/tools/bin/Falcon/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 92, in wait_for
>     raise Exception('Timed out waiting for {!r}'.format(fn))
> Exception: Timed out waiting for u'myassembly/FALCON-20170122/0-rawreads/raw-fofn-abs/pbdagcon.fofn'
> 
> real	1m0.585s
> user	0m0.062s
> sys	0m0.081s
>  returned: 256

**Comment by pb-cdunn** [comment]
1. Yes. Good catch. I'll trap os.symlink().
2. Yeah, this kind of thing has happened to me also. The answer is that pypeflow is not a meant to detect changes to inputs. Upon restart, it only runs tasks that have not been run. Anything that comes from a previous task -- rather than from a global input -- will not be recalculated unless that earlier task is also re-run. In this case, I think you would need to re-run the build_rdb step too. The good news is that you can simply delete the output of that step, forcing that step to re-run; existing daligner runs will not re-run, since pypeflow does not base decisions on timestamps (anymore), relying instead only on the *existence* of the "done" file. But note that if you change things which cause the number of jobs to change, you will make a mess. Changing the sge_options should be fine.
3. *Please* help us debug this. Someone else reported it too. In theory, this is impossible. How can it wait on a file that already exists? Maybe it did not exist when the waiter started, and maybe the waiter needs to do something to cause its view of the filesystem to be refreshed, e.g. readdir(). That would be a simple change in `wait_for()` inside `do_task.py` of pypeflow. Please try something like that.

**Comment by bredeson** [comment]
Hey Chris,

I think I may have found the issue to (3) above. In 1-preads_ovl/preads-fofn-abs/task.json, the "inputs" path to my .fofn file is not the path that I gave it in the main config. Falcon seems to be assuming that the .fofn file is going to be located under `0-rawreads/raw-fofn-abs/`, but I started my Falcon run with `input_type = preads`. Here Falcon is making a bad assumption, as Falcon cannot not guarentee that the user has generated their consensuses with Falcon (and would have the 0-rawreads directory/file structure it expects). Under this scenario, Falcon would time out because it's not checking that the inferred .fofn file path under 0-rawreads/raw-fofn-abs/ actually exists (only assumes it does?), and therefore 1-preads_ovl/preads-fofn-abs/input.fofn can never be created. 

Does this sound like it jives with your (far deeper) knowledge of the Falcon code?

Hope this helps.

**Comment by bredeson** [comment]
`cp`'ing my .fofn file to `0-rawreads/raw-fofn-abs/` fixes this issue.

**Comment by pb-cdunn** [comment]
Thanks, @bredson. Very helpful. We will fix for `input_type = preads` per your suggestion.

Notes to self:

* Really, pypeflow should check for existence of "pure" inputs without the timeout, before qsub.
* Also, this should auto-close when the fix for (1) is pushed from internal BitBucket. Double-check that.
