### ISSUE TITLE
failed to run FALCON-integrate

### ISSUE THREAD

**Issue by yilunhuangyue** [PacificBiosciences/FALCON#520]
Hello, I have installed FALCON-integrate using the easy way, 
export GIT_SYM_CACHE_DIR=~/.git-sym-cache # to speed things up
git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout master  # or whatever version you want
make init
source env.sh
make config-edit-user
make -j all

 Everything seems ok in installation and I have do a test using the E.coli data:

wget https://www.dropbox.com/s/tb78i5i3nrvm6rg/m140913_050931_42139_c100713652400000001823152404301535_s1_p0.1.subreads.fasta
wget https://www.dropbox.com/s/v6wwpn40gedj470/m140913_050931_42139_c100713652400000001823152404301535_s1_p0.2.subreads.fasta
wget https://www.dropbox.com/s/j61j2cvdxn4dx4g/m140913_050931_42139_c100713652400000001823152404301535_s1_p0.3.subreads.fasta.

It ran successfully and got the final result p_ctg.fa. But when I used my own data, I met an error like this:

[INFO]About to submit: Node(0-rawreads/job_37d3)
[INFO]About to submit: Node(0-rawreads/job_1e5e)
[INFO]About to submit: Node(0-rawreads/job_2bcd)
[ERROR]Failed generate_script() for Node(0-rawreads/job_164f)
Traceback (most recent call last):
  File "/home02/wuguizhi/software/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 344, in execute
    actual_script_fn = self.generate_script()
  File "/home02/wuguizhi/software/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 392, in generate_script
    open(task_json_fn, 'w').write(task_content)
IOError: [Errno 22] invalid mode ('w') or filename: u'/home02/wuguizhi/JLX/Falcon_test2/0-rawreads/job_164f/task.json'
Traceback (most recent call last):
  File "/home02/wuguizhi/software/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home02/wuguizhi/software/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/home02/wuguizhi/software/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 461, in main
    main1(argv[0], args.config, args.logger)
  File "/home02/wuguizhi/software/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 136, in main1
    input_fofn_plf=input_fofn_plf,
  File "/home02/wuguizhi/software/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 234, in run
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/home02/wuguizhi/software/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 226, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home02/wuguizhi/software/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 258, in _refreshTargets
    unsubmitted = set(self.tq.enque(to_submit)) # In theory, this traps exceptions.
  File "/home02/wuguizhi/software/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 67, in enque
    generated_script_fn = node.execute() # misnomer; this only dumps task.json now
  File "/home02/wuguizhi/software/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 344, in execute
    actual_script_fn = self.generate_script()
  File "/home02/wuguizhi/software/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 392, in generate_script
    open(task_json_fn, 'w').write(task_content)
IOError: [Errno 22] invalid mode ('w') or filename: u'/home02/wuguizhi/JLX/Falcon_test2/0-rawreads/job_164f/task.json'

my cfg file is like this:

[General]
use_tmpdir = True
job_type = local

input_fofn = input.fofn

input_type = raw

length_cutoff = 14000

length_cutoff_pr = 14000

jobqueue = production
sge_option_da = -pe smp 8 -q %(jobqueue)s
sge_option_la = -pe smp 2 -q %(jobqueue)s
sge_option_pda = -pe smp 8 -q %(jobqueue)s
sge_option_pla = -pe smp 2 -q %(jobqueue)s
sge_option_fc = -pe smp 24 -q %(jobqueue)s
sge_option_cns = -pe smp 8 -q %(jobqueue)s

pa_concurrent_jobs = 36
ovlp_concurrent_jobs = 36

pa_HPCdaligner_option =  -v -B4 -t16  -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -t32  -e.96 -l500 -s1000
pa_DBsplit_option = -x500 -s50 
ovlp_DBsplit_option = -x500 -s50 

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4  --max_n_read 200 --n_core 6

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 

The genome in my case is about 300M and I have 70X sequencing fasta data in all. Is there any wrong in my case. How should I deal with it?
Thank you so much~

**Comment by yilunhuangyue** [comment]
I have run Falcon successfully finally, but the result is not good enough. the genome is about 300M as expected, but I got only about 180M p_ctg.fa and 10M a_ctg.fa, after conbined the two file, the assembly N50 is 230K. I am not sure if it is caused by the parameters in cfg file . 
The data is sequenced by Pacbio sequel and I have got about 20G bases.
could anyone give me some advices? Thanks a lot~

**Comment by lijingjing1** [comment]
what is your subreads N50?May be length_cutoff 14k a litter high,normaly you should keep the corrected data by daligner and consensus to be 30x,so the length_cutoff may be 50x because of the decrease after consensus.And also the min_cov is too high,you can set it to 1-5 .

**Comment by yilunhuangyue** [comment]
@lijingjing1 ,thanks, I will rerun it.

**Comment by yilunhuangyue** [comment]
@lijingjing1, I have rerun the assembly as your suggestions and the result is much better. Now, I want to run falcon_unzip because my genome is heterozygosis, but I can't find smrt-analysis 3.0 needed by falcon_unzip. The downlink in other issues is useless. could you please tell me where I can download it? 

Thanks again~

**Comment by pb-cdunn** [comment]
Contact PacBio marketing (if you own a PB machine), or try https://github.com/PacificBiosciences/pitchfork/wiki

Glad you got the assembly working. You can also look at the "pre-assembly report" to learn where you might be having problems.

Unzip is a separate issue.

**Comment by kaikaixinxi** [comment]
i meet the same error with you , how  do you solve it?
