### ISSUE TITLE
Running FALCON using PBS 

### ISSUE THREAD

**Issue by MarisaMiller** [PacificBiosciences/FALCON#525]
I have successfully run FALCON using PBS here at MSI (https://www.msi.umn.edu/queues). However, we just upgraded to the newest FALCON and Unzip versions and I am no longer able to run the assembler.

I get an error like "Failed to enqueue 1 of 1 jobs: 
set([Node(0-rawreads/raw-fofn-abs)])", so it looks like the options I used for my older config file (see below for cfg file and pbs script) are no longer working with the newer Falcon. Is there new syntax I should use for the pbs type jobs that I am not aware of? It could also be an issue with the queue system here, so I will check with MSI as well and let you know what I find out.

**fc_run.cfg**
```ini
[General]
#list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

#Falcon-Unzip will be run subsequently and therefore we were recommend to run the Falcon job with 40-fold seed coverage per haplotype, so 80-fold seed coverage in the diploid case. 
length_cutoff = -1
seed_coverage = 80
genome_size = 120000000

#Use all preassembled reads for assembly
length_cutoff_pr = 1

job_type = pbs
sge_option_da = -l nodes=1:ppn=1,mem=32gb,pmem=32gb,walltime=8:00:00
sge_option_la = -l nodes=1:ppn=1,mem=32gb,pmem=32gb,walltime=8:00:00
sge_option_pda = -l nodes=1:ppn=1,mem=32gb,pmem=32gb,walltime=8:00:00
sge_option_pla = -l nodes=1:ppn=1,mem=32gb,pmem=32gb,walltime=8:00:00
sge_option_fc = -l nodes=1:ppn=1,mem=32gb,pmem=32gb,walltime=8:00:00
sge_option_cns = -l nodes=1:ppn=1,mem=32gb,pmem=32gb,walltime=8:00:00

pa_concurrent_jobs = 15
ovlp_concurrent_jobs = 15

pa_HPCdaligner_option =  -v -B128 -M24 -e.70 -l2500 -s100 -k18 -h1250 -w8
ovlp_HPCdaligner_option = -v -B128 -M24 -h1250 -e.96 -l1500 -s100 -k24

pa_DBsplit_option = -a -x500 -s200
ovlp_DBsplit_option = -s200

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 300 --n_core 8
falcon_sense_skip_contained = False

overlap_filtering_setting = --max_diff 120 --max_cov 200 --min_cov 3 --n_core 12
```
**pbs script**
```
#!/bin/bash -l

#PBS -l nodes=1:ppn=32,walltime=46:00:00

cd $PBS_O_WORKDIR
module load falcon
fc_run.py fc_run.cfg
```

**Comment by MarisaMiller** [comment]
Well, we figured out the issue is something with the upgrades to the queueing system here at MSI, so we are closing the issue!

**Comment by pb-cdunn** [comment]
@MarisaMiller, Is there anything we could change to make this work better for you next time? We do want PBS to work.

**Comment by MarisaMiller** [comment]
Hi Christopher,

I figured out how to run the latest version of Falcon here at MSI, but 
it required an inconvenient solution. It seems like after the latest 
updates to MSI, jobs that we submit to queues are not allowed to submit 
jobs on their own. I alerted MSI about this issue but haven't heard 
anything back, so I copied the MSI help desk on this e-mail so they know 
it's still an issue.

To get Falcon to run, I had to log into one of the HPCs (Mesabi) and 
remain on the login node, module load falcon, and then run fc_run.py 
directly. Then, the assembly can complete successfully because the other 
jobs can be submitted successfully from the login node. This is 
inconvenient because I need to prevent the computer from sleeping (for 
24+ hours) to maintain connection to Mesabi.

Not sure if this is an issue with other PBS users but perhaps it is. 
Please let me know if you have more questions or need more information.

Thanks,

Marisa

**Comment by pb-cdunn** [comment]
Running from a login node is the right way to do it. Falcon is intended to be very light-weight on a login node. We never qsub from within a qsub job either, as it has caused many problems in the past.

I plan to switch to `pwatcher_type=blocking` by default. After you get through your other problems, could you try this config?
```ini
job_type = string
pwatcher_type = blocking
job_queue = qsub -S /bin/bash -V -q lyra -N ${JOB_ID} -o "${STDOUT_FILE}" -e "${STDERR_FILE}" -l nodes=1:ppn=${NPROC},mem=25gb -W umask=0007,block=true "${CMD}"
```
You'll need to change `lyra` to your own job-queue name, and you might want to alter mem. If blocking-mode works for, it will be far more robust than the old way (watching for filesystem updates).

(It's a good idea to test with the `FALCON-exmamples/run/synth0` test-case, which is tiny.)

**Comment by vishalcdfd** [comment]
`job_type = PBS
pwatcher_type = blocking
job_type = string
job_queue = bash -C ${CMD}
job_queue = bash -C ${CMD} > ${STDOUT_FILE} 2> ${STDERR_FILE}`
For PBS this above mentioned code will work.
Thought of posting that it has worked on my system with qsub.

**Comment by tangerzhang** [comment]
Hi,
I used config file (attached below) you suggested in PBS system. But FALCON only works locally and not submit any job to the PBS grids. Any suggestions?
[General]
use_tmpdir = ./tmp
job_type = PBS
pwatcher_type = blocking
job_type = string
job_queue = bash -C ${CMD}
job_queue = bash -C ${CMD} > ${STDOUT_FILE} 2> ${STDERR_FILE}

input_fofn = input.fofn

input_type = raw

length_cutoff = 12000

length_cutoff_pr = 12000


jobqueue = high
sge_option_da = -l nodes=1:ppn=8 -q %(jobqueue)s
sge_option_la = -l nodes=1:ppn=2 -q %(jobqueue)s
sge_option_pda = -l nodes=1:ppn=8 -q %(jobqueue)s
sge_option_pla = -l nodes=1:ppn=8 -q %(jobqueue)s
sge_option_fc = -l nodes=1:ppn=24 -q %(jobqueue)s
sge_option_cns = -l nodes=1:ppn=8 -q %(jobqueue)s

pa_concurrent_jobs = 32
ovlp_concurrent_jobs = 32
pa_concurrent_jobs = 6
ovlp_concurrent_jobs = 6

pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24

**Comment by tangerzhang** [comment]
Hi,
I use the config file (attached below) you suggested. But FALCON only works locally, not submit any job to PBS grid. Any suggestion? Thanks!

[General]
use_tmpdir = ./tmp
job_type = PBS
pwatcher_type = blocking
job_type = string
job_queue = bash -C ${CMD}
job_queue = bash -C ${CMD} > ${STDOUT_FILE} 2> ${STDERR_FILE}

input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

length_cutoff = 12000

length_cutoff_pr = 12000


jobqueue = high
sge_option_da = -l nodes=1:ppn=8 -q %(jobqueue)s
sge_option_la = -l nodes=1:ppn=2 -q %(jobqueue)s
sge_option_pda = -l nodes=1:ppn=8 -q %(jobqueue)s
sge_option_pla = -l nodes=1:ppn=8 -q %(jobqueue)s
sge_option_fc = -l nodes=1:ppn=24 -q %(jobqueue)s
sge_option_cns = -l nodes=1:ppn=8 -q %(jobqueue)s

pa_concurrent_jobs = 32
ovlp_concurrent_jobs = 32
pa_concurrent_jobs = 6
ovlp_concurrent_jobs = 6

pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24

**Comment by pb-cdunn** [comment]
> I used config file (attached below) you suggested in PBS system. But FALCON only works locally and not submit any job to the PBS grids.

You have supplied your own job-submission string, but it's only bash. @ #622.

(By the way, `[General]job_queue` still works with `pwatcher=blocking`, but I recommend specifying that as `submit` in the `[job.defaults]` section now. See [Configuration wiki](../wiki/Configuration).)

**Comment by mictadlo** [comment]
Hi all,
We trying today to create a singularity container with the latest [falcon_unzip](https://pb-falcon.readthedocs.io/en/latest/_downloads/install_unzip_180312.sh). We are using PBSpro 14.2.4.  I just wonder whether this falcon.cfg file work on our system (diploid plant genome).

```
[General]
#list of files of the initial bas.h5 files
input_fofn = ../fasta2DB_input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads
 
seed_coverage = 80 
genome_size = 120000000 

#Use all preassembled reads for assembly
length_cutoff = 5000
length_cutoff_pr = 4000
 

job_type = string
pwatcher_type = blocking
job_queue = qsub -S /bin/bash -V -q lyra -N ${JOB_ID} -o "${STDOUT_FILE}" -e "${STDERR_FILE}" -l nodes=1:ppn=${NPROC},mem=25gb -W umask=0007,block=true "${CMD}"

pa_concurrent_jobs = 96
cns_concurrent_jobs = 96
ovlp_concurrent_jobs = 96
 
pa_HPCdaligner_option =  -v -B128 -M32 -e.70 -l4800 -s100 -k18 -h480 -w8 
ovlp_HPCdaligner_option = -v -B128 -M32 -h1024 -e.96 -l2400 -s100 -k18

pa_DBsplit_option = -a -x500 -s200
ovlp_DBsplit_option = -s400
 
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 2 --max_n_read 100 --n_core 8
falcon_sense_skip_contained = True
 
overlap_filtering_setting = --max_diff 80 --max_cov 80 --min_cov 2 --n_core 12
```

Do we also have to specify `sge_option_*` options and if yes then what would be the right syntax for PBS pro  14.2.4?

Thank you in advance.

Michal

**Comment by pb-cdunn** [comment]
> Do we also have to specify sge_option_* options

Those are obsolete in the latest falcon_kit (1.2.3). But that version of source-code is not in GitHub. If you use a binary tarball or Bioconda, you should be fairly up-to-date, in which case the warnings will tell you which settings need to be updated.

Ignoring falcon, if you want to discuss using PBSpro with pypeflow, please open a new ticket in the pypeFLOW repo. The code there is actually up-to-date (unlike in this FALCON repo), and I am interested in getting PBSpro to work.

**Comment by amnag** [comment]
I use the following [job.defaults]

[job.defaults]
job_type = string
pwatcher_type = blocking
NPROC=8
JOB_QUEUE = debug

submit = qsub -A cscdav -S /bin/bash -V -q ${JOB_QUEUE} -N ${JOB_ID} -o "${STDOUT_FILE}" -e "${STDERR_FILE}" -l nodes=1:ppn=${NPROC},mem=32gb -W block=true "${CMD}"

I get the following error:
qsub: submit error (Undefined attribute  MSG=detected presence of an unknown attribute)
[ERROR]Task Node(0-rawreads/build) failed with exit-code=154

How do I fix this issue ?
Thanks in advance.
