### ISSUE TITLE
Explanation for HPCdaligner_option parameters

### ISSUE THREAD

**Issue by iggyB** [PacificBiosciences/FALCON#527]
Hi,

Could you please briefly explain motivation behind choosing different -l, -k, -h and -w values?

The default HPCdaligner_option parameters are:
```
pa_HPCdaligner_option   =  -e.70 -l1000 -k14 -h35 -w6
ovlp_HPCdaligner_option =  -e.96 -l500  -k14 -h60 -w6 
```

In human (and other large genomes) assembly the parameters where altered, for example:
```
pa_HPCdaligner_option   =  -e0.75 -l4800 -k18 -h480  -w8
ovlp_HPCdaligner_option =  -e0.96 -l2500 -k24 -h1024 -w6
```

Why **-l4800** and **-l2500**?
Why **-k18** and **-k24**?
Why **-h480** and **-h1024**?
Why **-w8** in first overlap?

Even a very short explanation on how to choose these parameters would be appreciated!

Cheers,
Iggy

**Comment by pb-cdunn** [comment]
We simply call Gene Myers' `HPC.daligner`.
* https://dazzlerblog.wordpress.com/command-guides/daligner-command-reference-guide/

**Comment by iggyB** [comment]
Hi,

Che che, I'm familiar with Google ;)

And Gene Myers' daligner reference. And with following sentence:
>our search code looks for a pair of diagonal bands of width 2w (default 26 = 64) that contain a collection of exact matching k-mers (default 14) between the two reads, such that the total number of bases covered by the k-mer hits is h (default 35).

What I was hoping for is to hear why for large genomes you used higher k-mer values? why different h values and why higher w? why different length cut offs? Based on what were you making these changes?

I know you busy, but less simple, more complex answer would be nice.

Cheers,
Iggy

**Comment by pb-jchin** [comment]
well, it is for balancing sensitivity and specificity. With higher k-mer and higher h values, you can reduce the number of alignment due to small repeats. This can save time at some cost that you might loss a bit of true hits.

**Comment by iggyB** [comment]
Hej,

Thanks Jason for explanation. Here comes some feedback which might be interesting for other users.

```
Genome: >3.5Gbp
Data: 200Gb raw subreads
```

Settings used:
```
1) "Loose"
pa_HPCdaligner_option   =  -v -B128 -t16 -e.70 -l4800 -k18 -h480  -s1000 -w8
ovlp_HPCdaligner_option =  -v -B128 -t32 -e.96 -l2500 -k24 -h1024 -s1000
2) "Strict"
pa_HPCdaligner_option =   -v -B128 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B128 -t32 -e.96 -l500 -s1000 -h60
```

Run time:
```
"Loose"  - ~37h
"Strict" - ~93h
```

Stats:
```
Contig # 16K (Loose) vs 12K (Strict)
Longest contig 5Mbp (Loose) vs 10Mbp (Strict)
N50 0.75Mbp (Loose) vs 1.8Mbp (Strict)
```

All in all, if time is not an issue, it is worth running more with more strict parameters. Of course, this is just one example not taking into account other settings or compute resources, but it can give a hit when choosing daligner parameters.

I as well can report that using -s1000 I encountered "Duplicate overlap" issue [515](https://github.com/PacificBiosciences/FALCON/issues/515). I as well had AssertionError [505](https://github.com/PacificBiosciences/FALCON/issues/505), which was solved with commit [f1e392a](https://github.com/PacificBiosciences/FALCON/commit/f1e392a8604ebd7a2f7b6fcc811c776cad07912a).

Cheers,
Iggy

**Comment by lamz138138** [comment]
Hi @iggyB 

I had same discovery after adjust parameter several times, I would get a better result with smaller -l, it is really unlucky that I didn't see this issues.....

Anyway, I want to know with 200G raw data, **why you only take 93h hours, Do you have a supper cluster?** In fact, my cluster have 2 node (64 cpus, 512G memory), 1 node (32 cpus, 512G memory), and 25 small node (16 cpus, 48G memory), it take about four weeks using loose parameters. 

Thanks in advance.

**Comment by iggyB** [comment]
Hi @lamz138138,

Well, at least our observations are concordant :)

The analysis was done on a cluster with 36 nodes each having 16 cores and 128Gb RAM. Length cutoff was 10kb. Block size -s400.

Cheers,
Iggy

**Comment by lamz138138** [comment]
Hi @iggyB 

Thanks for your reply. I have new questions:

1. It seemed our cluster is comparable, why you take only 93h, is it only running time of daligner, or from beginning to get final contigs?

2. For daligner, do you set -M and -t at the same time?  I set both of them as indicated, but this time I tried to set only -t, since I think neither -t16 nor -t32 would use 24G memory. 

3. Do you have any suggestion to speed up my assembly? Since most of my memory is 16G, I set block size as -s100, and the thread of daligner is default 4. Considering IO is a big problem, I feel set concurrent_job as 102 is best. 

Any suggestion would be grateful!

**Comment by iggyB** [comment]
Hi @lamz138138,

1. It is total assembly time.
2. I used -M to be sure that memory limit is not exceeded. Have not done further testing. 
3. IO is important factor. We have fast storage dedicated for Falcon alone and use local tmp folders.

Cheers,
Iggy

**Comment by lamz138138** [comment]
Hi @iggyB 

Thanks for reply! 

1. It is amazing you can finish assembly (3.5Gb) within four days, I want to confirm that you only set -M without setting -t, **am I right?**

2. I am from China, do you also come from China? Time is very important for me, so it would be great if there is cluster that as fast as yours.

3. N50 of your genome is 1.8Mb, which is smaller than public human, gorilla, goat genome, do you get a better result later? 

Best regards!

**Comment by iggyB** [comment]
Hi @lamz138138,

1. Yes
2. Sweden :)
3. The example above was done a year ago. N50 varies from project to project (DNA quality, sequencing depth and etc), but I get anything in range 5Mb to 15Mb for similar size genomes.

Cheers,
Iggy

**Comment by lamz138138** [comment]
Hi @iggyB 

I see. at least I know it is possible to finish assembly in a week, I would try to find other cluster.

Thanks for all your help!

Best wishes.
