### ISSUE TITLE
How many more LA4Falcon/fc_consensus.py jobs yet to be processed?

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#53]
Hi, Jason,

When Falcon starts running the LA4Falcon | fc_consensus.py jobs, is there any way of determining how many are left to go (or how many total)?  

You had pointed me to run_jobs.sh but that only refers to the daligner and LAsort/LAmerge jobs.

Thanks!
David

**Comment by pb-jchin** [comment]
@dgordon562 It work on the unit of "block". The total number of reads in a block in the file `raw_reads.db`.  Of, you can try to use `DBshow.c` to figure it out.  I don't have code for that, but I do sometime do `grep -c ">" out*.fa` under the `preads` directory to check the progress.

**Comment by dgordon562** [comment]
I think I have a simple way to answer this question.  Let me know if I am right.

This will tell you the total number of ct_ jobs (and the total # of m_ jobs).
cd 0-rawreads
 grep "^LAmerge" run_jobs.sh | grep -v L1 | wc

Here is my reasoning and tell me if I'm wrong:

For each m_ job, there are a series of LAsort's and LAmerges ending with a single LAmerge of all of the L2 las files.  That will create a single las file with no L1, L2, C0, C1 ... N0, N1 ...  in the name.  That single las file is the single file input to a single corresponding ct_ job.  So there is a 1-1 correspondence between m_ jobs and ct_ jobs.  We can count the m_ jobs by looking at the run_jobs.sh and counting the LAmerge commands that only involve L2 files.  The command above will do that.

Correct?

If this is true, this will give everyone a good way of determining what % done your m_ and ct_ jobs are.

**Comment by pb-jchin** [comment]
@dgordon562 actually, the number of blocks, the number of `m_*` directory and the number of `ct_*` jobs are the same. The `m_*` directory are pre-created before the consensus jobs, so sometimes I just spot the largest number in `m_*` directory to figure out the number of `ct_*` jobs. 
Yes, you are right the script scans the `run_jobs.sh` generated `HPCalinger` to figure out how many `m_*` directories and  `ct_*` jobs should be.
