### ISSUE TITLE
Circularizing and trimming is still needed for FALCON result?

### ISSUE THREAD

**Issue by wangyugui** [PacificBiosciences/FALCON#530]
Circularizing and trimming is still needed for FALCON result?

If the input of FALCON is subreads, should there be no needs for Circularizing and trimming such as
https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/Circularizing-and-trimming

**Comment by rhallPB** [comment]
If you are generating complete bacterial genomes, then they still need circularizing and trimming before quiver / arrow correction.
I would recommend [http://sanger-pathogens.github.io/circlator/](http://sanger-pathogens.github.io/circlator/).
