### ISSUE TITLE
falcon with PacBio Sequel data

### ISSUE THREAD

**Issue by JeanQin** [PacificBiosciences/FALCON#533]
Does anyone have success using falcon to assembly PacBio Sequel reads?

Sequel provides bam file. I converted them to fasta files that were then used as input for falcon. However it failed immediately without any error message. Any suggestion will be greatly appreciated

**Comment by fbemm** [comment]
We have also Sequel issues. Falcon starts, does 75% of the 0_raw overlap daligner jobs and then dies with the rest of the jobs not being able to find daligner. Probably a slightly different problem.

**Comment by bostanict** [comment]
I also have the same question,

if we want to use falcon on the bam files from seuel, how should we do that? should we convert to fasta or fastq or it can accept the bam files?

thanks

**Comment by xshah** [comment]
it does work for me.
I do convert sequel bams to fasta and use them as input for falcon and after some effort to restart failed jobs( and such) it does finish  💯

**Comment by JeanQin** [comment]
thanks, guys. it worked for me after restarted failed job.

**Comment by pb-cdunn** [comment]
Yes, `bam2fasta` should work, either from [bam2fastx](https://github.com/PacificBiosciences/bam2fastx) or from **pbcoretools**.
