### ISSUE TITLE
Confusing parameter mapping

### ISSUE THREAD

**Issue by bredeson** [PacificBiosciences/FALCON#538]
Hey Falcon Devs,

I don't know if anyone has caught this previously, but I had a heart-stopping moment where I thought I had been doing my assemblies incorrectly for the past year. I took a dive into the source code and found that I was not wrong, but rather Falcon is using a backwardly-mapped set of parameters for some steps. For instance:

* The `overlapping` stage uses `pa_HPCdaligner_option` and `pa_DBsplit_option` (presumbably `pa` = "**P**re-**A**ssembly"?) and all other parameters associated with initial overlapping do not have the "p" prefix (e.g., `sge_option_da`, not `sge_option_pda` etc.).
* The `pre-assembly` stage uses `ovlp_HPCdaligner_option` and `ovlp_DBsplit_option` and all other parameters associated with pre-assembly do have the "p" prefix (`sge_option_pda`, not `sge_option_da` etc.)

Is this intended?

Best
-Jessen

**Comment by pb-jchin** [comment]
> The overlapping stage uses pa_HPCdaligner_option and pa_DBsplit_option (presumbably pa = "Pre-Assembly"?) and all other parameters associated with initial overlapping do not have the "p" prefix (e.g., sge_option_da, not sge_option_pda etc.).

>The pre-assembly stage uses ovlp_HPCdaligner_option and ovlp_DBsplit_option and all other parameters associated with pre-assembly do have the "p" prefix (sge_option_pda, not sge_option_da etc.)


for initial overlaps for error corrections,
```
length_cutoff
sge_option_da
sge_option_la
pa_HPCdaligner_option
```

for pread overlapping to generate assembly/contigs
```
length_cutoff_pr
sge_option_pda
sge_option_pla
ovlp_HPCdaligner_option
```
