### ISSUE TITLE
fc_ovlp_to_graph

### ISSUE THREAD

**Issue by pwmcclurg** [PacificBiosciences/FALCON#54]
Im noticing that "reverse_end" is defined twice (exactly the same) and there is a call to "oreverse_end" that is undefined.  At least that is what PyDev tells me.

Best, Phil

**Comment by pb-jchin** [comment]
which file and which line? should be a simple fix

**Comment by pwmcclurg** [comment]
this is in fc_ovlp_to_graph.py 

def_reverse_end is defined on line 73, and line 433

The call to oreverse is called on line 1084

**Comment by pwmcclurg** [comment]
I meant def reverse_end on 73 and 433

**Comment by pb-jchin** [comment]
thanks. I will remove the 2nd one next time I update the script.
