### ISSUE TITLE
How to determine haplotig positions and SVs.

### ISSUE THREAD

**Issue by a-velt** [PacificBiosciences/FALCON#540]
Dear developer,

I used falcon/falcon-unzip to generate my first _de novo_ genome assembly. Now, I have two files : cns_p_ctg.fasta and cns_h_ctg.fasta. The IDs of my haplotigs contain the ID of the corresponding p-contig and a number, I think that it represent the order of the different haplotigs of a p-contigs ?

Now, I want to align my h-contigs on my p-contigs in order to perform a variant calling and determine the "difference" between one haplotig and its p-contig. Before performing polishing with falcon-unzip, I tested the polishing step on falcon-unzip's output with quiver. I got a "gff" file containing different SVs. But, when I perform the polishing step inside falcon-unzip, I don't have this "gff" file, so it is why I want to align ma h-contigs and perform a variant calling ... 

Do you think this is the right way to determine the differences between my haplotypes and to determine their position on the p-contigs? Do you know a powerful tool to make this alignment? I wanted to use nucmer but it does not generate bam file ... I thought about blast too? Apparently it is possible to convert the blast output into a bam file. Thanks for your advices.

Best,
Amandine

**Comment by gconcepcion** [comment]
Hi Amandine - 

One way to generate a gff track with the variant information would be to use 
nucmer followed by show-coords to convert the delta file into a coordinates file. The coordinates file should have the location information you want, but you could also use:
https://metacpan.org/pod/distribution/Bio-Gonzales/bin/coords2gff.pl to convert to gff format.

Another alternative depending on the max length of your contigs would be to use bwa mem to map the contigs back and generate a bam file.
http://bio-bwa.sourceforge.net/

**Comment by a-velt** [comment]
Dear Greg,

I have aligned my h-contigs against my p-contigs with bwa mem (with the -M option). Here, I have four different flags on my alignments : 0, 16, 272, 256. So, the alignments with the flags 0 or 16 are my primary alignments and the others are my secondary alignments. After the alignments, I have one primary alignment per h-contig, great.

Then I wanted to perform the variant calling on my alignments with samtools mpileup/bcftools. As these tools don't perform the variant calling on the secondary alignments, I created a new alignment file, with less informations : I kept only the alignments with the flags 0 or 16 (so I have one alignment per h-contig in this bam file) and I performed the variant calling.

Here I have all the informations I wanted in my previous post.

When I look at the assignment of the h-contigs, I see that 92% of my h-contigs are assigned to the good contig (the same contig than in the name of the h-contig). But ... have you an explanation of why 8% of my h-contigs are aligned to an other contig ?

Also, if I put my bam file in a genome browser, I see that the order of the haplotigs is not necessarily the same than in their name ... Have you an explanation about that too ?

Overall, I think that the results are good, when I look at my data in a genome browser, it's look good ... and 92% of good assignment is great ! These are just the two previous cases that I don't understand ...

Thank you so much for your response.

Best,
Amandine

**Comment by gconcepcion** [comment]
Hi Amandine,

During consensus calling, it's possible that some lower coverage regions were incorrectly polished for a small percentage of contigs, which is one possible explanation of why ~8% are mapping to an alternate contig. 92% correct sounds like a pretty good number to me :)

The ordering of the haplotigs loosely follows the sequential order of the _XXX suffix, however parts of the graph contain complicated structures resulting from structural variation and  repetitive regions that result in certain contigs being output prior to traversing an alternate graph topology. 

Best,
Greg

**Comment by a-velt** [comment]
Hi Greg,

I found a tool, Assemblytics, which take a delta file as input and perform a great analysis of this file, generating some plots, stats, an interactive dot plot and a bed file of SVs. I put this here, if it interests someone.

Best,
Amandine

**Comment by madhubioinfo** [comment]
Hi Amandine,
Were you able to solve the phasing issue?

**Comment by madhubioinfo** [comment]
@a-velt did you able to solve the issue?
