### ISSUE TITLE
UnboundLocalError: local variable 'preads_fofn_plf' referenced before assignment

### ISSUE THREAD

**Issue by tpshea2** [PacificBiosciences/FALCON#543]
Hellow.  Is there a workaround for the error shown below:

In running a Falcon assembly starting with preads, and thus setting config file:

> input_fofn = preads.fofn
> input_type = preads

Very early on I get this error:

> Traceback (most recent call last):
>   File "/cil/shed/sandboxes/tshea/software/FALCON/new4/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
>     exec(compile(open(__file__).read(), __file__, 'exec'))
>   File "/cil/shed/sandboxes/tshea/software/FALCON/new4/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
>     main(sys.argv)
>   File "/cil/shed/sandboxes/tshea/software/FALCON/new4/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 662, in main
>     main1(argv[0], args.config, args.logger)
>   File "/cil/shed/sandboxes/tshea/software/FALCON/new4/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 423, in main1
>     setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
>   File "/cil/shed/sandboxes/tshea/software/FALCON/new4/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 557, in run
>     make_build_pdb_task  = PypeTask(inputs = {"preads_fofn": preads_fofn_plf },
> UnboundLocalError: local variable 'preads_fofn_plf' referenced before assignment

The only file written to any of the 0-rawreads/ or 1-preads_ovl/ directory  is 

> 0-rawreads/raw-fofn-abs/preads.fofn 

and this just looks like a copy of the input preads.fofn file.

Thus far there is nothing that I can find on the cause of this error.  In trying to figure out the cause I thought it might have been that the read names did not have a unique number in the middle part of the name (for example found that, prolog/142479270/0_15656, might "142479270" repeated in a read from other sample).  I saw on https://github.com/PacificBiosciences/FALCON/issues/249 that this number has to be unique.  Initially I found that some numbers were not unique (see below)  so I correct this.  However, after modifying the read names to be unique and then re-running I still got the  " UnboundLocalError: local variable 'preads_fofn_plf' referenced before assignment " error.

To clarify the above paragraph this is an assembly where preads from two different previous Falcon assemblies were merged together into a single set of pread fofns.  I had to change both fasta file names as well (as indicated above) the fasta headers for one set so that the >prolog/<digit>/ would have a unique digit in the single preads data set.

The preads.fofn file looks something like this (277 total preads fasta files):
 
> /20170405/preads_dir/br.cns_00001.fasta
> /20170405/preads_dir/br.cns_00002.fasta
> ...
> ...
> /20170405/preads_dir/lb.cns_00117.fasta
> /20170405/preads_dir/lb.cns_00118.fasta

and the fasta header is like this (in some cases modified to be unique):

> prolog/142479270/0_15656

I hope this all makes sense and there might be an a quick fix on my end.

Thank you for your help.

**Comment by pb-cdunn** [comment]
Yes, the preads workflow is currently broken. We will address that soon, subject to scheduling.

**Comment by tpshea2** [comment]
Thank you Chris.

Out of curiosity would there be any harm in running falcon with raw reads workflow (so it would start with error correction) yet still give as input the preads?  Would this speed things up?

**Comment by pb-jchin** [comment]
@tpshea2 the code will check dependency, I don't it is hard to "mock" those dependency if I understand what you want to do

**Comment by tpshea2** [comment]
Hi Jason- Thank you for your response.  I now see my explanation of how I am running the assembly is not clear.

What I am doing is taking preads from one previous Falcon assembly and combining this with the preads from a different Falcon assembly (different sample but same species) and running a new Falcon assembly in an entirely new directory (so the code sees this as a new assembly).  I have modified the preads fasta header name so that the number immediately after "prolog/" is unique.

My thinking was that even if preads workflow ("input = preads" in config file) does not work (thus requiring I use "input = raw") that I could still give preads as input and there would just be relatively little to error correct since the starting reads are higher quality.

I hope this all makes sense.  The assembly done this way did complete.  Please let me know if there are any downsides to giving existing preads as "input = raw" for a new Falcon assembly (in new directory).

Thank you for your time.

**Comment by pb-jchin** [comment]
> I hope this all makes sense. The assembly done this way did complete. Please let me know if there are any downsides to giving existing preads as "input = raw" for a new Falcon assembly (in new directory).

Yes, it could work.  The major downside is probably redundant computation. Beside that, how the reads are processed as raw reads and p-reads are different.   The "error correction" using "error corrected" might filter out some useful p-reads that has been error corrected.   In the mean time, the assembly results should valid if you treat p-reads as rawread for running the assembler

**Comment by pb-cdunn** [comment]
@tpshea2, you are running very old code, at least as early as this:
```
commit 166e60367c6cc1b9dc05c8b7e3566cd0ac7fed9b
Author: Christopher Dunn <cdunn@pacificbiosciences.com>
Date:   Fri Sep 30 08:52:32 2016
```
Here is code from that commit which matches your `line 557` stack-trace:
```py
538     # build pread database
539     if config["input_type"] == "preads":
540         preads_fofn_plf = makePypeLocalFile(os.path.join(pread_dir, 'preads-fofn-abs', os.path.basename(config["input_fofn"    ])))
541         make_fofn_abs_task = PypeTask(inputs = {"i_fofn": rawread_fofn_plf},
542                                      outputs = {"o_fofn": preads_fofn_plf},
543                                      parameters = {},
544                                      TaskType = MyFakePypeThreadTaskBase)
545         fofn_abs_task = make_fofn_abs_task(task_make_fofn_abs_preads)
546         wf.addTasks([fofn_abs_task])
547         wf.refreshTargets([fofn_abs_task])
548
549     pdb_build_done = makePypeLocalFile( os.path.join( pread_dir, "pdb_build_done") )
550     parameters = {"work_dir": pread_dir,
551                   "sge_option": config["sge_option_pda"],
552                   "config_fn": input_config_fn,
553                   "config": config}
554
555     run_jobs = makePypeLocalFile(os.path.join(pread_dir, 'run_jobs.sh'))
556     preads_db = makePypeLocalFile(os.path.join(pread_dir, 'preads.db')) # Also .preads.*, of course.
557     make_build_pdb_task  = PypeTask(inputs = {"preads_fofn": preads_fofn_plf },
```
As you can see, `preads_fofn_plf` is *definitely* defined if you properly provided `input_type=preads`. I suspect you mis-typed the `input_type`. I will add a check for `input_type`.

However,
A) I cannot repro your bug as described, even on that old commit, and
B) You need to use a more recent version if you want any support.
