### ISSUE TITLE
Tasks remain unsatisfied

### ISSUE THREAD

**Issue by tbawin** [PacificBiosciences/FALCON#551]
Hi,
I just installed Falcon on a Linux computer.
I tried the fc_run.py fc_run.fcg command using the ecoli dataset.  
Unfortunately it returned this message: Exception: We had 44 failures. 45 tasks remain unsatisfied.
I tried to manually rerun the failed rj*.sh files as suggested but nothing seems to happen.
Is someone could provide me some help?
Have a nice weekend !

**Comment by pb-cdunn** [comment]
You need to `cd` into the run-directory for a failed job. You should look at `stderr/stdout`. (Maybe look under `pwatcher.dir/std*`.)

> I tried to manually rerun the failed rj*.sh files as suggested but nothing seems to happen.

Try running one line at a time in your shell (or add `set -vex` to the `.sh` file). You are having an integration problem, and there is only so much we can help with.
