### ISSUE TITLE
0-rawreads/report job crashing

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#552]
This crashes in various ways with different datasets.  But is this job even necessary?  If not, how can I get Falcon to just bypass it?  I tried using:

report_pa_done

but Falcon ignores it.  Does Falcon now ignore done flags?   If so, how can I get it to bypass
this job?

Thanks!
David

**Comment by dgordon562** [comment]
I should mention that sometimes I can run the *.sh report job from the command line and it completes successfully, even though it failed running under Falcon.  In any case it prevents Falcon from continuing.

**Comment by pb-jchin** [comment]
maybe try to `touch run.sh.done report_pa_done` in `/lustre/hpcprod/jchin/tvaginallis/0-rawreads/report`

**Comment by pb-cdunn** [comment]
@pb-jchin, we solved this via email. The remote machine was using the wrong Python.
