### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by jrdemasi** [PacificBiosciences/FALCON#555]
I've got a few researchers interested in using this software -- could you possibly throw up some tagged releases so we actually know what versions we're using though?  Funzip!? Does that mean something?

**Comment by pb-jchin** [comment]
For the paper, the exact revision is in the supplementary, and this is the tagged version:
https://github.com/PacificBiosciences/FALCON-integrate/tree/funzip_052016

The code is under continuous improvement under git version control.  The idea case is that you can fork it and and modify for your system if necessary.

**Comment by jrdemasi** [comment]
@pb-jchin Do you have intentions to implement a versioning scheme in the future?  E.g. stable releases are 1, 2, etc. and minor revisions would be 1.1, 1.2, ...? 

This makes the software much more approachable and it increases the reproducibility aspect significantly if a researcher can definitively say "I used version 1.3 to attain the results for this research."

**Comment by pb-jchin** [comment]
@jrdemasi It will be decided by the software team in the near future.  I used the exact git revisions for different component in the paper.  For initial rapid development, it was necessary.

**Comment by jrdemasi** [comment]
Alright, thanks!  Looking forward to it.

**Comment by pb-cdunn** [comment]
There are tags on **FALCON-integrate**, the integration package.

* https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation
* https://github.com/PacificBiosciences/FALCON-integrate/releases

**Comment by jrdemasi** [comment]
@pb-cdunn I don't think that's an appropriate means for finding a stable version of Falcon, and for most end-users they're not going to understand how the integration/testing fits in with the package itself.
