### ISSUE TITLE
PBSpro: not going past 0-rawreads/preads/cns_*

### ISSUE THREAD

**Issue by hodgett** [PacificBiosciences/FALCON#556]
I am trying to run falcon on a suse12 cluster with pbs-pro13. I am using a small 2 cell test set of data from our Pacbio sequencer. If I run it as a local job it completes OK. If I run it as a pbs job it does submit jobs to the queue and gets as far as completing 0-rawreads/preads/cns_* jobs then does not go any further. There are no errors, no exit abnormal codes (EXIT 0, returned: 0) except for the usual `OSError: [Errno 2] No such file or directory: ` when removing heartbeats. There aren't any hung jobs, or jobs hitting walltime. 

Are there any clues? How should I go about trouble shooting this when there are no errors being reported? What should be happening after  0-rawreads/preads/cns_* ?

**Comment by vishalcdfd** [comment]
Can you show the fc_run.cfg file that you are running.
Are you using qsub file.sh ???

**Comment by hodgett** [comment]
I will need to check with the research group today if they are ready for 
that information to be released.

**Comment by pb-cdunn** [comment]
It should be easier to customize for PBS-Pro now.
* https://github.com/PacificBiosciences/FALCON/wiki/Configuration
* https://github.com/PacificBiosciences/pypeFLOW/wiki/Configuration
