### ISSUE TITLE
ID mapping between raw subreads and preads after correction

### ISSUE THREAD

**Issue by svm-zhang** [PacificBiosciences/FALCON#567]
Hello,

I am wondering is there a way I can some how find out id mappings between raw subreads and preads after fc_consensus? I'd like to do some benchmarks on performances of error correction. Thanks!

Simo

**Comment by pb-jchin** [comment]
@svm-zhang, you can check the following source code to see how one can trace the identities of the reads:

get_read_ctg_map.py
pr_ctg_track.py
rr_ctg_track.py

**Comment by svm-zhang** [comment]
@pb-jchin Thanks for the point-out. Could I keep this ticket open for now in case I have further questions on this matter.

**Comment by svm-zhang** [comment]
Hello @pb-jchin,

I did some exploration into the script `get_read_ctg_map.py`, and was able to successfully run on my data. Again thanks for pointing out.

In case someone else want the id mapping between raw and corrected reads **without waiting for the entire assembly finish**, the function `task_generate_read_to_ctg_ma` in the script `pype_task.py` explains the relation. For example, ids of error corrected reads for my virus dataset are in a format like `prolog/80/0_1324`. The second field `80`, divided by 10, gives the index of the raw read, i.e. 8th sequence in the raw read fasta file.

In a more complex case where you have `prolog/20/0_572` and `prolog/21/0_631`, my understanding is that the 2nd raw read being split into two corrected sequences possibly due to low cov (specified by --min_cov in the fc_consensus command line). Though I am not sure where are their original starting points in the raw read.

In case I am totally off here, please do correct me :)

Simo

**Comment by pb-jchin** [comment]
@svm-zhang I think you are right. Since I only have a number on the 2nd, I need to do some simple encoding. The downsize is that we won't be able to handle the case when a read is split into more then 10 pieces. (It is not supposed to happen in my opinion.)  

For the starting point, if it is important for you, just do a simple alignment....
