### ISSUE TITLE
identification of segmental duplication from contigs

### ISSUE THREAD

**Issue by madhubioinfo** [PacificBiosciences/FALCON#569]
I have tried assembling genome with the falcon assembler, it produced the assembly smaller than the expected genome size and the genome is highly repetitive and we think that lot of segmental duplication are happening in the genome, and i got more alternate contig than p contig and how can i find the contigs which are duplicated in the genome , i used the older version of Falcon ie Falcon integrate , any suggestions? . the genome size 71 ~ 75 Mb and assembled P_ctg is 60 Mb and a_ctg is 15 Mb .

**Comment by nottwy** [comment]
The p_ctg is 60 Mb and a_ctg is 15 Mb. Why did you say "more alternate contig than p contig"?

**Comment by BioWu** [comment]
@madhubioinfo Please try [get_homologs.py](https://github.com/PacificBiosciences/apps-scripts/blob/master/FALCONAssemblyTools/get_homologs.py) as reported [here](https://pb-falcon.readthedocs.io/en/latest/_downloads/Kingan_DiploidGenome_ECUGM2017_BFX.pdf).
Hope this will be helpful.
