### ISSUE TITLE
unable to run fc_run.py on SGE

### ISSUE THREAD

**Issue by mahulchak** [PacificBiosciences/FALCON#57]
Hi,
I am trying to run Falcon on SGE. I have a cfg file that is similar to the generic cfg file you have provided. However, I can't find the information on how to provide the job_type, sge_option for the pipeline. I tried entering them in the cfg file but the script prepare_db.sh that the first command generates in the 0-rawreads folder is not submitted to the grid by the pipeline. Am I missing something? I am appending first part of my cfg file for your convenience :

<pre>[General]
job_type = SGE
job_name = tes
sge_option = -q bio -ckpt blcr -l kernel=blcr 
# list of files of the initial subread fasta files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 12000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 12000</pre>

Thanks.
Mahul

**Comment by Imoteph** [comment]
Hi,

You don't have to specify SGE, as use it as default mode.
Regarding the other option you can add them to the sge_option (see ecoli.cfg)

**Comment by pb-jchin** [comment]
@mahulchak @Imoteph is right, the string in configuration variable `sge_option_*` will be included in `qsub` command as-is.  You should consult with your local cluster admin to see what is the best option.  There are multiple different `sge_option_*` as different steps have different computational requirement. You can fine-tune that to fit your computation infrastructure.

**Comment by mahulchak** [comment]
Thanks for the quick response. I spoke with the sys admins and they asked me if python virtual env is absolutely necessary for the pipeline to work. We are trying to figure out why automated job submission by the pipeline is not working. The admins want me to try the pipeline without the virtual env so the information about whether python virtual env is necessary or not will be helpful.

**Comment by pb-cdunn** [comment]
**virtualenv** is not strictly necessary, but without it you will have to find your own way to install Python and make the modules available in your environment.

You might try the new **[FALCON-integrate](../../FALCON-integrate)**. At least it gives you a more controlled, repeatable environment.
