### ISSUE TITLE
fc_run.cfg for a 550MB insect genome

### ISSUE THREAD

**Issue by hermeseduardo** [PacificBiosciences/FALCON#579]
Hi folks,
we have been trying to run Falcon with the *.cfg bellow. But the number of jobs is too large and it is taking forever and crashing from time to time, so far I have not been able to get any results, can not go further from the steps in 0-raws . Could you please provide any suggestion in to improve performance? particularly with the sge_options.
The genome is about 550MB full of nasty repeats. The coverage is about 44X (~2 million reads), and eventually I will try a length_cutoff of 3000 reads. It is running in a cluster with nodes of 3TB.
thanks!

**fc_run.cfg**

[General]
input_fofn = input.fofn
input_type = raw
length_cutoff = 10000
genome_size = 550000000
length_cutoff_pr = 10000
job_type = SLURM
job_queue = defq
sge_option_da = --ntasks 1 --nodes 1 --cpus-per-task 5 --mem 12gb --time 0:15:00
sge_option_la = --ntasks 1 --nodes 1 --cpus-per-task 4 --mem 32gb --time 10:40:00
sge_option_cns = --ntasks 1 --nodes 1 --cpus-per-task 4 --mem 80gb --time 5:40:00
sge_option_pda = --ntasks 1 --nodes 1 --cpus-per-task 4 --mem 80gb --time 5:30:00
sge_option_pla = --ntasks 1 --nodes 1 --cpus-per-task 4 --mem 25gb --time 5:30:00
sge_option_fc = --ntasks 1 --nodes 1 --cpus-per-task 4 --mem 26gb --time 5:31:00
da_concurrent_jobs = 296
la_concurrent_jobs = 296
cns_concurrent_jobs = 296
pda_concurrent_jobs = 296
pla_concurrent_jobs = 296
pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -t32 -h60 -e.96 -l500 -s1000
pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200
overlap_filtering_setting = --max_diff 40 --max_cov 30 --min_cov 4 --bestn 10

**Comment by mseetin** [comment]
Hi,

You should set the -s of your *DBsplit_options to -s400 or so, and the -B
of your *HPCdaligner_options to -B128 or so.  That will greatly reduce the
number of jobs.

**Comment by hermeseduardo** [comment]
THANKS!! yeap certainly less jobs, I was aware that -s400 is related to the number of jobs but could you please explain in more detail what is the -B argument? and how it may affect the assembly?

**Comment by mseetin** [comment]
B is the number of read blocks that get compared for each job submission. s
is the size of the read blocks. Neither should impact assembly contiguity,
only how the job runs.

**Comment by hermeseduardo** [comment]
cool, thanks again!!
