### ISSUE TITLE
How to find circular contigs?

### ISSUE THREAD

**Issue by a-velt** [PacificBiosciences/FALCON#585]
Hi,

I have a question about finding circular contigs. 

I want to remove contigs corresponding to the mitochondria and chloroplasts. So, I launched "purge_haplotigs" tool, that I found in one of your presentation here : 
http://www.pacb.com/wp-content/uploads/Sarah-Kingan-PacBio-East-Coast-Bioinformatics-Workshop-2017.pdf

I detected the over-covered contigs. Now, as described in the presentation, I have to find the circular contigs. After that, I will "blast" these contigs to see if they correspond to organelles, and if yes, I remove them from my genome assembly (and later, I will try to assemble them with Circulator or other tool, but its not my priority for now).

In the 2-asm-falcon/p_ctg.fa file, I see several contigs with "F" at the end, I undestood that it's my linear contigs. Then, I find  some contigs without "F" at the end, the name is of type "2376". So, this is the circular contigs ? I don't find them in my assembly after FALCON-unzip. So FALCON-unzip remove them ? 
And they aren't in my assembly after this step ? And if later I want to recover them, I can take all the contigs without "F" in 2-asm-falcon/p_ctg.fa, "blast" them and perform the organelle assembly ?

Thank you for your response.

Best,
Amandine

**Comment by skingan** [comment]
Hi Amandine,

The nonlinear contigs (those that lack the 'F' or 'R' notation) are circular, the full header specifies this:

e.g.
>1675 008889063:E~003766027:B~008889063:E~008889063:E ctg_circular 50123 102418

FALCON-Unzip discards contigs that don't end in 'F' or 'R'.

Some of these may be true circular chromosomes, others may be repetitive regions that form a complex graph. In addition, some of the 'F' and 'R' contigs may come from circular chromosomes but the overlap graph is less complex. When we assemble bacterial chromosomes, for example, the major contig is usually linear. So it is possible that your mtDNA and cpDNA are in you linear contigs.

Another clue to finding these chromosomes is coverage, which should be higher than for the nuclear genome. If you have polished your genome with Resequencing or fc_quiver, you can find contigs with unusually high raw read depth.

-Sarah

**Comment by a-velt** [comment]
Hi Sarah,

Thank you for your response.

I used blastx to see if my circular contigs matched the genomes of mitochondria or chloroplasts, but they match only in small places, which might be more like insertions of mitochondrial DNA rather than the mitochondrial genome itself.

Contigs with high raw read depth match rather repetitive regions than genomes of mitochondria or chloroplasts, so maybe that I don't have these genomes in my assembly or they are linear and not with high raw read depth. Maybe I will see them later, after further investigations.

So thank you for your help and have a nice day.

Best,
Amandine
