### ISSUE TITLE
fc_quiver.py fails on Drosophila data because of P5-C3 chemistry

### ISSUE THREAD

**Issue by ybukhman** [PacificBiosciences/FALCON#591]
Dear FALCON developers,

I am using the D. melanogaster dataset described in https://github.com/PacificBiosciences/DevNet/wiki/Drosophila-sequence-and-assembly as a test case to make sure FALCON and FALCON-unzip can run on my systems. I have an issue with the last step of the workflow, fc_quiver.py. It does not throw an error, but the output files are empty:
```
bash-4.1$ ls -l 4-quiver/cns_output/
total 87
-rw-rw-r-- 1 ybukhman mir   0 Nov 13 16:40 cns_h_ctg.fasta
-rw-rw-r-- 1 ybukhman mir   0 Nov 13 16:40 cns_h_ctg.fastq
-rw-rw-r-- 1 ybukhman mir   0 Nov 13 16:40 cns_p_ctg.fasta
-rw-rw-r-- 1 ybukhman mir   0 Nov 13 16:40 cns_p_ctg.fastq
-rw-rw-r-- 1 ybukhman mir   0 Nov 13 16:40 job_done
lrwxrwxrwx 1 ybukhman mir  90 Nov 13 16:40 pwatcher.dir -> /mnt/isi4homes/ybukhman/assy/stdout/falcon/drosophila/try7/mypwatcher/jobs/P8edd9327929fe3
-rw-rw-r-- 1 ybukhman mir 211 Nov 13 16:40 run.sh
-rw-rw-r-- 1 ybukhman mir   0 Nov 13 16:40 run.sh.done
-rw-rw-r-- 1 ybukhman mir 699 Nov 13 16:40 task.json
-rw-rw-r-- 1 ybukhman mir 161 Nov 13 16:40 task.sh
```

File 4-quiver/cns_output/pwatcher.dir/stderr has multiple warnings like this:

> 2017-11-13 16:40:26,170 - falcon_unzip.run_quiver - DEBUG - $('zcat /mnt/isi4homes/ybukhman/assy/stdout/falcon/d
> rosophila/try7/4-quiver/000000F/cns-000000F.fasta.gz >> /mnt/isi4homes/ybukhman/assy/stdout/falcon/drosophila/tr
> y7/4-quiver/cns_output/cns_p_ctg.fasta')
> 
> gzip: /mnt/isi4homes/ybukhman/assy/stdout/falcon/drosophila/try7/4-quiver/000000F/cns-000000F.fasta.gz: unexpected end of file
> 2017-11-13 16:40:26,205 - falcon_unzip.run_quiver - WARNING - Call 'zcat /mnt/isi4homes/ybukhman/assy/stdout/falcon/drosophila/try7/4-quiver/000000F/cns-000000F.fasta.gz >> /mnt/isi4homes/ybukhman/assy/stdout/falcon/drosophila/try7/4-quiver/cns_output/cns_p_ctg.fasta' returned 256.
> 

File 4-quiver/000000F/pwatcher.dir/stderr has these errors:

> (/isitools/pacbio/smrtlink5/smrtcmds/bin/variantCaller --algorithm=arrow -x 5 -X 120 -q 20 -j 24 -r /mnt/isi4homes/ybukhman/assy/stdout/falcon/drosophila/try7/4-quiver/quiver_scatter/000000F/000000F_ref.fa aln-000000F.bam            -o /mnt/isi4homes/ybukhman/assy/stdout/falcon/drosophila/try7/4-quiver/000000F/cns-000000F.fasta.gz -o /mnt/isi4homes/ybukhman/assy/stdout/falcon/drosophila/try7/4-quiver/000000F/cns-000000F.fastq.gz) || echo quvier failed
> \+ /isitools/pacbio/smrtlink5/smrtcmds/bin/variantCaller --algorithm=arrow -x 5 -X 120 -q 20 -j 24 -r /mnt/isi4homes/ybukhman/assy/stdout/falcon/drosophila/try7/4-quiver/quiver_scatter/000000F/000000F_ref.fa aln-000000F.bam -o /mnt/isi4homes/ybukhman/assy/stdout/falcon/drosophila/try7/4-quiver/000000F/cns-000000F.fasta.gz -o /mnt/isi4homes/ybukhman/assy/stdout/falcon/drosophila/try7/4-quiver/000000F/cns-000000F.fastq.gz
> Arrow: unsupported chemistries found: (P5-C3)
> \+ echo quvier failed
> 

I have verified that the D. melanogaster dataset is indeed P5-C3. However, the data I really need to work with are Sequel. 

I have the following questions:
1. Can anything be done to make fc_quiver.py work with P5-C3 data?
2. Does fc_quiver.py work with Sequel data?
3. Is there a small Sequel dataset that I could use for testing instead of the D. melanogaster data?

Thanks!

Yury

**Comment by skingan** [comment]
Hi Yury,

Yes, fc_quiver is compatible with Sequel data. You can find an arabidopsis Sequel dataset here:

https://www.pacb.com/blog/sequel-system-data-release-arabidopsis-dataset-genome-assembly/

Sarah
