### ISSUE TITLE
how to set option 'input_type' in FALCON

### ISSUE THREAD

**Issue by amiably** [PacificBiosciences/FALCON#593]
Hi, FALCON team,
     It means .fasta data as input file regardless of input_type option 'raw' or 'pread' in the manual(https://github.com/PacificBiosciences/FALCON/wiki/Manual). It aslo sets option 'raw' in the FALCON-example(Ecoli, Ecoli2 or synth0), but the type of the these files is dexta file. So my question is that whether option 'raw' can include two formats of input_type, subreads.fasta and .dexta? 
   Thank you for your attention.

**Comment by skingan** [comment]
Hello,
FALCON only takes fasta format as input.
Sarah
