### ISSUE TITLE
1-preads_ovl/job_*/rj_*.sh failed with "daligner: DB preads has only 136 blocks"

### ISSUE THREAD

**Issue by JifengTang** [PacificBiosciences/FALCON#594]
does anymore have such errors?

some jobs under 1-preads-ovl always failed.
I tried to run sh rj_*.sh and it outputed
"daligner: DB preads has only 136 blocks", then stopped.

Thank you very much.

**Comment by pb-cdunn** [comment]
I think that bug has been fixed.
