### ISSUE TITLE
Would -t be useless when set -M for daligner?

### ISSUE THREAD

**Issue by lamz138138** [PacificBiosciences/FALCON#596]
Hi,

According to example of fc_run.cfg, -t and -M were both set, on this occasion, would -t become useless? 

Best wishes!

**Comment by cschin** [comment]
no. when I tracde the code last time (~2 yr ago), there were two code branches. both will be executed. You should check with @thegenemyers https://github.com/thegenemyers/DALIGNER to be sure.

**Comment by lamz138138** [comment]
@cschin OK, thanks for your suggestion!

**Comment by pb-cdunn** [comment]
But Gene suggests setting *only* `-M`. That's more predictable.

**Comment by cschin** [comment]
All I can say is that I went to trace the code because I got sub-optimum results when I did only use -M according to Gene's recommendation. I did not do much FALCON assembly anymore, YMMV.
