### ISSUE TITLE
task_build_rdb vs task_build_pdb

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/FALCON#597]
Hi,
What is the difference between those two methods?

https://github.com/PacificBiosciences/FALCON/blob/67fec11556e135e0d3409558c5fd00f66f89ad2d/falcon_kit/mains/run1.py#L213

https://github.com/PacificBiosciences/FALCON/blob/67fec11556e135e0d3409558c5fd00f66f89ad2d/falcon_kit/mains/run1.py#L375

Thank you in advance.

Michal

**Comment by cschin** [comment]
Unofficial answer (Is there an official one?)
rdb = raw read db
pub = pread read db (pread = pre-assembled read ~= error corrected reads)
