### ISSUE TITLE
Missing daligner las file

### ISSUE THREAD

**Issue by pb-jchin** [PacificBiosciences/FALCON#6]
In some file system, the las output files might not create correctly due to file system issue.  The log shows the block comparisons are fine, but empty files are generated.  This makes the merging step fails but the root cause is not in the merging step.  This is actually a file system issue, but it is worth to track this to see if there is a work-around.

Example:

```
$ find . -wholename "*job*.las" | xargs ls -l | awk '$6 == 0' | less
-rw-r--r-- 1 jchin Domain Users      0 Dec  3 08:14
./job_00087/preads.59.preads.88.N0.las
-rw-r--r-- 1 jchin Domain Users      0 Dec  3 08:14
./job_00087/preads.59.preads.88.N2.las
-rw-r--r-- 1 jchin Domain Users      0 Dec  3 08:14
./job_00087/preads.88.preads.59.N0.las
-rw-r--r-- 1 jchin Domain Users      0 Dec  3 08:15
./job_00028/preads.25.preads.29.C3.las
-rw-r--r-- 1 jchin Domain Users      0 Dec  3 08:15
./job_00028/preads.29.preads.25.C0.las
-rw-r--r-- 1 jchin Domain Users      0 Dec  3 15:17
./job_00109/preads.110.preads.36.N2.las
-rw-r--r-- 1 jchin Domain Users      0 Dec  3 15:17
./job_00109/preads.36.preads.110.N0.las
-rw-r--r-- 1 jchin Domain Users      0 Dec  3 15:17
./job_00109/preads.36.preads.110.N3.las
-rw-r--r-- 1 jchin Domain Users      0 Dec  3 12:20
./job_00108/preads.18.preads.109.N3.las
-rw-r--r-- 1 jchin Domain Users      0 Dec  3 12:20
./job_00108/preads.109.preads.18.N3.las
-rw-r--r-- 1 jchin Domain Users      0 Dec  3 12:20
./job_00108/preads.18.preads.109.N0.las
-rw-r--r-- 1 jchin Domain Users      0 Dec  3 12:20
./job_00108/preads.18.preads.109.N2.las
-rw-r--r-- 1 jchin Domain Users      0 Dec  3 12:22
./job_00098/preads.16.preads.99.N0.las
-rw-r--r-- 1 jchin Domain Users      0 Dec  3 12:22
./job_00098/preads.16.preads.99.N2.las
-rw-r--r-- 1 jchin Domain Users      0 Dec  3 12:22
./job_00098/preads.99.preads.16.N0.las
```

All the `daligner` log shows these blocks are compared nicely.

In this case, the workflow is just idle since the necessary sentinel files are not generated due to the errors.

To recover, one needs to terminate`fc_run.py`, kill all jobs. remove the sentinel files `job_*done` for the problematic jobs, and restart the workflow.

**Comment by pb-cdunn** [comment]
We could force our wait-loop to wait for all .las files, but that might wait forever. I saw code in pypeFLOW which seems designed to update the network filesystem cache. Let's re-open this if it happens again.
