### ISSUE TITLE
sorry to bother you, but I have two questions

### ISSUE THREAD

**Issue by yingzhang121** [PacificBiosciences/FALCON#60]
Hi, Chin,

I have not been able to make FALCON running in our system.  So the first issue is when I ran
$ fc_run.py fc_run_ecoli.cfg
 No target specified, assuming "assembly" as target
qsub: script file 'smp' cannot be loaded - No such file or directory
qsub: script file 'smp' cannot be loaded - No such file or directory
......

Don't know where I should search for the smp script.

That is my first issue.

Then I decided to run the pipeline step by step.
So I first "$ cd 0-rawreads".
And ran " $ sh prepare_db.sh"

After a few minutes, the job was done without any warning or error message, however, in the directory, I only got the following files:

$ ls
db_build.log  prepare_db.sh  raw_reads.db  rdb_build_done  run_jobs.sh

Then I tried:
$ sh run_jobs.sh

Building index for raw_reads.1

   Kmer count = 49,943,490
   Using 0.74Gb of space
   Revised kmer count = 49,876,154
   Index occupies 0.37Gb

Building index for c(raw_reads.1)

   Kmer count = 49,943,490
   Using 0.74Gb of space
   Revised kmer count = 49,876,154
   Index occupies 0.37Gb

Comparing c(raw_reads.1) to raw_reads.1

   Capping mutual k-mer matches over 10000 (effectively -t100)
   Hit count = 13,538,725
   Highwater of 0.94Gb space

     13,538,725 14-mers (5.414721e-09 of matrix)
         51,983 seed hits (2.079025e-11 of matrix)
         41,009 confirmed hits (1.640127e-11 of matrix)
....

And got a bunch of raw_reads.1.raw_reads.1.C0.las ...

Am I on the right track? 

Best,
Ying

**Comment by pb-jchin** [comment]
smp is for SGE's parallel environment.  It is not a script.  You will need to work with your system admin to figure out the proper PE environment to use.

The rest is on the right track, but you will still need to do it automatically someway.
