### ISSUE TITLE
Running Falcon assembly steps manually

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/FALCON#603]
Hi, 
Is it possible to run all [thegenemyers](https://github.com/thegenemyers) tools manually and provide the results to FALCON?

The reason for is that we are not able to get FALCON running on our PBSpro cluster.

Thank you in advance.

Michal

**Comment by nottwy** [comment]
Of course you can. But it will take you a lot of time to do so.
I can provide you general idea.
daligner->LAmerge->generate preads.

**Comment by mictadlo** [comment]
My steps so far were:
## Creating database
```
source activate thegenemyers
find /work/waterhouse_team/All_RawData/Each_Cell_Raw/ -name "*.arrow" -type f > fasta2DB_input.fofn
sed -i.bak 's|.arrow|.fasta|g' fasta2DB_input.fofn
fasta2DB bananaDB -ffasta2DB_input.fofn

DBsplit -x500 -s250 bananaDB
DBdust bananaDB
Catrack -v DB dust
```


## TANmask
```
source activate thegenemyers
HPC.TANmask bananaDB -mdust -T4 -fTANmask
sh HPC.parallel_pbs.sh TANmask.01.OVL             #MEM:9GB; CPU time:00:06:25
sh HPC.parallel_pbs.sh TANmask.02.CHECK.OPT       #MEM:0.3GB; CPU time:00:00:02
sh HPC.parallel_pbs.sh TANmask.03.MASK            #MEM:0.4GB; CPU time:00:00:01  
sh TANmask.04.RM
qsub catrackTAN_pbs.sh
#      Catrack -v bananaDB tan
#      rm .bananaDB.*.tan.*
PBS Job 2678948.pbs
CPU time  : 00:00:01
Wall time : 00:00:11
Mem usage : 8164kb
```

## HPC.REPmask
```
source activate thegenemyers
HPC.REPmask -g1 -c20 -mdust -mtan bananaDB -T4 -fREPmask
sh HPC.parallel_pbs.sh REPmask.01.OVL           #MEM:30GB; CPU time:02:00:01
sh HPC.parallel_pbs.sh REPmask.02.CHECK.OPT     #MEM:1.4GB; CPU time:00:00:03
sh HPC.parallel_pbs.sh REPmask.03.MASK          #MEM:0.01GB; CPU time:00:00:06
sh REPmask.04.RM
Catrack -v bananaDB rep1
rm .bananaDB.*.rep1.*
```

## HPC.daligner
```
source activate thegenemyers
DBstats -b1 -mdust -mtan -mrep1 bananaDB > DBstats.out

/work/waterhouse_team/apps/bin> python  calc_cutoff.py --genome_size 1800000000 --coverage 38 --db_stats
/work/waterhouse_team/banana/assembly/DBstats.out
6973

HPC.daligner -mdust -mtan -mrep1 -H6973 -T4 -fdaligner bananaDB   
sh HPC.parallel_pbs.sh daligner.01.OVL
sh HPC.parallel_pbs.sh daligner.02.CHECK.OPT  
sh HPC.parallel_pbs.sh daligner.03.MERGE  
sh HPC.parallel_pbs.sh daligner.04.CHECK.OPT  
sh HPC.parallel_pbs.sh daligner.05.RM.OPT  
sh HPC.parallel_pbs.sh daligner.06.MERGE  
sh HPC.parallel_pbs.sh daligner.07.CHECK.OPT  
sh daligner.08.RM

```
I also would like to run [DASCRUBBER](https://github.com/thegenemyers/DASCRUBBER)

Could you please provide more information on how to run LAmerge and generate preads? I also found few steps describe here https://github.com/PacificBiosciences/FALCON/issues/111#issue-91020753 but I am not quite sure about LAmerge, LA4Falcon and the assembly step?

**Comment by mictadlo** [comment]
I started to use DASCRUBBER but I got stuck https://github.com/thegenemyers/DASCRUBBER/issues/11 .

**Comment by skingan** [comment]
Hi Michal, Have you had any luck running FALCON on your cluster since you filed this issue?
Sarah

**Comment by mictadlo** [comment]
I almost done with the DASCRUBBER steps. Almost halfway through.

**Comment by mictadlo** [comment]
All steps and scripts how I ran it can be found [here](https://github.com/mictadlo/FALCON-manually). Please let me know what can be improved and how to make it compatible with falcon_unzip.

**Comment by pb-cdunn** [comment]
If you want help getting FALCON to work on your cluster, please show us your `.cfg` file.

**Comment by mictadlo** [comment]
Please find [here](https://github.com/mictadlo/FALCON-manually) how I got it manually running. I am not quite sure whether it is compatible with falcon_unzip.

**Comment by pb-cdunn** [comment]
We cannot help you with that. However, if you show us your problem with using pypeflow, we could probably help you get that working.
