### ISSUE TITLE
DB2Falcon and LA4Falcon adding to the new daligner

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/FALCON#605]
Hi,
Could anyone please add `DB2Falcon` and `LA4Falcon` to the new daligner version https://github.com/thegenemyers/DALIGNER/issues/75

Thank you in advance,

Michl

**Comment by nottwy** [comment]
These two tools are designed for falcon and are not part of daligner.

**Comment by mictadlo** [comment]
Where can I find the latest version of this tools?

**Comment by mictadlo** [comment]
[Here](https://github.com/PacificBiosciences/DALIGNER) is the repository

**Comment by mictadlo** [comment]
Are there any plans to add `DB2Falcon` and `LA4Falcon` to the [thegenemyers repository] `https://github.com/thegenemyers/DALIGNER`?
