### ISSUE TITLE
fso, fog  or fo option for LA4Falcon

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/FALCON#606]
Hi
When should I use `fso`, `fog` or `fo`? I have tetraploid plant genome (1.8GB).

```
    if config["falcon_sense_skip_contained"]:
        LA4Falcon_flags += 'fso'
    elif config["falcon_sense_greedy"]:
        LA4Falcon_flags += 'fog'
    else:
        LA4Falcon_flags += 'fo'
```

Thank you in advance.

Michal

**Comment by skingan** [comment]
Hi Michal,

I would recommend against "falcon sense greedy" if your haplotypes are similar. "falcon sense skip contained" is rarely used except in particular cases.

Therefore: use 'fo.'

Sarah

**Comment by mictadlo** [comment]
Thank you, I will try it out.
