### ISSUE TITLE
How to deal with overlapping haplotigs ?

### ISSUE THREAD

**Issue by a-velt** [PacificBiosciences/FALCON#607]
Hi,

I have come a long way in assembling my diploid genome with FALCON / FALCON-unzip, but now, I think my genome is really good, thank you for this really nice tool !

But I still have a problem in this assembly, it's the overlapping haplotigs.

Here is an image of what I explain:  
https://www.dropbox.com/s/eog3q91v2lrigrd/overlapping_haplotigs.PNG?dl=0

I have about 25% of my haplotigs taken by a case like this. They overlap on a small part (the end of one haplotig and the beginning of another). I have the impression that FALCON has trouble managing the passage between two haplotigs. Strangely, I often see that part of this overlap is equal to the reference and the other part to the haplotype.

Do you have a solution for these overlaps? I can keep them, but it is not clean, because in some places of my genome, I would have "3 haplotypes".

Best,
Amandine

**Comment by cschin** [comment]
ping @skingan or @gconcepcion for this. When you have 3 haplotyes, it is likely (1) some error induce extra branch in the assembly graph (2) lager duplication appearing as an extra haplotypes.   It will need some extra analysis to tell what is the case.

**Comment by skingan** [comment]
Hi Amadine,
As Jason said, its hard to diagnose the issue with just the contig mapping. The simplest explanation would be that the haplotigs share a node in the graph where they were extracted from. Another possibility is a collapsed tandem duplication.

Here is a slide deck from one of our UGMs, see slides 17-18 to see how others handle this.

http://www.pacb.com/wp-content/uploads/2017-WC-UGM-Kevin-Fengler-From-Contigs-to-Chromosomes-High-throughput-Crop-Reference-Genomes.pdf

Sarah

**Comment by a-velt** [comment]
Hi Sarah,

Thank you for your response. Have you wrote a script to determine one hybrid contig per overlap and to trim this overlap from one contig ? Because yes it's a good idea,  I thought about it, but the overlap is never perfectly the same and it's hard to choose the sequence to keep or not at some bases ... But I know it will never be perfect, so if you don't have an existing script, I will create one to follow this procedure. Just a last thing, I don't understand what the "re-run hybrid scaffold" step means?

Best,
Amandine

**Comment by skingan** [comment]
Hi Amandine,

I don't have a script to do that now, so go ahead and write it!

The hybrid scaffold refers to a PacBio - Bionano assembly.

Sarah

**Comment by mictadlo** [comment]
Hi all,
[DASCRUBBER](https://github.com/rrwick/DASCRUBBER-wrapper#method) could maybe help.

Michal
