### ISSUE TITLE
Running example from paper

### ISSUE THREAD

**Issue by rob123king** [PacificBiosciences/FALCON#608]
I have installed as below using the binaries and seems fine
cd /home/data/bioinf_resources/programming_tools/
#use virtualenv-2.7
unset PYTHONPATH
source falcontest/bin/activate
tar xvzf falcon-2017.11.02-16.04-py2.7-ucs4.tar.gz -C falcontest
export LD_LIBRARY_PATH=falcontest/lib:${LD_LIBRARY_PATH}
export PYTHONPATH=/home/apps/python/lib64/python2.7/site-packages
pip install pandas
easy_install --upgrade numpy

#setpath for mummer nucmer and show-cords
export PATH=/home/data/bioinf_resources/programming_tools/mummer-3.9.4alpha:$PATH

How do I run the example data, what commands and config files to use:
I can download the raw data from ENA using project codes below but then what next?
Arabidopsis data: PRJNA314706
V. vinifera cv. Cabernet Sauvignon: PRJNA316730
I've downloaded the config files from below for a test run:
https://github.com/PacificBiosciences/FALCON_unzip/tree/master/examples
And changed the line in fc_unzip.cfg to below:
smrt_bin=/home/data/bioinf_resources/programming_tools/falcontest/bin/

Is this correct so far? If so what do I do next to run it?

**update:**
I've downloaded the example assemblies file which comes with the config files used:
/home/data/bioinf_resources/programming_tools/falcontest/assemblies/grape_assembly/
cns_h_ctg.fasta  fc_run.cfg    input.fofn
cns_p_ctg.fasta  fc_unzip.cfg  unzip.sh
Assume download the raw data and put paths in “input.fofn” but then how to start it..

*update2**
I have downloaded the raw data for the arabidopsis assembly as a test first. I ahve updated the input.fofn file with locations and smrtanalysis location in fc_unzip.cfg

The unzip.sh file first command has changed in the pre-built binaries
"This fc_track_reads.py" has become "fc_track_reads_htigs0.py"
Change made but when run first command get the below error

fc_track_reads_htigs0.py
No handlers could be found for logger "pypeflow.simple_pwatcher_bridge"
Traceback (most recent call last):
  File "/home/data/bioinf_resources/programming_tools/falcontest/bin/fc_track_reads_htigs0.py", line 11, in <module>
    load_entry_point('falcon-unzip==0.4.0', 'console_scripts', 'fc_track_reads_htigs0.py')()
  File "/scratch/cdunn/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/mains/track_reads_htigs0.py", line 338, in main
  File "/home/data/bioinf_resources/programming_tools/falcontest/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 273, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/data/bioinf_resources/programming_tools/falcontest/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 339, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads), Node(1-preads_ovl)])

**Comment by skingan** [comment]
Hi Rob,
Have you run FALCON already? FALCON-Unzip need to be run within a FALCON job directory. [This](http://pb-falcon.readthedocs.io/en/latest/index.html) may be helpful. 
Sarah

**Comment by rob123king** [comment]
ah ok thanks. I was using pacbio fastq data from ENA which was the wrong format, should ahve been fasta. I took it from ENA not thinking about the format. Plus my config file wasn't right, using the config file from falcon tutorial I got Falcon to complete although a "lfs setstripe not found command", still seemed to complete. I just need to try falcon unzip now which I am less sure of. I think I need to create the bam files by mapping the reads to the assembly and as above run within a falcon job directory?

**Comment by skingan** [comment]
Hi Rob. FALCON-Unzip requires both fasta and BAM files for the subreads. Note, the subreads.bam file is not fasta reads mapped to the reference, but rather the processed subreads off the sequencing machine with corresponding qualities and other information used in genomic consensus with arrow.

http://pacbiofileformats.readthedocs.io/en/5.0/BAM.html
https://github.com/PacificBiosciences/GenomicConsensus

If you don't have this format for your test dataset, consider using the arabidopsis sequel [dataset](https://www.pacb.com/blog/sequel-system-data-release-arabidopsis-dataset-genome-assembly/).

Sarah

**Comment by rob123king** [comment]
I've downloaded the grape data set from ncbi which is bax.h5 format. I can't find subreads.fasta format for falcon anywhere for these two datasets of grape and arabidopsis? So I'm not unzipping and converting to fasta for falcon to use using the below command. Hopefully this data will be fine to use in this format for falcon?
`for i in ./*bax.h5 ;do pls2fasta $i $i.fasta -trimByRegion -minSubreadLength 1000;done`
I will then try an assembly using some of the files as there are a lot and see if falcon completes on this, then move on to falcon unzip. I'm just trying to verify the install worked but need heterozygous data for the unzip part. There is heterozygous yeast data which would be good as example data to use from start to finish but again I found the project but not easy to find the raw fasta data to use, so have to stick to the grape example. Thanks for your assistance.

**Comment by rob123king** [comment]
I'm trying to run the unzip part locally as our SGE queue is not setup, using the config file below

> [General]
> job_type = local
> 
> [Unzip]
> smrt_bin=/home/data/bioinf_resources/programming_tools/falcontest/bin/
> 
> unzip_concurrent_jobs = 64
> quiver_concurrent_jobs = 64

Falcon using local as the job seemed to work successfully but not in unzip.

Error is seems try to run SGE job when trying to run a local job, am I missing something in the config?:
`[WARNING]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/home/data/bioinf_resources/programming_tools/falcontest/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pwatcher/fs_based.pyc'>
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/home/data/bioinf_resources/programming_tools/falcontest/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pwatcher/fs_based.pyc'>
[INFO]job_type='SGE', job_queue='default', sge_option=None, use_tmpdir=None, squash=False, job_name_style=0
[INFO]Num unsatisfied: 1, graph: 1
[INFO]About to submit: Node(3-unzip/reads)
[INFO]starting job Job(jobid='P8a631ab293d559', cmd='/bin/bash run.sh', rundir='/home/data/bioinf_resources/programming_tools/falcontest/raw/3-unzip/0-phasing/000015F/blasr/3-unzip/reads', options={'job_queue': 'default', 'sge_option': ' -pe smp 12 -q bigmem', 'job_type': 'SGE'})
[INFO]!qsub -N P8a631ab293d559 -q default -pe smp 12 -V -cwd -o stdout -e stderr -S /bin/bash /home/data/bioinf_resources/programming_tools/falcontest/raw/3-unzip/0-phasing/000015F/blasr/mypwatcher/wrappers/run-P8a631ab293d559.bash
Unable to run job: Job was rejected because job requests unknown queue "default".
Exiting.
[ERROR]In pwatcher.fs_based.cmd_run(), failed to submit background-job:
MetaJobSge(MetaJob(job=Job(jobid='P8a631ab293d559', cmd='/bin/bash run.sh', rundir='/home/data/bioinf_resources/programming_tools/falcontest/raw/3-unzip/0-phasing/000015F/blasr/3-unzip/reads', options={'job_queue': 'default', 'sge_option': ' -pe smp 12 -q bigmem', 'job_type': 'SGE'}), lang_exe='/bin/bash'))
Traceback (most recent call last):
  File "/home/data/bioinf_resources/programming_tools/falcontest/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pwatcher/fs_based.py", line 532, in cmd_run
    state.submit_background(bjob)
  File "/home/data/bioinf_resources/programming_tools/falcontest/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pwatcher/fs_based.py", line 117, in submit_background
    bjob.submit(self, exe, script_fn) # Can raise
  File "/home/data/bioinf_resources/programming_tools/falcontest/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pwatcher/fs_based.py", line 300, in submit
    system(sge_cmd, checked=True) # TODO: Capture q-jobid
  File "/home/data/bioinf_resources/programming_tools/falcontest/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pwatcher/fs_based.py", line 551, in system
    raise Exception('{} <- {!r}'.format(rc, call))
Exception: 256 <- 'qsub -N P8a631ab293d559 -q default -pe smp 12 -V -cwd -o stdout -e stderr -S /bin/bash /home/data/bioinf_resources/programming_tools/falcontest/raw/3-unzip/0-phasing/000015F/blasr/mypwatcher/wrappers/run-P8a631ab293d559.bash'
[ERROR]Failed to enqueue 1 of 1 jobs: set([Node(3-unzip/reads)])
[WARNING]Nothing is happening, and we had 0 failures. Should we quit? Instead, we will just sleep.
[INFO]sleep 0.1s
Traceback (most recent call last):
  File "/home/data/bioinf_resources/programming_tools/falcontest/bin/fc_unzip.py", line 11, in <module>
    load_entry_point('falcon-unzip==0.4.0', 'console_scripts', 'fc_unzip.py')()
  File "/scratch/cdunn/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/mains/start_unzip.py", line 25, in main
  File "/scratch/cdunn/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 319, in run
  File "/scratch/cdunn/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 198, in unzip_all
IOError: [Errno 2] No such file or directory: './3-unzip/reads/ctg_list'
`

**Comment by pb-cdunn** [comment]
Are you sure you set `LD_LIBRARY_PATH`?

**Comment by pb-cdunn** [comment]
```sh
$ ldd lib/libhdf5.so.10
        linux-vdso.so.1 =>  (0x00007ffd9eff3000)
        librt.so.1 => /lib64/librt.so.1 (0x00002ac64b911000)
        libz.so.1 => /lib64/libz.so.1 (0x00002ac64bb1a000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002ac64bd30000)
        libm.so.6 => /lib64/libm.so.6 (0x00002ac64bf34000)
        libc.so.6 => /lib64/libc.so.6 (0x00002ac64c237000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ac64c5fa000)
        /lib64/ld-linux-x86-64.so.2 (0x00005564b8ab6000)
```

**Comment by pb-cdunn** [comment]
> but we have gcc (GCC) 5.4.0 not 6.4.0

You must upgrade.

blasr is very hard to maintain, so we are strict about this.

The good news is that we expect to provide code (partly binaries) for bioconda soon. That will make everyone's life easier.
