### ISSUE TITLE
Can we use Falcon to assemble non pacbio reads (Hiseq 2500/4000)?

### ISSUE THREAD

**Issue by Tipplynne** [PacificBiosciences/FALCON#609]
Hi there

Is there a way to use assemble reads generated by other sequencers (Illumina's hiseq 2500 and 4000) with the falcon software?

Thanks
Crystal

**Comment by cschin** [comment]
@Tipplynne no. not without very significant modification.  while the basic principle of genome assembly are similar for long and short reads, the details of implement for efficient algorithm are totally different.  FALCON won't work well with short reads.  There are many other good short read assemblers that you should try.  Velvet. Spade, AllPath, SGA, SoapDenovo, SuperNova,.... etc...

**Comment by Tipplynne** [comment]
Understood, thank you.
