### ISSUE TITLE
qsub to bsub

### ISSUE THREAD

**Issue by sohnjangil** [PacificBiosciences/FALCON#61]
I wanted to run FALCON in my system, but it failed bacause of qsub commands.
In my lab, bsub is already installed in server, and most of scripts are implementing bsub.
So to use FALCON in my lab, the scipts using bsub is needed.
How can I convert the qsub command to bsub?
Or did you have plan for bsub users?

**Comment by pb-jchin** [comment]
The way FALCON handle jobs submission is quite generic. If you know your HPC queue systems well, you should be able to modify the `run_script()` in `fc_run.py` for your job submission system.   You might need to do some of experiments to know how your cluster handle the jobs submission request. For large genome, you need to know the architecture of your system well for proper job submission.  The default is written against a special cluster we have in-house. You are encourage to modify the code as open-source project to fit your needs.
