### ISSUE TITLE
The current code (FALCON @ cd08063) uses daligner_p to overlap raw reads. 

### ISSUE THREAD

**Issue by cschin** [PacificBiosciences/FALCON#613]
see the one liner change in https://github.com/PacificBiosciences/FALCON/pull/610 against the current head @ cd08063.  maybe I am wrong, but it does not seem to me that it is correct to run "daligner_p" for overlapping raw sequences.

**Comment by pb-cdunn** [comment]
I see the bug now. Thanks, Jason!

**Comment by pb-cdunn** [comment]
I see. Bug added here: c6e3eaebe0018a79be453b8cf5e34ae2a41df64e (Date:   Tue Jan 2 20:06:18 2018).

**Comment by pb-cdunn** [comment]
Fixed on `develop` branch: 8ac72361cfd

I'll recall the most recent release.
