### ISSUE TITLE
Does fc_consensus.py only correct InDels in seed reads?

### ISSUE THREAD

**Issue by nottwy** [PacificBiosciences/FALCON#617]
Dear developers,

Recently I'm learning the pre-assembly step of Falcon and found that it seems like Flacon only corrects InDel errors in raw reads.
The description of the process in the falcon manuscript is like this:
"We don't allow for mis-matches in the alignments. All differences are encoded as insertions and deletions."

Wait for your reply!

**Comment by cschin** [comment]
@nottwy, in the alignment graph, a mismatch is equivalent to a single base insertion followed by a single deletion.  the consensus algorithm does correct for mismatches.

**Comment by nottwy** [comment]
You are correct.
Another question.
Why does Falcon output so many contigs with only several bps (1-20) length in the final assembly?

**Comment by cschin** [comment]
@nottwy  The initial FALCON contig outputs the non-overlapped part.  If you have many small contigs, those are from two very similar reads that only different by a couple bases.  This is a design choice (and it is up to the current FALCON/PacBio assembler developers decide to change it or not.). During the graph to layout, the overlapped parts may contain repeats and may have ambiguity and duplication it they are included in the contigs.

**Comment by nottwy** [comment]
So, is it proper to remove contigs whose lengths are <= 100 (or other values) bp?

**Comment by cschin** [comment]
it depends. for large genome with enough coverage without crazy repeat, those short contigs should be a small potion of genomes.  On the other hand, in some other cases, those (short) contigs might have useful information.  You can try this https://gist.github.com/pb-jchin/013e65447d3dda978dc5fc717cb53f3a to get the 5'-end of those short contigs back for further analysis.

**Comment by nottwy** [comment]
Another problems:
How to understand --bestn parameter of the command 'overlap_filtering_setting':

bestn: output at least best n overlaps on 5' or 3' ends if possible

What does at least mean?

For example, if there's 5 overlaps and --bestn=10. I think all 5 overlaps will be output.
If --bestn=3, all 5 overlaps will also be output.
So can you explain the use of this parameter?
