### ISSUE TITLE
how to run fc_ovlp_filter in distributed mode?

### ISSUE THREAD

**Issue by com4343568** [PacificBiosciences/FALCON#619]
fc_ovlp_filter
LA4Falcon

**Comment by pb-cdunn** [comment]
I don't understand. `ovlp_filter` is run in the `2-asm-falcon` directory, which *is* distributed. It is also run with `NPROC=4` by default. It runs an instance of `LA4Falcon` for each instance of `--n_core`, which should match `NPROC`. Each LA4Falcon instance loads the entire DAZZLER DB into memory.

To reduce the number of LA4Falcon instances, do this (with the latest FALCON-integrate release):
```ini
[job.step.asm]
NPROC=1
```

**Comment by pb-cdunn** [comment]
(The latest FALCON release should set `--n-core` for you, based on `NPROC` for that step. If not, try setting `overlap_filtering_setting` in the `[General]` section.)
