### ISSUE TITLE
Losing a lot of reads in raw_reads.db

### ISSUE THREAD

**Issue by chklopp** [PacificBiosciences/FALCON#62]
Hi,

What could explain the important read loss in the first step of Falcon : 

DBstats raw_reads.db
Statistics for all wells in the data set

      1,655,303 reads       out of       4,099,447    59.6% loss
 13,561,952,097 base pairs  out of  24,496,694,744    44.6% loss

Base composition: 0.336(A) 0.192(C) 0.181(G) 0.291(T)

          8,193 average read length
          4,246 standard deviation

Cheers,

Christophe

**Comment by pb-jchin** [comment]
Do you also lost a lot of bases?  What input files do you use? Those "*.subreads.fasta" files?

**Comment by chklopp** [comment]
Yes.

**Comment by pb-jchin** [comment]
Then, for whatever reason, you might have many shorter reads which gets "trimmed"..

**Comment by chklopp** [comment]
How can I find out what is going on?
Are, for example, duplicated reads removed during the db building phase?

**Comment by pb-jchin** [comment]
`DBsplit -x500 -s75 raw_reads` inside `0-rawreads` dir determines the threshold for trimming.  You can check the length of the sequence in your subread files to see if they are consistent with the `DBstat` output. If those sequences are short, you will need to consult the scientists who collects the data about the source of initial DNA and some sequencing protocols.

**Comment by yunfeiguo** [comment]
Hi Dr. Chin, 

Here we used `DBsplit -x500 -s400`, so reads shorter than 500 bp are discarded in `raw_reads.db`. However, if we count number of reads shorter than 500, it's just 1 million, whereas DBstats reports loss of 14 million reads. Do you know what other criteria used in filtering?

**Comment by pb-cdunn** [comment]
Try `-a`.
* https://github.com/thegenemyers/DAZZ_DB/blob/master/DBsplit.c#L38

**Comment by pb-jchin** [comment]
@pb-cdunn Thanks. We should turn -a on by default. However, there could some some side effect for tracing read id. I will do some test before we turn it on.

**Comment by chklopp** [comment]
I ran :
DBsplit -x500 -s75 raw_reads.db
You are about to overwrite the current partition settings.  This
will invalidate any tracks, overlaps, and other derivative files.
Are you sure you want to proceed? [Y/N] Y
What is the next step?

**Comment by pb-jchin** [comment]
you should delete the db and rebuild it from scratch if it is not a super big one. We don't use other derivative files now.

**Comment by chklopp** [comment]
Do you mean changing the line in the falcon.cfg file?
from 
pa_DBsplit_option = -x500 -s400
to 
pa_DBsplit_option = -x500 -s75
and rerun Falcon.

**Comment by pb-jchin** [comment]
`-s` controls the block size, you setting could be fine depending on your cluster setting. Just re-rerun everything. Please also read https://dazzlerblog.wordpress.com to know more about the details.

**Comment by chklopp** [comment]
Changing the s parameter in the falcon config file did not change the loss rate.

DBstats raw_reads.db

Statistics for all wells in the data set

      1,655,303 reads       out of       4,099,447    59.6% loss
 13,561,952,097 base pairs  out of  24,496,694,744    44.6% loss

Base composition: 0.336(A) 0.192(C) 0.181(G) 0.291(T)

          8,193 average read length
          4,246 standard deviation

Distribution of Read Lengths (Bin size = 1,000)

    Bin:      Count  % Reads  % Bases   Average
 49,000:          1      0.0      0.0    49135
 48,000:          1      0.0      0.0    49036
 47,000:          0      0.0      0.0    49036
 46,000:          2      0.0      0.0    47642
 45,000:          4      0.0      0.0    46610
 44,000:          2      0.0      0.0    46125
 43,000:          3      0.0      0.0    45542
 42,000:         11      0.0      0.0    44177
 41,000:         22      0.0      0.0    42839
 40,000:         24      0.0      0.0    42046
 39,000:         31      0.0      0.0    41232
 38,000:         40      0.0      0.0    40453
 37,000:         55      0.0      0.1    39604
 36,000:         85      0.0      0.1    38655
 35,000:        112      0.0      0.1    37760
 34,000:        157      0.0      0.1    36820
 33,000:        205      0.0      0.2    35911
 32,000:        289      0.1      0.3    34963
 31,000:        358      0.1      0.4    34067
 30,000:        460      0.1      0.5    33175
 29,000:        613      0.1      0.6    32257
 28,000:        827      0.2      0.8    31317
 27,000:      1,044      0.3      1.0    30395
 26,000:      1,369      0.3      1.2    29459
 25,000:      1,739      0.5      1.6    28530
 24,000:      2,273      0.6      2.0    27581
 23,000:      2,996      0.8      2.5    26616
 22,000:      3,768      1.0      3.1    25671
 21,000:      4,919      1.3      3.9    24707
 20,000:      6,421      1.7      4.9    23729
 19,000:      8,232      2.2      6.1    22759
 18,000:     10,883      2.8      7.5    21766
 17,000:     14,434      3.7      9.4    20756
 16,000:     18,944      4.9     11.7    19747
 15,000:     25,340      6.4     14.6    18723
 14,000:     34,118      8.4     18.2    17686
 13,000:     46,067     11.2     22.8    16641
 12,000:     62,652     15.0     28.6    15590
 11,000:     84,652     20.1     35.7    14545
 10,000:    112,220     26.9     44.4    13519
  9,000:    144,232     35.6     54.5    12531
  8,000:    176,242     46.3     65.5    11600
  7,000:    199,628     58.3     76.5    10751
  6,000:    199,537     70.4     86.1    10024
  5,000:    141,570     78.9     91.9     9538
  4,000:    106,962     85.4     95.5     9158
  3,000:     94,579     91.1     97.9     8804
  2,000:     76,969     95.8     99.3     8499
  1,000:     49,891     98.8     99.9     8287
      0:     20,320    100.0    100.0     8193

**Comment by pb-jchin** [comment]
well, unless I can access your data, there is no simple way to see what is going on.

**Comment by hvdgeest** [comment]
The fact that DBstat is showing lost data is because your insert was smaller than raw read length.
I assume that DBstat only counts the longest subread per zmw, en disards all others.
For denovo coverage calculation this is the best thing to do, however for error correction I indeed think that we should use every read, including mutliple subreads per zwm.
The DBsplit -a should also takes these into account, But I am not sure wheter these extra subreads are actually stored in the .raw_reads.db.
You could ask Gene Meyers for help, or try to infer something from the database file size.

When we have amplicon sequence data, we 'loose' somewhere 90%. Which is positive in the case of amplicons :)

So did you run DBsplit with the -a option?
