### ISSUE TITLE
"g_best_ck" may be misused in falcon.c:494 (@09a8b7b)

### ISSUE THREAD

**Issue by lemene** [PacificBiosciences/FALCON#624]
Hi,
When I read the code in falcon.c, I think "g_best_ck" may be misused in statements below.
```C
425 for (ck = 0; ck < aln_col->n_link; ck++) { // loop through differnt link to previous column
...
452 best_ck = ck;
...
468 g_best_ck = best_ck;
...
494 ck = g_best_ck;
...
499 switch (ck) {
500    case 0: bb = 'A'; break;
...
521 ck = g_best_aln_col->best_p_q_base;
522 g_best_aln_col = msa_array[i]->delta[j].base + ck;
```
From line 425, 452 and 468, I infered "g_best_ck" is the index of "aln_col->n_link". 
From line 494, 499, 500 521 and 522, "g_best_ck" is used as the index of "msa_array[i]->delta[j].base".

**Comment by pb-cdunn** [comment]
Yes, `ck` starts as `g_best_ck` before the while loop at `497`. And it's updated each iteration at `521`. But I don't see a bug. Are you sure there is a problem?

**Comment by cschin** [comment]
@pb-cdunn @lemene  I am looking at the code. I think there could be a bug. The second use does seem to be weird.  I will do some analysis.

**Comment by lemene** [comment]
The error only occur in the first iteration and the value of "bb" may be incorrectly assigned.

**Comment by cschin** [comment]
@lemene is right.  What surprises me is that why this bug does not break the code... I guess if the 2nd `ck` > 5, the `ck` is simply be assigned the the correct one. We simply miss one last base. If ck is < 5, the last base in the generated consensus would be likely wrong in some cases.

I make PR:  https://github.com/PacificBiosciences/FALCON/pull/625 for my fix

**Comment by pb-cdunn** [comment]
Finally, this is incorporated into the next Bioconda release. Thanks for the fix!
