### ISSUE TITLE
`get_cns_from_align_tags` may lose the first base in falcon.c:519 (@05ed6fa) 

### ISSUE THREAD

**Issue by lemene** [PacificBiosciences/FALCON#626]
Hi, I think line 519 (`i==-1`)should be placed behind line 525. If not, the first base, `bb`, will not be added to `cns_str`. 

```C
...        bb = ...
             ....
518        i = g_best_aln_col->best_p_t_pos;
519        if (i == -1 || index >= t_len * 2) break;
           ...
524        if (bb != '-') {
525            cns_str[index] = bb;
               ...
```

I

**Comment by pb-cdunn** [comment]
```c
527         score0 = g_best_aln_col->score;
528         i = g_best_aln_col->best_p_t_pos;
529         if (i == -1 || index >= t_len * 2) break;
530         j = g_best_aln_col->best_p_delta;
531         ck = g_best_aln_col->best_p_q_base;
532         g_best_aln_col = msa_array[i]->delta[j].base + ck;
533
534         if (bb != '-') {
535             cns_str[index] = bb;
536             eqv[index] = (int) score0 - (int) g_best_aln_col->score;
537             //printf("C %d %d %c %lf %d %d\n", i, index, bb, g_best_aln_col->score, coverage[i], eqv[index] );
538             index ++;
539         }
```
(You have a slightly old version of the code.) Could you clarify?

**Comment by pb-cdunn** [comment]
Thanks for looking closely. We always value bug-reports from users. After giving this some attention, we think it's fine, but if you're sure, re-open.

**Comment by lemene** [comment]
@pb-cdunn 
I didn't run the code on test data, so I'm not sure if my though is right.
Let us assume that there is only one element in `g_best_aln_col`.  The structure of chain may be similar to "2 -> -1 ".
From line 492 to line 517, `i` is assgined `2` and  `bb` is assigned a value.  
From line 518 to line 519, `i` is assigned `-1` and the loop breaks, but `bb` has not been added to `cns_str`, which is function of codes from line 524 to line 525.

So, I guess the first base of corrected read lost.

(The line number is the old version. )

**Comment by pb-cdunn** [comment]
Oh, you mean when `i == -1`. Hmmm. We'll think about that case more...
