### ISSUE TITLE
setting tmpdir

### ISSUE THREAD

**Issue by rob123king** [PacificBiosciences/FALCON#627]
We have a problem that setting the tmpdir does not appear to work and our default /tmp gets full during the merge step (m_* folders). I manually changed the task.sh in each m_* folder and launch each run.sh manually and completes fine although complains 
`rsync: chgrp "/home/data/pisa_ngs/Backup_Genetics/PacBio/Fig_Falcon7/0-rawreads/m_00001/L1.1.90.las" failed: Operation not permitted (1)`  

I hopefully will then do a restart and the whole process will pickup that these jobs are now complete and continue? 

We have set use temp in the config file and exported the TMPDIR location at the command line. It appears as though there is a -P option for daligner here https://dazzlerblog.wordpress.com/command-guides/daligner-command-reference-guide/ but for pre-existing job where do I put this -P option to get it to pick it up and also from a fresh job?

**Comment by pb-cdunn** [comment]
The problems with `use_tmpdir` should be fixed in the latest binaries.
