### ISSUE TITLE
What to put into input.fofn for FALCON-unzip

### ISSUE THREAD

**Issue by LukeManship** [PacificBiosciences/FALCON#628]
It seems unclear which file names to put into the input.fofn file for FALCON-unzip. Should the file names refer to the original .fasta files from the first FALCON assembly, or should the names in the file refer to the .fa files that appear in the 2-asm-falcon folder?

**Comment by BioWu** [comment]
@LukeManship You just give the same file used in Falcon. Not any change is needed.

**Comment by pb-cdunn** [comment]
Yes. But you will also need `input_bam.fofn`, which should be BAM files from Sequel. Arrow requires Sequel data.
