### ISSUE TITLE
2-asm-falcon,fc_ovlp_filter.py failed,help

### ISSUE THREAD

**Issue by AnWD** [PacificBiosciences/FALCON#63]
Hi,jchin:
I have a problem here,would you give me a hand?
```
sge_log/falcon-38233749.o77234 shows error:
"File "/home/nfs_UserData_20/falcon/FALCON-master/fc_env/bin/fc_ovlp_filter.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.2.1', 'fc_ovlp_filter.py')
  File "/home/nfs_UserData_20/falcon/FALCON-master/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 696, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/nfs_UserData_20/falcon/FALCON-master/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1614, in run_script
    exec(code, namespace, namespace)
  File "/home/nfs_UserData_20/falcon/FALCON-master/fc_env/lib/python2.7/site-packages/falcon_kit-0.2.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_ovlp_filter.py", line 276, in <module>
    for res in exe_pool.imap(filter_stage3, inputs):
  File "/home/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/multiprocessing/pool.py", line 626, in next
    raise value
UnboundLocalError: local variable 'overlap_data' referenced before assignment"
```
and the size of file in the 2-asm-falcon directory is all 0.

when I remove 2-asm-falcon/preads.ovl ,and run the command "`fc_ovlp_filter.py --fofn las.fofn --max_diff 100 --max_cov 10 --min_cov 2 --bestn 30 --min_len 5000 > preads.ovl`" separately,the 
stderr shows the same error like above.

Thank you!

**Comment by pb-cdunn** [comment]
The crash is in `filter_stage3()`. Something like this can be helpful in getting stack traces:
```
class Pool(object):
    """Fake multiprocessing.Pool
    """"
    def __init__(self, n=1):
        pass
    def imap(self, func, inputs):
        for i in inputs:
            yield func(i)
```
In your case, `sp.check_output(shlex.split("LA4Falcon -mo %s" % fn)).splitlines()` has returned nothing, so `overlap_data` has not bee initialized by line 205. Trying running **LA4Falcon** from your shell (if you can learn the filename for `fn`) and see if that explains it.

**Comment by pb-jchin** [comment]
@pd-cdunn, Thanks. Maybe we should incorporate this as a specially "debug" option to turn off the multiprocess calls to make the debugging process easier.  I used to turn off the multiprocessing by replacing `pool.imap` to generic `iteratools.imap`. I like your solution better.  Please consider to submit a pull request for the `diconsensus` branch. Thanks.

**Comment by AnWD** [comment]
Hi pb-cdunn,thanks for your reply!

**Comment by pb-cdunn** [comment]
We have a [FakePool](#67) now.
