### ISSUE TITLE
Problems with trying to assemble corrected sequences in FALCON

### ISSUE THREAD

**Issue by ruthfa** [PacificBiosciences/FALCON#632]
I am trying to assemble corrected PacBio sequences with FALCON but it doesn't work. My sequences were corrected with Canu. I have this error report:

Traceback (most recent call last):
  File "/opt/share/software/packages/FALCON-integrate-2.0.4/pyvirt/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit', 'console_scripts', 'fc_run')()
  File "/opt/share/software/packages/FALCON-integrate-2.0.4/FALCON/falcon_kit/mains/run1.py", line 644, in main
    main1(argv[0], args.config, args.logger)
  File "/opt/share/software/packages/FALCON-integrate-2.0.4/FALCON/falcon_kit/mains/run1.py", line 159, in main1
    input_fofn_plf=input_fofn_plf,
  File "/opt/share/software/packages/FALCON-integrate-2.0.4/FALCON/falcon_kit/mains/run1.py", line 448, in run
    raise Exception('TODO')
Exception: TODO

My .cfg file was:

[General]
job_type = local
input_fofn = input.fofn
input_type = preads
length_cutoff = 1000
length_cutoff_pr = 5000
jobqueue = your_queue
sge_option_da = -pe smp 8 -q %(jobqueue)s
sge_option_la = -pe smp 4 -q %(jobqueue)s
sge_option_pda = -pe smp 8 -q %(jobqueue)s
sge_option_pla = -pe smp 4 -q %(jobqueue)s
sge_option_fc = -pe smp 4 -q %(jobqueue)s
sge_option_cns = -pe smp 4 -q %(jobqueue)s
pa_concurrent_jobs = 7
ovlp_concurrent_jobs = 7
pa_HPCdaligner_option =  -v -dal24 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal24 -t32 -h60 -e.96 -l500 -s1000
pa_DBsplit_option = -x500 -s200
ovlp_DBsplit_option = -x500 -s200
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 4 
overlap_filtering_setting = --max_diff 130 --max_cov 195 --min_cov 5 --bestn 10 --n_core 16

I don't know what happens because it seems that the program is not reading my sequences but I don't know if it is a problem of format or no. My input file is the fasta file provided from Canu correction.

**Comment by haghshenas** [comment]
I think your config file format is OK. I faced the same problem. I had a look at file "run1.py" and it seems like having `input_type = preads` causes an intentional exception as I see the following piece of code:

```
    if config['input_type'] == 'preads':
        """
        preads_fofn_plf = makePypeLocalFile(os.path.join(
            pread_dir, 'preads-fofn-abs', os.path.basename(config['input_fofn'])))
        make_fofn_abs_task = PypeTask(inputs={'i_fofn': input_fofn_plf},
                                      outputs={'o_fofn': preads_fofn_plf},
                                      parameters={},
                                      )
        fofn_abs_task = make_fofn_abs_task(
            pype_tasks.task_make_fofn_abs_preads)
        wf.addTasks([fofn_abs_task])
        wf.refreshTargets([fofn_abs_task])
        """
        raise Exception('TODO')
```

Any reason for that?
How are we supposed to assemble error-corrected reads using the new code?

**Comment by rob123king** [comment]
The headers produced by falcon are not compatible with starting from preads, which is insane but what we found when we tried it from preads from a previous run. You have to rename the pread headers to match what it is expecting for this to work and we got it to work this way.

**Comment by pb-cdunn** [comment]
@rob123king, yes, daligner is very particular about headers.

**Comment by chunlinxiao** [comment]
I encountered the same problem, but not sure what the solution is to this?

**Comment by pb-cdunn** [comment]
To be clear, you are attempting to run with `input_type=preads`, using a FASTA file from a previous FALCON run? Could you state clearly which FASTA file you used? We could generate that file with proper headers if we know *precisely* which one needs them.

**Comment by chunlinxiao** [comment]
Hi Chris,

I was trying to run Falcon with input_type=preads, and the error-corrected reads fasta file was actually generated by canu. Is there anyway I can run Falcon with input_type=preads with canu-error-corrected reads?

thanks

**Comment by pb-cdunn** [comment]
No. You need to convert.

There used to be a filter to help with that. You just need to use the expected header format. But these data are not from a PacBio machine, right?

**Comment by chunlinxiao** [comment]
the raw reads were from pacbio machine and error-corrected by canu.

I'm still not sure what the "the expected header format" is.    The input_type=preads expects input file format as fasta file - the error-corrected file is fasta format.   I assume Falcon also generate error-corrected reads in fasta format.   

do you have some example of the header format? or is there any script for such conversion?

thanks

**Comment by pb-cdunn** [comment]
It's a constraint of `fasta2DB`:
* https://dazzlerblog.wordpress.com/command-guides/dazz_db-command-guide/

> The .fasta headers must be in the “Pacbio” format (i.e. the output of the Pacbio tools or our dextract program) and the well, pulse interval, and read quality are extracted from the header and kept with each read record.

* https://github.com/thegenemyers/DAZZ_DB/blob/master/fasta2DB.c#L437

I think you need
```
>name/well/beg_end
e.g.
>synthetic/0/0_5000
```

**Comment by pb-cdunn** [comment]
Try this:
* https://github.com/phasegenomics/FALCON-Phase/blob/master/bin/FALCON_headerConverter.pl
* https://github.com/phasegenomics/FALCON-Phase/pull/32

**Comment by chunlinxiao** [comment]
I used the script (falcon_name_fasta.pl) from SchwarzEM  (following https://github.com/PacificBiosciences/FALCON/issues/249) to do the conversion.  Still got the similar error as ruthfa in the begining of this issue(632). 

Not sure what was wrong?

**Comment by pb-cdunn** [comment]
Could you paste an example of a FASTA header after running this SchwarzEM script?

**Comment by chunlinxiao** [comment]
the example header from  SchwarzEM script

>falcon_read/00000001/0_6877
>falcon_read/00000002/0_15035
>falcon_read/00000003/0_7582

thanks

**Comment by pb-cdunn** [comment]
The headers need to start with `>`. Did you forget to use triple-backticks for github markdown?

Otherwise, these headers look fine. Could you run fasta2DB on one of these directly and show the error?

**Comment by chunlinxiao** [comment]
thanks Chris - the headers start with ">".

```
>falcon_read/00000001/0_6877
>falcon_read/00000002/0_15035
>falcon_read/00000003/0_7582

```

**Comment by pb-cdunn** [comment]
Here is an example that works:
```fasta
>m000_000/0/1899_3899 RQ=0.0
```

Hmmm. Maybe you need `RQ=0` too.

I will ask Gene Myers to add some debug output for `fasta2DB` failures.

**Comment by pb-cdunn** [comment]
```
File "/opt/share/software/packages/FALCON-integrate-2.0.4/FALCON/falcon_kit/mains/run1.py", line 448, in run
raise Exception('TODO')
```
Unfortunately, we are no longer able to update source-code in GitHub. Please use either a [binary-tarball](https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries) or bioconda (`conda install pb-assembly`).

**Comment by chunlinxiao** [comment]
Thanks Chris for the help.

I tried a couple things:

- no luck after adding R=0 (same error).

- removed all previous installation, and reinstalled the FALCON_unzip binary-tarball as suggested (https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries) , then re-run falcon and gott the following error.  I did update PYTHONPATH with installed falcon "lib": 

ImportError: No module named falcon_kit.mains.run1

I probably need to wait a newer version of falcon.

**Comment by pb-cdunn** [comment]
`RQ=0.0` not `R=0`. (`RQ instead of `R` and `0.0` instead of `0`. This is not our constraint. That's how Gene Myers wrote [his code](https://github.com/thegenemyers/DAZZ_DB/blob/master/fasta2DB.c#L453).)

> ImportError: No module named falcon_kit.mains.run1

That's a bigger problem.

> I did update PYTHONPATH with installed falcon "lib"

That's not how you use Python.
* If you use a **virtualenv**, then simply `source DIR/bin/activate`.
* If you use `pip install --user`, then you need the same `PYTHONUSERBASE` that you had set.
* If you don't want to install, you can simply `cd FALCON; python setup.py; export PYTHONPATH=$(pwd)`. (You might need to upset `$PATH` too.) You do *not* set the `PYTHONPATH` to a `lib` directory ever.
