### ISSUE TITLE
high heterozygous genome

### ISSUE THREAD

**Issue by yplee614** [PacificBiosciences/FALCON#635]
Hi,  we assembling genome the estimated size is of 460Mb (the heterozygous ratio is about 2.5%), the falcon have produced the result of p_ctg.fa as 862Mb, 41M a_ctg.fa, then we run falcon-unzip to phased the genome, we got the 827M all_p_ctg.fa and 250 all_h_ctg.fa. after that, we polished the p_ctg.fa using the pacbio and illumina and using purge_haplotigs the remove the heterozygous, but we got 667M genome files which are also larger than the estimated size of our genome.

So, how to reduce the genome size to estimated size?

Thanks in advance~

**Comment by cschin** [comment]
@yplee614 it is like that you genome has high heterzygousity between the haplotypes.  You will need to do some customerized analysis to ensure that is indeed the case before using some third party tool to process the assembly results.

**Comment by yplee614** [comment]
what do you mean by customerized analysis? we also have the hi-c data, can we use it to assist the assembly?

**Comment by pb-cdunn** [comment]
Hi-C data is sometimes used after Unzip to improve the polishing.
