### ISSUE TITLE
missing reads.fa files during unzip

### ISSUE THREAD

**Issue by rob123king** [PacificBiosciences/FALCON#636]
I have progressed to the unzip stage of falcon but in the creation of reads.fa files for the contigs before 0-phasing begins, there are 15 reference contigs without reads.fa files. However it progresses to the folder 0-phasing stage but crashes due to not finding those missing reads.fa files.

0-phasing failing
001037F

Not found
001037F_reads.fa

How can I manually generate these missing reads.fa files for the unzipping to complete? I checked the rawreads to map files and these 001037F ID's were not found in here which I guess why these files were not created.

**Comment by diriano** [comment]
Same problem here. If you found a solution will greatly appreciate it if you can share.

**Comment by rob123king** [comment]
I looked for the reads that were used to generate these contigs and pulled the sequences out using a script. I can't remember the file but one of the maps files has the list of reads to extract so just do it yourself and put the files in the directory. It appears like those with very low coverage, like 3-4 reads.

**Comment by pb-cdunn** [comment]
I think we have a fix for this, but we need to update the tarball. Is that correct, @isovic?

**Comment by diriano** [comment]
I would be great if you can share the fix @pb-cdunn . Thanks.

**Comment by pb-cdunn** [comment]
I wish we could. But it's in the binary release now.
