### ISSUE TITLE
Unclear release information

### ISSUE THREAD

**Issue by peterjc** [PacificBiosciences/FALCON#637]
What is the latest release, and where is it tagged on GitHub?

The README file at https://github.com/PacificBiosciences/FALCON/blob/master/README.md says

> The current latest intergrated release is v0.3.0. Check v0.3+ Integration Installation Guide for installation

Note there is a typo (intergrated -> integrated).

The link is broken, https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation does not exist.

Looking at the https://github.com/PacificBiosciences/FALCON-integrate repository, there is a tag for 0.3.0 https://github.com/PacificBiosciences/FALCON-integrate/tree/0.3.0 but there are many later looking tags as well, currently up to https://github.com/PacificBiosciences/FALCON-integrate/tree/2.1.4

Looking at this repository there are only tags for v0.1, v0.2 and funzip_052016 which seems to be the latest tag: https://github.com/PacificBiosciences/FALCON/tree/funzip_052016

**Comment by pb-cdunn** [comment]
It's worse than you think. We no longer even push the latest code into GitHub, so tagging would be pointless. Sorry.

There is a plan to release into Bio-conda, using pre-built wheels or something. Someday.

**Comment by peterjc** [comment]
Oh wow. That's a shame. Could you at least add something to the README and maybe repository description so people know this is no longer active? Thanks!

**Comment by pb-cdunn** [comment]
The `README` is in the repo, so that's hard to change. I'll try to get a PR for that internally, but it would't show up on the `master` branch for at least 2 weeks. I'll update the repo description though.
