### ISSUE TITLE
unzip is failing due to incorrect nucmer option

### ISSUE THREAD

**Issue by rob123king** [PacificBiosciences/FALCON#638]
hasm.sh script failing at this point
# more script -- a little bit hacky here, we should improve

```
WD=$PWD
for f in `cat ../reads/ctg_list `; do mkdir -p $WD/$f; cd $WD/$f; python -m falcon_unzip.mains.dedup_h_tigs $f; done
```

#It is doing as below
nucmer -mum p_ctg.000000F.fa h_ctg_all.000000F.fa -p hp_aln
#but should be the with double dash as below which is why failing
nucmer --mum p_ctg.000000F.fa h_ctg_all.000000F.fa -p hp_aln

Where do I go to correct the script to add the extra "-" so it is "--mum"

**Comment by rob123king** [comment]
I fixed this by providing a standalone script with the change and replacing it in the hasm.sh file so completed the hasm.sh script.

**Comment by pb-cdunn** [comment]
Glad you found a work-around. This should also be fixed in the latest binary release.
