### ISSUE TITLE
Large genomes

### ISSUE THREAD

**Issue by iggyB** [PacificBiosciences/FALCON#639]
Hej,

I successfully used Falcon to assemble many large genomes in the range of 1-4Gb, but I wonder if anyone has used Falcon for genomes larger than **10-15Gb**?
If so, would be great to hear any tips/suggestions/stats. Especially optimizing parameters for first overlap step.

Perhaps developers could advise on choice of parameters? block size? k-mer? -h and -w?
Is it worth adding "-b" for DBdust if genome is AT biased (and highly repetitive)?

Cheers,
Iggy

**Comment by pb-cdunn** [comment]
No parameters would need to be changed. But it would take a lot longer. (10x)? And the real bottleneck is disk-space.
