### ISSUE TITLE
falcon-unzip "hanging" with no output

### ISSUE THREAD

**Issue by cschu** [PacificBiosciences/FALCON#642]
Hi,

my falcon-unzip run seems to be stuck after the get_read_ctg_map step. The stderr output for the last running job shows a lot of Read_Overlap lines (before Read_Overlap record j = 581000000 out of 581874755 at ...), then shows

completed loop record j = 581874755 out of 581874755 at ... 

and then just idles around for days, seemingly without doing anything. Is that expected behaviour?

Falcon version is 20180312.

Thanks, 
Christian

Config file below:

```ini
[General]
input_fofn = input.fofn
input_type = raw
input_bam_fofn= input_bam.fofn

job_type = slurm
job_queue = ei-long

smrt_bin= /tgac/software/testing/smrtlink/5.1.0.26412rev2/x86_64/bin/

sge_phasing= -c 24 --mem 64GB
sge_quiver= -c 24 --mem 64GB
sge_track_reads= -c 12 --mem 64GB
sge_blasr_aln=  -c 24 --mem 64GB
sge_hasm=  -c 48 --mem 64GB
unzip_concurrent_jobs= 32
quiver_concurrent_jobs= 32
```

**Comment by pb-cdunn** [comment]
Half a trillion overlaps? Your dataset is too large. I can't guess why from here.
