### ISSUE TITLE
Only 21 jobs are performed out of 60 Daligner jobs and the run fails w/o ERROR

### ISSUE THREAD

**Issue by alslonik** [PacificBiosciences/FALCON#646]
Hi, new here ,trying to run the tutorial with the provided fastas of ecoli and the cfg example, locally, on 40-core, 504G memory. 
Not sure what is wrong. 
$fc_run fc_run.cfg starts to run, but falls after 21 jobs only, w/o giving any ERROR. 
(grep "ERROR" in log gives me 0) 
Can anyone please give me a clue where is the problem? Where  I shoud look for it?

$ grep '^#' 0-rawreads/run_jobs.sh

    # Daligner jobs (60)
    # Initial sort jobs (400)
    # Check initial .las files jobs (80) (optional but recommended)
    # Remove initial .las files
    # Level 1 merge jobs (20)
    # Check level 2 .las files jobs (20) (optional but recommended)
    # Remove level 1 .las files (optional)

And the subsequent : 
$ find 0-rawreads/ -name "job*done" | wc -l
21

Meaning that it somehow falls after 21 out of 60 jobs.
Can anyone here tell where is my mistake?

Many thanks in advance, Alex

**Comment by alslonik** [comment]
OK. It actually finished the run. There are only 20 jobs done as level 1 .las files are removed, I am guessing.

**Comment by pb-cdunn** [comment]
`job_done` is kind of a legacy "sentinel". It's gone in most parts of Falcon. But if you're curious, `cd` into a task-dir and look at the `.sh` files. One has `touch`, which shows the name of current sentinel files.
