### ISSUE TITLE
Falcon vs Falcon-integrate

### ISSUE THREAD

**Issue by alslonik** [PacificBiosciences/FALCON#649]
Hi, 
I am trying to understand - 
What is the difference between Falcon and Falcon-integrate. Is it the same software? Is there any difference? And what should I be using if I am willing to perform a PacBio reads assembly for a 350Mb genome. Thank you.
Alex

**Comment by pb-cdunn** [comment]
Falcon is the source-code. Falcon-integrate is a repo of git sub-repos that are used to run some simple integration tests.
