### ISSUE TITLE
Problem with restarting

### ISSUE THREAD

**Issue by gengyuncong** [PacificBiosciences/FALCON#653]
Hi,

I run Falcon-integrate v2.1.4 with the following settings: 
```
[job.defaults]
njobs = 17
pwatcher_type = blocking
submit =  qsub -S /bin/bash -sync y -V -q st_supermem.q -P st_supermem \
  -N ${JOB_NAME}     \
  -o "${JOB_STDOUT}" \
  -e "${JOB_STDERR}" \
  -l vf=24g,num_proc=4 -binding linear:4 \
  "${JOB_SCRIPT}"

use_tmpdir = false
job_type = SGE

[job.step.cns]
njobs = 8

[General]
 
#list of files of the initial bas.h5 files
input_fofn = input.fofn
 
input_type = raw
 
#The length cutoff for raw reads. defines seed read length
# “-1” does an automated cut off at the specified seed coverage based on your genomes size
length_cutoff = -1
genome_size = 2000000000
seed_coverage = 30

#The length cutoff for preassembled reads
# you can rerun the final stage of the assembly with different cut offs but this is a good place to start
length_cutoff_pr = 3000
 
# M specifies max memory usage in Gb, reduce if you need to based on your computer system
pa_HPCdaligner_option = -v -M24 -t16 -e.70 -l3200 -k18 -h480 -s1000
ovlp_HPCdaligner_option = -v -M24 -e.96 -l1600 -k24 -h1024 -s1000

 
# increase block size
pa_DBsplit_option = -a -x500 -s400
ovlp_DBsplit_option = -s400

# reduce min cov
LA4Falcon_preload = true
falcon_sense_option = --output-multi --min-idt 0.70 --min-cov 2 --max-n-read 200 --n-core 8 

# reduce min cov
overlap_filtering_setting = --max-diff 80 --max-cov 125 --min-cov 5 --bestn 10 --n-core 12
```

Since some jobs in `0-rawreads/daligner-runs/j_*` failed due to errors in computing nodes, I deleted the directories of corresponding jobs in `0-rawreads/daligner-runs/` and change the name of `mypwatcher/` to `mypwatcher0/` and then restarted fc_run.py.

However, after restarting, no `mypwatcher/` is generated. I think that a new `mypwatcher` directory should have been generated, right? And the files of standard outputs and standard errors go to the running directory (`0-rawreads/daligner-runs/j_*`) rather than `mypwatcher/jobs/*`. 

My question is that:
1. Why no `mypwatcher/` is generated after restarting? 
2. Is that OK to run without `mypwatcher/`?

**Comment by pb-cdunn** [comment]
The `mypwatcher/` directory is used by the `fs_based` filesystem-based process-watcher. (We should rename the directory, probably.)

You are now using `pwatcher = blocking`, which is must simpler. (And *much* easier for us to maintain, so thank you for switching!) For that, all `stderr/stdout/run.sh/run.sh.done` go directly into the run-directories, which are 1:1 with pypeflow tasks.

> Is that OK to run without mypwatcher/?

Yes, since you are using "blocking" qsub calls (`-sync y`).
