### ISSUE TITLE
Regarding Filtering Synthetic construct PacBio

### ISSUE THREAD

**Issue by harsh-shukla** [PacificBiosciences/FALCON#659]
Hi all,

  I am trying to assemble a mammalian genome and I found that some of my reads are mapping  to Synthetic construct PacBio DNA sequence.

I will be using FALCON to assemble . My question is do I have to remove these sequences before I give to falcon for assembly or does FALCON pipeline takes care of it further downstream . And does the pipeline use these sequences for internal quality purposes and I should not be removing them at all.

Any help will be highly appreciated.

Thanking You,

Your's Sincerely,
Harsh

**Comment by mseetin** [comment]
Hi Harsh,

If your length_cutoff (whether you manually set it or if you have it
automatically computed) is above 2 kb, the length of the synthetic
construct, then it won't appear in your final assembly.  If you followed
our usual recommendations and have 50 or more fold coverage of sequencing
from a long insert, size-selected library, and you aim to use a seed
coverage of 30-fold, this should almost always be the case.  If you're
starved for coverage and/or length, then maybe it'll show up as a primary
contig, but you can just delete it from your fasta at that point prior to
final polishing.

Matthew Seetin
Pacific Biosciences

**Comment by harsh-shukla** [comment]
Hi Matthew ,

  Thank you so much for the quick reply. I have a much better idea as to how to proceed further.

Regards,
Harsh
