### ISSUE TITLE
falcon_kit.mains.ovlp_to_graph fails to produce c_path files

### ISSUE THREAD

**Issue by fayina** [PacificBiosciences/FALCON#669]
Hello,
when I run the 2-asm-falcon run_falcon_asm.sh: time python -m falcon_kit.mains.ovlp_to_graph --overlap-file preads.ovl >| fc_ovlp_to_graph.log, it fails to produce c_path files and report an erro in output, the erros looked like this:
![image](https://user-images.githubusercontent.com/32829960/45250191-aae27400-b360-11e8-810e-806306f669c8.png)

the pre-steps seems completed successfully(here is the list of files).
-rw-r--r-- 1 yehua genewiznj     58848 Sep  8 11:58 chimers_nodes
-rw-r--r-- 1 yehua genewiznj         0 Sep  8 11:56 fc_ovlp_to_graph.log
lrwxrwxrwx 1 yehua genewiznj       132 Sep  8 11:47 preads4falcon.fasta -> /YZGROUP/genewiz/genewiznj/SMRT_Denovo/Project/N08122_YH_80_179436343/Analysis/1_assembly/1-preads_ovl/db2falcon/preads4falcon.fasta
-rw-r--r-- 1 yehua genewiznj 212483923 Sep  8 11:47 preads.ovl
lrwxrwxrwx 1 yehua genewiznj       121 Sep  8 11:07 pwatcher.dir -> /YZGROUP/genewiz/genewiznj/SMRT_Denovo/Project/N08122_YH_80_179436343/Analysis/1_assembly/mypwatcher/jobs/P066a10e13c5cb6
-rw-r--r-- 1 yehua genewiznj      1724 Sep  8 11:07 run_falcon_asm.sh
-rw-r--r-- 1 yehua genewiznj       259 Sep  8 11:07 run.sh
-rw-r--r-- 1 yehua genewiznj 167658122 Sep  8 12:00 sg_edges_list
-rw-r--r-- 1 yehua genewiznj      3546 Sep  8 11:07 task.json
-rw-r--r-- 1 yehua genewiznj       227 Sep  8 11:07 task.sh

**Comment by cschin** [comment]
it seems to be a networkx compatibility problem to me. you might have a newer version networks which the API convention is chnaged.

**Comment by fayina** [comment]
Thank you for your reply. I tried to change the version of networkx and it completed succesfully.

**Comment by pb-cdunn** [comment]
Thanks, Jason. For the code in the repo, that's right.

For the version in Bioconda or the most recent binary release, we have this change:
```
4d342dfa falcon_kit/mains/ovlp_to_graph.py (Christopher Dunn 2018-07-20 1118)                 w, w_ = list(sg2.out_edges(w))[0]
```
We're pretty sure the latest falcon works fine with the latest networkx.
