### ISSUE TITLE
2018.08.31 binaries LAcheck duplicate in tan-runs

### ISSUE THREAD

**Issue by jasmynp** [PacificBiosciences/FALCON#670]
With the new binaries (2018.31.08), it halts after LAcheck step in tan-runs.  Looks like datander compares the alignment files to itself?  Then would LAcheck always find duplicates?  I have skip_checks = true set in my config but I don't know if this means anything.  I added "-v" to the LAcheck cmd since it did not spit out any stderr to the logs, only "[WARNING]Call 'bash -vex run_datander.sh' returned 256."

Part of the stderr from run_datander.sh:
```
...
Comparing raw_reads.4 to itself

     251,544 seed hits (1.572138e-12 of matrix)
      40,302 confirmed hits (2.518856e-13 of matrix)
LAsort ./datander.2931/raw_reads.4.T@.las
LAmerge TAN.raw_reads.4.las ./datander.2931/raw_reads.4.T@.S.las
which LAcheck
\+ which LAcheck
/falcon/falcon-2018.31.08-03.06/fc_env_180905/bin/LAcheck
LAcheck -v raw_reads TAN.raw_reads.1.las TAN.raw_reads.2.las TAN.raw_reads.3.las TAN.raw_reads.4.las
\+ LAcheck -v raw_reads TAN.raw_reads.1.las TAN.raw_reads.2.las TAN.raw_reads.3.las TAN.raw_reads.4.las
  TAN.raw_reads.1: Duplicate LAs (6981 vs 6981)
  TAN.raw_reads.1: Not OK, see stderr
  TAN.raw_reads.2: Duplicate LAs (52311 vs 52311)
  TAN.raw_reads.2: Not OK, see stderr
  TAN.raw_reads.3: Duplicate LAs (111157 vs 111157)
  TAN.raw_reads.3: Not OK, see stderr
  TAN.raw_reads.4: Duplicate LAs (184363 vs 184363)
  TAN.raw_reads.4: Not OK, see stderr
```

**Comment by pb-cdunn** [comment]
Hmmm. We'll need your help debugging this. Maybe you are not using our forks of thegenemyers repos? We'll need to you look at more `stderr` files. E.g. I have this in `0-rawreads/tan-runs/tan_000/*stderr`:
```
+ datander -v -k18 -w8 -h200 -e0.8 -P. raw_reads
+ LAcheck raw_reads TAN.raw_reads.las
+ TANmask raw_reads TAN.raw_reads.las
```
I do not see any directories like `datander.2931`.

When you open tickets, please give us as much information as possible on your versions of software: X.Y.Z, git-sha1, where you installed from (bioconda, binary release, this git-repo, etc.), plus whatever you know about your version of DAMASKER.

**Comment by jasmynp** [comment]
The datander is being called from within the binary install.  

I'm not sure what you mean about using forks of thegenemyers repos.  I assumed downloading the binaries meant everything was included within the binaries (with the exception of mummer, samtools, and minimap).  How would I go about doing that?

Here's what I did:
Downloaded the binaries falcon-2018.31.08-03.06-py2.7-ucs4-beta.tar.gz from https://downloads.pacbcloud.com/public/falcon/ and then installed it using virtualenv.  

datander and LAcheck are being called from within the installation dir.  Logs show:
falcon-kit 1.2.3+git.989aaec145d8cfb83ad2417a65ea5c013fb4fca6
pypeflow 2.1.0+git.1f16ef5a470e01d570e81b45d759b6c3623d1fe1

Somehow, I do think the DAMASKER version is different because the cmds being called do not look like yours.  But I can't tell how to spit out the DAMASKER version.  Directory name `datander.2931` was only reported in the verbose stdout of datander when I run `run_datander.sh` manually.

This is what the `stderr` under `0-rawreads/tan-runs/tan_000` looks like:
```
datander -v -e0.7 -s1000 -P. raw_reads.1 raw_reads.2 raw_reads.3 raw_reads.4
+ datander -v -e0.7 -s1000 -P. raw_reads.1 raw_reads.2 raw_reads.3 raw_reads.4
LAcheck raw_reads TAN.raw_reads.1.las TAN.raw_reads.2.las TAN.raw_reads.3.las TAN.raw_reads.4.las
+ LAcheck raw_reads TAN.raw_reads.1.las TAN.raw_reads.2.las TAN.raw_reads.3.las TAN.raw_reads.4.las
[WARNING]Call 'bash -vex run_datander.sh' returned 256.
```

**Comment by SRodenburg** [comment]
I have exactly the same problem. It took me a while to figure this out, since the stderr of the tan-runs directory only reports the exit code (256). I downloaded and installed falcon via 
[https://pb-falcon.readthedocs.io/en/latest/_downloads/install_unzip_180808.sh](https://pb-falcon.readthedocs.io/en/latest/_downloads/install_unzip_180808.sh)

**Comment by SRodenburg** [comment]
Let me just tell you I solved the problem by setting a smaller trace size (-s1000 --> -s100) in the daligner command.

**Comment by jasmynp** [comment]
> Let me just tell you I solved the problem by setting a smaller trace size (-s1000 --> -s100) in the daligner command.

Thanks, @SRodenburg .   I will try this out.  Got same error using the new conda package as well.

Update:  This works. Thanks so much.

**Comment by pb-cdunn** [comment]
We are currently unable to reproduce this problem. (And currently we cannot test via Bioconda because of the weird openssl problems.)
