### ISSUE TITLE
Can't start assembly jobs for  the latest version of falcon

### ISSUE THREAD

**Issue by fayina** [PacificBiosciences/FALCON#671]
Hello
      I installed the latest version of falcon on my cluster and setting the parameters in cfg file suit for my genome(fish, 1.5~1.7G), but the program can't start succesfull and with no erro information in all.log. I don't know where is wrong in my cfg file or any thing else. This is  my config file:

[General]
job_type=lsf
input_fofn = input.fofn
input_type = raw
length_cutoff = 10000
length_cutoff_pr = 15000
stop_all_jobs_on_failure = False
target = assembly
jobqueue = Sharedqueue
sge_option_da = -n 5 -q %(jobqueue)s
sge_option_la = -n 6 -q %(jobqueue)s
sge_option_cns = -n 6 -q %(jobqueue)s
sge_option_pda = -n 6 -q %(jobqueue)s
sge_option_pla = -n 7 -q %(jobqueue)s
sge_option_fc = -n 6 -q %(jobqueue)s

pa_concurrent_jobs = 200
cns_concurrent_jobs = 200
ovlp_concurrent_jobs = 200
pa_HPCdaligner_option = -v -B188 -t16 -w8 -M24 -e.75 -k18 -l4000 -s1000
ovlp_HPCdaligner_option = -v -B188 -t24 -M24 -k24 -h180 -e.96 -l2800 -s1000

pa_DBsplit_option = -x1000 -s250 -a
ovlp_DBsplit_option = -x1000 -s250
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 300 --n_core 8
overlap_filtering_setting = --max_diff 60 --max_cov 70 --min_cov 1 --bestn 10 --n_core 12
use_tmpdir = true
use_tmpdir = /YZGROUP4/STORAGE/genewiz/genewiznj/Public

and this is all.log:
[all.log](https://github.com/PacificBiosciences/FALCON/files/2365621/all.log)

this is mypwatcher dir output
![image](https://user-images.githubusercontent.com/32829960/45283655-081d2780-b511-11e8-800b-70faebf48247.png)

**Comment by pb-cdunn** [comment]
> I installed the latest version of falcon

Meaning, a binary release? Something from Bioconda? This repo is out-of-date, as we no longer mirror our internal code-base here.

You should always test integration with the tiniest example possible. There is "synth0" in FALCON-examples for this purpose.
