### ISSUE TITLE
falcon_unzip result 

### ISSUE THREAD

**Issue by lijingjing1** [PacificBiosciences/FALCON#675]
I test falcon unzip version fc_env_181016 on my own pacbio data about genome size 550 mb.

i get two questions about the unzip result.

1.in floder 3-unzip all_p_ctg.fa and all_h_ctg.fa file size vary considerably.in my opinions the all_h_ctg.fa and the all_p_ctg.fa should have the similar size like the test data greg200k-sv2.

![image](https://user-images.githubusercontent.com/17422156/48395752-39a1b180-e753-11e8-9cb6-a4e86eff61b0.png)

2.in floder 3-unzip file all_p_ctg.fa have the similar id and similar sequence like this.

000678Fp01 、000678Fp02 and how to understand this p01 and p02.

![image](https://user-images.githubusercontent.com/17422156/48395499-6608fe00-e752-11e8-94f5-c3eba077e562.png)

Do you have any some idea about this two questions？

**Comment by pb-cdunn** [comment]
1. p_ctg can be much bigger. (greg200k-sv2 is very artificial, only for testing the workflow.)
2. p01 and p02 -- you should update your code. We have made some changes there.
