### ISSUE TITLE
Meaning of gfa outputs

### ISSUE THREAD

**Issue by gbdias** [PacificBiosciences/FALCON#682]
Hi,

- In the latest version of Falcon (falcon-unzip 1.1.4, falcon-kit 1.2.4, pypeflow 2.1.1), the assembly output include multiple files with the gfa extension.
```
asm.gfa
asm.gfa2
contig.gfa2
sg.gfa
sg.gfa2
```
- Could you provide an explanation on what are these files encoding or links to the relevant documentation? 
- I did some extensive searching in the Falcon docs but could not find any info about the gfa files.
- I also tried examining these files using Bandage. The only file with a number of nodes compatible with the number of contigs contained in my assembly (contig.gfa2) had zero edges, so I am not sure how this compares to Canu's <prefix>.contigs.gfa, where you can see chromosome-like graphs comprising multiple connected nodes.

Thanks,
Guilherme

**Comment by foala** [comment]
Hi,
asm = assembly pread graph
sg = string graph
contig = contig graph with associate contigs attached to each primary contig

GFA is the standard format used for graph representation. GFA2 is the new format. Both are supported by Bandage.

Source: https://github.com/PacificBiosciences/FALCON/blob/master/falcon_kit/bash.py

Hope this helps

**Comment by gbdias** [comment]
Hi @pb-cdunn, 

I am still unsure on how to visualize the FALCON gfa files.

- None of the gfa files generated by FALCON have a total length that matches the assembly length when loaded onto Bandage.
  - Assembly length: `170,967,379` (p_ctgs) + `45,710,955` (a_ctgs).
  - sg.gfa: `1,089,627,645`
  - asm.gfa: `893,130,356`
  - contigs.gfa: `10,410 bp`
- Also, the file where the node count reflects the number of contigs  (`contigs.gfa`) has zero edges or edge overlaps. And the node lengths don't reflect contig lengths.
- Is there a similar view to that of Canu `contigs.gfa` available from FALCON output? Like in the figure below from Koren et al. 2017. Gen Res

<img width="1053" alt="Screen Shot 2019-03-25 at 1 34 53 PM" src="https://user-images.githubusercontent.com/7614153/54941288-dc88ea00-4f02-11e9-9b8e-a6fbd846f5fe.png">
