### ISSUE TITLE
pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by wuxiaopei0509** [PacificBiosciences/FALCON#688]
when running the second step of falcon ,it occurs " pkg_resources.DistributionNotFound: The 'pysam>=0.8.4' distribution was not found",and I don't know how to solve it.

**Comment by pb-cdunn** [comment]
It's easier to deal with these problems by using *bioconda*/*Anaconda*. Keeping track of versions of all dependencies is a tricky business. Partly for that reason, we no longer support installing from source.
