### ISSUE TITLE
running falon.unzip is wrong

### ISSUE THREAD

**Issue by wuxiaopei0509** [PacificBiosciences/FALCON#689]
when running the second step of falcon ,it occurs " pkg_resources.DistributionNotFound: The 'pysam>=0.8.4' distribution was not found",and I don't know how to solve it.

**Comment by cguyomar** [comment]
I have the same problem.
It appears than pbalign requires python 2.7 while pb-assembly is using 3.6

```
$ conda install -c bioconda pbalign
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - pbalign -> pbcommand >=1.1.1 -> python >=2.7,<2.8.0a0
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

A workaround is to downgrade pb-assembly to 0.0.5, that seems to have a Python2 version.

**Comment by pb-cdunn** [comment]
Same as #688.

**Comment by wuxiaopei0509** [comment]
Thank you very much,the issue has already resolved,however I have another problem with job submission.the job submission section is as follows:


and my submit command is：
qsub -S /bin/bash -sync y -V \
-q all.q \
-N Assemble \
-o Assembleoutput \
-e AssembleSTDERR \
-pe smp 10 \
-l h_vmem=1000M \
/home/wuxiaopei/miniconda2/bin/fc_run.py /data/wuxiaopei/fc_run.cfg
Immediately，the error occurs :


I
I don't know how to do with it.Can you tell me ?Thank you very much



At 2019-08-05 15:19:59, "cguyomar" <notifications@github.com> wrote:


I have the same problem.
It appears than pbalign requires python 2.7 while pb-assembly is using 3.6

$ conda install -c bioconda pbalign
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - pbalign -> pbcommand >=1.1.1 -> python >=2.7,<2.8.0a0
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.


A workaround is to downgrade pb-assembly to 0.0.5, that seems to have a Python2 version.

**Comment by pb-cdunn** [comment]
`conda update --all`

You might need to start with a fresh environment, using `python=3.7`, activate, and then `conda install pb-assembly`.
