### ISSUE TITLE
How to modify configure file to specify RAM and CPU number

### ISSUE THREAD

**Issue by feixue1039** [PacificBiosciences/FALCON#690]
I have installed falcon-kit 1.4.2 and ran a test with E. coli data set. I specified "MB = 6000" and "NPROC=4" in the configure file (Attached). However, when I checked the running log file (Attached), I found that the system always use 4000MB RAM for every job submitted. And the nproc ranges from 1 to 6. Could you kindly suggest how to modify the configure file so that the system will use the "MB" and "NPROC" specified in the configure file?

Thanks!

[Ecoli.faclon.run.log](https://github.com/PacificBiosciences/FALCON/files/3485250/Ecoli.faclon.run.log)
[Ecoli.faclon.fc_run.cfg.txt](https://github.com/PacificBiosciences/FALCON/files/3485251/Ecoli.faclon.fc_run.cfg.txt)

**Comment by pb-cdunn** [comment]
You would need to alter your `qsub` (or whatever) job-submission string. See https://github.com/PacificBiosciences/pypeFLOW/wiki/Configuration

But be sure to figure out that proper job-submissions string using a simple hello-world program, not Falcon. We cannot spend time debugging problems for specific users with various grid submission systems. That's exactly why we stopped supporting `job_type=SGE` etc and switched to the `submit=` configuration. As a user, you now have a lot of control over how jobs are submitted.
