### ISSUE TITLE
falcon-unzip error :Call 'which gcpp' returned 256

### ISSUE THREAD

**Issue by wuxiaopei0509** [PacificBiosciences/FALCON#694]
Hi ,
When I run fc_unzip.py fc_unzip.cfg,the follwing error happens and can anyone know why ?
The information is :
[INFO]$('which gcpp')
which: no gcpp in (/usr/bin/python ....
[WARNING]Call 'which gcpp' returned 256.
Exception: Call 'which gcpp' returned 256

Thanks!

**Comment by pb-cdunn** [comment]
You may need to update `pb-assembly` in your Bioconda python3 environment.
