### ISSUE TITLE
[ERROR]Task Node(2-asm-falcon) failed with exit-code=1

### ISSUE THREAD

**Issue by liufeibio** [PacificBiosciences/FALCON#697]
Hi,
I run Falcon to assemble the genome for fungi, but got error as follows:
`[ERROR]Task Node(2-asm-falcon) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: {Node(2-asm-falcon)}
[ERROR]ready: set()
        submitted: set()
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "/home/sujitmaiti/miniconda3/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==1.4.1', 'console_scripts', 'fc_run')()
  File "/home/sujitmaiti/miniconda3/lib/python3.6/site-packages/falcon_kit/mains/run1.py", line 706, in main
    main1(argv[0], args.config, args.logger)
  File "/home/sujitmaiti/miniconda3/lib/python3.6/site-packages/falcon_kit/mains/run1.py", line 73, in main1
    input_fofn_fn=input_fofn_fn,
  File "/home/sujitmaiti/miniconda3/lib/python3.6/site-packages/falcon_kit/mains/run1.py", line 460, in run
    wf.refreshTargets()
  File "/home/sujitmaiti/miniconda3/lib/python3.6/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/sujitmaiti/miniconda3/lib/python3.6/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: {Node(2-asm-falcon)}`

And this is my config for the running:
```
#### Input
[General]
input_fofn=input.fofn
input_type=raw
pa_DBdust_option=
pa_fasta_filter_option=pass
target=assembly
skip_checks=False
LA4Falcon_preload=false
 
#### Data Partitioning
pa_DBsplit_option=-x500 -s50
ovlp_DBsplit_option=-x500 -s50
 
#### Repeat Masking
pa_HPCTANmask_option=
pa_REPmask_code=1,100;2,80;3,60
 
####Pre-assembly
genome_size=73000000
seed_coverage=20
length_cutoff= -1   
pa_HPCdaligner_option=-v -B128 -t16 -e0.75 -M24 -l3200 -k18 -h480 -w8 -s100
pa_daligner_option=-v -B128 -M24 -k24 -h1024 -e.96 -l2500 -s100
falcon_sense_option=--output-multi --min-idt 0.70 --min-cov 2 --max-n-read 800
falcon_sense_greedy=False
 
####Pread overlapping
ovlp_daligner_option=-e.96 -l2000 -k24 -h1024 -w6 -s100
ovlp_HPCdaligner_option=-v -B128 -M24
 
####Final Assembly
overlap_filtering_setting=--max-diff 100 --max-cov 300 --min-cov 2
fc_ovlp_to_graph_option=
length_cutoff_pr=2000
 
[job.defaults]
job_type=local
pwatcher_type=blocking
JOB_QUEUE=default
MB=32768
NPROC=6
njobs=32
submit = /bin/bash -c "${JOB_SCRIPT}" > "${JOB_STDOUT}" 2> "${JOB_STDERR}"
 
[job.step.da]
NPROC=4
MB=32768
njobs=16
[job.step.la]
NPROC=4
MB=32768
njobs=16
[job.step.cns]
NPROC=8
MB=65536
njobs=5
[job.step.pla]
NPROC=4
MB=32768
njobs=4
[job.step.asm]
NPROC=12
MB=196608
njobs=1

```
Could you help with it? Thanks!
Fei

**Comment by baishengjun** [comment]
好像是版本问题，我也运行不了，GitHub上200k的例子都不行；我用之前版本的falcon就可以顺利运行。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liufeibio"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月30日(星期三) 凌晨0:15
收件人:&nbsp;"PacificBiosciences/FALCON"<FALCON@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[PacificBiosciences/FALCON] [ERROR]Task Node(2-asm-falcon) failed with exit-code=1 (#697)




Hi,
 I run Falcon to assemble the genome for fungi, but got error as follows:
 [ERROR]Task Node(2-asm-falcon) failed with exit-code=1 [ERROR]Some tasks are recently_done but not satisfied: {Node(2-asm-falcon)} [ERROR]ready: set() submitted: set() [ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM. Traceback (most recent call last): File "/home/sujitmaiti/miniconda3/bin/fc_run", line 11, in <module&gt; load_entry_point('falcon-kit==1.4.1', 'console_scripts', 'fc_run')() File "/home/sujitmaiti/miniconda3/lib/python3.6/site-packages/falcon_kit/mains/run1.py", line 706, in main main1(argv[0], args.config, args.logger) File "/home/sujitmaiti/miniconda3/lib/python3.6/site-packages/falcon_kit/mains/run1.py", line 73, in main1 input_fofn_fn=input_fofn_fn, File "/home/sujitmaiti/miniconda3/lib/python3.6/site-packages/falcon_kit/mains/run1.py", line 460, in run wf.refreshTargets() File "/home/sujitmaiti/miniconda3/lib/python3.6/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets self._refreshTargets(updateFreq, exitOnFailure) File "/home/sujitmaiti/miniconda3/lib/python3.6/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets raise Exception(msg) Exception: Some tasks are recently_done but not satisfied: {Node(2-asm-falcon)}
 
And this is my config for the running:
 `#### Input
 [General]
 input_fofn=input.fofn
 input_type=raw
 pa_DBdust_option=
 pa_fasta_filter_option=pass
 target=assembly
 skip_checks=False
 LA4Falcon_preload=false
 
Data Partitioning
 
pa_DBsplit_option=-x500 -s50
 ovlp_DBsplit_option=-x500 -s50
 
Repeat Masking
 
pa_HPCTANmask_option=
 pa_REPmask_code=1,100;2,80;3,60
 
####Pre-assembly
 genome_size=73000000
 seed_coverage=20
 length_cutoff= -1
 pa_HPCdaligner_option=-v -B128 -t16 -e0.75 -M24 -l3200 -k18 -h480 -w8 -s100
 pa_daligner_option=-v -B128 -M24 -k24 -h1024 -e.96 -l2500 -s100
 falcon_sense_option=--output-multi --min-idt 0.70 --min-cov 2 --max-n-read 800
 falcon_sense_greedy=False
 
####Pread overlapping
 ovlp_daligner_option=-e.96 -l2000 -k24 -h1024 -w6 -s100
 ovlp_HPCdaligner_option=-v -B128 -M24
 
####Final Assembly
 overlap_filtering_setting=--max-diff 100 --max-cov 300 --min-cov 2
 fc_ovlp_to_graph_option=
 length_cutoff_pr=2000
 
[job.defaults]
 job_type=local
 pwatcher_type=blocking
 JOB_QUEUE=default
 MB=32768
 NPROC=6
 njobs=32
 submit = /bin/bash -c "${JOB_SCRIPT}" &gt; "${JOB_STDOUT}" 2&gt; "${JOB_STDERR}"
 
[job.step.da]
 NPROC=4
 MB=32768
 njobs=16
 [job.step.la]
 NPROC=4
 MB=32768
 njobs=16
 [job.step.cns]
 NPROC=8
 MB=65536
 njobs=5
 [job.step.pla]
 NPROC=4
 MB=32768
 njobs=4
 [job.step.asm]
 NPROC=12
 MB=196608
 njobs=1`
 
Could you help with it? Thanks!
 Fei

**Comment by pb-cdunn** [comment]
Look for a "stderr" file under `2-asm-falcon/`. That might answer your question immediately.

Note that our Issue queue is actually https://github.com/PacificBiosciences/pbbioconda

Also, `conda update --all` to get our most recent updates.

**Comment by B10inform** [comment]
Hi,

I am also having exactly similar error. The stderr in 2-asm-falcon/. has following message.
```
# write sg_edges_list, c_path, utg_data, ctg_paths.
falconc m4filt-contained --in preads.m4 --out preads.filtered.m4 --min-len 1
+ falconc m4filt-contained --in preads.m4 --out preads.filtered.m4 --min-len 1
fatal.nim(49)            sysFatal
Error: unhandled exception: overlapParser.nim(75, 20) `iSpace != -1` Bad input line '---'.
(Be sure to delete the .idx file if written!) [AssertionError]
2020-06-04 16:04:51,029 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2020-06-04 16:04:51,030 - root - INFO - CD: '/home/FALCON/Exam/2-asm-falcon' -> '/home/FALCON/Exam/2-asm-falcon'
2020-06-04 16:04:51,030 - root - INFO - CD: '/home/FALCON/Exam/2-asm-falcon' -> '/home/FALCON/Exam/2-asm-falcon'
2020-06-04 16:04:51,031 - root - CRITICAL - Error in /home/.conda/envs/denovo_FALCON/lib/python3.7/site-packages/pypeflow/do_task.py with argv="{'json_fn': '/home/FALCON/Exam/2-asm-falcon/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/home/.conda/envs/denovo_FALCON/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/.conda/envs/denovo_FALCON/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/.conda/envs/denovo_FALCON/lib/python3.7/site-packages/pypeflow/do_task.py", line 280, in <module>
    main()
  File "/home/.conda/envs/denovo_FALCON/lib/python3.7/site-packages/pypeflow/do_task.py", line 272, in main
    run(**vars(parsed_args))
  File "/home/.conda/envs/denovo_FALCON/lib/python3.7/site-packages/pypeflow/do_task.py", line 266, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/home/.conda/envs/denovo_FALCON/lib/python3.7/site-packages/pypeflow/do_task.py", line 241, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/home/.conda/envs/denovo_FALCON/lib/python3.7/site-packages/pypeflow/do_task.py", line 200, in run_bash
    util.system(cmd)
  File "/home/.conda/envs/denovo_FALCON/lib/python3.7/site-packages/pypeflow/io.py", line 27, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
+++ pwd
++ echo 'FAILURE. Running top in /home/FALCON/Exam/2-asm-falcon (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real	0m1.339s
user	0m0.984s
sys	0m0.285s
+ finish
+ echo 'finish code: 1'
```

**Comment by pb-cdunn** [comment]
We pushed a new `falconc` (in Bioconda module `nim-falcon`), so updating that should fix this.
