### ISSUE TITLE
[falcon-unzip] ctg_list file generated, but nothing in the file

### ISSUE THREAD

**Issue by chanikyu** [PacificBiosciences/FALCON#698]
Hello,

Recently I ran falcon-unzip, and an error popped up.
I tracked the file that caused an error, and found something wrong in "3-unzip/reads/ctg_list" file.

"ctg_list" file was generated, but nothing was in there. There should be something in there...😱

What should I do? Any solutions?

Thank you

**Comment by pb-cdunn** [comment]
We haven't seen this problem. But we updated in Bioconda recently. Maybe that will help you. `conda update --all`. Then `rm -rf 3-unzip/` and start over.

**Comment by pb-cdunn** [comment]
Btw, our Issue queue is https://github.com/PacificBiosciences/pbbioconda
