### ISSUE TITLE
Unable to run my PacBio data with snakemake and pbassembly

### ISSUE THREAD

**Issue by wjj666** [PacificBiosciences/FALCON#713]
I convert sequel bams to fasta (using bam2fasta) and use them as input for falcon. But I got an error like this:

> ValueError: Error tokenizing FASTA header

Referring to this issue, I tried the snakemake workflow, but there was another error:

> File "/XXX/Anaconda3/envs/falcon/lib/python3.7/site-packages/falcon_kit/io.py", line 147, in deserialize
>     raise Exception('Unknown extension for {!r}'.format(fn))
> Exception: Unknown extension for '../../fc_run.cfg'

The snakemake cmd I used was:

> snakemake --config input_fofn=input.fofn config_fn=fc_run.cfg MAKEDIR=/tmp/local/csjjwang/data/NA12878/1_asm/pacbiofalcon --cores 64 -s falcon.clr.snakemake --verbose -p

Could you please help solve these problems and help me assembly my pacbio data with falcon?

Thank you very much.

**Comment by pb-cdunn** [comment]
Same as #695 and https://github.com/PacificBiosciences/pbbioconda/issues/400
