### ISSUE TITLE
How to diagnose for lower coverage?

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/FALCON#76]
Dear Dr. Chin,

We have used a data set to do assembly and obtained 80% genome coverage, however, when more data comes in, we ran falcon from beginning and genome coverage dropped drastically to 2%.

The parameters are a little bit different, but I don't believe they are the main reason here. Could you give us some clues about what potentially are going wrong and how to find out? Thank you!

Parameters we used for 80% coverage:

<pre>
# The length cutoff used for seed reads used for initial mapping
length_cutoff = 6000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 6000

#-M means limit memory usage, use integer
pa_HPCdaligner_option =  -v -dal128 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal128 -t32 -h60 -e.96 -l500 -s1000

#-x is length threshold for including reads in DB
pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 8

overlap_filtering_setting = --max_diff 60 --max_cov 60 --min_cov 2
</pre>

Parameters we used for 2% coverage:

<pre># The length cutoff used for seed reads used for initial mapping
length_cutoff = 6000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 6000

#-M means limit memory usage, use integer
pa_HPCdaligner_option =  -v -dal128 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal128 -t32 -h60 -e.96 -l500 -s1000

#-x is length threshold for including reads in DB
pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6

overlap_filtering_setting = --max_diff 40 --max_cov 25 --min_cov 2  --n_core 6
</pre>

**Comment by pb-jchin** [comment]
Please search related issues raised before, Use "DBstat" as keyword. Thanks

**Comment by pb-jchin** [comment]
this might help, https://github.com/PacificBiosciences/FALCON/issues/28

**Comment by yunfeiguo** [comment]
Thanks for help! Yes, I should have posted some details of our data.

Actually the read length distribution looks fine with average read length about 8.7 kb and N50 about 8 kb (for all data).

But the overlap statistics shows more repeats than expected (showing result with 2% coverage):
![image](https://cloud.githubusercontent.com/assets/7737294/7758109/e5a1113e-ffbb-11e4-947e-fe474e5da536.png)

**Comment by pb-jchin** [comment]
ok, you will need to see the details of the 5' or 3' overlap.  there are some interesting repeats in your genomes. (Making me want to study something like when I have a chance...)  Anyway, I think your coverage cut-off might be too stringent.  The `-maxcov 25` gets rid off too many reads. Do an 1-D histogram of 5'- or 3'- overlaps count, and choose a cutoff accordingly.

**Comment by yunfeiguo** [comment]
I just tried `-maxcov 180 -max_diff 120`, but still no improvment.

Here's the histogram:
![image](https://cloud.githubusercontent.com/assets/7737294/7758505/06f0f0cc-ffbf-11e4-946c-9174e6d6ab75.png)
![image](https://cloud.githubusercontent.com/assets/7737294/7758524/22b8eada-ffbf-11e4-810c-79c7acafc635.png)

**Comment by pb-jchin** [comment]
can you scale the histogram so one can see the details between 0 to 100?

**Comment by pb-jchin** [comment]
also, you mentioned that  `--max_diff 60 --max_cov 60 --min_cov 2` gives you 80% of the coverage, but ` --max_diff 120 --max_cov 120 --min_cov 2` still gives you 2%?

**Comment by yunfeiguo** [comment]
Yes, besides parameter difference, actually I used 20% more data for the 2% result. I am suspicious if there is something wrong with the new data, but I don't know how to check it.

![image](https://cloud.githubusercontent.com/assets/7737294/7759976/6206905a-ffcb-11e4-9954-aef02bbf66de.png)

**Comment by yunfeiguo** [comment]
![image](https://cloud.githubusercontent.com/assets/7737294/7760040/266aa1c0-ffcc-11e4-87d6-0565176f138c.png)

**Comment by yunfeiguo** [comment]
I forgot to mention another difference and I'm not sure if this is important at all:
for the 80% result, we used raw reads converted from `bax.h5` files, for 2% result, we used filtered subreads generated by `SMRTportal`.

**Comment by pb-jchin** [comment]
it depends how you convert the reads from bax.h5. The difference between the SMRTportal output should be some RQV threshold cut.  Why don't you compare the raw sequence lengths between the two data sets?

**Comment by yunfeiguo** [comment]
Good idea, I'm checking it.

When converting from `bax.h5` to `fasta`, we used `-trimByRegion` option in `pls2fasta` command. And for filtering subreads, we used default settings in smrtportal.

**Comment by yunfeiguo** [comment]
It turns out the numbers of bases/reads differ by <10% with and without subread filtering. And the N50 is almost the same....

**Comment by yunfeiguo** [comment]
I tried to run from preads a couple of times with loosened parameters but nothing improves significantly.

So maybe the problem occured before preads were generated. Looking at two sets of parameters I used, there is only one option `--local_match_count_threshold` is different between the 80% and 2% coverage. For 80% result, I used `--local_match_count_threshold 2`, for 2%, I used default `--local_match_count_threshold 6` . Do you think it could be the reason? ps. actually I don't understand the meaning of it...

**Comment by pb-jchin** [comment]
Do you do a separate assemblies? If you do, you can examine the pread4falcon.fasta files. If that parameter is a factor, you should have different distribution of length and number of sequences there.   If not, you might have overwrite something which can affect your results.  

Also. quick comment on the 5'- and 3'- overlap count histograms.  The mode is about 8. It says the average genome coverage of the error corrected reads is about 8x.   The width is about 10.  So, if a p-pread 5'- or 3'-end is "unique" in the genome, you should expect the count is no more then 8 + 2x10 ~= 30x.  If there are more 30x overlapping for some reads, it is likely those reads have "repeat-end".  A trick I use is to ignore those reads which have repeat end to simplify the string graph. (I do plan to bring them back someday.)   Of course, if you filter too much, then the assembly will be fragmented. If you don't filter, the assembly can be also more fragment due to repeats. However, there is no good theory for the later and it is genome (large) repeat content dependent too.  If you don't like to filtering ,you can always setting the `max_cov` and `max_diff` to some high number. For some genomes, there is almost no effect. For others, it might help.

**Comment by yunfeiguo** [comment]
Thanks for comments of overlap histograms. Very informative! If 30 is a good choice, then I guess I should be fine with 25 max coverage.

For preads4falcon.fasta, I found that this file is EXACTLY identical for different assemblies. For example, I have two preads4falcon.fasta generated in the following ways:
1) in folder A, use subread filtered FASTA as input, specify `raw` in `fc_run.cfg`.
2) create and enter another folder B, use `../A/1-preads_ovl/input_preads.fofn` as input, specify `preads` in `fc_run2.cfg`.
`fc_run.cfg` and `fc_run2.cfg` differ by `--local_match_count_threshold`, ` --max_cov`,`--max_diff` options. 
What is going wrong here?

**Comment by pb-jchin** [comment]
the `--local_match_count_threshold` is irrelevant for this case as you already use the same input preads. The option is only used for pread generation.  In this case, your `preads.db` and `las` files in the `1-preads_ovl` should be identical. Can you check that?

**Comment by yunfeiguo** [comment]
Yes, they are the same

<pre>
$du -Lc 1-preads_ovl/preads.db 1-preads_ovl/*.las | tail
113276  1-preads_ovl/preads.86.las
120260  1-preads_ovl/preads.87.las
128376  1-preads_ovl/preads.88.las
130124  1-preads_ovl/preads.89.las
128212  1-preads_ovl/preads.8.las
137940  1-preads_ovl/preads.90.las
132080  1-preads_ovl/preads.91.las
124484  1-preads_ovl/preads.92.las
125008  1-preads_ovl/preads.9.las
12080792        total
$ du -Lc ../A/1-preads_ovl/preads.db ../A/1-preads_ovl/*.las | tail
113276  ../A/1-preads_ovl/preads.86.las
120260  ../A/1-preads_ovl/preads.87.las
128376  ../A/1-preads_ovl/preads.88.las
130124  ../A/1-preads_ovl/preads.89.las
128212  ../A/1-preads_ovl/preads.8.las
137940  ../A/1-preads_ovl/preads.90.las
132080  ../A/1-preads_ovl/preads.91.las
124484  ../A/1-preads_ovl/preads.92.las
125008  ../A/1-preads_ovl/preads.9.las
12080792        total
</pre>

**Comment by pb-jchin** [comment]
ok. run the assembly twice, using the same run_falcon_asm.sh in the same dir but different parameter to compare the results to avoid other variables.

**Comment by yunfeiguo** [comment]
This is what I did ( I don't want to overwrite existing files, so I created a new one).

````
mkdir 2-asm-falcon-2
cd 2-asm-falcon-2
cp ../2-asm-falcon/*.sh .
#comment out DB2falcon
#change 2-asm-falcon to 2-asm-falcon-2
#change max_cov from 25 to 60 and max_diff from 40 to 60
vi run_falcon_asm.sh  
source run_falcon_asm.sh
````

This time I was able to have a 80%+ coverage again!!! Thanks a lot!

But why didn't I get this result when I used fc_run.py and fc_run2.cfg?

**Comment by pb-jchin** [comment]
well. It is hard to say. Do you like to do another end-to-end test?

**Comment by yunfeiguo** [comment]
I tested `max_cov` and `max_diff` separately and found that `max_diff` is the key variable here. If I use `max_diff 40` I will get very small assembly, if I use `max_diff 60`, I will get a reasonably large assembly. Looking at the overlap count scatterplot, quite a few reads are off-diagonal.

End-to-end test at this moment may not be possible as first few steps are too time-consuming, unless I can use only a subset of input data.

**Comment by pb-jchin** [comment]
This is still open.  @yunfeiguo, it has been a while, not sure if you have find some root cause yet?

**Comment by yunfeiguo** [comment]
Hi Dr. Chin,

The root cause is `max_diff 40` which is too stringent for our data. `max_diff 60` works well in our case. I should have closed this issue.
