### ISSUE TITLE
extra consensus tasks generated

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#81]
Hi, Jason,

My latest batch of changes to fc_run.py have caused problems and
perhaps you can suggest how to debug the problem.  

The issue is that fc_run.py is submitting each ct_... job (for
0-rawreads) 3 times.  E.g., it will submit:

ct_00005-588a29fb
ct_00005-9a09c07e
ct_00005-d641bf5e

Each of these uses the same 0-rawreads/preads/c_00005.sh shell script.

I added the following debugging code to create_merge_tasks

        print "consensus task out_file = " + szOutFile + " done file: " + szDoneFile + " job_id = " + str( p_id ) 

and it shows that there is only one task created (correct).

When I use it without my changes, it works fine, so I don't think it
is any of your new pypeFLOW changes.  

I should mention my changes:  I made the m_ job run all of
LAsort/LAmerge/LA4Falcon and just touch the m_*_done file.  Then the
ct_ job just sets the ct_*done flag--it is essentially a no-op.

I just need some suggestions of how to debug this.

Thanks,
David

**Comment by pb-cdunn** [comment]
Please push your changes into your own "fork" so we can pull them. We might integrate some of them, and they're hard to debug without seeing them.

Also, we will soon push some debugging aids of our own, [here](78) and in [pypeFLOW](https://github.com/pb-jchin/pypeFLOW/pull/4). Try them early if you'd like.

**Comment by pb-cdunn** [comment]
Try the latest master branch.
