### ISSUE TITLE
program for splitting a fasta file for falcon

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#82]
Hi, Jason or Chris,

I'm getting the error below.  If I recall, this is because I have combined into the same fasta file sequences that daligner can't handle together.  I also remember you had a little program (java) that would split such fasta files into those that can be handled.  Could you point me again to that program?

(Sorry for the same request again.)

Best wishes,
David

> fc_run.py fc_run_human.cfg                                                    │·
 No target specified, assuming "assembly" as target                             │·
Your job 5732493 ("build_rdb-7f725e92") has been submitted                      │·
Exception in thread Thread-4:                                                   │·
Traceback (most recent call last):                                              │·
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/pyt│·
hon2.7/threading.py", line 551, in __bootstrap_inner                            │·
    self.run()                                                                  │·
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/pyt│·
hon2.7/threading.py", line 504, in run                                          │·
    self.__target(*self.__args, **self.__kwargs)                                │·
  File "/net/gs/vol1/home/dgordon/falcon4/FALCON-master/install/fc_env/lib/pytho│·
n2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 317, in __ca│·
ll__                                                                            │·
    runFlag = self._getRunFlag()                                                │·
  File "/net/gs/vol1/home/dgordon/falcon4/FALCON-master/install/fc_env/lib/pytho│·
n2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 147, in _get│·
RunFlag                                                                         │·
    runFlag = any( [ f(self.inputDataObjs, self.outputDataObjs, self.parameters)│·
 for f in self._compareFunctions] )                                             │·
  File "/net/gs/vol1/home/dgordon/falcon4/FALCON-master/install/fc_env/lib/pytho│·
n2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 812, in time│·
StampCompare                                                                    │·
    if min(outputDataObjsTS) < max(inputDataObjsTS):                            │·
ValueError: max() arg is an empty sequence                                      │·

**Comment by pb-jchin** [comment]
Here is a snippet of the python script I use to split a fasta file by the movie names.  Please read it and test it to see if it fits your user's case.

```
import sys
state = 1
files = {}
seq = ""
read_name = ""
with open(sys.argv[1]) as f:
    for l in f:
        l = l.strip()
        if l[0] == ">":
            if len(seq) > 0 and len(read_name) != "":
                mn = read_name.split("/")[0]
                if mn not in files:
                    f = open(read_name.split("/")[0]+".subreads.fasta","a")
                    files[mn] = f
                print >> files[mn], ">"+read_name
                seq = "".join(seq)
                for s in xrange(0, len(seq), 60):
                    print >> files[mn], seq[s:s+60]

            read_name = l[1:]
            state = 1
            seq = []
            continue
        else:
            seq.append(l)

if len(seq) > 0 and len(read_name) != "":
    mn = read_name.split("/")[0]
    if mn not in files:
        f = open(read_name.split("/")[0]+".subreads.fasta","a")
        files[mn] = f
    print >> files[mn], ">"+read_name
    for s in xrange(0, len(seq), 60):
        print >> files[mn], seq[s:s+60]

for mn in files:
    files[mn].close()
```

**Comment by dgordon562** [comment]
Thanks, Jason!

**Comment by pb-cdunn** [comment]
I copied Jason's code to here:
* https://github.com/pb-cdunn/DALIGNER-extras/blob/master/scripts/split_fasta_by_movie.py

That's a temporary location for simple scripts.
