### ISSUE TITLE
preads.db .preads.bps, and .preads.idx

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#84]
Hi, Chris or Jason,

rawreads.db, .rawreads.bps, and .rawreads.idx are
read but not written to by LA4Falcon during the 0-rawreads stage of
Falcon.  

1)  During the 1-preads_ovl stage of Falcon, there is no
LA4Falcon.  Is this correct?

However, there are analogous files preads.db, 
.preads.bps, and .preads.idx  

2) Which programs reads these files?  

3) If I am running 1-preads_ovl tasks on local disks on several different
nodes (each with their own local disk), is it necessary to copy these 3
files to the local disk before running LAsort/merge?  

4) Are these 3 files used in a read-only manner just as LA4Falcon
does?

Thanks!
david

**Comment by pb-jchin** [comment]
1) `LA4Falcon` generates data for error correction and dump the overlapping data.  It is used for overlap filtering in `2-falcon-asm` but not in `1-preads_ovl`. 

2) the `LA4Falcon` in `2-falcon-asm` uses `preads.db` and `.preads.*`.  They are also used to dump fasta files for constructing contigs at the end by calling `DB2Falcon preads` inside `2-asm-falcon/run_falcon_asm.sh`

3) Yes. Just like the step in `0-rawreads`. However, I have never have a problem here.  The data is smaller and the computing is way faster than the `0-rawreads` error correction step.  

4) Yes. Once they are created and error corrected reads loaded, it should not be changed.

**Comment by dgordon562** [comment]
thanks, Jason!
