### ISSUE TITLE
combining m_ and ct_ 0-rawreads tasks

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#85]
Hi, Jason,

I have successfully moved the m_ tasks and the
ct_tasks of 0-rawreads onto local disk, and the m_ task of
1-preads_ovl also onto local disk.  

However, I tried to make one further improvement and that's where I am
stuck.  I thought that I would combine the m_ and the ct_ task
together, since the output las file of the m_ task is the input of the
ct_ task.  Why copy that las file back to the network drive just to
copy it back out to the local disk?  

So I made the m_ task do both LAsort/merge and LA4Falcon and then touch
the m_*done file.  To try to keep fc_run.py happy, I allowed it to
still run the ct_ task, but it did nothing except touch the ct_*done
file.

Well, fc_run.py was not happy at all about this.  After running the m_
tasks (successfully), it tried to run the ct_ tasks over and over.  It
did successfully find the ct_ done files in wait_for_file each time, however, but that wasn't enough for it apparently.

After 3 times of submitting the same ct_ task (with different task ids), it finally gave an error:

fasta2DB: File preads_norm.fasta is already in database preads.db
You are about to overwrite the current partition settings.  This
will invalidate any tracks, overlaps, and other derivative files.
Are you sure you want to proceed? [Y/N] 

So somehow fc_run.py must not have seen what it was expecting when it
found the done flag.  What more is it wanting?  And how can I tell it that the ct_ task has successfully finished?

Thanks,
David

**Comment by pb-cdunn** [comment]
> Why copy that las file back to the network drive just to
copy it back out to the local disk?

Because in a large run, there could be a *lot* of .las files, produced on different hosts. There might be some room for a bit more efficiency on the first level (merging occurs in levels of hierarchy, so higher levels will merge files from different hosts) but that's not high priority since copying files is *not* the slowest part.

> And how can I tell it that the ct_ task has successfully finished?

Try the diconsensus branch. There, we have improved how the "done" files work.

**Comment by dgordon562** [comment]
I should also mention that I didn't change one line of fc_run.py between the my version A that (successfully) runs LAsort/merge in the m_ task and runs LA4Falcon in the ct_ task and my version B that (repeatedly) runs LAsort/merge and LA4Falcon in the m_ task and that runs nothing but touch *done in the ct_ task.  The only difference are my two python scripts.  In version B I just move some of the code from the ct_ python script (the part that runs LA4Falcon) and put it into my m_ python script.  I don't see how fc_run.py could even know that I had done that.

One other clue I should mention:  I put some print statements in create_merge_tasks to see if it is creating any extra make_c_task's.  It is not.  It creates 20 c tasks (for ecoli).  But then after those 20 have run, e.g.,

Your job 5824654 ("ct_00017-c494abcb") has been submitted

it runs the same tasks again:

Your job 5825378 ("ct_00017-144f6e52") has been submitted

(notice the slightly different task id).

How does pypeFlow know when a task has completed?  Why would pypeFlow submit the same task again?

**Comment by dgordon562** [comment]
thanks, Chris.

Yes, there are a lot of .las produced on different hosts (I've done several human assemblies).  Each 0-rawreads m_ task produces, as output, a single .las file.  And that single .las file is the input to a single ct_ task.  So why not keep that file on the same host and run both tasks as one?    That's what I was trying to do, and I was careful (please re-read above) to preserve the same task dependency structure.

**Comment by pb-cdunn** [comment]
The code in the diconsensus branch fixes some race conditions and is better for restarts. I don't even want to discuss the 'done' files for the older code.

As for your code, why not fork FALCON into your GitHub account and push your changes there? Then we can discuss your ideas with reference to actual code. You can comment on any line of any commit in GitHub, or you can include hyperlinks in these "issue" discussions.

**Comment by dgordon562** [comment]
Got it working.  I suggest you modify the main path to be this way:

combine the m_ and ct_ tasks into one.  The big advantage is that the output .las file of LAsort/merge can be fed directly into LA4Falcon and then deleted.  If this combined task is run on a node running on a local disk, this means there is no need to copy the .las file back to the network drive and then back to another node--do it all on one node with one local disk.

The way I implemented this, with minimal changes to fc_run.py, was to have the m_ task be all of LAsort/merge/LA4Falcon and have ct_ just touch the ct_*done file.  pypeFlow didn't like that because pypeFlow saw that the output .fa had a timestamp earlier than the ct_ task.  The solution was to have the ct_ task touch the ct_*done flag.  Then pypeFlow was happy.  

You guys, having more of a command of fc_run.py than I do, could do me one better by simply eliminating the ct_ task all together.

**Comment by pb-jchin** [comment]
Yes. Those two steps are "unbranched" path in the workflow DAG and can be combined. The initial reason that I put the as separate step is to adapt to our computational and storage infrastructure. The merge step is almost IO-bound, I need to control how many jobs to hit the file system at the same time. The consensus step is both computation and I/O-bound but the I/O access pattern is very different from the merge step, so I separate them.   

For your system which might have different I/O characteristics, I think it makes sense to merge them locally at one. Depending on your following workflow, you might still want to consider the copy the .las file back the to network drive if you might want to re-use the data.

**Comment by pb-cdunn** [comment]
This was a good idea. Top-level merging (plus all LAsort calls) is now part of the daligner tasks. The rest of merging remains associated with consensus.

The issue mentioned in #51 should be solved with `use_tmpdir=True`.
