### ISSUE TITLE
Contigs not containing beginning overlapping node of string graph

### ISSUE THREAD

**Issue by arangrhie** [PacificBiosciences/FALCON#89]
By looking into short consensus (both primary and associated contigs), with less then 50 bp,
I've found out that the beginning of overlapping preads are not included. Hence, inferred from the tiling path, the first 'Edge' of the string graph was the beginning of the consensus.
I think this could by 'by-design', however, this is actually missing a lot.
for example, the shortest consensus (35bp) had actually an overlap of 19kb between two preads, and only the 'edge (non-overlapping part) of one pread was made as the consensus.
Also from our longest contig, at the beginning of the contig, first overlapping 16kb between 2 preads was lost.
If assuming all contigs are missing those overlaps, this will resulting into a shorter assembled contig than expected.

**Comment by pb-jchin** [comment]
please see slide 4 of this deck. https://speakerdeck.com/jchin/de-novo-diploid-genome-assembly-and-haplotype-sequence-reconstruction

The first read is not included in the layout to maintain the notion of the string graph.  If a contig path is part of larger graph, it is desirable to not include the first reads so we can potential extend the path on the 5'-end if necessary. 

You can padding the 5' sequence if you see it is good. However, this may not be general. For example, if you get a contig of circular genome, it will not be necessary to pad the 5'-end.

**Comment by arangrhie** [comment]
Thanks for your reply. I have one more question. I am handling a diploid human genome.
Although most of the preads have an initial pread of the tiling path (starting pread) that is unique to other contigs, I see some preads being the first pread in multiple primary contigs.
The highest pread was used in 6 different contigs as a starting pread.
How should I interpret this?
I see some are at the beginning of a bubble, so one of 2 contigs having same starting pread actually  belongs to an associated haplotype. And some pread are aligned on multiple regions but same chromosome, when aligned on a different genome. So I guess this case is because the starting pread falls into a repetitive region.
What is the criteria for selecting the initial pread of a contig? Am I missing some other cases?

**Comment by pb-jchin** [comment]
@arangrhie  Typically, when the code traverse the graph to layout contig, it will stop at where there is some ambiguity.  For example, if there is a very long repeat that have multiple copies in the genome, there could be multiple contig stating from the same repeat.  If you are interested, you can take a look of my note related to this (here)[https://dl.dropboxusercontent.com/u/38943405/assembly_graph_notebook/asm_graph_exploration_notebook_CHM13.slides.html#/12]  Some of the node in the beginning of the end of the contigs are indeed likely to be some repeat element.

**Comment by arangrhie** [comment]
Thanks for your support.
