### ISSUE TITLE
restarting falcon between 0-rawreads and 1-preads_ovl

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#90]
Hi, Jason and Chris,

I am getting this error:

fasta2DB: File preads_norm.fasta is already in database preads.db
You are about to overwrite the current partition settings.  This
will invalidate any tracks, overlaps, and other derivative files.
Are you sure you want to proceed? [Y/N] 

When I try to ^C out of fc_run.py, fc_run.py resubmits a bunch of daligner jobs for 1-preads_ovl that had previously completed.  Even if I kill those jobs, I assume they will partly overwrite the completed information in the 1-preads_ovl/job_* directories.

So what to do?  

If I allow them to complete and recreate the information, and then restart fc_run.py, I will still run into the fasta2DB problem again because preads.db already exists with preads_norm.fasta in it.

So how can I cleanly restart fc_run.py without having to go back to recreating all of 0-rawreads (which would take days)?

Which files should I delete from 1-preads_ovl before restarting fc_run.py?  Must I delete preads.db and its associated .preads.bps and .preads.idx ?   At what stage are these regenerated?  Any done files I should delete?  Or should I delete *everything* in 1-preads_ovl, or will that delete some things that are created in the 0-reads ct_ stage?

Thanks!
David

**Comment by pb-cdunn** [comment]
Which commits are you using for FALCON and pypeFLOW?

**Comment by dgordon562** [comment]
pypeFlow--none
fc_run.py--none for the 1-preads stage
for 0-rawreads I made the m_ task call a python script of mine that runs both LAsort/merge and LA4Falcon
I made the ct_ task of 0-rawreads call a python script of mine that just sets the done file for the ct_ task and touch's the out*.fa file

All of this works fine on ecoli.  

The problem I ran into with a large dataset is that (for a trivial reason) two  of the m_ tasks for 1-preads-ovl  crashed.  No problem--I fixed the problem and qsub'd them.  They completed successfully, set the done file, and fc_run.py (which had been polling waiting for them), saw the done flag and continued.  

Then all hell broke loose (see above).

I don't know if the hell was related to the manual qsub'ing of the 2 m_ tasks or not.

But my questions (see above) are not related to debugging--they are related to how I can complete the assembly without having to redo all of the 0-rawreads processing.

**Comment by pb-cdunn** [comment]
We can help with basic usage issues, but debugging requires the actual code. We need to know  which commits you are using. Or at least which branch.

There are recent changes which could solve most of these problems, potentially. Specifically, the reason for this error is that some steps did not have all dependencies specified in fc_run.py.

> But my questions (see above) are not related to debugging...

Not debugging *your* code. But we need to debug pypeFLOW.

Btw, why not use a GitHub "fork"? We could discuss actual code then.

**Comment by dgordon562** [comment]
What program *writes* 

preads.db and its associated .preads.bps and .preads.idx 

?

**Comment by pb-jchin** [comment]
fasta2DB, check the script `0-rawreads/prepare_db.sh`

**Comment by dgordon562** [comment]
Thanks, Jason.  It looks as though that happens twice, and I'm just concerned with the preads occurrence.  The preads occurrence of fasta2DB occurs *before* the preads daligner and LAsort/merge.  Thus I should be safe with deleting *everything* in 1-preads and restarting fc_run.py  

fc_run.py will then run fasta2DB to recreate everything in 1-preads.  I do not need to redo any of the 0-rawreads processing.

**Comment by pb-cdunn** [comment]
Ah, yes, I see why that's not obvious. [fasta2DB](https://github.com/thegenemyers/DAZZ_DB/blob/master/fasta2DB.c#L222) says 'preads' on the command-line, but not 'preads.db'.

@pb-chin, Couldn't one also use 'DB2fasta' to dump a preads fasta file, and then use "input_type = preads"? I'm not sure.

Btw, the "done" files are not reliable on the old branch. Yes, removing 1-* should work. To be safe, you could 'chmod -w' everything  under 0-.

**Comment by pb-jchin** [comment]
yes. you can use DB2fasta to dump a db and assembly the p-reads again. The file format should be compatible, but one needs to double check.

**Comment by dgordon562** [comment]
this is very helpful.  Thank you!

This seems to be working.

I would be willing to write up some additions to your github documentation, if you would be willing to use it.  Since I have recently learned Falcon, I am aware of things other new users need to know which is probably so obvious to both of you that it wouldn't occur to you to put it into the documentation.

but I only want to put the time into this there is a reasonable chance you will accept it.  You have a good start with that on github so it would make most sense for me to add to it, rather than make an addendum, but I am ok either way.

**Comment by pb-cdunn** [comment]
Yes, that would be helpful! Try to edit this wiki:
* https://github.com/PacificBiosciences/FALCON/wiki/Contrib

If you cannot, I'll see if we can get permission to open up the wiki to the public. (That's the default.)

Please don't modify the Manual page until we release the latest branch. Your code is probably quite a bit different.

**Comment by pb-cdunn** [comment]
Oh, you know what? You can freely modify  the Manual and anything else in this wiki:
* https://github.com/pb-cdunn/FALCON/wiki

I'll eventually integrate it back to PacBio, whether or not the other ideas there are kept.

**Comment by dgordon562** [comment]
Thanks, Chris.  I've submitted the info to https://github.com/pb-cdunn/FALCON/wiki .  (It might seem obvious to you guys, but it wasn't to me.)

**Comment by pb-cdunn** [comment]
That's helpful, actually. I'll reformat that and copy to main wiki. Thanks!

**Comment by pb-cdunn** [comment]
Copied into [Contrib](../wiki/Contrib). Sorry for delay. Thanks.
