### ISSUE TITLE
2-asm-falcon directory doesn't contain p_ctg.fa

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#94]
Hi, Jason and Chris,

This is a problem I've never seen before.  My 2-asm-falcon directory looks like this:
```
-rw-rw-r-- 1 dgordon dgordon_g       830 Jun 12 23:18 run_falcon_asm.sh
-rw-rw-r-- 1 dgordon dgordon_g     18708 Jun 12 23:29 las.fofn
-rw-rw-r-- 1 dgordon dgordon_g 427422232 Jun 13 01:08 preads.ovl
lrwxrwxrwx 1 dgordon dgordon_g       106 Jun 13 01:08 preads4falcon.fasta -> /net/eichler/vol24/projects/whole_genome_assembly/nobackups/xxxx/1-preads_ovl/preads4falcon.fasta
-rw-rw-r-- 1 dgordon dgordon_g 308322544 Jun 13 01:19 sg_edges_list
-rw-rw-r-- 1 dgordon dgordon_g   7115340 Jun 13 01:24 c_path
-rw-rw-r-- 1 dgordon dgordon_g  39562810 Jun 13 01:24 utg_data
-rw-rw-r-- 1 dgordon dgordon_g   5557544 Jun 13 01:24 ctg_paths
-rw-rw-r-- 1 dgordon dgordon_g    399384 Jun 13 01:25 fc_ovlp_to_graph.log
drwxrwxr-x 2 dgordon dgordon_g      2048 Jun 13 01:46 .
-rw-rw-r-- 1 dgordon dgordon_g         0 Jun 13 01:46 falcon_asm_done
```
What program creates p_ctg.fa (and a_ctg.fa) and what are its inputs?

Thanks!
David

**Comment by pb-jchin** [comment]
`fc_graph_to_contig.py` generates the `p_ctg.fa` and `a_ctg.fa`. The input is the `preads4falcon.fasta` and ` ctg_paths` taken implicitly (hard-coded in the script for now) from the files in the working directly.

**Comment by dgordon562** [comment]
tHANKS--just what I needed.  Using this information, I was able to manually complete the assembly.  The problem was that sge killed fc_graph_to_contig.py due to not enough memory allocated.
