### ISSUE TITLE
Small N50 contig size

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#95]
Just finished a mamalian genome that had 80x coverage but only got 3.8M N50 contig size.  

I had used the following parameters:
```
# The length cutoff used for seed reads used for initial mapping
length_cutoff = 10000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 6000
```
To get a higher N50 contig size, what do you suggest changing these parameters to?

Thanks!

**Comment by pb-jchin** [comment]
I will suggesting look into the p-read overlapping statistics first. https://github.com/PacificBiosciences/FALCON/issues/76 has some related discussion. I typical fine tune the max_cov and max_diff first as that if they are set wrong, you could filter out too much data.

**Comment by dgordon562** [comment]
Thanks, Jason.

I used:
--max_diff 60 --max_cov 60
which is what worked for #76.  I am now trying 
length_cutoff = 6000
(see below)
Or will that create so many reads that the runtime will be many, many times longer?


[General]
# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 6000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 6000


#sge_option_da = -pe orte 1 -l mfree=30G
# changed to -pe serial 4 -l mfree=7.5G per Brian's suggestion
sge_option_da = -pe serial 4 -l mfree=7.5G -l ssd=FALSE -q all.q
# changed to -pe orte 6 per Elizabeth's suggestion since
# fc_consensus.py spawns 6 jobs and this causes node "wedging"
sge_option_la = -pe orte 6 -l mfree=6G -l ssd=TRUE -q all.q
#sge_option_la is for the m_ jobs
#sge_option_la = -pe orte 2 -l mfree=6G
# changed to -pe serial 4 -l mfree=7.5G per Brian's suggestion
# now increasing more:
sge_option_pda = -pe serial 4 -l mfree=10G -l ssd=FALSE -q all.q
#sge_option_pda = -pe orte 1 -l mfree=33G -l ssd=FALSE


sge_option_pla = -pe orte 2 -l mfree=6G -l ssd=TRUE -q all.q
# I don't know what sge_option_fc is
sge_option_fc = -pe orte 6 -l mfree=6G -q all.q
# below is for ct_ tasks
sge_option_cns = -pe orte 6 -l mfree=6G -l ssd=FALSE -q all.q

# will decreased slightly due to John's suggestion
# increased just for today (June 11, 2015)
pa_concurrent_jobs = 100
ovlp_concurrent_jobs = 100
cns_concurrent_jobs = 100


pa_HPCdaligner_option =  -v -dal128 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal128 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6

#drosophila:
#overlap_filtering_setting = --max_diff 30 --max_cov 60 --min_cov 5
# from https://github.com/PacificBiosciences/FALCON/blob/master/examples/fc_run_LG.cfg
overlap_filtering_setting = --max_diff 60 --max_cov 60 --min_cov 2

**Comment by pb-jchin** [comment]
You should try to look the histogram of the 5'- and 3'- overlaps first.  Each data set can be different. I have yet to have time to write some code to automagically guess the threshold. (It is theoretically possible.)  About run time, you should only re-run the part of pipeline that is necessary for the updates. 
check https://github.com/PacificBiosciences/FALCON/wiki/FAQs for how I typically restart jobs for the necessary part. If you change the p-read threshold, you should only re-run every thing after `1-pread_ovl`
