### ISSUE TITLE
LA4falcon segmentation faults

### ISSUE THREAD

**Issue by HenrivdGeest** [PacificBiosciences/FALCON#96]
With one of my latest trials I found that LA4falcon gives a segmantation fault or illigal instruction. (after 2 seconds of run time)

Ouput with the latest checkout (15th of May) : (an earlier version gives the same result)

#....../15052015/FALCON/fc_env/bin/LA4Falcon -H15000 -o -f:raw_reads las_files/raw_reads.1.las
00018796 TGTATA..................some more sequence
Illegal instruction

Or the illigal instruction is replaced with a "Segmentation fault"
All the LA4falcon jobs fail, none of them produces normal output.

If I try different las files, I always see a single sequence being outputted, followed by the Fault message.

This is all on:
(fc_env) uname -a
Linux compute-0-3.local 2.6.32-279.14.1.el6.x86_64 #1 SMP Tue Nov 6 23:43:09 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

(fc_env) lsb_release -a
LSB Version:    :core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.3 (Final)
Release:        6.3
Codename:       Final

The source data stats:
#############################
Statistics for all wells in the data set

      1,113,819 reads        out of       1,113,819  (100.0%)
 12,146,387,941 base pairs   out of  12,146,387,941  (100.0%)

         10,905 average read length
          7,718 standard deviation

  Base composition: 0.328(A) 0.180(C) 0.183(G) 0.310(T)

  Distribution of Read Lengths (Bin size = 1,000)

        Bin:      Count  % Reads  % Bases     Average
     71,000:          1      0.0      0.0       71794
 ....
      1,000:     73,316     95.2     99.7       11427
##############################

A second problem I found with this:

Despite of this, the job_success is always written. I think because the command is invoked with the 'time' binary included, which always exits normally. This makes that the pipeline does not see the failed jobs, which is not the desired situation I guess.

command:

#more c_00005.sh
...............
/usr/bin/time bash cp_00005.sh  >> /mnt/nexenta/hvdg/2015-04-melon/falcon/0-rawreads/preads/c_00005.log 2>&1  && touch c_00005_done

**Comment by pb-jchin** [comment]
There is no simple way to debug seg fault without data. Several suggestions: (1) using gdb to track down the exact point where the seg-fault happen.  (2) It is likely you might use a daligner version which generates data in a different format.  Please make sure you use the same version where the current master branch is designed to.  (3) if the *.las is not too big, you can paste it somewhere, I can see if it indeed a case where different version of daligner is used.

**Comment by pb-cdunn** [comment]
Re-open with more details if this happens with **FALCON-integrate**.
