### ISSUE TITLE
low coverage FALCON settings (30x ,ecoli)

### ISSUE THREAD

**Issue by michel-moser** [PacificBiosciences/FALCON#97]
Dear Jason Chin, 

In order to compare performance and disk-space usage between PBcR and FALCON with low-coverage pacbio-only data, i would like to run Falcon with the PBcR ecoli dataset (30x pacbio data with readN50 11'757bp). 

Unfortunately, default settings of the fc_run_ecoli.cfg result in no assembly being generated. I suspect this is due to the high coverage settings in the config-file (the original dataset is about 220x coverage) 

Is FALCON also running on low coverage data (20 - 30x )? 
Could you provide us some parameters for such data? 
Thank you very much, 
Michel

**Comment by pb-jchin** [comment]
My guess is that you will need to adjust `--max_diff` and `--min_cov` for `fc_ovlp_to_graph.py`. see https://github.com/PacificBiosciences/FALCON/issues/76
