### ISSUE TITLE
how to use the whole computing resources,when LAmerge in 0-rawreads?

### ISSUE THREAD

**Issue by AnWD** [PacificBiosciences/FALCON#98]
Hi Chin:
    If I regard 0-rawreads as three steps:daligner,LAsort,LAmerge.I know daligner could produce very large raw data,it takes the major distributed computing resources.But when we finish daligner step,
we found that LAmerge could not use the sge computing resources,it can only use local computing resources. Now daligner is not our weakness,but LAmerge now is. Is there any way to solve this problem?Thank you!
                                                                                                            Jingyu

**Comment by pb-jchin** [comment]
depending on your system, you might have to work out a customized solution.  For example see https://github.com/PacificBiosciences/FALCON/issues/85
https://github.com/PacificBiosciences/FALCON/issues/51

**Comment by AnWD** [comment]
Thanks Chin,one more question: I know,as you told me ,falcon could re-run from where it was suspended,now in order to use the majority of computing resources,when it is in the third step of 0-rawreads LAmerge, we started another fc_run.py to falcon the other sample,and when it is in the  1-preads_ovl step using most of the computing resources,we plan to kill the latter fc_run.py temporarily.    Is there any problem to the final results?
Jingyu

**Comment by pb-cdunn** [comment]
Are you saying you have multiple runs for the same workspace, simultaneously? That would be problematic. If they are different workspaces (i.e. different run directories) then it's no problem.

Stopping and re-starting a run is supposed to work, but the current code-base does not handle dependencies properly. (We have made some improvements on the soon-to-be promoted branch.) However, if you *completely* remove a stage-directory (e.g. 2-asm-falcon), then a re-start should be fine.

**Comment by pb-jchin** [comment]
@AnWD as what @pb-cdunn said, you need separate working space for different sample.  please also check out https://github.com/PacificBiosciences/FALCON/wiki/FAQs to see how I typically restart some jobs for later stage optimizations
